### ISSUE TITLE
Fix RSPEC deprecation errors

### ISSUE THREAD

**Issue by askl56** [empirical-org/Empirical-Core#1001]
```
andrew@andrews-MacBook-Pro:shared_repos/Empirical-Core ‹develop*›$ rspec
I, [2015-11-19T22:45:02.302337 #54363]  INFO -- : ** [Raven] Raven 0.14.0 configured not to send errors.
set_default_options has been deprecated, use set_options
DEPRECATION WARNING: `#ignore` is deprecated and will be removed in 5.0. Please use `#transient` instead. (called from block (3 levels) in <top (required)> at /Users/andrew/code/shared_repos/Empirical-Core/spec/factories/users.rb:62)
DEPRECATION WARNING: `#ignore` is deprecated and will be removed in 5.0. Please use `#transient` instead. (called from block (3 levels) in <top (required)> at /Users/andrew/code/shared_repos/Empirical-Core/spec/factories/users.rb:62)
DEPRECATION WARNING: `#ignore` is deprecated and will be removed in 5.0. Please use `#transient` instead. (called from block (3 levels) in <top (required)> at /Users/andrew/code/shared_repos/Empirical-Core/spec/factories/users.rb:62)
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 8816
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
Each child in an array should have a unique "key" prop. Check the render method of ListFilterOptions. See http://fb.me/react-warning-keys for more information.
Each child in an array should have a unique "key" prop. Check the render method of UnitTemplates. See http://fb.me/react-warning-keys for more information.
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
Each child in an array should have a unique "key" prop. Check the render method of ListFilterOptions. See http://fb.me/react-warning-keys for more information.
Each child in an array should have a unique "key" prop. Check the render method of UnitTemplates. See http://fb.me/react-warning-keys for more information.
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
Each child in an array should have a unique "key" prop. Check the render method of ListFilterOptions. See http://fb.me/react-warning-keys for more information.
Each child in an array should have a unique "key" prop. Check the render method of UnitTemplates. See http://fb.me/react-warning-keys for more information.
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /Users/andrew/code/shared_repos/Empirical-Core/spec/models/classroom_activity_spec.rb:82:in `block (3 levels) in <top (required)>'.

```

**Comment by askl56** [comment]
I'm happy to fix these if someone wants to assign me to them :+1:

**Comment by RyanNovas** [comment]
Hi @askl56, thanks for pointing this out!

I tried assigning it to you, but was unable to, perhaps because you aren't part of the organization.

In any case, go ahead, it is all yours. 

By the way, how did you find us?

**Comment by askl56** [comment]
Was asking around for great examples of open source Rails projects in #ruby on Freenode.

I don't know what your org settings are but if you want to add me to it, feel free.

Will get around to fixing these this week.

**Comment by RyanNovas** [comment]
Great, I added you. Glad you found us. We're generally on Slack during the American business day if you ever have questions. I just an invite to our channel to your posted email address.

**Comment by askl56** [comment]
No worries. Is there a GH org?

**Comment by RyanNovas** [comment]
Yes, empirical-org. You should now be added to it.

On Wed, Dec 2, 2015 at 4:52 PM, Andrew Scott <notifications@github.com>
wrote:

> No worries. Is there a GH org?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/1001#issuecomment-161445075>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org
<http://t.sidekickopen30.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsfD3xvW4WJ4Vn5wvHZnW2B89Qs56dL9qf72Hr4d02?t=https%3A%2F%2Ftwitter.com%2Fquill_org&si=5074814419337216&pi=07a8532f-a000-4e90-f644-53b479d3cfc8>

**Comment by askl56** [comment]
Don't think so, haven't received an email or anything

**Comment by RyanNovas** [comment]
It says your username has a pending invitation. Maybe check the
notifications section on the actual github website?

On Thu, Dec 3, 2015 at 4:13 AM, Andrew Scott <notifications@github.com>
wrote:

> Don't think so, haven't received an email or anything
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/1001#issuecomment-161559287>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org
<http://t.sidekickopen30.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsfD3xvW4WJ4Vn5wvHZnW2B89Qs56dL9qf72Hr4d02?t=https%3A%2F%2Ftwitter.com%2Fquill_org&si=5074814419337216&pi=75edb94f-3a51-4037-f41d-457b8fe8c445>

**Comment by askl56** [comment]
https://www.dropbox.com/s/hzx371rs1hiao5r/Screenshot%202015-12-03%2015.47.03.png

**Comment by askl56** [comment]
My email is amscott@openmailbox.org

**Comment by RyanNovas** [comment]
I'd contact Github then. Putting in your email goes to the same page that
shows the pending invite for your username.[image: Inline image 1]

On Thu, Dec 3, 2015 at 10:47 AM, Andrew Scott <notifications@github.com>
wrote:

>
> https://www.dropbox.com/s/hzx371rs1hiao5r/Screenshot%202015-12-03%2015.47.03.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/1001#issuecomment-161682950>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org
<http://t.sidekickopen30.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsfD3xvW4WJ4Vn5wvHZnW2B89Qs56dL9qf72Hr4d02?t=https%3A%2F%2Ftwitter.com%2Fquill_org&si=5074814419337216&pi=6fa719e8-0bd5-45d3-f296-16d99a63314d>

**Comment by Echelon9** [comment]
One small PR to address a set of these deprecation warnings here: https://github.com/empirical-org/Empirical-Core/pull/1491
