### ISSUE TITLE
Chart for Typing Results. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1010]
https://docs.google.com/document/d/1fIVvX_XuTnm9OpgMyGRGAbQ_diGERdSiz9ZCmcyXS7M/edit

Here is a mockup for what I'd like the basic table to look like.

**Comment by ddmck** [comment]
Regarding making the query: we can really only tell the browser type, device results are pretty spotty. These are unique to devices though. So we will have mobile safari/chrome vs non mobile browsers.
