### ISSUE TITLE
Activity Pack Follow Up Features

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1026]
# Recommended Packs 
Overview: After a teacher creates a classroom, the next step is being brought to a page that shows four activity packs flagged to that grade level.
- [x] If the teachers create a grade 4 classroom, show the grade 4 packs. 
- [x] We should only show 4 packs flagged to that grade. 
- [x] The packs, for now, can be sorted by time created or something simple like that. 
- [x] After they press assign, they are sent to the “my units” page for that grade. 

——

# Skip Due Date 
- [x] Add a toggle directly above the interface, to the right. 
- [x] By default due dates are turned off
- [x] When they are turned off, the app should automatically assign the 1st activity one week from now, +1 day for each subsequent activity (e.g. the first activity is due the 23rd, the 2nd is due the 24th, the third is due the 25th, etc.). 
- [x] Add a field that tracks whether due dates or hidden or not. 
- [x] On the my activities page, the due data is not shown to teachers if the due date is hidden. 
- [x] Due dates are shown in the student tooltip. They should be hidden if it is skipped.  

——

# Not Signed In page 
- [x] From the discover page, add the activities pack as a tab. 
- [x] It should generate a URL which is linkable. 
- [x] One issue is that the not signed in pack might have a different URL from the Signed in page. We should look into how we can solve this and whether we could have the same URL path structure for signed in and not signed in people. 

# Share The Pack 
- [x] After you assign a pack, the next page is a page that asks teachers to share. 
- [x] The page should look like the quick mockup below (sorry for now actual mockup). 
- [x] clicking on the share button will pop up a modal where the text is pre-filled in as it is below.
- [x] After you assign it, the system checks whether you have any students or not. If you have no students it goes to the invite students page. If you have students, it goes to the my units page. 

# Quick mockup of Share Pack

*(Centered Text)*

**Share Your Pack** (header)

Know another teacher interested in writing tools? Share this activity pack to your network. 

*(Box that has some text filled in, for them to get a sense of what they are sharing)*
[I'm using the Quill activity pack "ACTIVITY PACK NAME" to help my students become better writers. (Link).]

Buttons - buttons - buttons

**Comment by marcellosachs** [comment]
from convo with peter - we may want to find a way of sorting the activity assignments in such a way that they appear in the same order in the activity pack profile page, in the student profile page, in the my units page, even if they dont have due-dates (which is the traditional field they are sorted by)

**Comment by petergault** [comment]
@ddmck @RyanNovas almost done with the activity packs. The Discover page is the last big feature. Assigning this one to Ryan.
