### ISSUE TITLE
Add Press Bar and Users Impacted Bar 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1030]
We will add two skinny bars to the homepage:

# Impact Bar

1. Quill has helped 120,000 students become better writers. (something like that, this is probably too long):
2. 120,000 students becoming better writers. 
3. Quill has impacted 120,000 students. 

The number 120,000 should be a different color to indicate it is a link, and it goes to our stats page. 

# Press Bar
The standard skinny bar of the major press links we have gotten. They direct to the press page.

**Comment by RyanNovas** [comment]
@petergault do you want to flesh this out or close it? I know we've done some work with press, media etc. so maybe this is no longer an issue.
