### ISSUE TITLE
Make Concept Results Page in Angular

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#1035]
Currently, the page just spits the user back out to the homepage. This is terrible because most users who are completing an anonymous activity are doing so to test out Quill. With the current setup, they get no exposure to our feeback system, and are given a gradeless quiz.

This occurs because the concepts results page is rendered from Rails -- however, all the information is available directly within the app. We can display it for everyone, and faster, by switching to Angular.

**Comment by ddmck** [comment]
@tomcalabrese do you have any designs for the game results page before I get started on this.

**Comment by petergault** [comment]
I don't want to work on this one for now, moving it into the ideas folder.
