### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ejcupcake** [empirical-org/Empirical-Core#10562]
Please add dark mode to quill.org

**Comment by dandrabik** [comment]
Hi @ejcupcake1234alt, thanks for the feedback. We have a page where you can [file product requests here](https://quillorg.canny.io/feedback). There is already a [request for Dark Mode](https://quillorg.canny.io/feedback/p/dark-mode) which has a few votes. You can upvote and add comments on that page.

Thanks for your feedback, and hope you are enjoying using Quill!
