### ISSUE TITLE
Add the Waffle Board to the Staff Dashboard

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1098]
- [ ] Add a new header to the Staff Dashboard called "Project Kanban Board"
- [ ] Add a link to Admin Dashboard Project. 
- [ ] This is the link. 
https://waffle.io/empirical-org/empirical-core?milestone=Admin%20Dashboard

**Comment by RyanNovas** [comment]
@ddmck this PR takes care of that https://github.com/empirical-org/Empirical-Core/pull/1101
