### ISSUE TITLE
Multiple Accounts Per Admin

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1100]
An IT person and and a school Administrator should have access to the same view or the same teachers. 

Should we change it so that each account can have multiple emails and passwords that sign into that account? Or should we create separate accounts that all access the same data set? If we key accounts off of emails, we may have a problem.

**Comment by marcellosachs** [comment]
the following models/relationships were set up to account for this - 

an **AdminAccount**
can have many **Admins** associated to it.

an **AdminAccount** 
can also have many **Teachers** associated to it.

Any user (of possibly many) that is an **Admin** associated to **AdminAccount_X** will have access to all of the teachers that are associated to **Admin_Account_X**.
