### ISSUE TITLE
News Page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1125]
- [x] Create a new page called quill.org/news

- [x] It belongs in the sub-nav “news” under the header “media” (swaps out the old news page). 

- [x] The page is a grid 2 columns and any number of rows. 

- [x] In each grid cell a user can copy and paste the Medium embed code. 

- [x] Please add lots of white space to the code, so that it is easy to read, like the team page. 

- [x] Here is a sample of the embed code:

<script async src="https://static.medium.com/embed.js"></script><a class="m-story" data-collapsed="true" href="https://medium.com/@quill/play-testing-stories-with-friends-at-nyc-bigapps-1758cef008d9">Play-testing Stories With Friends at NYC BigApps</a>

![page_news_page 0](https://cloud.githubusercontent.com/assets/3667179/12054266/0ee4117a-aef0-11e5-8ee6-62afb7e2a51d.png)

Link to the page: 
https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a385184f3

**Comment by petergault** [comment]
@RyanNovas please close issues when you finish them.

**Comment by RyanNovas** [comment]
I need to update the links still.
