### ISSUE TITLE
Add error page tracking 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1161]
- [ ] Fire a Segment ever every time the LMS loads the 500 page. 
- [ ] Fire a segment event every time the LMS loads a "Heroku Application Error" page.

**Comment by marcellosachs** [comment]
500 error tracking is done, implemented in the app (with associated spec).
Heroku Application Error is also done, implemented by changing the javascript in our error.html file on amazon s3 - https://s3.amazonaws.com/compass-files/error.html
(mixpanel javascript was removed, segment javascript was added, segment Heroku Error Page event firing included)

**Comment by marcellosachs** [comment]
duplicate of #1193
