### ISSUE TITLE
Update the Tooltip 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1162]
## Assets:

![tooltip export](https://cloud.githubusercontent.com/assets/8131465/12278073/fc74b960-b94c-11e5-940a-e6391bc71384.png)

Zeplin file to copy CSS attributes, along with comments: https://zpl.io/MF3MJJ

Icons: https://drive.google.com/folderview?id=0B_iotSi5wcFXM200NmdJVEI3NGs&usp=sharing

## Updates & Revisions to tooltip:
- Fix the comma in the date. The comma should go after the day of the week, not the month. 
- Have the tooltip go below each square in the scorebook, instead of above - as it currently is. 
- Remove the orange premium section on the bottom if the user has a premium acount. 
- Remove the sections in red below:

![screen shot 2016-01-12 at 5 07 38 pm](https://cloud.githubusercontent.com/assets/8131465/12278320/7670651a-b94e-11e5-9453-79720432f39e.png)

**Comment by marcellosachs** [comment]
two things are done - 
1) tooltip will always appear below, not above icon
2) fixed commas in date

**Comment by marcellosachs** [comment]
finished, on develop
