### ISSUE TITLE
email teachers when their premium trial runs out

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#1166]

**Comment by petergault** [comment]
- Start trial - get an email. Here are the benefits of premium! (Copy and paste benefits from the page).
- 7 days before trial runs out - your trial is running out. 
- 0 days - Trial has run out. 



- Detailed progress reports for actionable insights based on student needs.
- Unlimited access to over 150 writing and grammar activities for your entire school.
- A classroom dashboard to view and manage classes.
- A Quill representative who will provide training, support, and professional development sessions.
Quill Premium users will also have priority access to our new state diagnostic assessments, which assess student needs based on your state exams.
