### ISSUE TITLE
Anonymous Sessions Tracking Discussion 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1174]
# Session Data Corruption
- Are there deleted sessions? Do we have every session? How could we diagnose for that? How do we make sure they are properly connected?
# Month over Month Goals

Context: Our Year over Year numbers are bad (negative growth) if you look just at the Quill LMS. However, with the addition of the BrainPOP app, we’re having a lot of learning happen there, which boosts up our numbers. 

The problem is that we need to come up with a tracking solution that allows us to integrate these numbers together in an easy to use fashion. 
# Option Given Current System:

Add numbers together in Google Sheets 
- Total for each month last year from SQL to sheets. 
- Total for each month this year from SQL sheets. 
- Import Totals from BrainPOP via manual update. 
- Create a separate table that is the percentage growth for each month.f 
- Show the total counter. 
# Option #1 Chartbeat Strategy - Time Tracking on Partner Apps
- We can calculate time across all apps (not just LMS connected apps) by sending all concept results to the Chartbeat app and calculate it from there. 
- Send every concept result to Chartbeat (from partner and main apps). 
- Aggregate the results of the concept results.
  >> We might need Segment SQL to actually do this. 
# Option #2 - Keen SQL as an option.

Chart beat aggregates the data, but we might not be able to run any math on it. While we could do this with Keen, we might be out of luck with chart beat for this. 
However, it might work. Chart beat is sexy. 
# Option #3 - Post data to LMS as Anonymous

Just track all sessions as new tables with results. 
# Time Tracking Results
- Once we have a strategy set up, we can then compare total learning time and questions answered as better metrics. We should pick one to focus on. 
- How many learning hours per day. 
- How many concept results each day. Questions answered. These

**Comment by ddmck** [comment]
- Show results page for anon sessions. Post data to session table.
- Track time_spent with ngClock (capture on results page) Not tracking started at with system.

#### Mixpanel
- Should post back to main project key.
- Add event for BrainPop passage fired when green and red feedback is displayed.
