### ISSUE TITLE
Add 500 error tracking to Segment and Mixpanel

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1193]
While I see the heroku error page, I do not see the event for the 500 page.

**Comment by marcellosachs** [comment]
The "Heroku Error Page" had an issue - I did not make it public on AWS. It is now public, so it should work. I will check on Monday to make sure.

**Comment by marcellosachs** [comment]
Now to fix 500 page...

**Comment by marcellosachs** [comment]
The 500 analytics event was not getting fired because Rails was bypassing our Controller actions.
This was solved using the line 
`config.exceptions_app = self.routes`
taken from 
https://mattbrictson.com/dynamic-rails-error-pages.
Have deployed to staging and production, will see soon if this works.

**Comment by marcellosachs** [comment]
The "Heroku Error Page" is already coming up on Segment after the fix.

**Comment by marcellosachs** [comment]
Got "500 error" to come through segment as well. 
The presence of both errors is indicated in the attached screenshot.
In addition to the `config.exceptions_app` fix mentioned above, I had to pass an anonymous_id to segment's tracking service (wasn't before, segment was complaining) https://github.com/empirical-org/Empirical-Core/blob/develop/app/services/analytics/error_analytics.rb#L9-L10.

**Comment by marcellosachs** [comment]
![screen shot 2016-02-08 at 10 18 19 am](https://cloud.githubusercontent.com/assets/1789723/12889611/bd2db64c-ce4d-11e5-8b28-ac13fc6dda13.png)
