### ISSUE TITLE
Ryan Update APIs and Addresses 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1203]
# School Selection Moment of Truth
- User adds a school
- The user table updates with the city, state and zip of the school

# API fetching location. 
- User does not add a school and presses skip
- the IP address is sent to the Telize API, which returns the city, state and zip. 
- This data is written into the User table. 

# Updating Location
- If the user updates their school, it will also update the city, state, and zip on their user table. 
- If the user updates their IP address, it does not update the user table. 

# Backfilling old Users 
- Backfilling the old users - we backfill all users except for the ones that have a 10005 zip code? 
- Ignore all 10005 updates. 
- Add them and then delete.

**Comment by RyanNovas** [comment]
##Architecture

In talking with Marcello about architecture, and Elliot about querying needs, my plan is to make a ip-location table that is associated with every single teacher. 

This will mean that there will be two potential tables for teacher-location (school location/ip-location). A SQL query can just be made that retrieves ip-location if school is null. So, retrieval will be trivially more complicated, but the database will stay more normalized.

##Tools 

Still looking at these -- right now I like:
- http://dev.maxmind.com/geoip/ (would be totally in-house by looking up ip-address in geolocation csv_ $50

- https://pointp.in/docs/get-started ($12 a month, seems to have a nice Ruby gem)

- http://www.telize.com/ (api $5 or $7 a month)
