### ISSUE TITLE
Teacher Dashboard

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1211]
We have the first pass of the teacher dashboard. There's going to be section above what's in the Zeplin file that we still have to work on: 

![screen shot 2016-01-27 at 11 57 18 am](https://cloud.githubusercontent.com/assets/8131465/12620987/8bc84d0c-c4ec-11e5-9572-3eb1491f4d00.png)

## Design Mockup with notes
https://zpl.io/B36ULW

**Comment by RyanNovas** [comment]
@tomcalabrese where are we reg: this dashboard component?
