### ISSUE TITLE
Admin Dashboard Issues - emails

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Empirical-Core#1217]
Can't add this gmail account as an admin: Qpl.longislandcity@gmail.com. Previously created a Teacher account with this email address, which did not allow us to create an Admin account with the same email. 

Deleted the Teacher account but still unable to create admin with Qpl.longislandcity@gmail.com as the email.

**Comment by RyanNovas** [comment]
@elliotmandel the account is now an admin one.
