### ISSUE TITLE
Numbers Check on Stats Page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1230]
148k Concept Results 

3,804 Students 

5,652 activities completed. 

148 / 3.8 = 38 questions per student. 

5652 / 3804 = 1.6 activities per student. This would imply 23.6 concept results per activity completed. 

Is this right? Perhaps we are counting incorrect attempts as questions? I don’t know how we should handle this. Ideally we might want to count only correct answers or only count the number of questions answered, rather than the concept results. Alternatively, we could use “question attempts” as our main metric - where we say that 148,000 questions were answered, even if that includes one student attempting a question 3 times - (answering the question 3 times?)

**Comment by RyanNovas** [comment]
@petergault where does this stack as a priority?
