### ISSUE TITLE
Ip location not passed to account creation callback worker when signing up with Google

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#1231]
Error: https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/719164-12df9d12-ca8d-11e5-ad22-c81f66b8ceca

Line 86 in sessions_controller

**Comment by marcellosachs** [comment]
came across this today, this will be fixed in the new google-classroom feature

**Comment by marcellosachs** [comment]
(ive done a big refactor of all the google SSO code, so may not make sense to fix before then)

**Comment by RyanNovas** [comment]
@marcellosachs is this issue closed?
