### ISSUE TITLE
fix clever 500 error

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#1242]
make sure i have all i need from clever to look into this
clever.com - there's an app developer login
    login information has been sent through email

information has been forwarded to me in an email

max time = 2hrs to diagnose, then talk to peter

**Comment by marcellosachs** [comment]
Most likely one of these two issues - 
https://app.getsentry.com/empirical-core/production/issues/109944059/
https://app.getsentry.com/empirical-core/production/issues/109723245/

**Comment by petergault** [comment]
# Message 1: Marcello
When we request a user's sections, the response is indeed an instance of Clever::NestedResource, however the response produces errors when calling .collect on it. This is strange, given that Clever::NestedResource includes the Enumerable module, which should respond to .collect. The error is "TypeError: no implicit conversion of nil into String"

> Here is the error trace -
from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby.rb:97:in `+' from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby.rb:97:in `api_url' from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby.rb:166:in `create_request_opts' from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby.rb:211:in `request' from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby/api_operations/page.rb:17:in `initialize' from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby/api_operations/pagelist.rb:26:in `new' from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby/api_operations/pagelist.rb:26:in `each' from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby/api_operations/results_list.rb:23:in `each' from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby/nested_resource.rb:37:in `count' from /app/vendor/bundle/ruby/2.3.0/gems/clever-ruby-0.13.1/lib/clever-ruby/nested_resource.rb:37:in `length' from (irb):22 from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start' from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start' from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console' from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!' from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'


# Message 2: Aashay
Looks like something's up with the config block. Can you show me what your block looks like (replacing keys, of course)? I'm wondering if something is being overridden here, as api_base should be a constant.
Particularly, the one that starts:  Clever.configure do |config|

# Message 3: Marcello
This is Clever.configuration :
<Clever::Configuration:0x007f39061ab968 @api_key=nil, @token=nil, @api_base="https://api.clever.com/", @timeout=120, @open_timeout=30>
Strangely enough, it seems like api_base is present.


# Message 4: Aashay
I suppose it's probable that the error message is a bit misleading. Is your token attr actually nil? Nothing will work with a nil token (you'll have to provide a district token to the config object before you use it).

# Message 5: Marcello
looks like it's an issue with supplying a token at some point.

**Comment by aashay** [comment]
Hi team,

Can you guys give me a little more context on how you're pulling tokens from Clever? If you're looking at the sections resource, that means you need to use a District token (not a user's OAuth2/Instant login token), which gets pulled via a GET to /oauth/tokens:  https://clever.com/developers/docs/explorer#endpoint_identity_token

You can verify a token's validity using cURL as well.

**Comment by marcellosachs** [comment]
Hi @aashay , looking at this today. Going to clean up our code about around this feature, and then write out a description of the context in which we use clever. Thanks again for helping us.

For my personal notes - this is a recent write-up related to a recent bug in our clever integration- https://docs.google.com/document/d/1SdWITR7V5ysPSO_G4wDKL3C9YHVdqZidMbcp7v8z-Zw/edit?usp=sharing

**Comment by marcellosachs** [comment]
Hi @aashay , a quick question for you when you have a moment - 
It seems we implemented a feature where districts can 'sign up' and when they do, we persist a record of them in our db, and also import the associated schools.

When a teacher signs up, however, it seems we can also import that teachers district by just calling `.district` on the teacher object produced in CleverRuby https://github.com/Clever/clever-ruby/blob/a78cb04ecde44f9739ebf3c92cbb41813fb984ad/lib/clever-ruby/teacher.rb#L5

If this is the case, it seems we can get rid of our feature where districts 'sign up'.
If we need a district for its token to retrieve Sections or other resources, we can just get the district using a clever teacher object. Am I right on this?

Thanks!
-Marcello

**Comment by marcellosachs** [comment]
Hmmm I think I may understand it now - 
A teacher can retrieve her district, but the response will not include a token.
To get a district token, we need our district sign up feature. (Or we need to make requests to /oauth/tokens).
Does that make sense?
Thanks,
Marcello

**Comment by marcellosachs** [comment]
(I'm still a bit confused about how CleverRuby Teacher objects can make requests for linked_resources (sections, classrooms, etc.) without a district token. Perhaps clever knows the district authorized us on their end).

**Comment by marcellosachs** [comment]
Hmmm.. perhaps the reason a CleverRuby Teacher object can request the kinds of things that would normally require a district token is that one needs a district token to retrieve a CleverRuby Teacher object in the first place...

**Comment by marcellosachs** [comment]
this is I believe the desired process : 

**writ large**

district signs up
	persist to db with its id, name, token

teacher signs up
	retrieve district id
	if district_id matches district in our db, then
		import school
		import classrooms
		import students

student signs up
	retrieve sections
	if any sections match a classroom in our db, then
		persist to our db, join classroom


**in detail**

district signs up
	persist to db, incuding its clever id, name, token (all taken from auth_hash)

teacher signs up
	district_id will be in auth_hash
	if district_id matches a district1 in our db, then
		clever_teacher = Clever::Teacher.retrieve(teacher_id, district1.token)
		save_teacher_to_our_db(clever_teacher)
		import (and persist to db) school (by calling clever_teacher.school)
		import (and persist to db) sections (as classrooms) (by calling clever_teacher.sections)
			for each imported section
				section = Section.retrieve(section_id, district1.token)
				import (and persist to our db) students (by calling section.students)

student signs up
	district_id will be in auth_hash
	if district_id matches a district1 in our db, then
		clever_student = Clever::Student.retrieve(student_id, district1.token)
		sections = clever_student.sections
		if any section matches a classroom in our db, then persist student to our db have it join that classroom
