### ISSUE TITLE
Premium Page & Trial 

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1245]
- [x] This zeplin page: https://zpl.io/Z1RNVl7 will replace https://www.quill.org/premium for a signed in and signed out user. Make sure to read the comments in the zeplin file. 

- [x] These two sections will have part of the premium page below them. 
![screen shot 2016-02-09 at 3 08 35 pm](https://cloud.githubusercontent.com/assets/8131465/12929019/b3a329bc-cf3e-11e5-8426-28f9abddd47f.png)
![screen shot 2016-02-09 at 2 39 06 pm](https://cloud.githubusercontent.com/assets/8131465/12929020/b3a386e6-cf3e-11e5-9935-dd6eae96d44c.png)
This is the section of the premium page that we want under these two bars:
![screen shot 2016-02-09 at 3 10 24 pm](https://cloud.githubusercontent.com/assets/8131465/12929070/dfbb0588-cf3e-11e5-89d6-150600e4d1c0.png)

- [x] Link the text 'pricing plans' to the premium page
![screen shot 2016-02-09 at 3 09 37 pm](https://cloud.githubusercontent.com/assets/8131465/12929085/f6eb0b0e-cf3e-11e5-8fef-7e5687222528.png)

- [x] When a user clicks "Get Premium Free for 30 Days” it will take them to the success page seen below 
![screen shot 2016-02-09 at 3 15 11 pm](https://cloud.githubusercontent.com/assets/8131465/12929145/4b005d7a-cf3f-11e5-82b9-e4b99545760f.png)
![screen shot 2016-02-09 at 3 08 35 pm](https://cloud.githubusercontent.com/assets/8131465/12929019/b3a329bc-cf3e-11e5-8426-28f9abddd47f.png)

- [x] Setup Stripe for Teacher Premium  

- [x] Set up tracking on the backend to make sure we're activating timed trials, and are able to see them for drip campaigns 

- [ ] Create transactional email for new Premium user (Personally welcome you to Quill as a premium user, if it is for another teacher, please email us. I am here to help - my number is ________. Call at any time.)

- [ ] Set up drip emails for "In trial mode" mode user, and "Expired trial mode" user

**Comment by tomcalabrese** [comment]
Bugz Life:

Dashboard
- [ ] Make sure when a teacher signs in that it goes to dashboard first, when I log in to another teacher it goes to scorebook first.
- [ ] Lowest Performing Student Image not showing
- [ ] “assign activities” buttons does not go away when I assign activities to the whole class, only when they complete them. we need to change this.
- [ ] The Premium Trial box in the top right of the dashboard page is missing
- [ ] When logged into an active teacher and click “view all student results” it comes up as a 404 error

Student Reports
- [ ] It’s not showing the orange bar under the Concepts, Common Core Standards, or Activities tab page.
- [ ] When you click “Try it Free for 30 Days” button nothing happens.

Premium Page
- [ ] The tabs under “Try Premium for Free” should be “Pricing”, “Example” and “Questions"
- [ ] Remove from the old price table to the “talk with anytime” line — we want to remove this whole section.
- [ ] For the School & District Premium table it says “district wide” it should be “district-wide"

Tabs
- [ ] When you’re in the Student Reports the tabs jump a bit, and you see the green background.

**Comment by tomcalabrese** [comment]
Urgent fixes that need to be resolved before launch:
- [ ] When a user logins in it current goes to: https://staging.quill.org/teachers/classrooms/scorebook it should go to the teacher dashboard page.
- [ ] With a teacher who has a lot of activities (beth) the “View Results” button links to local host
- [ ] A Premium user is getting the trial messages. Box on dashboard, tab, and bar on Student Reports pages
- [ ] For Beth, the boxes: Struggling Students, and Difficult Concepts are not appearing.
- [ ] "Learn more about Premium” under https://staging.quill.org/teachers/classrooms/scorebook goes to the wrong Premium page

Shortly after launch:
- [ ] Pixel tab, overlaid.
- [ ] A user should not be able to “Download Report” if they didn’t activate the trial or are paying for premium. Modal about activating the trial
- [ ] Clicking “Free Trial” on the Premium page doesn’t work
- [ ] When a user activates the trial the bar should be the green background one with the green button.
- [ ] When a user activates the trial, the Premium Tab still says “Try Premium for Free” it should go into the countdown.

**Comment by RyanNovas** [comment]
Remaining issues have been moved to https://github.com/empirical-org/Empirical-Core/issues/1246
