### ISSUE TITLE
⭐ Update Sign Up & Login Pages ⭐

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1262]
Updating the SSO with google and clever. Along with a few design updates. Please take a look at the Zeplin comments for further directions. 

![screen shot 2016-02-18 at 9 33 59 am](https://cloud.githubusercontent.com/assets/8131465/13146104/222e3a86-d622-11e5-82af-a5009401ada9.png)

New teacher sign up page:
https://zpl.io/ZOU4yB

![screen shot 2016-02-18 at 9 34 13 am](https://cloud.githubusercontent.com/assets/8131465/13146113/2a45c46e-d622-11e5-9878-92022ecbc2b4.png)

New student sign up page:
https://zpl.io/Z1Hg33W

![screen shot 2016-02-18 at 9 34 22 am](https://cloud.githubusercontent.com/assets/8131465/13146124/3bd8c5aa-d622-11e5-8b2f-21c4a3daf4ba.png)

New login page:
https://zpl.io/17Kai1

**Comment by RyanNovas** [comment]
buttons and copy have been updated -- i need to fix the button css so the images never get resized.
