### ISSUE TITLE
Activity Pack Creator defaults to the 2nd step

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1274]
When you load the planner, the bar is filled up. Only half the bar should be loaded. 

![screen shot 2016-02-21 at 12 18 29 am](https://cloud.githubusercontent.com/assets/3667179/13201088/d80c6da4-d830-11e5-8ec6-098f3adb9eb9.png)

**Comment by ddmck** [comment]
https://github.com/empirical-org/Empirical-Core/pull/1282 fixes this
