### ISSUE TITLE
Google Classroom bug with existing teachers signing up for a class

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1286]
I signed up for Google Classroom with an existing Quill teacher account, tom@quill.org. In Google Classroom I invited students, had one of them join. Then I tried to sign up for Quill as a teacher account with Google (the associated Google Classroom tom@quill.org account)

![screen shot 2016-02-23 at 3 31 50 pm](https://cloud.githubusercontent.com/assets/8131465/13266424/10396c2e-da46-11e5-8df4-7226d9f7c33f.png)

Then right after I hit accept it takes me to:

![screen shot 2016-02-23 at 3 32 17 pm](https://cloud.githubusercontent.com/assets/8131465/13266445/23c943c2-da46-11e5-94f9-11abd42fcf2f.png)

And whenever I try to sign in through Google it keeps taking me to this screen.

**Comment by petergault** [comment]
@marcellosachs It seems that rather than starting the sign up flow, it should be checking if you already have an account. If you do, it should not bring you through the auth flow and instead show an alert that says "you already have registered with google, please log in through it."

**Comment by marcellosachs** [comment]
I wasn't able to repo with my test google classroom account, then @tomcalabrese pointed out it's likely caused by the fact that his account is a staff account.
