### ISSUE TITLE
Flatdoc 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1290]
https://github.com/rstacruz/flatdoc

Grab all of the readmes and pull them together. 
Can you grab readme's from multiple github repos?

**Comment by marcellosachs** [comment]
@petergault I don't think this is what you're looking for, it basically just takes the main README file of the app and embeds it in a website whose stylings are a bit nicer / more customizable than github. I dont think it pulls in all the READMEs within a repo.

**Comment by petergault** [comment]
https://github.com/rstacruz/flatdoc/issues/15
