### ISSUE TITLE
Google Classrooms and Drip Campaign Email 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1302]
Problem: It seems that teachers who are using Google Classroom are still getting the drip campaign emails to set up a classroom because that segment event did not fire. It seems that if a teacher imports a classroom through Google, it should cause that event to fire at some point. 

Teacher with issue:
https://docs.google.com/document/d/1Y_AnrESB36ELKic-T8OVJ-vDXJDNyqnh1aCqkG3yq7s/edit

**Comment by RyanNovas** [comment]
There is probably a callback on classroom creation that triggers the segment event. The google integration is likely circumventing it and needs to also trigger this callback.
