### ISSUE TITLE
Dataclips Confusion

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1323]
Data Clips "Location of Teachers by Country" shows a different number of users in India than a search in Intercom. Why is this?

**Comment by RyanNovas** [comment]
Looking into this now. @petergault can you link to relevant data clips when you post these going forward?

**Comment by RyanNovas** [comment]
The ip locations are fixed -- there were two problem sources:

1. The dataclip was pulling from staging.

2. the rake task toa ssociated all accounts with ip locations had not been run on prod.
