### ISSUE TITLE
Sections are not displaying in the proper order

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1333]
The sections are not displaying by the order assigned to them in the CMS. 

![screen shot 2016-03-21 at 11 30 41 am](https://cloud.githubusercontent.com/assets/3667179/13923825/7713bbd0-ef58-11e5-909a-275f49e260b6.png)

![screen shot 2016-03-21 at 11 30 48 am](https://cloud.githubusercontent.com/assets/3667179/13923829/7aef5eb2-ef58-11e5-9a24-295c66ef0aa3.png)

**Comment by RyanNovas** [comment]
#1335 fixes this
