### ISSUE TITLE
Improve copy on Build your own Activity pack box.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#1341]
![screen shot 2016-03-24 at 14 40 44](https://cloud.githubusercontent.com/assets/3110565/14027537/7d49e394-f1ce-11e5-94da-99b276544fd0.png)

Possibly specifying that it's from X number of premade activities. 
It kind of sound's like a lot of work at the moment.

**Comment by petergault** [comment]
Suggestion:
Change the word build to **Create**
Add the sub-title: *Select from over 150 grammar exercises.*
