### ISSUE TITLE
Improve CSS and design of classroom boxes on dashboard.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#1342]
![screen shot 2016-03-24 at 21 06 26](https://cloud.githubusercontent.com/assets/3110565/14035427/7c0c5792-f204-11e5-8535-373a17c63184.png)

The current style doesn't really support long class names that well. 
CSS shouldn't allow the button to escape the box.

**Comment by tomcalabrese** [comment]
Maybe we should limit the title to a certain length and then do the dots "..."
