### ISSUE TITLE
Student Dashboard - Multiple Classes / Teachers

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1347]
Student Dashboard with Multiple Classes mockup:
https://zpl.io/Z17F62I

Student Join a Class:
https://zpl.io/17W0hQ

Successfully Joined Class - Add another why don't ya:
https://zpl.io/Z1Qw4MU

Class Settings:
https://zpl.io/ZJKH8y

**Comment by ddmck** [comment]
Done by @RyanNovas
