### ISSUE TITLE
Retry, resume, and start lesson in Student Dashboard

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1392]
Currently, there are three states of an activity in a Student's Dashboard — retry, resume, and start lesson. But it only says "start lesson", we need to change this. 

![screen shot 2016-05-09 at 12 15 37 pm](https://cloud.githubusercontent.com/assets/8131465/15119659/f653430e-15df-11e6-9869-1a5c82067918.png)

**Comment by emilia-friedberg** [comment]
If the current activity session state is unstarted, show "Start Activity." If started, show "Continue Activity," and if finished/completed, show "Replay Activity."

 ### Notes for Resuming Started Activity When the Student Has Previously Completed the Activity

If you complete an activity, it shows up with the option to replay it. When you start it again, but don't finish it, it'll currently display the results of the finished activity and the option to replay it. It should display the option to resume it, but the results of the previously finished one.
