### ISSUE TITLE
Allow teachers to unarchive classes

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1414]
Right now in the teacher's class manager they can delete a class, which is just hiding it — basically archiving it. We need to change this from "Delete Class" to "Archive Class"

![screen shot 2016-05-18 at 5 05 49 pm](https://cloud.githubusercontent.com/assets/8131465/15374931/b1221bd8-1d1a-11e6-8eff-accf03fa1fe1.png)

We could follow a similar logic as we did for the student's class manager: 

![screen shot 2016-05-18 at 5 06 27 pm](https://cloud.githubusercontent.com/assets/8131465/15374930/b11f0632-1d1a-11e6-9d41-333cd1686b39.png)

**Comment by RyanNovas** [comment]
Done
