### ISSUE TITLE
Revised Educator Sign Up Flow

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1415]
[Join a new class](https://zpl.io/Z2iLhCE)
[Faculty member?](https://zpl.io/ZoLtXB)
[Find your school](https://zpl.io/3mlXo)
[Type of educator](https://zpl.io/wehmj)

Once we have these pages created we'll want to attribute any of the "type of educator" responses as completing the "add your school" in the teacher guide checklist.

**Comment by tomcalabrese** [comment]
We need to revise this checkbox once we implement this new sign up flow

![screen shot 2016-06-02 at 10 49 31 am](https://cloud.githubusercontent.com/assets/8131465/15752913/554d25dc-28be-11e6-9616-e416ef03b4d4.png)

**Comment by RyanNovas** [comment]
Above comment moved to #1453
