### ISSUE TITLE
If a request is made to /profile.json while the student has no classrooms a 500 error is raised.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#1426]
Visiting /profile.json as a user who has no classrooms raises a 500 error.

This is because if there is no classrooms for the student the server tries to render the student_classrooms/add_classroom template, which does not exist for json responses.

We should return some sort of empty json response instead.

https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/7199e1-d612e302-241f-11e6-b894-c81f66b8ceca?original_error_id=7199e1-f9da6389-241f-11e6-b894-c81f66b8ceca

To reproduce, log in as a new user with no classrooms and try to access profile.json.

I can't see anywhere in the code that we try to access this. So maybe someone is deliberately trying to access it. Or it could be that when new users return they go straight to profile and cause the error there.

**Comment by RyanNovas** [comment]
#1461 takes care of this
