### ISSUE TITLE
Create link from Class Code to share with students

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1434]
We can easily create automatic links from the teacher's class codes that teachers can share with their students, maybe even with a pre-created email or printable pdf

![screen shot 2016-06-03 at 5 03 43 pm](https://cloud.githubusercontent.com/assets/8131465/15792693/dd24e2a8-29ac-11e6-83f6-aa1aec4c02c3.png)

**Comment by petergault** [comment]
moving to ideas repo.
