### ISSUE TITLE
Classroom Drip might be broken

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1447]
A teacher claims that she created a classroom but continued to receive our drip campaign to create a classroom. The teacher’s info is in the linked page. She claims to have created the classroom before June 12th at 8:52 pm, which is when the email was sent. 

https://docs.google.com/document/d/1B2EX798N_kPtxgxIUxO2gQq0cGvonOMtlyvsOvhcETA/edit

**Comment by RyanNovas** [comment]
@tomcalabrese  and I learned that there are 374 people who have assigned activities, but intercom has not flagged as having any classrooms. These people are probably all receiving unnecessary drips. 70% of them are Google or Clever users. Of the other 30% only about a dozen were from 2016, so the innacurracy rate here doesn't seem to justify looking to far into them. I will revisit this query `User.find(ids).select{|x| !x.signed_up_with_google && !x.clever_id}.map(&:created_at)` (where ids is teachers without a classroom, but with activities or students) has grown significantly and decide whether to pursue it then.

In the short term, Tom is going to adjust the drip so it has a filter excludes those who have added students, assigned activities, or whose students have completed have completed activities.

In the long term, I will make a callback for classroom creation that will fire off an intercom event regardless of whether a user is a Clever/Google user.
