### ISSUE TITLE
Activity Planner - with Diagnostic

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1462]
Read the comments in the Zeplin file:
https://zpl.io/1sFWIn

- Revised navigation in the Activity Planner, "My Activities" & "Assign a New Activity"
- I changed the header and navigation height, you can ignore that for now

**Comment by RyanNovas** [comment]
PR #1469 does this -- diagnostic is designed but commented out until we have the rest of that feature live
