### ISSUE TITLE
Custom Dashboards to Review

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1470]
- Two options:
- We could do dataclips > sheets > awesome table > google sites. 
Link to google sites. 
- Or we could grab the dataclips json, put in Victory (as a table). 

- show the scores of students per grade level. 

Once the custom dashboard functionality is running, review the scores following dashboards:
# Sentence Structure:

Expanding Simple Sentences With Adjectives
Complex Sentences
Compound Sentences
Parallel Structure
# Coordinating and Subordinating Conjunctions:

Comma before Coordinating Conjunctions
Nor, Yet
Unless, Until, When
After, Although, Since
Before, By the time, Even though
Whenever, While, Because
Even if, Every time
Once, Since, So that
The first time, As soon as, Than
# Commonly Confused Words:

A Lot, All Right
Regardless, Figuratively
# Prepositions:

After, During
To, Over, Toward
Into, Through
Between, Beyond
From
# Verb Tense:

Subject Verb Agreement
Pronoun-Antecedent Agreement
Future Tense Verbs
# Irregular Verbs:

Bought, Flew
Took, Spoke
Paid, Drove, Became
Irregular Nouns “ves”
Swam, Ran, Broke
Ate, Met, Cut
Dug, Drank, Fell
Swam, Ran, Read
Grew, Gave, Heard

**Comment by ddmck** [comment]
@petergault What info are these dashboards support to provide.
