### ISSUE TITLE
Revise header / tabs for teacher interface

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1472]
Problem:
Right now the height of the header for the teacher LMS is pretty tall and teachers need to scroll a lot to access most of the content. Also, the tabs are long and don't allow for a great responsive experience when the browser width is small.

Solution:
Tightened up the height of the navigation, tightened the width of the tabs, reduced the size of the Quill logo. 

Full-width header:
https://zpl.io/jMQfa

Mobile header:
https://zpl.io/Z2sCC1Q

**Comment by RyanNovas** [comment]
@tomcalabrese can you give me an svg of the logo please
