### ISSUE TITLE
Assigned Activities are going to Archived Classrooms

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1490]
From a teacher:
I first archived classrooms from last school year, and then assigned an activity pack to a group of learners. The assignment went to all of the archived classes

Are activity packs going to archived classrooms? Are they showing up on activity planner?

**Comment by RyanNovas** [comment]
I need more info to begin trouble shooting this. What teacher, what students, etc....

**Comment by RyanNovas** [comment]
Unable to reproduce this or find evidence. Reopen if another report comes in
