### ISSUE TITLE
Enable continuous deployment

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#1504]
When Travis passes deploy develop to staging and master to prod. 

This will cut down on the time spent waiting for me to deploy new builds.
Also will enforce us to keep the test suite green.

**Comment by Echelon9** [comment]
Almost there on Travis passing:
```
Finished in 9 minutes 4 seconds (files took 7.59 seconds to load)
752 examples, 9 failures, 22 pending
```

**Comment by ddmck** [comment]
@Echelon9 Finally got a passing test suite, thanks to @jaredsilver tidying up and adding Jest + Enzyme to replace our flaky integration tests.

**Comment by Echelon9** [comment]
Great news. Well done @jaredsilver and @ddmck.
