### ISSUE TITLE
Remove student info when there are no students

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1510]
Currently, if a class has no students in it we still show part of the spreadsheet for student info:

![screen shot 2016-07-25 at 5 57 31 pm](https://cloud.githubusercontent.com/assets/8131465/17119344/4b6e3926-5293-11e6-81d4-5c89b0696119.png)

Solution:
Remove/hide the form until there are students in the class.

**Comment by RyanNovas** [comment]
#1528 resolves this.
