### ISSUE TITLE
User Manager - EDIT feature not working/loading

### ISSUE THREAD

**Issue by yuwenmich** [empirical-org/Empirical-Core#1517]
In User Manager when you select the EDIT button the page that shows up is attached in a screen shot below. This issue happens regardless of Browser (safari or chrome) or Quill admin. It didn't work for myself (Yuwen) or Tom. 

This issue is also occurring for **all** teacher accounts in User Manager 

![screen shot 2016-07-28 at 2 27 46 pm](https://cloud.githubusercontent.com/assets/16887932/17225118/9f1616f8-54d1-11e6-9e99-04c907cd4776.png)

**Comment by RyanNovas** [comment]
fixed by #1519
