### ISSUE TITLE
Google Classroom Sync & Import Pages 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1536]
The Designs:

https://app.moqups.com/gault8121/mCho0yeSOv/view
# Note: Tom Design

Tom should think a bit about the design on this before we formalize it. 

@tomcalabrese EdPuzzle does a nice job with the Google Classroom sync - we may want to look there to see how they do it. 
# The Card

![screen shot 2016-08-09 at 11 18 40 pm](https://cloud.githubusercontent.com/assets/3667179/17541040/b243ae54-5e89-11e6-8ccc-08716a9431db.png)
# The Modal

![screen shot 2016-08-09 at 11 31 32 pm](https://cloud.githubusercontent.com/assets/3667179/17541025/88bb2eb8-5e89-11e6-8bce-73427e9c89b0.png)
# Feedback

The following states should display somewhere - (Not sure where):
1. Success - We  have imported your data. 
2. Unsuccessful - We could not get your data. 
3. No Account Found - We could not find a Google Classroom account associated with your Quill account.

**Comment by tomcalabrese** [comment]
## Final design mockups

Sync with Google Classroom:
https://zpl.io/2jpM1j

Import with Google Classroom:
Dashboard - https://zpl.io/ZiEHDN
Modal - https://zpl.io/Z2105TK

**Comment by RyanNovas** [comment]
As of PR #1984, this is done, except for the feedback section.

@petergault, this action requires a redirect to the Google Classroom authentication. There certainly is a way to give them status updates, but that will be a project better suited for once we have web sockets. Right now, the time vs payoff is too high. Google Classroom will tell them if their email is invalid, and I think that gets us 85% of the way to where we want to be.
