### ISSUE TITLE
App Data Has Wrong Names

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1540]
![screen shot 2016-08-11 at 1 11 57 pm](https://cloud.githubusercontent.com/assets/3667179/17597743/408e7acc-5fc5-11e6-9c32-edf97f54ff8b.png)

**Comment by RyanNovas** [comment]
@petergault what do you want instead?

**Comment by petergault** [comment]
@RyanNovas Quill Grammar and Quill Proofreader

**Comment by emilia-friedberg** [comment]
@ddmck it looks like changing the name should be safe and will update the display name on the page in the issue screenshot (Premium List View). The Activities table in Rails Admin refers to the activity classifications by name rather than by key, which should probably be changed.
