### ISSUE TITLE
User Bug - Cannot Reproduce 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1543]
With certain student accounts, assigned activities do not show up. 

# NonWorking Account Example. 

### Teacher account 
- With quill.org/demo
- Go to assign and assign a new unit. 

### Student account. 
- As a student, I cannot view the unit. For example, Margret Atwood doesn't work. 
- Username: trystudentdemo
- Password: Atwood

# Working Accounts

This account works. 

### Teacher Account
teacher
demo

### Student Account
ryan.rhombus@yummy-move
Rhombus

With this account, I can assign a unit.

**Comment by RyanNovas** [comment]
@petergault, this seems to be confined to the demo account.

The demo is set up very irregularly (via a rake task) and is probably missing some of the db relationships that exist for any regular user, hence the issue.

I tried this on several regular accounts and was unable to reproduce. @ddmck, do you know off the top of your head how your rake task may have caused this issue? It could be bad for users prodding around in the demo account.
