### ISSUE TITLE
Pagination partially broken

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1556]
Once a user clicks past page 13 the background color behind the numbers don't change and they stay on page 13. 

![pagination](https://cloud.githubusercontent.com/assets/8131465/17701739/f773c55e-6398-11e6-8eb2-b33e2d2dcc72.gif)

**Comment by petergault** [comment]
To reproduce, limit the view to a set number of pages (such as by selecting 4th grade ccss). The pagination will not update once you move to the last 4 pages.
