### ISSUE TITLE
Duplicating Classrooms in Google Classroom

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1558]
If a teacher signs in through Google Classroom and then archives a classroom, Quill creates a new version of the classroom the next time the teacher signs in. It seems Quill's Google Classroom Update is checking the teacher's Google Classrooms against the teacher's live Quill classrooms. Instead, it should check against all of the classrooms, both archived and non-archived.

**Comment by RyanNovas** [comment]
Solved by PR #1564
