### ISSUE TITLE
Check Google Status on Sign On

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1571]
With the peter@quill.org account, I signed up and then signed in through google. However, my google sign-on status is false, even though I can successfully sign in through google. 

The site should check if I am signing in through google and then update my status to true if I do so. 

![image](https://cloud.githubusercontent.com/assets/3667179/17792774/ce8714fa-6570-11e6-9b26-50b47cd17db2.png)

**Comment by RyanNovas** [comment]
unable to rep
