### ISSUE TITLE
Update Password Reset Message Location

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1573]
This element should be:
- [ ] more padding should be added
- [ ] the color should be changed to a light yellow
- [ ] the text should be centered. 

![screen shot 2016-08-18 at 6 09 44 pm](https://cloud.githubusercontent.com/assets/3667179/17792811/0c2acf2c-6571-11e6-881e-569bd2385c5d.png)

**Comment by ddmck** [comment]
Just move these notifications to the top now. The code is in the application layout.

Bigger, centered text, colored background depending on severity. More padding. X to close.

I'll follow up with a lo-fi mockup.
