### ISSUE TITLE
Update Dropdown Of Units for Visual Overview

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1582]
![screen shot 2017-01-19 at 8 00 59 pm](https://cloud.githubusercontent.com/assets/3667179/22131543/26017aa6-de82-11e6-9ae1-f2b9bce9ba84.png)

In the teacher dashboard "overview" page, add the following options to the Activity Pack selector. 
- [ ] Add "Completed Activities". Filters all completed activities 
- [x] Rename "All Units" to "All Activity Packs"
- [ ] If a teacher has no completed activities, show all assigned activities by default.
- [ ] If a teacher has a completed activity, show all completed activities by default. 
- (The goal is to avoid showing a blank page for new teachers getting started). 
- note: if it is slow to make the decision to show either completed or assigned based on number of activities, let's brainstorm something else. 
- The order of the dropdown:
1. Completed Activities
2. Assigned Activities 
3. All Activity Packs 
4. Pack 1
5. Pack 2, etc.

**Comment by ddmck** [comment]
This might be out of date, but investigate regardless.
