### ISSUE TITLE
In Progress Sessions 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1584]
- [ ] If a user has started a session, update the color of the cube & the icon to show that it is in-progress. This helps teachers see which sessions students have not finished. 
- [ ] To see if a session is started, see if there is a started at but not a completed at. 
- [ ] The tool tip has a special note at the bottom. "The student has started this activity but has not yet completed it. If a student is having issues saving their results, please ask them to sign out, sign in, and then re-submit."
- Note: instead of showing the clock over the icon, we may want to preserve the activity's icon and show a clock in the upper right corner to communicate this is a special state (while also preserving the activity's icon).

![screen shot 2016-08-23 at 11 27 14 pm](https://cloud.githubusercontent.com/assets/3667179/17917332/643555c2-6989-11e6-82a7-d2c9134ee5d3.png)

# Note
- students know if they are in a resume state or a start state. If it is resume, the activity is flagged. 
- A second option is to put a little clock in the upper right corner and make the activity blue, while preserving the app's icon (instead of swapping the app with a clock.

**Comment by ddmck** [comment]
There might be an issue where once a student has completed the activity once, new attempts cannot always be resumed.

In the case where a student has completed it once, but may have an abandoned retry, we should show the completed icon in the dashboard.
