### ISSUE TITLE
Hide 'Manage Class' for Inactive Classes

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1610]
Currently, a user can click 'Manage Class' for inactive classes but it just goes to an error page. We should remove it and only allow users to unarchive. 

![screen shot 2016-09-02 at 10 32 20 am](https://cloud.githubusercontent.com/assets/8131465/18207309/aba96562-70f8-11e6-8eb2-accb95c8ff39.png)

**Comment by jaredsilver** [comment]
This appears to have been fixed already 😃

**Comment by petergault** [comment]
@emilia-friedberg please remove manage class anyways for archived classrooms.

**Comment by emilia-friedberg** [comment]
@petergault  Jared was right, this is already the case. Is there something else you want here?

<img width="1206" alt="screen shot 2017-01-20 at 10 40 59 am" src="https://cloud.githubusercontent.com/assets/18669014/22155320/fc4e2558-defc-11e6-846a-4681e53cd5a8.png">
