### ISSUE TITLE
Google Classroom - Pulling too much info 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1613]
An admin google classroom user is getting all of the classrooms for the entire school pulled into Quill. 

- The right thing to do now is that when you sign in with google classroom, you get a page where you choose which classrooms you want to import. 

I just want to make you aware of a little glitch when signing on with my Google Account.  When I agreed for it to access my info it brought in all Google Classrooms in our building, not just the ones that I set up in my Google Classroom account. It may be related to the fact I am the Google Admin for our building so my Google ID accesses the Admin panel.  I have not had that happen in any other online programs where I have linked my Google Accounts/Classrooms.

**Comment by ddmck** [comment]
This is a duplicate issue
