### ISSUE TITLE
Adjust class code in the invite students page

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1617]
If a class code is longer in length you can't see all of it unless you scroll through. We should just extend the length of the box. 

![class_code](https://cloud.githubusercontent.com/assets/8131465/18293472/e99be44c-7460-11e6-8408-f1eff8c63ce2.gif)
- [x] We should also add more fault tolerance to the class code box. For example, we ignore all spaces in the box. 
- [x] We track every time a student fails to input a correct code and build more logic to better connect them with their classrooms. 
- [x] The box exists on the manage classrooms page and the create a classroom page. Make sure the size is updated in both locations.

**Comment by RyanNovas** [comment]
Box does not exist on create classrooms page -- all else is done
