### ISSUE TITLE
Reorganize Pages / Navigation

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1633]
## Link
https://docs.google.com/document/d/1bn3wEYXABVKlPny5fEcYFPXihf98e9IJHm_YOIMwy7s/edit

Here's a link that explains the new structure. 

## Overview

We're reorganizing pages and tabs to make more sense for users along with showcasing new content. 
## New Navigation
- [x] Tools
- [x] Resources
- [x] About Us (Our Story?)
- [x]  Login
- [x] Sign Up

---

![screen shot 2016-09-13 at 12 35 38 pm](https://cloud.githubusercontent.com/assets/8131465/18482602/cbefa3b8-79ae-11e6-9562-629f7037f2cf.png)
### Tools
- [ ] **Quill Connect** (default tab)
- [ ] **Quill Diagnostic**
- [ ] **Quill Proofreader**
- [ ] **Quill Grammar**

These will be landing pages for each tool. There is an issue with the design of these pages. 

---

![screen shot 2016-09-13 at 12 35 49 pm](https://cloud.githubusercontent.com/assets/8131465/18482623/e01d3210-79ae-11e6-8229-6b9b2a03e249.png)
### Resources
- [x] **Topics** (default tab) - Currently, this is the [Activity Packs](https://www.quill.org/activities/packs) tab. For signed out users we're going to remove the blue banner and the sorting labels "All, Elementary, etc." will be in the subnav under the Topics tab.
- See the google doc for a discussion on the link structure. 
- [x] **Standards** - Grabbing from the current [Activities tab](https://www.quill.org/activities/section/7). Removing the "Benchmark Assessments" link.
- See the google doc for a discussion on the link structure. 
- [x] **Getting Started** - This it the current wordpress [iframed page](https://www.quill.org/teacher_resources). 
- [x] **FAQ** - Moving the [current page](https://www.quill.org/faq). 
- [x] **Premium** - Moving the [current page](https://www.quill.org/premium).
- [x] "Topics, Standards, and Premium" are the only tabs that have subnav links. See the images to see what the links are. 

![screen shot 2016-09-13 at 12 35 59 pm](https://cloud.githubusercontent.com/assets/8131465/18482684/1f474f20-79af-11e6-8591-dc045cac85a6.png)

![screen shot 2016-09-13 at 12 36 08 pm](https://cloud.githubusercontent.com/assets/8131465/18482683/1f405756-79af-11e6-856f-64bc9d3b322e.png)

---

![screen shot 2016-09-13 at 12 36 19 pm](https://cloud.githubusercontent.com/assets/8131465/18482667/0a52adee-79af-11e6-84c3-1fb180d57ac4.png)
### About Us
- **About** - Move from [current page](https://www.quill.org/mission). 
- **Impact** - Move from [current page](https://www.quill.org/impact).
- **Team** - Move from [current page](https://www.quill.org/team).
- **Partnerships** - Will be from [wordpress page](https://community.quill.org/partners/), once Peter updates copy.
- **News** - Move from [current page](https://www.quill.org/news).
- **Press** - Move from [current page](https://www.quill.org/press).

---

For Tom: 
- [x] Give the same directions for the footer
- [x] Change Press Kit to Media Kit
- [x] In Press page have a thing at the bottom saying, "want to write about us" and link to the Media Kit

**Comment by RyanNovas** [comment]
@petergault let me know when the partnerships page is updated an i'll put it in

**Comment by RyanNovas** [comment]
This is completed up to the tool page.
