### ISSUE TITLE
Diagnostic Lock on Top of Activities 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1665]
# Diagnostic Lock on Top
- [x] The diagnostic unit should always display as the first unit. 
- [x] The diagnostic units should have a button next to the title that says “Recommendations” 
  ![screen shot 2016-08-30 at 12 30 59 pm](https://cloud.githubusercontent.com/assets/3667179/18097846/a573aff6-6ead-11e6-87b6-c4fa94883dc6.png)

**Comment by amr-thameen** [comment]
Zeplink: https://zpl.io/1fta8R
