### ISSUE TITLE
More White Space on Invite Students

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1677]
![screen shot 2016-09-21 at 11 54 08 am](https://cloud.githubusercontent.com/assets/3667179/18718732/8515faf6-7ff2-11e6-9ebf-554a49419616.png)
- More space between the bottom of the student table and the footer.

**Comment by petergault** [comment]
- [ ] The sub-nav tab is not highlighted either at the moment.

**Comment by ddmck** [comment]
- [ ] there should be no table header until there is a student to go in it.
