### ISSUE TITLE
Typo on Community Page

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#1694]
Correct a typo on the community development page. The typo is highlighted in the image below. (I don't have access to editing this code)

![image](https://cloud.githubusercontent.com/assets/20426718/18792271/cddb675c-8183-11e6-9dbd-084fb65b230d.png)

**Comment by Echelon9** [comment]
@Hannahmonk Can be closed now I think. Thanks.

**Comment by RyanNovas** [comment]
@Echelon9 Thanks!
