### ISSUE TITLE
Improve Account Flow - Teachers Signing Up Students

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1809]
There are a few things we need to do to improve the user flow for adding students:

- [x] teachers who didn't sign up with google need the option to import. Many are "signing in" with their account but don't see the option to import.
- [ ] On the teacher creates student accounts page, we need to communicate that if they are a clever or google user, they don't need to do this. Perhaps we lock the page to communicate students should sign in with google. 
- [x] we need to make sure we're properly flagging users as google. We only have 21k google users according to a query, which is def. wrong
- [x] we need to stop sending the drip emails to teachers with google signup. 
- [ ] We need to review the ReadWorks UX (they did a great job for creating accounts) to see if their are other ideas we can implement here. 
- [ ] change the sign up page to make the 3 options email, google, and clever. If they select email, they then see the form. This only applies to teachers. We can't use the word email with students because they don't actually need an email and many schools don't have it.

**Comment by ddmck** [comment]
@petergault Students were not being correctly marked as coming from google, but I fixed that around two weeks ago.

We can possibly work backwords from the google classroom classrooms to correct the numbers if it is important.
