### ISSUE TITLE
Teacher Dasbhoard  - CSS Updates

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1820]
Classroom page:
- When a teacher loads the overview page, it loads all of the possible cards and then removes the ones that it should not show, which  looks like something is broken. Let's just not load those in the first place?

- When a new page loads on the teacher dashboards, let’s start by blocking out a grey section that is the same length as the page. It doesn't look good for it to start with the header and then for the header to drop.

**Comment by RyanNovas** [comment]
@ddmck do you know which PR led to the second issue?

**Comment by RyanNovas** [comment]
The teacher guide gets hidden depending on an ajax call (/components/teacher_guide/teacher_guide.jsx) -- instead, it should be shown depending on the results of the ajax call

**Comment by ddmck** [comment]
I dunno, it was the second week of november, its just in the css for the card.
