### ISSUE TITLE
Bug with Layout of Options 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1826]
- [ ] The four options should be along one row.
- [ ] When an option is selected, it should be highlighted in a green border, similar to the border when you hover over it. 
- [ ] Concept and Standard Level should be on the same row as search.

![screen shot 2016-12-12 at 10 55 29 pm](https://cloud.githubusercontent.com/assets/3667179/21127055/205d337e-c0be-11e6-81da-9796e5913f13.png)

**Comment by RyanNovas** [comment]
PR #1831 solves this
