### ISSUE TITLE
Updates to Page Nav. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1844]
https://quill.org/activities/packs

- [x] The resources link in the very top of the page (next to our story) goes to the wrong page. It should go to the activity packs page. 
- [x] The teacher resources page has the wrong tabs. It should have the sources tabs:
https://quill.org/teacher_resources
- [x] When you click on an individual pack, the sub nav bar disappears. 

![screen shot 2016-12-19 at 11 33 28 am](https://cloud.githubusercontent.com/assets/3667179/21320423/02d4f8fc-c5df-11e6-89dd-9b4cc197b9c5.png)

- [x] on the premium page, the pay with card displays. 

![screen shot 2016-12-19 at 11 33 58 am](https://cloud.githubusercontent.com/assets/3667179/21320453/14b2a3da-c5df-11e6-9a24-62031572f7ec.png)

**Comment by RyanNovas** [comment]
The issue with the headers disappearing upon going to an individual activity pack stems from the divide located at /lesson_planner/unit_templates_manager/unit_templates_manager.jsx

The way we update state will need to be overhauled a level to deal with this -- probably via the this.props.data that gets passed
