### ISSUE TITLE
Not Duplicating Units

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#1868]
# Unit Model Changes

- [x] add teacher ID to unit
- [x] add unique name validation scoped to teacher 
- [x] save teacher ID of current_user.
- [x] add a rake task to add a teacher id to all existing units. Go through classroom activity -> classroom to get the id.

# When an Activity Pack is Assigned

- [x] change to find or create based on unit name scoped to teacher
- [x] throw error to end user if they try to assign an activity pack with the same name as one they have already created
- [x] change to find or create for classroom activity creator
- [x] change to find or create for activity session creator

# Things we may have broken that need to be fixed
- [x] Ensure that new students still get activities assigned at classroom level
- [x] Fix diagnostic controller so it isn't always going through the updater route
- [x] clickContinue unit_stage1 needs to be fixed
- [x] make sure we didn't break activity templates
- [x] make sure we don't presuppose a single classroom in the unit updater

# After everything works

- [x] remove classroom ID from unit 
- [x] remove assigned students from unit
- [x] write tests for diagnostic rec path
- [ ] write tests for units controller uniqueness test
- [ ] write tests to ensure that where query for unit names really is case-insensitive
- [x] write tests for unit_helper.rb
- [ ] make it so teachers can click assign on the recommendation page, then assign some more lessons, without refreshing the page

**Comment by petergault** [comment]
https://docs.google.com/document/d/1BM2gPnHXE-ME2a0D2lOrLUjdbj3pMcm7lyn86VvjVgw/edit notes on the discussion of this issue.
