### ISSUE TITLE
Drop Beta Tags

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1881]
Note: Let's wait two weeks before dropping the beta label from the activities, as there are still some bugs we need to work out. 

- [ ] Remove the word beta from all of the activities. 
- [ ] Remove the word beta from the activity packs.

**Comment by ddmck** [comment]
@petergault Can i drop the beta tags now?

**Comment by amr-thameen** [comment]
We can drop the beta tags now!
