### ISSUE TITLE
Classroom nav bar doesn't scale well. 

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#1897]
https://docs.google.com/a/quill.org/document/d/1_Ke1R8DWVEn61a0x5j8n8h-yxgL3Rr-sYtyqnTk5RTQ/edit?usp=sharing

**Comment by ddmck** [comment]
What should this look like when a student is in more than 3 classes?

**Comment by amr-thameen** [comment]
Zeplin: https://zpl.io/Z1OF8yX

- [ ] Remove the name of the student from the subnav
- [ ] Add a new tab/drop-down if the student has more classes 
- [ ] The name of the student and the class are on the page
