### ISSUE TITLE
Bug  - Teachers See Onboarding Emails 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1918]
Teachers are getting the onboarding reminder messages even if they have created classrooms - it is likely due to Google Classroom. Review these accounts and see if we need to create a segment event called “Google User.’ With this event, we can tell Intercom to not send out certain emails to teachers based on their behaviors.

Note: there are other ways we could solve this for google users. 

**This might not be a google user either.**

Check the Doc for more info and a teacher to review. 

https://docs.google.com/document/d/1dzk0eLHmfDed4k0WIsrrfmh7VEDv0VueH7CpZOD2xSY/edit#

**Comment by RyanNovas** [comment]
should be solved by the classroom creation worker fix in pr #1850
