### ISSUE TITLE
New Card for new tools. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1963]
- Re-use the Beta Diagnostic card design. 
- Learn more is a Quill green button 
- link to the medium announcement. 

> # Two New Writing Tools 
> Use Quill’s diagnostic to assess students and build a learning plan. Use Quill Connect to build sentence structure skills. 
> **Learn More**

**Comment by ddmck** [comment]
@petergault is the medium post live?

**Comment by ddmck** [comment]
I'm linking to the tools page for now.
