### ISSUE TITLE
Important Bug - Students are getting all of the packs 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1969]
Confirmed by peter - students are getting all of the packs, not just the recommended packs. 

https://docs.google.com/document/d/16AT1IShVndYoRt1bAQnT7G2bTda7q_mGCPbU1sXrwL0/edit#

**Comment by ddmck** [comment]
I have fixed the cause of this bug, an empty array signalling that no students are recommended was getting passed to the unit updater, where in the context of classroom activities an empty array meant the entire class is assigned.

we need to write a script to backdate this fix.

```names = ["Compound Subjects, Objects, and Predicates | BETA",
"Adjectives | BETA",
"Parallel Structure",
"Compound Sentences | BETA",
"Appositives and Modifying Phrases | BETA",
"Adverbs of Manner | BETA",
"Complex Sentences | BETA"]

names.each do |name|
  units = Unit.where(name: name)
  units.each do |unit|
    classroom_activities = ClassroomActivity.unscoped.where(unit_id: unit.id)
      classroom_activities.each do |ca|
        #######  PSUEDO CODE
        if ca.assigned_student_ids !== []
          ca.activity_sessions.each do |ass|
             if ass.user_id not in ca.assigned_student_ids
                ass.delete
             end
          end
         end
      end
  end
end
```

**Comment by emilia-friedberg** [comment]
this should work:

names = ["Adjectives | BETA",
"Parallel Structure",
"Compound Sentences | BETA",
"Appositives and Modifying Phrases | BETA",
"Adverbs of Manner | BETA",
"Complex Sentences | BETA"]

names.each do |name|
  units = Unit.where(name: name)
  units.each do |unit|
    classroom_activities = ClassroomActivity.unscoped.where(unit_id: unit.id)
      if classroom_activities.any?
        classroom_activities.each do |ca|
          if ca.assigned_student_ids.any?
            ca.activity_sessions.each do |ass|
               if !ca.assigned_student_ids.include?(ass.user_id)
                  ass.destroy
               end
            end
         end
      end
    end
  end
end

**Comment by ddmck** [comment]
Moving the above script to the editing units feature in Milestone 3
