### ISSUE TITLE
Asset Pipeline - Pages to Build

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1998]
High Priority 
- [x] Homepage
- [x] Login page
- [x] Student Profile 
- [x] Sign up pages (student or teacher, teacher form, student form, etc. A bunch of pages here). 

Medium Priority 
- [x] All of the "our story pages" and "resources pages."

**Comment by RyanNovas** [comment]
for student
- [ ] make a new layout that only student gets reference: app/views/layouts/twenty_seventeen_home.html.erb
- [ ] make js bundle that includes only student facing js/scss
- [ ] add to client/webpack.client.base.config.js
