### ISSUE TITLE
Hover Box Area Broken. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2000]
When a user hovers over a box, the tooltip should pop up. At the moment, it doesn't happen reliably because elements are blocking the tooltip. 

![screen shot 2017-01-19 at 7 58 25 pm](https://cloud.githubusercontent.com/assets/3667179/22131496/cf214ef0-de81-11e6-844b-3554526be873.png)

**Comment by RyanNovas** [comment]
@petergault how were you able to get this working un-reliably? I cannot ever get this tooltip and do not know where it lives in the code base.
