### ISSUE TITLE
Submit Button Not There 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2002]
![image](https://cloud.githubusercontent.com/assets/3667179/22132869/b3f08322-de8a-11e6-811d-a52ac0e414dc.png)

The submit button disappears under certain circumstances. In addition to fixing the one off issues, can we somehow change the logic so that the submit button never disappears, it simply alternates between a state of being active and not active?

**Comment by RyanNovas** [comment]
@petergault with these connect issues, if you could include a link to the URL, we can jump directly into them and hopefully replicate the issue more expediently.
