### ISSUE TITLE
404 Design Debt 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2017]
Occasionally we will introduce bugs into Quill that send people to the 404 page. Ideally, in these circumstances, we would route students to their profile page. 

- When students hit a 404 page, we can do the following:
1 . Forward them to their profile page if they are signed in. 
2. Forward them to the sign up page if they are not signed in. 

Weird edge case: if we break something around our sign in or profile page logic, we could risk breaking the 404 page as well. If the redirect fails, can we fall back to a 404 page? What's an example of where the logic could fail here - what do we do?

**Comment by RyanNovas** [comment]
I don't agree with this. The 404 page is an established convention that indicates there has been an error and the user should know about it. We have a link back to their profile from the page already. 

If we redirect them, then we'll start getting misleading reports that could have been resolved by the user seeing the 404 page.
