### ISSUE TITLE
Change Route for Premium

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2038]
Problem:
- We use Demo for showing off premium to new teachers and showcasing premium to partners. The problem here is that we should use a different route for these two use cases. 
1. For demo teachers, we should send them to the concepts page. 
2. For demoing partners, we should send them to visual overview. 

This would be a nice solution. quill.org/demo?name=name&route=activityanalysis 

Append the "&route=name" where name sends the user to a specific page. This way we can send premium teachers to concepts and everyone else to visual overview.

- [ ] change the demo default route from standards report to visual overview.
- [ ] add the ability to define a second route to concept reports.
- [ ] update the "try the demo" button on premium to send users to this custom page.

**Comment by RyanNovas** [comment]
PR pending
