### ISSUE TITLE
Activity Planner is missing icons

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2040]
In the activity planner, the icons and description text are missing. 

![screen shot 2017-01-29 at 4 09 38 pm](https://cloud.githubusercontent.com/assets/3667179/22407899/65b9861c-e63d-11e6-8920-8cd2c021c544.png)

**Comment by ddmck** [comment]
@emilia-friedberg  This is because they are using the ActivityClassification name for deciding the icon. They should be using the key.
