### ISSUE TITLE
Default Sorting on Questions Page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2046]
The sorting on the questions page is sorted by question number by default. It should be sorted by score (lowest on the top). Here's how it looks now: 
![screen shot 2017-01-29 at 4 53 31 pm](https://cloud.githubusercontent.com/assets/3667179/22408219/88a19fec-e643-11e6-9542-83cb063d4ae3.png)

**Comment by ddmck** [comment]
Move score to the first column?
