### ISSUE TITLE
Preview Link goes to firebase

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2048]
The preview diagnostic button goes to the firebase link rather than the connect.quill.org url. 

![screen shot 2017-01-29 at 4 59 54 pm](https://cloud.githubusercontent.com/assets/3667179/22408258/7a44bcda-e644-11e6-8758-82d286d4185f.png)

**Comment by ddmck** [comment]
This should be abstracted to use the anonymous activity link with id 413 (Assuming this is the activity id for the diagnostic)
