### ISSUE TITLE
Spinner for Assigning Packs 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2050]
# How it looks now:
![image](https://cloud.githubusercontent.com/assets/3667179/22408355/9e92f150-e645-11e6-923b-230b1d0d19b0.png)

# With a spinner:
![screen shot 2017-01-29 at 5 22 18 pm](https://cloud.githubusercontent.com/assets/3667179/22408481/82bdaa7c-e647-11e6-94fd-832c9a390aef.png)

Here's the design: it's the same as our green spinner, except that it is white. Instead of having a different color for the small bit, it's invisible. 

# Featured Activity Pack 
- [ ] Show the spinner on the "assign all" button. 
- [ ] note: check to see what's going on with the background job. Donald said that there is an arbitrary 10 second delay. However, it seems that the action is completed instantly. Should we restore an arbitrary delay of say 5 seconds?

![screen shot 2017-01-29 at 5 26 20 pm](https://cloud.githubusercontent.com/assets/3667179/22408550/b9cdeca6-e648-11e6-9098-7efba99745b5.png)

# Spinner on Diagnostic
- [ ] when you assign the activity packs for the diagnostic, this should get the spinner as well.

**Comment by RyanNovas** [comment]
this will also need to happen for
- [ ] the cta button in components/lesson_planner/create_unit/stage1/unit_stage1.jsx
- [ ] the update unit button /components/lesson_planner/create_unit/stage2/update_unit_button.jsx
