### ISSUE TITLE
Update The "Editing Activity Packs"

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2070]
- [ ] dotted lines for the bottom row
- [ ] button in quill green with white text. 
- [ ] plus button from font awesome. 

<img width="1092" alt="add more activities" src="https://cloud.githubusercontent.com/assets/3667179/22567505/284bfba6-e95e-11e6-9c5d-3482a2d51e15.png">

**Comment by amr-quill** [comment]
- [ ] Dashed row at the bottom
- [ ] Add secondary white button with font awesome plus

Zeplin link: https://zpl.io/zVn7D
