### ISSUE TITLE
Activities Out of Order in Connect Activity Packs

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#2077]
When I create an Activity Pack, the Activities don't save in the same order they are added. In Connect, all the activities are specifically sequenced, so it's important that they keep their order in the packs. 

Out of order on the student side as well.

Activities out of order:
![screen shot 2017-02-03 at 3 18 11 pm](https://cloud.githubusercontent.com/assets/20426718/22607013/012ea55c-ea24-11e6-8b3c-a3a737d8934b.png)

**Comment by RyanNovas** [comment]
open pr #2106
