### ISSUE TITLE
 Add Sorting Logic for Activity Planner (re-opended)

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2128]
At the moment, the activity planner sorting logic is broken. It should be numeric, and it seems it is alphabetic now. 

Once the logic is fixed however, I would like the sorting logic to change.

# 1. By app
all activities are sorted by app. Diagnostic is #1, connect #2, grammar #3, proofreader #4. Set the order in the activity classification. 

# 2. By standard level 
within each app, sort by standard level. Each standard should have a ranking, not alphabetic. (the standard level is called section in the code). All of the non-common core standard levels (such as custom activities) should be given numbers below the standard levels. 

This is the correct sorting here:
![screen shot 2017-02-11 at 12 06 52 am](https://cloud.githubusercontent.com/assets/3667179/22851369/06ee3b90-efee-11e6-82d2-9e60bd364701.png)

# 3. By standard 
within each standard level, you see the activities. 

# Why This is Important 
This means that you see all of the connect first by standards and then all of the proofreader. I'd prefer to do it this way to keep the content organized by app first. At the moment we do not sort by app, but I think it's important we do it this way to make the connect content as prominent as possible and not mixing the content together.

**Comment by petergault** [comment]
This is not on production. 

This is what the current page looks like:
![screen shot 2017-03-21 at 11 21 12 pm](https://cloud.githubusercontent.com/assets/3667179/24180803/71813972-0e8d-11e7-9581-1694a55d3977.png)


With the correct logic, you would see:
- the first two activities are the diagnostic activities. 
- The next set of activities are all quill connect activities. 

- [ ] All activities should first be sorted by app: Diagnostic is #1, connect #2, grammar #3, proofreader #4.
- [ ] This setting should be set in the app classification. 
- [ ] in the activity planner bar, the order of the tools (for filtering) should be diagnostic, connect, grammar, proofreader.

**Comment by ddmck** [comment]
@petergault This was on production, the numbers were not set.
