### ISSUE TITLE
Homepage - Making the text a link to tools 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2130]
On the homepage, the text descriptions for the tools should all link to the tools page. 
The video, if possible, should also link to the tools page.

**Comment by amr-quill** [comment]
- [ ] Change the number of students and questions
- [ ] Change the patterns behind the animation and have it be 85% opacity
- [ ] Change the font size of the text in the button to 18px
- [ ] Change the style of the Try A Sample Activity button
- [ ] Add a Learn More button
- [ ] Add tool icons next to tool titles
