### ISSUE TITLE
MVP Spec for Mobile App

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2131]
Mobile app spec:

Note: all of the copy is placeholder. We’ll update it when Peter gets back. We also add lots of emojis into the process. 

1. It starts with a message that states:
“Welcome to Quill! This tool will help you become a strong writer. (add strong arm emoji twice)

2. next message:
“Let’s start with the diagnostic.
(note: on the backend, do you want to hardcode messages into the process? How will we track the state of which messages they see?” Perhaps we have an “event” series where at each event you get a certain array of JSON data?”

3. Show the first title page text. 

4. show the first question of the diagnostic. 

5. Show the 2nd, etc. 

6. show the next title page text. 

7. At the end provide a message that says 

You did it! Based on your results, you should practice compound sentences, complex sentences, and adjectives (show the names). 

8. then show the first question for the 1st recommended activity.

**Comment by ddmck** [comment]
Make sure messages are in the right order, specifically the messages for keep going after 1st question.

Also add the ready to progress button to the end of the onboarding.
