### ISSUE TITLE
Indicate previously assigned activities on Recommendations page

### ISSUE THREAD

**Issue by emilia-friedberg** [empirical-org/Empirical-Core#2136]
When teachers have students complete the diagnostic at different times, nothing indicates what they have already assigned (rather than just what has been recommended) when they revisit the recommendations page.

**Comment by amr-thameen** [comment]
Zeplink (Sentence Structure Diagnostic): https://zpl.io/Z1Djz07
Zeplinkl (ELL Diagnostic): https://zpl.io/Z19LO96

** See comments on the zeplin screens**

New elements:

- [ ] Add the pattern and the key for the pattern
- [ ] Drop downs at the top of the page for class and diagnostic type


Logic:
- [ ] When a teacher gets to this page, they see the recommended activities checked, darker gray font and blue box. Not recommended activities are gray font, white box and unchecked.
- [ ] Once the teacher assigns the activity packs, they get the pattern treatment. 
- [ ] If an activity pack is assigned and recommended -> blue and pattern
- [ ] If an activity pack is assigned and not recommended -> Only Pattern
- [ ] If an activity pack is recommended but not assigned -> Only Blue
- [ ] If an activity pack isn't recommended and not assigned -> Only white
