### ISSUE TITLE
Change "Assign Custom Activity" to "Assign Entry Diagnostic" in Getting Started card

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2162]
- [x] Add a diagnostic guide (Amr and Hannah) 
- [x] Change the copy on the getting started card
- [x] Link the guide button to the new diagnostic guide, http://support.quill.org/knowledgebase/articles/1144849-assigning-the-quill-diagnostic
- [x] Link "Assign Entry Diagnostic" to https://quill.org/diagnostic#/stage/1?_k=tyx7u3

Zeplink: https://zpl.io/Z1ciDc9

**Comment by RyanNovas** [comment]
#2313
