### ISSUE TITLE
Broken shared URL 

### ISSUE THREAD

**Issue by amr-quill** [empirical-org/Empirical-Core#2171]
Teachers are still sharing a broken link to twitter from the "Share the activity pack". I am not sure if this was fixed last week or still in the works. I am sorry to bring it up again if its already in the works. It's just that I am seeing more and more people share it 

This is the broken link: https://quill.org/activities/packs/diagnostic

**Comment by ddmck** [comment]
Thanks, looks like the fix was for the singular of activities. I’ll get this live in a bit.
