### ISSUE TITLE
Investigate visibility of due dates on student dashboard

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2175]

**Comment by ddmck** [comment]
The due dates are not visible on the student profile, and this needs to be designed. @amr-quill

**Comment by amr-quill** [comment]
- [ ] Add Due Date title and only show it if there are due dates set
- [ ] Include the Due Date next to the name of the activity
- [ ] Change "lesson" to "activity" for the entire page
- [ ] Include the due date in the hover modal, if there is no design for it let me know

Zeplink: https://zpl.io/Z1Ud4Fd
