### ISSUE TITLE
AdWords Prep

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2180]
A non-technical issue for Ryan to track. 

- [ ] prep  a list of questions to ask all of the adwords managers. See who has the best responses. 

- [ ] include a short segment about our current strategy. 
1. we were bidding 40k and getting 1.2m conversions and 500 conversions. 
2. We then focused on specific grammar terms, and this drove our impressions down to 700k a month with 300 conversions. 
3. We paused those ads, but most of our spend is now going to our original ad. We're back up to 500 conversions a month. It's called General Grammar Terms - the ad is called Grammar Quizzes. 
4. The problem with the ad is that it is not k-12 focused, and it does not target teachers, our primary user. 
5. We wrote a new one that is strong than the original (the competitor campaign group). Not sure how to target more teachers on it. The ad focuses on it being a free online tool for k-12. Ideally, we would spend the full amount on this campaign. We still see the higher conversion our old ad. 

# The copy of the new ad
**Quill.org's Free Writing Tools - Activities For K-12 Students**
Interactive lessons and instant feedback to help students become better writers.

# Old Ad
**Free Grammar Quizzes - For K-12 Students**
150+ activities, graded instantly. Learn grammar online today.

**Comment by RyanNovas** [comment]
I put together this doc.
https://docs.google.com/document/d/1ofQEP_MooI9-erwpuZiC9X56Ww1TgHbrEI2AAVbyUS4/edit
