### ISSUE TITLE
Only show 4 Activity Packs after creating a new class

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#2187]
When teachers create a new class, they are automatically shown featured activity packs. Currently, teachers see all activity packs. Instead, they should only see 4 activity packs. The top left pack shown should be the diagnostic. The other three packs should be from the appropriate grade level.

**Comment by emilia-friedberg** [comment]
@Hannahmonk this appears to have been fixed with the new routing, so it'll be live once that branch gets pushed to Heroku.
