### ISSUE TITLE
Create an intermediary page "What's next" after assigning diagnostic 

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2237]
These are pages for when the teacher clicks on the Diagnostic link if they have not assigned the diagnostic or if their students have not completed it yet. 

No diagnostic is assigned: https://zpl.io/1aM1yn 
Diagnostic Assigned, Students haven't completed: https://zpl.io/Z1dUXQy

Assets: https://drive.google.com/open?id=0B1gIVBvHm9BgNHhqSnM4cGtOVDg

- [ ] Add title 
- [ ] Add the diagnostic image next to it
- [ ] 2 buttons each page

**Comment by ddmck** [comment]
Part of https://github.com/empirical-org/Empirical-Core/pull/2490/commits/0e0412f962017a4560c2c5b1d910038aace68c04
