### ISSUE TITLE
Homepage: Tools pattern are shown on top of the gifs on Mobile 

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2251]
The pattern should be behind the tool gif. 

![img_2799](https://cloud.githubusercontent.com/assets/25299820/23613970/6c687c74-024f-11e7-97f2-f1f3ace36839.PNG)

**Comment by emilia-friedberg** [comment]
note to self: hide tools pattern altogether at media breakpoint

**Comment by ddmck** [comment]
This issue has re-emerged! Lets take another look.
