### ISSUE TITLE
Investigate Jest

### ISSUE THREAD

**Issue by emilia-friedberg** [empirical-org/Empirical-Core#2258]
- [ ] Blogposts on best practices
- [ ] Tutorials on use
- [ ] Additional tools we might want or need to use
- [ ] Update this issue as we learn.

**Comment by jaredsilver** [comment]
https://egghead.io/lessons/javascript-test-javascript-with-jest

**Comment by jaredsilver** [comment]
For snapshot testing, it looks like we'll have the choice between using Jest with ReactTestUtils or AirBnB's Enzyme. This dev prefers Enzyme: https://hackernoon.com/testing-react-components-with-jest-and-enzyme-41d592c174f
