### ISSUE TITLE
Update Copy in Connect reports.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2261]
Response is too technical, and really it's an attempt.

<img width="1249" alt="quill_org_ _interactive_writing_and_grammar" src="https://cloud.githubusercontent.com/assets/3110565/23664988/35a041fa-0325-11e7-8a92-80126a01b7c1.png">

**Comment by RyanNovas** [comment]
We're going to use submission instead of response or attempt.

**Comment by ddmck** [comment]
@emilia-friedberg note that we are going to use submission rather than attempt

We should also update the non-connect reports.
