### ISSUE TITLE
database.yml.example is missing

### ISSUE THREAD

**Issue by hrishimittal** [empirical-org/Empirical-Core#2300]
Hi, I just found this awesome project while searching for examples of code using the react_on_rails gem.

I was trying to set it up on my machine and found that the database.yml.example file is missing.

It looks like it got removed in PR #1879 ([here](https://github.com/empirical-org/Empirical-Core/commit/20b037ae3e6ef187553c2da16229341b128ec08c#diff-a8894981075fa828a16e492bf9a0a7aeL1)), but it's not clear why.

Should I send a PR to restore it?

**Comment by ddmck** [comment]
HI @hrishimittal, apologies for taking so long to reply! If you like to submit a pull request to restore it that would be great!
