### ISSUE TITLE
Student Has Become a Teacher

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2301]
A student became a teacher and now all of the other students in the class belong to that student as a teacher. The student is tech savvy, and likely found a loophole in our logic. See more in the issue. 

https://docs.google.com/document/d/13pj7iZL3h_EyAZ8EUZQu8ycTCUuwl2Glw8B5XuPo6FM/edit

**Comment by RyanNovas** [comment]
Right now, the hypothesis is that Google Classroom is indiscriminately importing associated classrooms from the user, and then making the user the teacher if they are a teacher in our system.

If this theory holds up, the short term solution is to look at the owner id on the course object and verify that it is the same as the current user's Google ID. https://developers.google.com/classroom/reference/rest/v1/courses#Course

The long term solution is this validation, and then allowing the user to selectively pick out various classrooms. Khan Academy does a good job of this.

**Comment by RyanNovas** [comment]
Fixed by #2309
