### ISSUE TITLE
don't import archived classes from Google Classroom

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#2349]
Currently, we're importing all classes from Google Classroom, even if they are archived.

We should no longer create archived classes, though we should continue to sync them if they've been added to Quill and then archived on Google Classrooms.

To do this: 
google classroom provides this json that we parse in /app/services/google_integration/classroom/parsers/courses.rb

we should grab `courseState` and if archived, try to find the class, but never create or show it in the list of classes that can be imported.

```{"id"=>"5169992618", "name"=>"archive test", "descriptionHeading"=>"archive test", "ownerId"=>"112188393285935083024", "creationTime"=>"2017-03-16T19:09:15.524Z", "updateTime"=>"2017-03-16T19:10:21.493Z", "enrollmentCode"=>"csaous", "courseState"=>"ARCHIVED", "alternateLink"=>"http://classroom.google.com/c/NTE2OTk5MjYxOFpa", "teacherGroupEmail"=>"archive_test_teachers_d85e9a6a@quill.org", "courseGroupEmail"=>"archive_test_732f640d@quill.org", "teacherFolder"=>{"id"=>"0B42XhC1mwehmfkI2aDBsc2dxbS1RSGxmdXBJd3lmYU9OQU1ob2VwUTgtRkhPSGZzWmxCMTg", "title"=>"archive test", "alternateLink"=>"https://drive.google.com/drive/folders/0B42XhC1mwehmfkI2aDBsc2dxbS1RSGxmdXBJd3lmYU9OQU1ob2VwUTgtRkhPSGZzWmxCMTg"}, "guardiansEnabled"=>false}```

**Comment by emilia-friedberg** [comment]
bundled into #2360
