### ISSUE TITLE
Editing a custom unit to have no students causes it to disappear

### ISSUE THREAD

**Issue by jaredsilver** [empirical-org/Empirical-Core#2352]
Steps to reproduce:

1) Have a classroom with students and a classroom without students.
2) Assign a new custom activity pack to a classroom with students. Remember the name.
3) Edit that activity pack. Unassign the classroom with students, and assign the classroom without students.
4) This pack will have disappeared from the activity packs screen.
5) If you try to create a new activity pack with the same name, an error will be raised saying that your pack needs to have a unique name.

**Comment by ddmck** [comment]
Units are likely being queried for by classroom activities. Querying by Units instead may fix this.

**Comment by jaredsilver** [comment]
I can't seem to reproduce this again even though my database shows that it definitely happened. I'm going to close this for now but keep my eye open.
