### ISSUE TITLE
setup twitter cards for sharing lessons on twitter. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#236]
https://dev.twitter.com/docs/cards

**Comment by dalrayes** [comment]
Hey - I am going to take a look at this. Is there a specific picture/text you would like to display?

**Comment by dalrayes** [comment]
OK Peter - 

We're gonna take a stab at this.

**Comment by dalrayes** [comment]
Sorry - we didn't manage to get this done. We will try to revisit in a couple of weeks!

**Comment by RyanNovas** [comment]
@dalrayes no problem! Thank you for all of your help today, we truly appreciate it.

**Comment by RyanNovas** [comment]
@petergault @tomcalabrese do the share buttons take care of this?
