### ISSUE TITLE
Google Classroom: Select and Sync Classes

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2360]
## New teacher signing up through Google Classroom: 
- [x] New Create Class page (When a teacher signs up through Google Classroom, after they find their school, they get sent to the screen to choose if they want to create a class or import) https://zpl.io/1YzKw3

## Returning teacher clicking sync with Google Classroom: 
- [x] Change "Import" to "Sync" and change "Classrooms" to "Classroom" in the dashed button (https://zpl.io/ryVxK)
- [x] First Update Your Email (https://zpl.io/yEo7O)
- [x] Updated! (https://zpl.io/Z1N9mYf)
- [x] Incorrect Email Address (https://zpl.io/ZmtO4)
- [x] Email already in use (https://zpl.io/Z1F6ArG)
- [ ] Choose classes page (https://zpl.io/Z1ak3Ex) Note: If a class is already synced then it will be checked and it will say Connected on the tab. All synced classes are at the top of the table. If a user hasn't synced anything yet, let's arrange the classes by creation date and have the most recent at the top. We are also showing 15 classes and hiding the rest in the Show Classrooms tab. 
- [ ] Warning Modal (https://zpl.io/Z2t1z2) Note: This shows up if a user deselects a classroom and clicks Sync Classrooms.
- [ ] Success Modal (https://zpl.io/Z1vp1ML) Note: once the user clicks on Got It, they get sent back to the teacher dashboard where they started. 

## Returning teacher going through Manage Classes: 
- [ ] Add a new column to the classes list and remove count (https://zpl.io/1BQ4B4)
- [ ] Archiving Modal (https://zpl.io/1kYBSP) (Only comes up for Google Classroom)
- [ ] Unarchiving Modal (https://zpl.io/1ahAHs) (Only comes up for Google Classroom)

## Returning teacher going through Create a Class: 
- [x] Create A Class (https://zpl.io/1YzKw3) Here teachers have the option of creating a class or importing from Google Classroom 

## Returning teacher going through Invite Students:
- [x] Invite Students screen (https://zpl.io/Z1betPy)

**Comment by emilia-friedberg** [comment]
- [ ] add validation to make sure student import isn't trying to connect students to classrooms without teachers
- [ ] jest test everyone
- [ ] handle bad token (see above)
- [ ] front end!

**Comment by emilia-friedberg** [comment]
[ ] talk to @petergault and @amr-thameen about how to handle two teachers trying to import the same classroom

**Comment by emilia-friedberg** [comment]
test coverage!

[ ] - google classroom modal (valid and invalid input)
[ ] - test google classroom mini, test different actions depending on teacher account

**Comment by jaredsilver** [comment]
As a teacher signed in with Google Classroom but not with Quill, clicking the "Sign Up with Google Classroom" button on the signup page redirects me back to the signup page instead of signing me in.

(Not sure if we want to address this, but it's a thing that happens.)

**Comment by jaredsilver** [comment]
As a teacher who does not have an account with Quill, clicking the "Sign In with Google Classroom" button on the sign in page redirects me to a 404.

**Comment by jaredsilver** [comment]
Should we consider better handling the case where a teacher does not want to sync any classrooms? This seems a tad weird.
<img width="549" alt="screen shot 2017-03-29 at 2 34 37 pm" src="https://cloud.githubusercontent.com/assets/1312199/24470420/dc5a8488-148c-11e7-9243-6d55e7411ed3.png">

**Comment by jaredsilver** [comment]
The regenerate class code link on `teachers/classrooms/new` does not work.

**Comment by jaredsilver** [comment]
If you select one or more classrooms to archive, but you are also selecting one or more classrooms to newly synchronize, the modal only speaks to the classrooms you are archiving. Not sure if this is worth addressing though.

**Comment by jaredsilver** [comment]
If I archive a classroom on Google classroom and then sync with Quill, the classroom archived on Google classroom is also archived on Quill. This seems to be the intended behavior, but there isn't any messaging around it, so it may have the potential to confuse users.

**Comment by jaredsilver** [comment]
As a learner signed in with Google, if I change my email address the next time I try to log in with Google I will be redirected to the sign up page.

If I sign in as a student, it will create a new account for me, and a ghost account will exist under my teacher with the email address I just changed to.

If I sign in as a teacher, I will also be added to my teacher's classroom but with no username.

**Comment by jaredsilver** [comment]
If I'm a teacher who is also in another teacher's classroom, Quill assumes that I'm a student instead of a teacher. This can be easily changed by changing the account type, but it may make sense to assume that if a Google account is the teacher of classes, it should default to being a teacher and not a student account.

**Comment by jaredsilver** [comment]
If I'm a teacher who is also a student in another teacher's Google Classroom, I cannot delete my account.

**Comment by jaredsilver** [comment]
`Uncaught Error: ReactOnRails encountered an error while rendering component: DashboardApp.Original message: Could not find component registered with name DashboardApp. Registered component names include [  ]. Maybe you forgot to register the component?`

**Comment by jaredsilver** [comment]
As a teacher reading this page, I'm not sure I would realize that **here** is a link.
<img width="625" alt="screen shot 2017-03-30 at 1 29 49 pm" src="https://cloud.githubusercontent.com/assets/1312199/24517630/0809c826-154d-11e7-86aa-1763ee7b0d0e.png">

**Comment by jaredsilver** [comment]
As a teacher with a synced Google Classroom, deselecting that classroom and resyncing still displays the **Great! You've synced 0 classes** modal.

**Comment by jaredsilver** [comment]
As a learner signed in with Google, if I change my email address the next time I try to log in with Google I will be redirected to the sign up page. I then get stuck in an infinite loop that does not allow me to sign up or sign in.

**Comment by jaredsilver** [comment]
LGTM! Awesome work!
