### ISSUE TITLE
Diagnostic Tool Page: Add new ELL Diagnostic section 

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2424]
** None of this will go live until the ELL diagnostic is live **

- [x] New section between What's being tested and Student's Responses Analyzed
- [x] Add title 
- [x] New tag
- [x] New copy
- [x] Illustration, should I send you a png of that since it's easier to code? 
- [x] Learn More will send users to the medium article about the ELL diagnostic, not live yet

Zeplink: https://zpl.io/2kdyCu

**Comment by emilia-friedberg** [comment]
@amr-thameen A png of the the illustration would be great, if you don't mind.

**Comment by amr-thameen** [comment]
https://drive.google.com/open?id=0B1gIVBvHm9BgRWxVRXU4aEN1UUE
