### ISSUE TITLE
Fix Social Media Text

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#243]
When a user links to Quill via Facebook or Google Plus, it draws the text from the homepage in a funky, unappealing way. We should find out how we can present clean text. 

![quill 170614](https://cloud.githubusercontent.com/assets/3667179/3323394/61eb920a-f761-11e3-80f4-20a16ef3b5c6.JPG)

**Comment by dalrayes** [comment]
Hey - I am going to take a look at this. Is there a specific picture/text you would like to display?

**Comment by bobmazanec** [comment]
Different.

Better? Good enough?

![screen shot 2015-03-13 at 8 46 46 pm](https://cloud.githubusercontent.com/assets/2031462/6650024/85916688-c9c2-11e4-9604-7cf451ae18cc.png)
![screen shot 2015-03-13 at 8 48 46 pm](https://cloud.githubusercontent.com/assets/2031462/6650025/85959028-c9c2-11e4-8ce6-ba76c4bbf01c.png)

**Comment by RyanNovas** [comment]
@dalrayes , thanks for looking into this. @bobmazanec mocked up some great images, and the copy is ok. Why don't we try to get that pushed live, and then we can change the copy later if necessary.

**Comment by bobmazanec** [comment]
You give me too much credit :smile:

My images are live screen captures from Facebook & Google+ &mdash; not mockups. So I expect this is the 'live' behavior anyone can see right now.

**Comment by RyanNovas** [comment]
You deserve it Bob. With that said, it looks like Facebook is doing a better job since we redesigned the site a couple weeks ago. I don't believe it was pulling images before. 

@petergault do we want to close this in light of what is happening now?

**Comment by petergault** [comment]
Yes we can close this. This essentially got fixed by pushing the new
homepage live.

On Mon, Mar 16, 2015 at 11:54 AM, Ryan Novas <notifications@github.com>
wrote:

> You deserve it Bob. With that said, it looks like Facebook is doing a
> better job since we redesigned the site a couple weeks ago. I don't believe
> it was pulling images before.
>
> @petergault <https://github.com/petergault> do we want to close this in
> light of what is happening now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/243#issuecomment-81757275>
> .
>



-- 
Peter Gault
Quill Co-Founder and Product Director
http://quill.org

Learn more about Quill: http://youtu.be/BA6jaeberMg
