### ISSUE TITLE
Edits before launching the ELL Diagnostic

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2435]
This is a list of things that need to happen on the front end before the launch of the ell diagnostic:
# For Devs 
- [x] Add recommendations button to activity analysis for ELL activity
- [x] Make sure that its called ELL Diagnostic and not Spanish ELL Diagnostic
- [x] Dropping Beta from Diagnostic and Connect 
- [x] Announcement card on the teacher dashboard (link: https://zpl.io/Z1EoPQV )
- [x] Note: We will drop the old announcement when we add this one.
- [x] Learn more button on announcement should link to Medium article (TBW)
- [x] note: drop the blue bar as well for launching new tools. 
- [x] Edit to the Assign a New Activity page (link: https://zpl.io/1xOiGI ) 
- [x] New page for when the teacher clicks on Entry Diagnostic on the previous page (link: https://zpl.io/Z5j0rz)
- [x] Edit to the Student Reports landing page (link: https://zpl.io/1tfY7l)
- [x] Edit to the Activity Analysis page to hide anything else thats not diagnostic 
- [x] Assign custom activity, change the name of the filter to Quill Diagnostic instead of beta (https://zpl.io/Zjd9Ly)

# For Amr 
- [x] Edit guide to include the update of recommendation and ELL Diagnostic

**Comment by emilia-friedberg** [comment]
Places that might be broken from route restructuring:

[ ] - Entry Diagnostics card on the Assign a New Activity page (should now go to Assign a Diagnostic page)
[ ] - diagnostic cards on the new Assign a Diagnostic Page
[ ] - Assign Entry Diagnostic link in the Getting Started guide
[ ] - diagnostic tool page 'Assign' button (should now go to Assign a DIagnostic page)
[ ] - clicking 'Preview the Diagnostic' or 'Continue to Assign' from stage 2 of diagnostic assignment should bring you to the correct pages respectively
[ ] - back button of Select Classroom page of diagnostic assignment
[ ] -

**Comment by emilia-friedberg** [comment]
- [ ] new route under diagnostic_reports specifically for diagnostic reports called '/diagnostics'
- [ ] the container for this route should call and api endpoint that returns only the units with diagnostic activities, and only the diagnostic reports within them.
- [ ] the retrieved data can then be rendered in a similar manner to the activity packs reports page.
- [ ] if the number of reports is equal to 1, redirect to that report.
- [ ] if the number of reports is equal to 0, render info about not having assigned yet.

**Comment by amr-thameen** [comment]
@emilia-friedberg 

While we are no longer making the changes to the diagnostic report page to filter by class and type of diagnostic. We still need to change the title and the description under it. Check comments on Zeplin

Zeplin link: https://zpl.io/Z1nnIUH

**Comment by jaredsilver** [comment]
The image on the second card of the diagnostic assignment stage 1 page seems to be a little off:

<img width="618" alt="screen shot 2017-04-20 at 5 26 12 pm" src="https://cloud.githubusercontent.com/assets/1312199/25253336/7bcfdac8-25ee-11e7-8ede-3dc070863a76.png">

**Comment by jaredsilver** [comment]
Is it intentional that the ELL Diagnostic does not have a stage 1 like the regular Diagnostic?
