### ISSUE TITLE
Student Dashboard: Title of the class stylistic issue

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2456]
Title of the class has a bottom padding that's unnecessary 

https://docs.google.com/a/quill.org/document/d/1ilzEG9ltoe5Ui3ffai9mrwQZJvAHjiHN6RIUeMHwJA0/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
@amr-thameen closing this because there's already a pull request for it.
