### ISSUE TITLE
Connect Tool Page: Pattern not there

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2459]
The prompt section on the connect page doesn't have the pattern behind it. I think something got broken when we took it out from mobile. 

I consider this a personal attack on my beautiful beautiful art.

- [x] Also, could you connect "Try Quill Connect Now" with http://connect.quill.org/#/play/lesson/-Kbvv3WS6vGNkeW7d6dt
- [x] Add Pattern

Drive: https://drive.google.com/open?id=0B1gIVBvHm9BgM3h6d2xoZHFEV2M
Zeplin: https://zpl.io/167eKT

# The Issue
- [ ] Asset Pipeline not working - two pipelines issue.

**Comment by emilia-friedberg** [comment]
[ ] - Extra space between logo and nav bar (should be ~10px)
[ ] - 'Show Relationships' in Second Attempt header should fit on one line
[ ] - page header section top margin unequal to bottom margin
[ ] - same issue in "try it out for yourself" section
[ ] - left carousel control not working

**Comment by emilia-friedberg** [comment]
The images are not showing up because of an issue with the asset pipeline, not anything in the css or html. However, the other issues in this branch are fixed in PR #2466.

**Comment by petergault** [comment]
Move the image so that it works with the asset pipeline.
