### ISSUE TITLE
Next Activity Shows The Last Activity

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2473]
![screen shot 2017-04-14 at 4 00 17 pm](https://cloud.githubusercontent.com/assets/3667179/25054503/7c0a0b84-212b-11e7-95a9-3ff77e1a91de.png)

Students are seeing their last activity as their next activity.

**Comment by jaredsilver** [comment]
Can't seem to reproduce this -- is there a specific account this is happening to?

**Comment by emilia-friedberg** [comment]
@petergault like @jaredsilver, I checked in a couple of student accounts and none of them seem to have this issue. Do you know who was experiencing it?
