### ISSUE TITLE
Activity Analysis: Time shown seems to be from starting the activity

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2512]
Total time spent on the activity seems to be the entire time from when the student starts the activity until they complete it. 

https://docs.google.com/a/quill.org/document/d/1cr1EK2K-D5aUUBhE2f6YEVZlXbd-nMSQQJGo91U6pEA/edit?usp=sharing

**Comment by ddmck** [comment]
If time taken is greater than 60 mins, replace time with "> 60 min."
