### ISSUE TITLE
Improve drip campaign for SSO users

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2516]
- [ ] update drip campaign to not pester SSO users to add students.
- [ ] track events in Segment for SSO users.
- [ ] audit actions.

**Comment by RyanNovas** [comment]
Why not pester them to add students if they have not?

**Comment by ddmck** [comment]
The checkbox completion is tied to the forms that non SSO users complete to add students. We need to track them in the SSO sign on when classes and students are added.
