### ISSUE TITLE
Custom Activity Packs: Fixes

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2549]
- [x] Clear X not working, when the teacher tries to filter using the search then tries Clear, the page gets reloaded but nothing happens. It should remove the filter.
- [x] When you add activities to your activity packs, the activities should be placed under the line divider and a text that says: "Selected Activities:"
- [x] Let's remove the line after the continue button 
- [x] Button: should be green and the error should just appear next to it center aligned with the font awesome warning sign
- [x] Spacing between Name the Activity Pack and Select Activities (Check Zeplin)
- [x] Spaces between search bar and button and drop down next to it (Check Zeplin)
- [x] Error style for the text field of the name

Zeplin: https://zpl.io/Zjd9Ly

**Comment by emilia-friedberg** [comment]
@amr-thameen in regard to point #2, what does that section look like when it's empty? right now we aren't displaying anything until the teacher selects that activity.

**Comment by emilia-friedberg** [comment]
@amr-thameen in regard to point #4, the button should always be green?
