### ISSUE TITLE
Bug - clever users don't have a last updated

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2557]
Clever users don't have their last updated change when they sign in. We should make sure Google Classroom and Clever users both have their last updated change.

**Comment by RyanNovas** [comment]
I think that this would be a perversion of what last_updated is for. Instead, we could add a last signed_in field

**Comment by ddmck** [comment]
https://github.com/empirical-org/Empirical-Core/issues/2612
