### ISSUE TITLE
Sign Up/Login pages: Stylistic changes for mobile

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2558]
Sign up screen: https://zpl.io/bk46E
Login screen: https://zpl.io/Z2gQNmm
Assets: https://drive.google.com/open?id=0B1gIVBvHm9BgYk9SVEZ0ZmQwNkk

- [x] Rearranging the top section in the signup page
- [x] Make form fields wider in the signup page and keep that consistent with the login page 
- [x] Make the sign up and the login buttons as wide as the field forms 
- [x] Google and Clever Buttons are not images but created in CSS. 
- [x] Make sure the buttons are updated in all sign up pages including teachers, students mobile and desktop
- [ ] Allow mobile students to skip the Educator - Student choice in the sign up and get send directly to the sign up page

**Comment by emilia-friedberg** [comment]
Moving last check to an issue in Mobile.
