### ISSUE TITLE
New Timeout Page 

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2570]
Zeplin link: https://zpl.io/Z2hbqJD
Illustration: https://drive.google.com/open?id=0B1gIVBvHm9BgdktuZmhuV1FibWM
Logo: https://drive.google.com/open?id=0B1gIVBvHm9BgYzcxN01veXVnb1U

**Comment by emilia-friedberg** [comment]
I have these files ready for @ddmck to upload to S3. Adelle Sans will also need to be uploaded.

**Comment by ddmck** [comment]
@emilia-friedberg Where do these files live? Could you add them to the CDN?

**Comment by emilia-friedberg** [comment]
@ddmck added to the CDN here: https://github.com/empirical-org/Quill-CDN/pull/14
