### ISSUE TITLE
Send teachers to teachers/classrooms/activity_planner/assign-new-activity after creating a new class

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2580]
Currently, we send teachers to the activity packs filtered to their grade level, but now that we have the diagnostics it makes more sense to send them to teachers/classrooms/activity_planner/assign-new-activity as it better explains the what we offer, and funnels them through the diagnostic set up flow.

- [x] change the URL users are sent to after creating a classroom to ```teachers/classrooms/activity_planner/assign-new-activity```

**Comment by RyanNovas** [comment]
resolved by #2603
