### ISSUE TITLE
Diagnostic Recommendation Button

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2596]
In the Activity Analysis page and the Diagnostic page, if any of the diagnostics is assigned to multiple classes, the recommendation button should show as soon as a student in one of the classes completes the diagnostic. 

Logic: if any student completes the diagnostic, the recommendation button should appear in both the diagnostic and the activity analysis pages.

**Comment by emilia-friedberg** [comment]
@amr-thameen and I discovered that it appears to be working after all. Closing this issue unless this problem reappears.
