### ISSUE TITLE
ELL Diagnostic Issues

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2599]
# Desktop:
- [x] Fix the font in the Language Selection Screen, its currently serifed, it should be sans serif
- [x] Aligning the Arabic translations with the Save and Exit so everything is right aligned: (complete sentences slide, fill in the blank slide, verb tense slide etc.) in the case of illustrations, align the translation to the right of the English translation if there is no illustration (save and exit) 
- [x] clicking anywhere after the dropdown is selected should collapse the dropdown 
- [x] Broken animation in (after "football game" question, after"marco lives in ny" question, "ricardo" question, all the fill in the blank questions, after the "fridge" question, before "dog is sleeping question,
- [x] In the fill in the blank question: when a student gets an error, the field should be empty and remove the wrong answer
- [x] No results page for the students who did the ELL Diagnostic (i was able to see the result page, is that because I accessed it through a preview?)
- [x] Make the margin above the blank in the fill in the blank question 35 px 
- [ ] lets top align the illustration with save and exit
- [ ] discuss: making the font size larger for the fill in the blank, from 24 to 30px

# Mobile:
- [x] Language Selection screen: Language buttons needs to be centered
- [x] English button can be the same width as the rest of the button so cut the copy to "Only English" 
- [x] No need for the burger sign on the language selection page
- [x] The dropdown to select languages should be in the nav bar instead of the burger sign. (Let me know if this is not possible) 
- [x] Remove the illustration from mobile for now.

**Comment by ddmck** [comment]
Students are not supposed to see results for ELL diagnostic.

**Comment by emilia-friedberg** [comment]
@ddmck I have inconsistently weird animations, as in, their weirdness or running over onto themselves does not appear to be related to the specific questions. Does this have something to do with the loading of concept results?

**Comment by amr-thameen** [comment]
New Illustrations: https://drive.google.com/open?id=0B1gIVBvHm9BgVXpibjBQQWNTMUU
