### ISSUE TITLE
Caching strategies and debt

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2614]
Resources:

- Using BraveCacher https://www.sitepoint.com/speed-things-up-by-learning-about-caching-in-rails/ (mostly focuses on front-end caching, but model and HTTPS caching could apply)
- Side by side comparison, including Benchmarks, for common Rails caching stores (https://www.speedshop.co/2015/07/15/the-complete-guide-to-rails-caching.html)
- https://github.com/rails/actionpack-action_caching

Strategies:

- If we are caching a whole model, we would probably want to make an invalidate/revalidate cache `after_commit` callback
- Need to make sure we have a distributed caching system so we can access caches across dynos
- Can use Apache Bench to benchmark how long network cached requests take

Debt:

- [ ] example

**Comment by RyanNovas** [comment]
We should look into page caching for all static pages
