### ISSUE TITLE
Show password option on login page

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2666]
Zepelin: 
inactive https://app.zeplin.io/project/58939e73c4a8fbc0512e606e/screen/5967eb0f37725e1b51ea1ffe
active  https://app.zeplin.io/project/58939e73c4a8fbc0512e606e/screen/5967eb0ee7b8daa9a05b2bbb

- [ ] Add a new entry point to client/webpack.clinet.base.config.js called login
- [ ] Add a new clientRegistration.js file to client/app/bundles/Login
- [ ] In client registration import a file called LoginForm.jsx from the same directory and register it.
- [ ] Create LoginForm.jsx, using NewAccountAppClient as inspiration.
- [ ] recreate the functionality from app/views/sessions/new.html.erb contained in the comment block.
- [ ] Implement the show hide functionality. When showing, input type is text, when hiding, input type is password.
- [ ] replace the existing code in app/views/sessions/new.html.erb with the new react component
- [ ] Write jest tests for the new functionality

**Comment by dainchatel** [comment]
I'm gonna do this!
