### ISSUE TITLE
Assigning follow up activities

### ISSUE THREAD

**Issue by emilia-friedberg** [empirical-org/Empirical-Core#2678]
### activity_follow_up table
- [x] activity_id (the activity you just finished, a lesson)
- [x] follow_up_activity_id (the one coming up, a connect activity)

no uniqueness restriction - each lesson can have multiple follow-ups
maybe add order at future date?

### hit follow up route
- [x] get follow_up activity from new table and assign to same unit as lesson

**Comment by RyanNovas** [comment]
i did this in #2693 as a self reference rather than creating a new table
