### ISSUE TITLE
Remove Promotion Banner on Pricing Guide

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#2706]
Remove the banner on the pricing page that offers premium until July 2018 if purchased now. 

![screen shot 2017-07-24 at 2 57 14 pm](https://user-images.githubusercontent.com/20426718/28539774-de7e916e-7080-11e7-9014-dae52478a561.png)

**Comment by emilia-friedberg** [comment]
fixed in PR #2694
