### ISSUE TITLE
Lessons Tools page

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2724]
Make sure all assets are added to the CMS repo.

Zepelin link: https://app.zeplin.io/project/58939e73c4a8fbc0512e606e/screen/597a645a62166f95f08202f0
Check with Amr if there are any updates.

**Comment by amr-thameen** [comment]
- [ ] Update the copy for Q&A section of the page. This is the doc: https://docs.google.com/document/d/1bz8yAwxA0TIIyH5HFwZsFj2rELMUUvHg190gRxK4sXs/edit
- [ ] Update animation. I'm working on the file it should be uploaded today to gdrive
