### ISSUE TITLE
Cache of commonly checked teacher values

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2728]
Examples:
Has classroom, number of classrooms, activities completed count, activities assigned count, etc.

Look for commonly queried teacher stats.

Store these values in Redis.
Decide how we want to expire and update these values.

**Comment by RyanNovas** [comment]
Has classroom doesn't seem too bad as a db implementation -- `!!Classroom.unscoped.find_by_teacher_id teacher.id`. However, we're looking at all classrooms the teacher has -- `@user.classrooms_i_teach.any? || @user.archived_classrooms.any?` which is stupid. Let's just fix the db call.

Number of classrooms I don't know of where we use -- if infrequent, it seems lightweight enough.

Activities assigned is a brutal call, particularly if operating across classrooms, but again, not sure where we use it.

Activities completed is again a brutal one. We could either run a scheduled job that will check these, or just update redis whenever a student completes an activity.
