### ISSUE TITLE
Teacher Dashboard Launching Lesson

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2745]
In the launching lesson card let's make sure this happens:

[ ] Lessons are organized by the order of the assigned lesson on the list, with all of the lessons where all of the classes that have completed it being hidden. 

When you click to launch the following check is made:

- Is the activity assigned to one class or to multiple classes?
If one class is assigned, check - is the activity completed? 
If yes, the code is broken, because you shouldn’t be showing lessons where the class has completed it.

If no, start the lesson. 

If the activity is assigned to multiple classes, launch a page “Select Class to Launch Lesson. On the page, show the list of classes. Look up whether the class has completed the activity or not. 

If the class has completed the activity, show a “completed” button next to the class name. Don’t make the class selectable. 

If the class has not completed the activity, enable the teacher to select it.

**Comment by emilia-friedberg** [comment]
@amr-thameen not sure what this means: "Lessons are organized by the order of the assigned lesson on the list."

**Comment by emilia-friedberg** [comment]
notes for tomorrow:

- [ ] update everywhere that teachers can attempt to launch a lesson to hit a controller route which takes a unit and activity
- [ ] this controller route will check whether the teacher's tutorial milestone has been completed and if there is more than one class assigned the lesson. this will determine whether to send teachers to the tutorial, to the lesson, or to the choose classroom page.
- [ ] a similar route will exist for preview that just decides whether to send teachers to the tutorial or preview.
