### ISSUE TITLE
School Manager Page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2761]
# Add to admin dashboard 
- [x] right under user manager add a new link called “School Manager” 

# School Directory Page 
- [x] Add school premium type a drop-down selector. (Allow multiple selections)
- [x] By default only search schools with at least one teacher. ass a checkbox to include schools with 0 teachers.

**note: click on the image for a full-size picture**
![school_manager](https://user-images.githubusercontent.com/3667179/31023147-f79a176a-a508-11e7-8a5f-dcccd587587a.png)

# View School Page

## Teachers
- [x] Add each of the fields in the wireframe. 
- [x] For total count of activities, if that is challenging to get, the total number of sign-ins is a good proxy for us for now. 
- [x] shows the teachers premium status. If the school has school premium, that will generally over-ride the teacher's status. 

![view_school](https://user-images.githubusercontent.com/3667179/31023173-0c246776-a509-11e7-9595-d08ac3cf279e.png)

## Edit Subscription 
- [x] user sees the premium status and expiration for the school. 
- [x] Show all of the options (See github issue #3106 )
School District Paid
School NYC Free
School NYC Paid
School Research
School Sponsored Free
School Strategic Free
School Strategic Paid
School Paid
- [x] can we make the default for the expiration date as the current date plus one year. 
![edit_subscription_page](https://user-images.githubusercontent.com/3667179/31023226-30318d7e-a509-11e7-9ded-db4fbd5587f8.png)

## Edit School Info
![edit_school_info](https://user-images.githubusercontent.com/3667179/31023402-ab8c509e-a509-11e7-9c45-e8d344fd07b5.png)
- [x] Warning: Please don't edit the school info unless you are 100% sure it needs to be changed. 

# Add new school 
- [x] Enable users to add new schools along this criteria. 
- [x] include the warnings on the right hand side. 
- [x] when you save the school, it should bring you the edit verision of the school to add a new admin. 
![add_new_school](https://user-images.githubusercontent.com/3667179/31023462-e2541440-a509-11e7-95bb-af82ce9aebb5.png)

**Comment by jaredsilver** [comment]
Remaining:

- [ ] Pagination?
- [ ] Clean up query (mail_city versus city, mail_state versus state, mail_zipcode versus zipcode)
- [ ] Thoroughly check the `show` query for sanity
- [ ] Make Admin function
- [ ] Sign in link
- [ ] Show / teachers query: override teacher premium status with school premium status?
- [ ] Styling
- [ ] Finish edit subscription functionality

**Comment by jaredsilver** [comment]
TODO: Make sure you're using the correct join tables for subscriptions!

**Comment by jaredsilver** [comment]
Note: correct table for admin is schools_admins
