### ISSUE TITLE
Warning if you try to add a teacher to an admin profile where that teacher already exists. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2784]
If a teacher already exists in the Quill database, there is no warning. Instead, it should show a message in red. 

- [ ] Rename “Add Teacher” button to “Create Teacher Account” 
- [ ] Show the following message: "This teacher already has an account on Quill. To add this teacher, ask the teacher to select your school from their My Profile page."

![screen shot 2017-08-16 at 2 30 40 pm](https://user-images.githubusercontent.com/3667179/29379168-875be21c-828f-11e7-9498-b456b4535716.png)

**Comment by RyanNovas** [comment]
will be irrelevant upon transferring to new system

**Comment by RyanNovas** [comment]
We're pulling the ability to directly add teachers. Instead all associations will occur by the user joining the admin's schools.
