### ISSUE TITLE
Filter By Tool Buttons Missing from Activity Planner

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#2799]
The buttons that allow teachers to filter by tool when creating a custom activity pack seem to be missing. 
![screen shot 2017-08-17 at 6 01 03 pm](https://user-images.githubusercontent.com/20426718/29435797-6e332916-8376-11e7-8e78-54a6eb27ec4f.png)

**Comment by RyanNovas** [comment]
unable to repo this
