### ISSUE TITLE
Quill Lessons LMS Issues and Adjustments 

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2824]
- [x] Card on Teacher dashboard: List of Assigned Quill Lessons: From oldest to newest if completed don’t show it and the copy should be List of Assigned Quill Lessons instead of List of Recently Assigned Quill Lessons
- [x] Add animation to tool page
- [ ] Drop Number column in the list of activities under Explore All Activities 
- [x] empty lessons launcher card. Zeplin: https://zpl.io/bl34G0a
- [x] empty lessons launcher card with diagnostic completed. Zeplin: https://zpl.io/bl34G0a
- [x] In the Questions and Answers section in the tool page, this link "View All Questions and Answers" should link to https://support.quill.org/activities-implementation

## Later
- [x] Change the copy from launch lesson to resume lesson if the teacher does not complete a lesson
- [x] Change the copy of the button on the student end to Join Lesson

**Comment by emilia-friedberg** [comment]
@amr-thameen In regard to the teacher dashboard card, it should still only show five lessons at a time, right?

**Comment by amr-thameen** [comment]
@emilia-friedberg yeah it should show 4 lessons at a time and be able to launch them from there.
