### ISSUE TITLE
Update dashboard mini copy images

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2911]
Now that the query only shows the performance from the last 30 days we need to update the copy of these images. (Or maybe they should have never been images...)

New copy: 
Once your students have completed
**30 activities** in the past 30 days, 
you'll see their **X results** here. 

![image](https://user-images.githubusercontent.com/3110565/30194681-aa4ca3c0-9422-11e7-919b-3b888f8ee26c.png)

![image](https://user-images.githubusercontent.com/3110565/30194702-ca86532a-9422-11e7-87ef-4ac10f345585.png)
![image](https://user-images.githubusercontent.com/3110565/30194708-d070da9e-9422-11e7-8821-9d53610a5ebf.png)

**Comment by amr-thameen** [comment]
assets/images/shared/results_card.svg
zeplin: https://zpl.io/2EmyRoD

- [ ] Add the new image 
- [ ] write the text under it
