### ISSUE TITLE
Activity Search Improvements

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2954]
When searching for activities we currently only search the title of the activities. We also want to include matches from the description and activity category titles.

- [ ] Add the Activity.description text string to the ransack search
- [ ] Add the ActivityCategory.name text string to the ransack search
- [ ] try it out.
- [ ] Investigate changing the weights that a match on each field contributes to the order of the returned activities.

**Comment by emilia-friedberg** [comment]
we are not currently using ransack to search activities. However, the query we are using has been updated to include matches from descriptions and activity categories, although it is not possible to weight these values at this time.
