### ISSUE TITLE
NoMethodError: undefined method `classroom_id' for nil:NilClass

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2973]
https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/b40c6f2c-9c24-11e7-b844-0242ac11000f_0_16450

/teachers/get_completed_diagnostic_unit_info

**Comment by jaredsilver** [comment]
Leaving some notes for myself:

Line 50.

Possibilities:
- CA has been archived --> need to look for unscoped
- There's something wonky with the sql query in `finished_diagnostic_unit_ids`
- The milestones are being created incorrectly
- ~~activity ids are not accurate~~ (they are)
