### ISSUE TITLE
Admin Dashboard Page

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2974]
Zeplin: https://zpl.io/2GEQ0y3
https://docs.google.com/a/quill.org/document/d/1ScXfsLuO9ojDR7JtwzQRF-U_XrqYuFSiFw95ymk6MBs/edit?usp=sharing
- [x] Rename "Admin Dashboard" tab to "School Dashboard"
- [x] Add the premium features section at the top of the page
- [x] Link to YouCanBookMe
- [x] Add Questions and Answers section (use the same elements of the Lessons question and answer section) 
- [x] Allow admin to add teachers 
- [ ] Allow and admin to grant admin rights to other teachers.
- [x] send emails based on the case of the teacher added (existing account vs new account)

**Comment by ddmck** [comment]
@amr-thameen where is the copy for the emails and the Q&A section?
