### ISSUE TITLE
BUG REPORT: Diagnostic recommendations not displaying as assigned

### ISSUE THREAD

**Issue by jenny-price** [empirical-org/Empirical-Core#2980]
https://docs.google.com/document/d/1H2Mjv8RMv4OMazyTagtC4dXfIFg_nfgkijBLEXxoAXg/edit

**Comment by ddmck** [comment]
@jaredsilver This may be related to us renaming the packs earlier in the month when we took them out of beta and removed " | BETA" from the pack name.

**Comment by jaredsilver** [comment]
The issue here is that `/app/models/concerns/public_progress_reports.rb:217` is looking for the `.first` of any units that match either "name" or "name | BETA" -- which sometimes results in different units.

**Comment by jaredsilver** [comment]
Closing this for now because it is likely related to the mess we discussed yesterday. If it comes up again after we resolve that, we can revisit it.
