### ISSUE TITLE
Explore All Activities Page: Fixes

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#2989]
- [x] Add Activity Category column instead of the Concept Column (I'm just calling it Category, activity is redundant.)
- [x] The tools filter tabs should be in this order: Diagnostic, Lessons, Connect, Grammar, Proofreader
- [x] The page is taking a long time to load Peter was saying maybe it is an indexing issue? (We added a bunch of new labels and sorting, this is the consequence.)

## For Amr:
- [x] By default, the list of activities should be sorted by tools so Diagnostic, Lessons, Connect, Grammar Proofreader.

**Comment by ddmck** [comment]
Sorting tools can now be done from the admin panel
