### ISSUE TITLE
QA'ing Units Improvements

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#3012]
Before I left, units seemed to display fine in the user I was logged into, but that was not checked more widely.

Upon attempting to edit units, it seems that it may have made duplicate units. I would log into a non-power user's account and edit some units to see if this is true.

The units components are shared by about 3-5 features. They will all also need to be QA'd. Do a global search for any files that are different and see what else touches upon them.

Starting yesterday I began making methods that would accommodate for the props other features pass. For example something like:

```
getCaId(){
    return this.props.caId || this.props.classroom_activity.id
}
```

I would continue this pattern and we can refactor later. 

However, be aware that at the earliest stages, of this feature, I may have just overwritten props used by other features. So, if when testing the other features that use the units components, for any `undefined` or `can't call x on undefined` errors, I would suggest logging the props and there is probably something similar to what it is expecting that is being passed.

Finally, make the test suite green.

**Comment by jaredsilver** [comment]
I have not been able to reproduce the units being duplicated.

**Comment by RyanNovas** [comment]
Good. Then it likely isn't happening. I saw something that looked weird but
it was while I was on my way out so may have been nothing

**Comment by jaredsilver** [comment]
Putting a note here that the `classroom_lessons` component is broken -- there are some additional endpoints that we may need to rejigger in order for everything to work properly.

I really haven't done a super thorough QA of this stuff yet w/ every edge case, but I've fixed a few things I noticed were broken.

#3018 has everything I did as a PR off of @RyanNovas's refactor branch, and it's worth @RyanNovas reviewing it a bit before merging it in to make sure what I did makes sense.
