### ISSUE TITLE
404 when students complete a sessions that teachers archive while they are playing.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3013]
https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/3ed42f52-9edb-11e7-9864-0242ac110009_0_16570

We are checking for visible and non-visible units, so is there someplace that activity sessions are being deleted rather than made non-visible from?

**Comment by jaredsilver** [comment]
>"is there someplace that activity sessions are being deleted rather than made non-visible from?"

From what I can tell, no.
