### ISSUE TITLE
BUG REPORT - "Assigning..." button does not change to "Assigned"

### ISSUE THREAD

**Issue by jenny-price** [empirical-org/Empirical-Core#3017]
https://docs.google.com/document/d/1q-l77i8tlD4DprXdoZO3Nxb5u_0KSXWbsTXzMPlnwn0/edit

**Comment by jaredsilver** [comment]
Closing this for now because I can no longer reproduce it locally after this week's merges into develop. If the issue occurs again, I can take another look into it.
