### ISSUE TITLE
BUG REPORT - Students completed diagnostic, but no recommendations

### ISSUE THREAD

**Issue by jenny-price** [empirical-org/Empirical-Core#3031]
https://docs.google.com/document/d/13p2qENMndVPZePMwvV8zN8Z7j3f5wj_4wDQbDugAj5w/edit

**Comment by ddmck** [comment]
@jaredsilver this issue it seems to be only an issue for the class in the screenshot. The students are coming back as null, so I would check how we are querying the data.

**Comment by jaredsilver** [comment]
Errors being logged in #3032
