### ISSUE TITLE
BUG REPORT - Unarchived class shows only partially restored data

### ISSUE THREAD

**Issue by jenny-price** [empirical-org/Empirical-Core#3072]
https://docs.google.com/a/quill.org/document/d/1sN33ocOdG_wo1ztxNRz7gNH8F0U9OmVyWlbsEO9gUz0/edit?usp=sharing

**Comment by ddmck** [comment]
@emilia-friedberg Could you take a look at this, as it might be related to the unarchiving, but it seems weird in general.
