### ISSUE TITLE
new teacher fix: restore archived activity sessions

### ISSUE THREAD

**Issue by emilia-friedberg** [empirical-org/Empirical-Core#3075]
When teachers reassign activities, particularly the diagnostic, they frequently do not realize this will archive other students' activity sessions. We can add a method to teacher fixes that will take a teacher name, a unit name, and a classroom id. This method should find all archived activity sessions associated with classroom activities with that unit and classroom id, unarchive them, and add those ids back to the classroom activity's assigned_student_ids array.

**Comment by ddmck** [comment]
@emilia-friedberg is this done now?
