### ISSUE TITLE
Homepage / Lessons Tool Page - Minor Fixes/Additions

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3094]
## Lessons Tool Page
- [x] Add "View My Story" button under the testimonial, open this in a new tab "https://medium.com/writing-with-quill/quill-launches-quill-lessons-fb983f2b8970#3bb3" 
- [x] "View All Question" links to "https://support.quill.org/using-quill-tools#quill-lessons"
- [ ] pattern behind "Try It Out Yourself" is a little messed up. (ask amr)
- [x] Add "how-to-guide" banner, check zeplin: https://zpl.io/2Z0zB4a

## Homepage
- [x] On the homepage, let's remove the Atlantic logo and replace it with ISTE (link: /images/homepage/iste_logo.svg
- [x] homepage, the text inside all buttons is not centred

**Comment by emilia-friedberg** [comment]
@amr-thameen where does the how to guide on the tools page link to and where is that illustration?
