### ISSUE TITLE
BUG REPORT - Diagnostic Recommendations not getting assigned

### ISSUE THREAD

**Issue by jenny-price** [empirical-org/Empirical-Core#3116]
https://docs.google.com/a/quill.org/document/d/1VqDhxY6j_PMmU-oW3TNAYgE2SpEzAadwvC9QzCFLafc/edit?usp=sharing

**Comment by beccaquill** [comment]
Still having issues with Quill Diagnostic Recommendation Assigning page: [https://drive.google.com/file/d/0B81dPcYVVZFTUjEyQllfZkxtZVk/view](url)

User is: hcampion@ms343.com Hannah Campion

She's a friend of mine, so let me know if you'd like me to reach out to her directly with follow up questions.
