### ISSUE TITLE
Add Students Issues

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#313]
When a teacher invites a student, if only the first or last name is used two different problems occur.

1) Only the first name is used -- this leads to a 500 error
2) Only the last name is used -- this leads to the student populating the roster with the last name in the first and last field. In the example from the screen shot below, this means:
First Name: test Last Name: test Username: .test@merry-honey
![screenshot 2014-08-26 at 10 44 05 am](https://cloud.githubusercontent.com/assets/6655439/4046161/ed206be4-2d2f-11e4-8316-165e583c6eed.png)

Instead of these outcomes, let's just make a notification requesting the first and last name.

**Comment by bobmazanec** [comment]
`'Please provide both a first name and a last name.` notification was added in 432a3939.
