### ISSUE TITLE
Activity Analysis: Lessons marked complete for absent student

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3142]
Currently, if a teacher assigns and launches a lesson with their class but a couple of students don't join the lesson, we are still marking these students as if they completed their lesson in the Activity Analysis. Can we only mark the students who join the lesson complete? So the lesson box will be grey in the visual overview and on Activity Analysis, we don't show the students or show them as grey in the list. Let me know if this is crazy to implement

**Comment by ddmck** [comment]
As part of the visual overview improvements, we can now update this.

- [ ] on completion of a lesson, set completed: true on the classroom activity. This will require a migration.
- [ ] for any students who do not have concept results saved, delete their activity session.
- [ ] Update the visual overview to take account of the completed status.
- [ ] Update the student profile to take account of the completed status.
