### ISSUE TITLE
Authors Editor page not loading 

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3189]
I was not sure if this issue should go here or Quill CMS, let me know and I can move it 

This page is not loading https://www.quill.org/cms/authors 

----

Jared notes:

- [x] Rewrite the author stuff in the CMS in erb
- [x] Deprecate Paperclip
- [x] Update the serializer
- [x] Manually check components that use the image url
- [x] Upload new files (including `missing`) to CDN

**Comment by jaredsilver** [comment]
Jared note: port over `app/assets/javascripts/cms/authors/authors.jsx` into a proper React component.

**Comment by jaredsilver** [comment]
Jared note: just rewrite this whole thing in erb instead of dealing with these React shenanigans.

**Comment by jaredsilver** [comment]
Jared note: deprecate Paperclip.
