### ISSUE TITLE
BUG REPORT: Unable to delete students from a class

### ISSUE THREAD

**Issue by jenny-price** [empirical-org/Empirical-Core#3203]
https://docs.google.com/a/quill.org/document/d/1N78EA3sI3SVxNIEF8f1SveGi70F6yKRO9BZhXyoQ4aI/edit?usp=sharing

**Comment by jaredsilver** [comment]
@RyanNovas -- this seems like it might be related to the activity session stuff. The `teacher_hide` method in `app/controllers/students_classrooms_controller` seems to be loading a bunch of random things (including a bunch of activity session stuff) through callbacks, and it seems that the "visible: false" isn't committing as a result.
