### ISSUE TITLE
Visual Overview: status, ordering, tooltip, keys

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3218]
https://zpl.io/2p16XAo

## Colors/Status
- [x] Not Started: gray border and no fill
- [ ] Missed: grey border and no fill, crossed out. (Not done yet)
- [x] Started: blue border, white fill, grey apple and clock
- [x] First completed: the color of status (red, yellow, green depending on the score) 
- [x] Second attempt started: clock, original color of the first attempt, tooltip includes number of attempts
- [x] Second attempt completed: color of the second attempt, number of retries badge

## Ordering:
- [x] We first order activities by completion. Oldest completed to the left. 
- [x] Next, we have started activities.
- [ ] Missed activities
- [x] Not started activities 

## Tooltip:
- [x] Add in the tooltip the number of retries the student has done. (in the score section)
- [x] Add 2nd score, 3rd score if the students attempt multiple times
- [x] Diagnostic: “Quill Diagnostic does not provide a score. You can click to view recommended activities based on the student's’ performance.” 
- [x] Lessons: “Quill Lessons are facilitated by the teachers and not graded. You can click to view your student’s’ answers from this lesson.” 
- [ ] Missed Lessons: "This student has missed this in-class group Quill Lessons activity."

## Keys:
- [x] Add a key for completed activities blue.
- [x] Add a key for in progress activities
- [x] Change the color for the default tools key to grey and no fill
- [x] Not finished is now “not started”

**Comment by amr-thameen** [comment]
Images:

assets/images/scorebook/grammar-embossed.svg
assets/images/scorebook/blue-circle-sliced.svg
assets/images/scorebook/blue-circle-solid.svg
assets/images/scorebook/connect-embossed.svg
assets/images/scorebook/diagnostic-embossed.svg
assets/images/scorebook/grammar-embossed.svg
assets/images/scorebook/lessons-embossed.svg
assets/images/scorebook/proofreader-emobssed.svg

**Comment by emilia-friedberg** [comment]
@amr-thameen do not answer this today because you are home sick, but just to make sure I'm clear on this logic:

right now, when students have completed multiple attempts, we default to showing the color associated with their best score. Is it the case that we are no longer doing that, and now want to show the color associated with their most recent score?

**Comment by amr-thameen** [comment]
@emilia-friedberg Yeah, let's keep showing their best score and when they try again we show the time ticker on top of the color of the best score.
