### ISSUE TITLE
Visual Overview and Activity Analysis

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3222]
Once we finish the visual overview refactor, show the empty students in the activity analysis by showing all students from the classroom activity minus the completed sessions. 
We’re saying not completed and were started not finished. 

Clarification:

Add two items to bottom of students page for activity analysis: 'Unstarted' and 'In Progress'
List the names of the relevant students.

**Comment by emilia-friedberg** [comment]
@ddmck Can we talk about this? I'm not sure exactly what you mean.
