### ISSUE TITLE
Fix Metabase and Check Query

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#3230]
Query to grab teachers by school premium type. It works great when it is account.type=X

When you add OR logic, it breaks. 

- [ ] check for indexes on premium type. 
- [ ] Check if the query works. For example, there is "US strategic partners" query in metabase. It is a combination of "Us strategic free" or "us strategic paid." It runs with just free, but it times out with paid.

**Comment by petergault** [comment]
https://data.quill.org/question/40
https://data.quill.org/question/45

**Comment by RyanNovas** [comment]
Got it working by not pulling in the address and phone number of schools. If queries are running slow, try removing non-essential info from the select statemetn.
