### ISSUE TITLE
Bug Report: Diagnostic recommended activities not changing to assigned activity packs with the green icon

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3315]
https://docs.google.com/a/quill.org/document/d/1kO4NQV_ARJ5sJKU6_Gkg_Ge8VjzhUG1ICW64VZE4vEY/edit?usp=sharing

**Comment by jaredsilver** [comment]
This is likely because these units do not have the appropriate unit template ID on them. Closing this particular instance because it's been over a month.
