### ISSUE TITLE
Assign Activity Page Changes

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3329]
https://zpl.io/ag80eAb

- [x] Add title and stylize it 
- [x] Add the note tooltip
- [x] Add the number of students assigned next to the name of the classes (three different messages based on how many students selected)
- [x] Changing the font size and style for the labels

**Comment by emilia-friedberg** [comment]
The individual classroom components are in the classroom.jsx file at Empirical-Core/client/app/bundles/HelloWorld/components/lesson_planner/create_unit/stage2/classroom.jsx

This component appears on the the second create unit page (http://localhost:3000/teachers/classrooms/assign_activities/create-unit), the assignment step of both diagnostics (http://localhost:3000/diagnostic/413/stage/3), and on the edit students page for a given unit.

These pages correspond to the following components respectively:

Stage2 (Empirical-Core/client/app/bundles/HelloWorld/components/lesson_planner/create_unit/stage2/Stage2.jsx)
ClassroomPage (Empirical-Core/client/app/bundles/HelloWorld/components/diagnostic/diagnostic_questionnaire/ClassroomPage.jsx)
ClassroomsWithStudents (Empirical-Core/client/app/bundles/HelloWorld/components/lesson_planner/create_unit/stage2/ClassroomsWithStudents.jsx).
