### ISSUE TITLE
Edit Student for Activity Pack Page

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3330]
https://zpl.io/25E4MWJ

- [x] Add Note tooltip
- [x] Add the number of student assigned next to the name of the class

**Comment by emilia-friedberg** [comment]
The individual classroom components are in the classroom.jsx file at Empirical-Core/client/app/bundles/HelloWorld/components/lesson_planner/create_unit/stage2/classroom.jsx

This component appears on the the second create unit page (http://localhost:3000/teachers/classrooms/assign_activities/create-unit), the assignment step of both diagnostics (http://localhost:3000/diagnostic/413/stage/3), and on the edit students page for a given unit. These are in components Stage2 (Empirical-Core/client/app/bundles/HelloWorld/components/lesson_planner/create_unit/stage2/Stage2.jsx), ClassroomPage (Empirical-Core/client/app/bundles/HelloWorld/components/diagnostic/diagnostic_questionnaire/ClassroomPage.jsx), and ClassroomsWithStudents (/Users/emiliafriedberg/quill/Empirical-Core/client/app/bundles/HelloWorld/components/lesson_planner/create_unit/stage2/ClassroomsWithStudents.jsx).
