### ISSUE TITLE
Rake task to update schools database (& investigate value of external APIs)

### ISSUE THREAD

**Issue by jaredsilver** [empirical-org/Empirical-Core#3385]
- [x] Create a Rake task to update the public schools
- [x] Investigate whether we should use an external schools API

**Comment by jaredsilver** [comment]
Looks like we've been at around 10-15% of users listing their school as 'not listed' over the past month or so. It's been decreasing slightly, but not by a huge amount. I think we should go ahead and do the rake task, wait a while to see if that makes a further dent, and then invest in an external API if it seems necessary.

The other important thing to consider here is that a significant percentage of these signups may not actually have a school. Homeschoolers, independent learners, and people just checking out the site may make up a significant proportion of that group, so I'm not sure it's worth worrying too much about.

**Comment by ddmck** [comment]
@jaredsilver This was resolved by us running a script a while ago, correct?

**Comment by jaredsilver** [comment]
We did this for the private schools, but I do not believe we have done it for the public schools yet.
