### ISSUE TITLE
Co-teachers

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3388]
What we will need:
- [x] A join table for co-teachers
- [x] To update the class_i_teach function to take account of the join table.
- [x] Update the validations on anything that requires ownership of classrooms.
- [ ] New views for adding co-teachers
- [ ] Update views when data from a co-teacher may be present or functionality may be limited.
- [ ] Update Google Classrooms and Clever importers to bring in co-teachers.

## The classroom_teachers table.
fields: 
user_id - int, 
classroom_id -  int, 
role - string with pg validation on allowed values. For now, "owner" and "co-teacher" are allowed.

# The classrooms_i_own function
- [x] looks for classrooms via join on classrooms_teachers where role = "owner"

# The classrooms_i_teach function
- [x] looks for classrooms via join on classrooms_teachers regardless of role.

# Classrooms_i_co_teach function
- [x] looks for classrooms via join on classrooms_teachers where role = "co-teacher"

# Implications.
- [x] update google classroom importer.
- [x] update create classroom
- [ ] update all of the dataclips.
- [ ] remove edit functionality from places shouldnt be.

# Permissions
Coteachers can do everything but
- [ ] archive classrooms
- [ ] archive units

# Authentication
- [x] teachers auth will ensure that the current user is amongst the classrooms teachers
- [x] owner auth will ensure that the current user is the classrooms owner

# Broken Things to Come Back To
- [x] app/controllers/concerns/unit_queries.rb #get_classroom_activities_for_activity
- [x] students on assign lessons page

# Deprecate.teacher 
- [x] change it to `#owner`

# Caching
- [x] lessons_array and more (working list)

# Affected SQL queries (need to update & test)
- [x] `app/profiles_controller.rb`
- [x] `app/teachers/classroom_manager_controller.rb`
- [x] `app/teachers/units_controller.rb`
- [x] `app/models/concerns/teacher.rb`
- [x] `app/queries/dashboard.rb`
- [x] `app/queries/progress_reports/standards/classroom.rb`

# Restricted Access
- [ ] Can’t archive classrooms. 
- [ ] Can’t archive units. You don’t see the archive unit if it is not a unit you created.
- [ ] Can only change assigned activities in units you own.
 
# Questions
(@ryannovas writing this, addressed to @ddmck ) For storing pending co-teacher requests, would we want to do this through redis, or through the DB? In either case, we'd need to either store the email of a user that is yet to sign up for Quill, then check new signup emails against this store, or give a custom email link which has either a key or id related to the store. 

My first instinct is to use Redis as this data is so ephemeral. However, if we do it through the DB, we could have somewhat of a path to the initial referrer (i.e., the one who invited the user to Quill).  The other downside of Redis is that thus far, we've mostly (entirely?) been using it for caching, and as such could clear it at will. If we are going to simply start using at as a nosql db, then we'll no longer be able to wholesale wipe it.

**Comment by RyanNovas** [comment]
Script to associate classrooms with their owner:

```
Classroom.unscoped.all.each do |classy| 
  if classy.teacher_id
    ClassroomsTeacher.find_or_create_by!(classroom_id: classy.id, user_id: classy.teacher_id, role: 'owner')
  end
end
```

**Comment by amr-thameen** [comment]
Zeplin: https://zpl.io/V1M1Ow5

- [ ] adding the (created tag) to the activity packs that are not owned by the teacher 
- [ ] show tooltip on hover
- [ ] activity packs with (created tag), no edit name, no delete activity pack,

**Comment by jaredsilver** [comment]
Pure SQL for adding ClassroomsTeachers:

```
INSERT INTO classrooms_teachers (classroom_id, user_id, role)
SELECT classrooms.id AS classroom_id, users.id AS user_id, 'owner' AS role
FROM classrooms
LEFT JOIN users on classrooms.teacher_id = users.id
WHERE users.id IS NOT NULL;
```
