### ISSUE TITLE
BUG REPORT - Unable to load diagnostic results page

### ISSUE THREAD

**Issue by jenny-price** [empirical-org/Empirical-Core#3425]
https://docs.google.com/a/quill.org/document/d/1PNVx39D9YL8nfc7dlxoiYxY5e-JBCYElXS4OWl23dNQ/edit?usp=sharing

**Comment by jaredsilver** [comment]
It seems like the units query here is taking like 30 seconds to run, resulting in a 503 error on the ajax call. Not quite sure why.

**Comment by jaredsilver** [comment]
Well, it might have something to do with the fact that this is loading 200 rows from the database...

**Comment by jaredsilver** [comment]
We're going to close this as wontfix for now because of the extremity of this user's scenario.

As a temporary fix for this individual user, we should have her break down that massive classroom into more realistic class sizes (a max of ~50 students per classroom would probably work well).
