### ISSUE TITLE
Bug Report - Diagnostic recommendations checkmarks don't change to green to show they have been assigned

### ISSUE THREAD

**Issue by Istishna** [empirical-org/Empirical-Core#3458]
https://docs.google.com/a/quill.org/document/d/1ROtTH3hcvCXWGjvqyPT9w5o9UaSVC3c4hUn89_C0h9o/edit?usp=sharing

**Comment by jaredsilver** [comment]
This bug is due to the created recommendations not having the appropriate unit_template_id. I'll update it in the production database. This does not seem to be widespread.

This teacher's account should be fixed within the next few minutes.
