### ISSUE TITLE
Bug Report- Due dates not saving when entered

### ISSUE THREAD

**Issue by jkaufmanquill** [empirical-org/Empirical-Core#3464]
https://docs.google.com/document/d/1FVMmG3suu9KQxKiLopr8H1pIjdQpDBFZS3dfzNNoW1E/edit

**Comment by jaredsilver** [comment]
Something's causing a stack level too deep error here. Only seems to be affecting this teacher.

**Comment by jaredsilver** [comment]
Fix forthcoming.
