### ISSUE TITLE
Teacher Onboarding: Add school page 

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3504]
Zeplin: zpl.io/bAOQJ4p

- [ ] (Adding school page) should be a separate page (either that or add a "Back" link at the bottom of the page) 
- [ ] Currently, if I am on the page and I hit back, I get sent to the login page even though I am logged in (See image below) 
- [ ] The prefill text in the zip code field should be Zip Code instead of just Zip
- [ ] white space between the label and the field should be 8px 

![image](https://user-images.githubusercontent.com/25299820/33395723-6a09742c-d514-11e7-9cee-773b4796429e.png)

**Comment by ddmck** [comment]
Blocked by onboarding rewrite.
