### ISSUE TITLE
Activity Analysis: Loading All Students At Once

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3523]
Currently, on the activity analysis page, we are loading In Progress and Not Started students first. Can we delay showing those students until we have all loaded all the other students and show them all at once?

<img width="794" alt="screen shot 2017-11-30 at 6 08 37 pm" src="https://user-images.githubusercontent.com/25299820/33486583-acf199bc-d678-11e7-9165-43ca58eac962.png">

**Comment by jaredsilver** [comment]
Note: we added the 'in progress' and 'not started' pieces separate from the component that shows the completed ones, so this may require a hacky solution.

Idea: make the bottom `display: none;` by default, and then pass a function as a prop into the 'completed' component that makes them display. Call it in the 'completed' component when the data is loaded.
