### ISSUE TITLE
Reverse Order of Recommended Packs 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#3567]
Classroom Unit Order

# Quick Fix. 
- Let's review the quick fix issue of changing the code. Is it worth the quick fix vs. the classroom unit order? 

# 1. Create Classroom Units
- [ ] Does it make sense to build classroom+units before we build classroom_units order? How do these two things play into each other?
- [ ] set order for just the recommendations? 

# 2. Option - Create Classroom Unit Order
- Set an order for packs. 
- When you edit a pack it does not change the order of the packs. 
- Create an “Edit Order” button that allows a teacher to reset the order of the packs. This will change the order for all of the students. 
- Logic now is that the packs that are unstated or partially unstated come in the order. Completed packs always are displayed at the bottom. 

# Compass Fix
- [ ] Reset the packs in the right order. Set the order or write the code order feature?
- [ ] Remove all of the activities from the packs from the packs: capitalization, articles, irregular verbs, and prepositions. Don’t remove the completed one, just unassigns the uncompleted ones. 
What happens with an empty pack?

**Comment by RyanNovas** [comment]
Ultra-Quick Fix To Stop This From Continuing:
`controllers/teachers/progress_reports/diagnostic_reports_controller.rb create_or_update_selected_packs` has a reverse in it. Remove this

Longer Term Quick Fix for Recommendations:
1. Add order column to units
2. Explicitly set order whenever recommendations are at play.
3. Return this as part of the unit to the scorebook/student profile.
4. We can manually edit through console as necessary.

Real Fix:
Set a drag and drop ordering system whenever a teacher goes to "My Units"
