### ISSUE TITLE
New Premium Report: Activity Scores

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3574]
Zeplin: zpl.io/aRmv14r
Zeplin: zpl.io/an6Ap3v

- [x] make sure lessons and diagnostic are not computed in average
- [x] Main class score page: list of all students in one class, their numbers of activities completed and their overall score on Quill
- [x] From main page, you can click on one student and that will bring you to the student report.Student Report contains:
- [x] Average Overall Score on Quill (count the highest score if the student has multiple attempts)
- [x] Number of Activities Completed 
- [x] Date Last Active and by default sort by that
- [x] List of All Activity Packs assigned by students with Average Score.
- [x] The Activity Pack will have a list of all activities within the activity pack, date completed, and score
- [ ] ~~if the activity is done multiple times show that and the score and if its missed or not started the same thing~~
- [x] from the table, you should be able to get to the activity report, preview activity and download report

Main Page:
![screen shot 2017-12-12 at 1 18 37 pm](https://user-images.githubusercontent.com/25299820/33901191-04678f0c-df3f-11e7-87f1-b2a078a22dda.png)

Student Page:
https://app.zeplin.io/project/58939e73c4a8fbc0512e606e/screen/5a33fd207599a2a6a3fee7b1

**Comment by RyanNovas** [comment]
Queries have been built on `feat/new-unit-reports`. Awaiting Zeplins

**Comment by amr-thameen** [comment]
New comments:

- [ ] Update the description copy of the activity scores page
- [ ] add how we grade 
- [ ] click download, will have a drop down on activity scores page
- [ ] when you click on pdf or csv, the download button will be fiiled and say "preparing report" with spinner, then goes to download now.
