### ISSUE TITLE
Manage Classes Page Updates

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3598]
- [ ] Can we extend the width of the page to 950 instead of the current 910px so Edit Students and Date Created do not get a break
- [x] "Co-Teacher Invited" message is persistent after I invite a co-teacher, it should disappear after 3 seconds of inviting a co-teacher.
- [x] Lets remove the illustration from the "What can cp-teachers do?" section and extend the text box
- [x] Build the top section of the page. zpl.io/bo0Dx0X

![image](https://user-images.githubusercontent.com/25299820/34005989-bf80a8fa-e0ca-11e7-8130-481271f6e141.png)

![image](https://user-images.githubusercontent.com/25299820/34006041-f76c2668-e0ca-11e7-80d0-2378d1c49172.png)

**Comment by jaredsilver** [comment]
@amr-thameen: extending the width of the table doesn't seem to be sufficient for preventing those line breaks, but perhaps we can just wait until we change that Edit Students link to Edit Class (and then hide the Archive link as a button on the edit page instead).

**Comment by jaredsilver** [comment]
@amr-thameen: because "View Premium reporting (unless they have a Premium account)" is the only thing that wraps to a new line, could we change it to something terser like "Share your Premium features"?
