### ISSUE TITLE
Visual Overview: Updates 

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3608]
zeplin: https://zpl.io/bezr4dq

- [x] Changing name of the page to Activity Summary (make sure the link at the top is changed)
- [x] Add avg overall score next to the name of the student with a link to the Activity Scores report
- [x] When you are filtering the dates, lets have it update from the date you choose on and not stop so it keeps updating. For example: if I choose Last week, and I check the report tomorrow, then that report should update to show Last Week from tomorrow. If this does not make sense let me know

**Comment by jaredsilver** [comment]
I believe the final bullet here was already implemented by @emilia-friedberg in a prior PR.
