### ISSUE TITLE
Explore All Activities: Updates

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3610]
Zeplin: zpl.io/aXKAP6l
Zeplin: zpl.io/bWQPXKxdrop 

## Expected Behaviour

- [x] use the same new table white background. Light green when hover and once you select it stays green.
- [ ] ~~clicking on row, you select that activity, if you click again, you unselect~~
- [x] dropdowns are white instead of gray 
- [x] switch the columns around: Concept - Tool - Activity Name - checkmark
- [x] Include standards in the tooltip of the hover
- [x] change the dropdown to "level" instead of "standards" and "concept" instead of "category"
- [x] hovering on tooltip should not keep it open, the hover effect is propagating 
- [x] if you select an item from the dropdown, the outline turn green
- [x] "Selected Activities for New Activity Pack" section should include icons

**Comment by RyanNovas** [comment]
@amr-thameen I disagree with the clicking on the row. If the only interaction is limited to check/uncheck, it would make sense, but as it has a link embedded within it, I believe we should keep the click actions local to whatever they are hovering over.
