### ISSUE TITLE
List Overview Updates

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3611]
** Use the same table **

Zeplin: zpl.io/2p0QPmE

## Expected Behaviour
- [x] Change the name from List Overview to Data Export
- [x] Update the description copy
- [x] default sort by date of completed activity so most recently completed first
- [x] blur the score and the name zpl.io/VDpRdee
- [x] when an item is selected from the dropdown, give it green outline zpl.io/2p0Qj5E
- [x] Download report is only CSV 
- [x] columns should be sortable

---

- [x] Refactor the query because it is **slow**.

**Comment by jaredsilver** [comment]
@amr-thameen How are we handling Lessons and Diagnostic scores on this page? Should they show up as 100% or something different?

**Comment by amr-thameen** [comment]
@jaredsilver Let's handle them as "Completed" and not show a score so we maintain how it's represented in the rest of the reports. If it seems like there is no space for the entire "Completed" maybe try to make the Score column wider.
