### ISSUE TITLE
Activity Analysis: Activity Page

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3637]
Zeplin: zpl://screen?sid=5a4cfb606f0b74a4cf96eda8&pid=58939e73c4a8fbc0512e606e

- [x] Add icon of the tool next to the name of the activity 
- [x] Update icon style
- [x] Add preview activity next to the name of the activity 
- [x] Add info icon next to the prompt
- [x] Clicking on the row will send the teacher to the breakdown of that activity by student (in another word, show the question tab) 
- [x] by default sort from low to high score
- [x] hover effect
- [x] completion
- [x] average score

**Comment by jaredsilver** [comment]
@amr-thameen the icons on the activity planner page currently have a border around them (see below). Do we want to add the same border to the icons on the activity analysis page too?

<img width="967" alt="screen shot 2018-01-03 at 2 15 27 pm" src="https://user-images.githubusercontent.com/1312199/34535687-afff3830-f090-11e7-87ef-9a47162e3a9a.png">

**Comment by jaredsilver** [comment]
@amr-thameen in the mockup, the ELL diagnostic row has some different styles to it; under what circumstances should those styles be displayed? (Is it a hover effect, for unscored activities, etc.?)

**Comment by amr-thameen** [comment]
Yes, that's the hover effect
