### ISSUE TITLE
Create callback on StudentsClassrooms for when a student is removed from a class

### ISSUE THREAD

**Issue by jaredsilver** [empirical-org/Empirical-Core#3640]
Our database has some instances of classroom activities where the assigned student ID list contains IDs of students for whom StudentsClassrooms associations are no longer visible.

When a student is removed from a classroom, we should make sure that we:

- [ ] Remove them from assigned classroom activities
- [ ] Hide their activity sessions
- [ ] Do anything else we would generally do when archiving an individual classroom that is relevant to individual students

**Comment by RyanNovas** [comment]
@jaredsilver is this resulting in complications, or just a messy database?

**Comment by jaredsilver** [comment]
@RyanNovas I believe it was having some implications with data reporting, but I don't remember any specifics off the top of my head.
