### ISSUE TITLE
Featured Activity Packs Page

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3651]
#Zeplin: zpl://screen?sid=5a4e5d5438cdda41c87a6513&pid=58939e73c4a8fbc0512e606e

- [x] Bring the Whats in the pack section to the top of the page
- [x] use the same style that we had for the reports, gray header, white rows.
- [x] "What's inside the pack" needs to be left aligned with the table under it.

Add New Tag to the new activity packs
- [x] Add the new icon next to the name
- [x] The rule will be the three most recently created activity packs get the new tag.

**Comment by RyanNovas** [comment]
@amr-thameen I'm going to do new for things created in the last month. This way we'll never need to update it and things won't keep saying new if we haven't updated in a long time. If this isn't ok let me know and I'll revert.

**Comment by RyanNovas** [comment]
@amr-thameen flags do not fit for longer names. what should it look like if there is not enough room?

Note to myself: function is `newFlag` in `unit_template_first_row.jsx`
