### ISSUE TITLE
Empty/Partial State for Progress reports

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3664]
## Expected Behaviour

That's for @amr-thameen to decide!

## Actual Behaviour
When there are no results for a student:
![image](https://user-images.githubusercontent.com/3110565/34678894-6c98d5da-f462-11e7-8da2-ba9295ac59ad.png)

When there are less than 20 rows:
![image](https://user-images.githubusercontent.com/3110565/34678959-90424e8a-f462-11e7-9aaf-9a52ef25d847.png)

I think we should atleast change the default "No rows found" to something less robotic.

**Comment by RyanNovas** [comment]
I have this set up so there should be no empty rows and there is a 'No Results to Report' message. Will update it to whatever @amr-thameen wants, but this should be fine as a place holder.
