### ISSUE TITLE
Recommended Activities Not Assigning

### ISSUE THREAD

**Issue by jkaufmanquill** [empirical-org/Empirical-Core#3676]

**Comment by jkaufmanquill** [comment]
https://docs.google.com/document/d/1xQ0PjGuQwwRzJNBnQOh1ymrbQ6fIyrwPNZZII8Anfpc/edit?usp=sharing

**Comment by jaredsilver** [comment]
@jkaufmanquill -- if she refreshes the page, it should be good now.
