### ISSUE TITLE
Bug Report: Adverbs of Manner unable to assign from diagnostic recommendations 

### ISSUE THREAD

**Issue by Istishna** [empirical-org/Empirical-Core#3682]
## Potential sources for the issue (filename, new features ect.)

https://docs.google.com/document/d/180tA60kplc6bUtRoaTqSXVg9gJtWoq9kmnpxTvZABpg/edit?usp=sharing

**Comment by jaredsilver** [comment]
@ddmck tagging you per conversation

**Comment by emilia-friedberg** [comment]
This no longer seems to be the case so I am closing this issue.
