### ISSUE TITLE
Activity Scores Report: Followup Issue II

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3683]
# UI:
- [x]  Download bubble: "Download report as" should be left aligned with the pdf button. See image 1
- [x]  Download bubble: clicking anywhere around it should hide it
- [x]  Main table: 'Average Overall Score' instead of 'Overall Score'.
- [x]  Activities that are not started or without score, the color for the link should be #666666
- [x]  Completed Lessons should have the chevron and send teachers to the activity analysis of that lesson, currently it doesnt. See image 4 below

# Download
- [x]  CSV: no need for: completed at, activity session id, activity classification id, is_a_completed_lesson, activity_id, classroom_activity_id. See image 3
- [x]  CSV: 'name' to 'activity name', 'unit name' should be 'activity pack name', 'percentage' should be 'score' and it should have a percentage and for not started activities the percentage should be 'Not Started', and if its a lesson then it should be 'Completed'
@amr-thameen I think having null is better as CSV's are for data reporting and this is a standard practice with data.
- [x]  CSV: For the activities if there is a percentage grade, and not connect, diagnostic or lessons, show percentage, else show complete/incomplete
@amr-thameen I am not sure where this is happening
@amr-thameen again not sure what this is referring to
- [x]  CSV: Add the name of the student and the overall average score
- [x]  PDF: no need for icons if we cant show them lets hide the squares, no need for the bubble. See Image 2
- [x]  PDF: is it possible to always end the page on an end of the activity pack so an activity pack is never chopped.

Image 1:
![image](https://user-images.githubusercontent.com/25299820/34845827-39f5d23e-f6e4-11e7-9b97-3b546b987835.png)

Image 2:
![screen shot 2018-01-11 at 3 42 10 pm](https://user-images.githubusercontent.com/25299820/34846838-74cd35b6-f6e7-11e7-9f18-ea435092aa0d.png)

Image 3:
![screen shot 2018-01-11 at 3 53 00 pm](https://user-images.githubusercontent.com/25299820/34847125-5623a3d8-f6e8-11e7-8f4c-b74be4dee628.png)

Image 4:
![image](https://user-images.githubusercontent.com/25299820/34847386-24b15984-f6e9-11e7-936b-4c1144a1e5a2.png)

**Comment by RyanNovas** [comment]
@amr-thameen, @ddmck and myself were talking about how a lot of these changes makes the csv exports largely mirror the pdf ones. In most services I use, the CSV's are pretty rich in terms of information. If anyone wants to run analytics, do data science, or anything advanced, many of these proposed changes make that much more difficult to do. Are we sure we want to make them this sparse?
