### ISSUE TITLE
teacher unable to access account

### ISSUE THREAD

**Issue by katherineziegler** [empirical-org/Empirical-Core#3719]
## Potential sources for the issue (filename, new features ect.)

https://docs.google.com/document/d/1T42oucshqtw6C2K76mn3jMHhvN6HL6Od4BnH5782J8Y/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
I updated the password a second time and Jared and I could no longer replicate the problem on either Chrome or Safari, so I'm closing the issue.
