### ISSUE TITLE
Remove intercom local storage values from browser when a non teacher is present.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3737]
## Expected Behaviour

Only teachers should see intercom

## Actual Behaviour

Sometimes students see it. This is mostly due to teachers sharing a computer with them

## Steps to Reproduce

Sign in as a teacher, inspect the local storage of the browser, look for data from intercom.

## Potential sources for the issue (filename, new features ect.)

We need to try and clear this local storage data when we see a teacher sign out or a student sign in.

**Comment by jaredsilver** [comment]
`Intercom('shutdown')`
