### ISSUE TITLE
Teacher Resources

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3745]
## Staff CMS

- [x] Copy Featured Activity Pack logic, fields needed: 
- - [x] authors
- - [x] title
- - [x] subtitle
- - [x] body (via markdown)
- - [x] topics (as a column).
- - [x] read_count as int

- [x] Update the Nav bar and to include Teacher Resources

## Overview page
 
[Zepelin](https://app.zeplin.io/project/58939e73c4a8fbc0512e606e/screen/5a660f9b6d9e22a31a854178)
- [x] Implement sections (Case Studies, Teacher Stories, Webinars, Teacher Materials, Education Research)
- [x] How are notifications for webinars stored? 
- [x] Show all should take users to the subpage /teacher-resources/webinars for example.

## Post Page

[Zepelin](https://app.zeplin.io/project/58939e73c4a8fbc0512e606e/screen/5a66115a42683ca66a2b447f)

- [x] Render body with the markdown renderer we currently use for activity packs.
- [x] Render most recent posts at the bottom, selected by date. **Do not use the styling from the Zepelin**, reuse the component from the overview page 

## Topic Page
[Zepelin](https://app.zeplin.io/project/58939e73c4a8fbc0512e606e/screen/5a66115bdfa1c9d3ce8bff4c)
- [x] Reflect in the sub-sub-navbar that we are looking at case-studies etc. This is the page that should load if clicking on those links 
![image](https://user-images.githubusercontent.com/3110565/35240270-e5df3b0e-ff80-11e7-8f81-bb300928c94c.png) (here Case Studies should be highlighted)
- [x] ~~Paginate posts sorted by creation date descending (9 per page for now.)~~ (note: not doing this for now because it's actually more computation at this stage to run separate queries to grab all the information we need than it is to just grab everything and sort through it on the front end... if we get up to some crazy number of posts, this may change, but for now it seems to make sense not to paginate on the back end)

---

# Jared's notes:

### Navigation

- [x] implement teacher resources subnav
- [x] add appropriate hrefs to teacher resources subnav
- [x] implement admin tab
- [x] implement admin subnav
- [x] implement user dropdown menu
- [x] add appropriate links to user dropdown menu
- [x] mobile optimize user dropdown menu
- [x] user dropdown menu vertical rule
- [x] swap links in top navigation menu
- [x] eliminate left and right borders when tab is active
- [x] ensure everything still appears properly on mobile

### Knowledge Center 
- [x] preview cards need links
- [x] create page for displaying 'blog posts'
- [x] implement draft toggling / draft saving
- [x] implement designs and editing functionality for tweets
- [x] implement designs and editing functionality for videos
- [x] implement designs and editing functionality for blog posts
- [x] implement designs and editing functionality for custom HTML
- [x] determine a way to generate appropriate fields upon returning to page
- [x] Remove the existing teacher resources page

### Search Box
- [x] Determine how we want to build this (ElasticSearch, PSQL full-text index, etc.)
- [x] Write a Postgres full-text search query
- [x] Create column on blog_posts for storing ts_vectors
- [x] Create trigger for updating ts_vectors on update or insert
- [x] Add appropriate indexes to ts_vectors column
- [x] Build a search view

### View counter
- [x] Increment view count with each page view
- [x] Front end: implement "most read" section
- [x] Most read post link

### Blog Post Pages
- [x] Convert this into React
- [x] Use react render component to render the body content
- [x] Implement links back to knowledge center
- [x] Navbar active when on an article belonging to a topic in the navbar

### Slugs
- [x] On post create, generate a slug
- [x] If the slug already exists, add "-#"
- [x] If "-#" already exists, increment "#"

### Announcements
- [x] Announcements model
- [x] Announcements CMS controller
- [x] Announcements display for webinar in the knowledge center
- [x] Announcements CMS controller: account for timezones in displaying and saving timestamps
- [x] Gather more requirements about announcements --> would it be better to just have text, link, and CTA?
- [x] Connect back end of announcements display to front end
- [x] Fancy css pulsating animation on the green dot would be nice

### FAQ
- [x] Redesign this page

### Testing & Code Quality
- [x] Blog posts controller spec
- [x] Blog posts model spec
- [ ] 'Topic' should really be its own entity...
- [x] Announcement model spec
- [x] Ensure we're using the proper index on Announcement with respect to start and end dates

---

# Staging Review
- [x] Tools pages navbar needs to be fixed
- [x] All Posts --> show published or unpublished
- [x] Add option to unpublish post
- [x] Edit posts page experiencing some flexbox weirdness in Firefox
- [x] Delete needs a confirmation
- [x] Unpublish --> Unpublish & Save Draft

**Comment by RyanNovas** [comment]
branch is feat/blog
