### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#3767]
## Stronger Stripe Integration

- [x] figure out how to do a one off stripe charge via API
`charge = Stripe::Charge.create(amount: 1000, currency: 'usd', customer: "cus_CFJK1jjfrsD0Pt")
- [x] add stripe_customer_id to user table
- [x] when a user makes a purchase, see if they already exist as a stripe customer
- [x] if they don't exist, create them
- [x] use expire and credit user when a user updates an existing subscription. The update action occurs in subscription.rb

## Renewals
- [x] add a renew boolean column to subscriptions, false by default, true if they opt in
- [x] when a user account is redeemed for credit, turn renew to false
- [x] method to get all subscriptions expiring today with recurring charge
- [x] make method where by a new subscription is made upon successful one off stripe charge via api
- [x] method that goes through all subscriptions expiring today with recurring charge
- [x] chron job that goes each night activating subscriptions
~~- [ ] send grid integration that tells users what happened~~ (this should be done through sales machine or something)

## Subscription Table
- [x] allow users/schools to have multiple subscriptions
- [x] check for future subscriptions everywhere we activate new user subscriptions
- [x] make `user.subscription` and `school.subscription` only returns a single valid subscription
- [x] add subscription start date
- [x] add contact email (for contacts outside of the system)
- [x] add contact_user_id (for contacts with Quill accounts)

## Subscription Type Table
- [x] add subscription type table with name
- [x] add price to subscription type table
- [x] populate subscription types table

**Comment by RyanNovas** [comment]
Give all subs start dates after migration
```
Subscription.each do |sub|
 if !sub.start_date
 sub.update(start_date: sub.created_at)
end
end
```

**Comment by RyanNovas** [comment]
# RULES

## User has never had paid subscription
If current date is between Jan 1 and July 30th sub is created that expires on July 30 following year.
Else it expires December 31 of the following year.

## User has valid paid subscription

Upon payment, start date is the expiration of the current subscription, and end date is one year from then.

## School Buys Subscription and Teachers Already Have It

They get credit for the amount of days left. Teacher premium is set to expire the start date of the school premium.

## If a teacher has multiple subscriptions in the future...

Loop through them, crediting the user and expiring each of them

**Comment by RyanNovas** [comment]
- [ ] Add payment type to subscriptions
- [ ] Show payment types for subs where contact user is current user
- [ ] Show "Premium Credit" (not "Free Credit") for credited purchase
- [ ] Start/End Date is always startdate - expiration date (not to de_activated date)
- [ ] Subscription redemption note goes on top of redeemed subscription

**Comment by tronroy** [comment]
- [ ] Partial months should be displayed rounded to the tenth decimal place
- [ ] 'Quill teacher premium credits' should be changed to 'teacher premium earned credits history'
- [ ] In 'Credit history table' length of time should be whole weeks rounds down
- [ ] Below 'Credit history table' only display total of premium credits earned

**Comment by RyanNovas** [comment]
- [ ] add `SchoolCoordinator` join table
- [ ] add `SchoolAuthorizer` join table
