### ISSUE TITLE
Create a rake task to titleize all schools in the database

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#3788]
Quill has a database of almost every school in the United States. Unfortunately, our data sets were inconsistent, so some of the formatting is different for different schools. In particular, the names of many schools are all capitalized, when they should be titleized.

Please write a rake task that will iterate through every school in the schools table and titelize the name, address, and other relevant data points of the school.

**Comment by kartik-25** [comment]
Hi @jaredsilver, I would like to work on this issue. Can you assign this to me?

**Comment by jaredsilver** [comment]
Hi @kartik-25, please feel free to go ahead and give it a shot!
