### ISSUE TITLE
Standards Page: Add Vertical White Space

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3789]
## Expected Behaviour
There should be white space between:
- The title of the standard and the activities below it.
- The description of the activity and the activity under it.

## Actual Behaviour
There is no white space currently.

## Steps to Reproduce
Go to this link: https://www.quill.org/activities/section/7

**Comment by djbarnwal** [comment]
Hey, @amr-thameen I would like to work on this issue. Can you please assign this issue to me?

**Comment by jaredsilver** [comment]
Hi @djbarnwal -- please feel free to work on it and open a PR.
