### ISSUE TITLE
Problem with speech Assistant

### ISSUE THREAD

**Issue by hardy1334** [empirical-org/Empirical-Core#3809]
## Expected Behaviour
As that tab has been closed so assistant should stop speaking as well .
I have checked it on chrome,so not sure about other browsers. 

## Actual Behaviour
Whenever a user visit links of verb-tense or any other like that where there are questions the user needs to click thrice on that question to let assistant speak that sentence,but even if user has closed that tab assistant continues to speak till that sentence is completed.
like this:  https://grammar.quill.org/play/sw?anonymous=true&uid=rkhMz0hsImTienlg_ZkxUg

As that tab has been closed so assistant should stop speaking as well .
I have checked it on chrome,so not sure about other browsers. 
## Potential sources for #  @the issue (filename, new features ect.)
@jaredsilver  do look into it

**Comment by hardy1334** [comment]
click 3 times on that question statement

**Comment by jaredsilver** [comment]
Hi @hardy1334, thanks for opening this issue!

I'm having a bit of trouble reproducing it though. On my machine (also using Chrome), the voice assistant does seem to be stopping when the tab is closed.

Do you think you might be able to record a screen capture showing what's happening?

**Comment by jaredsilver** [comment]
Ah, I see. To clarify, this bug did not occur for me when closing the tab. However, it did occur for me when submitting my answer and moving on to the next question. Perhaps the right behavior here is to stop the voice assistant when the user has navigated to another question.

Thanks, @hardy1334!

The grammar.quill.org domain is actually a separate service from this repo. If you'd like, you can access it here: https://github.com/empirical-org/Quill-Grammar

I'm going to close this issue in this repo, but please feel free to open the same issue in /empirical-org/Quill-Grammar and/or submit a PR fix there.

Good find!
