### ISSUE TITLE
Update Ruby on Rails to the most stable version 5.1.5.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3859]
Currently, Empirical-Core uses:

```
ruby '2.3.1'
gem 'rails', '=4.2.7.1'
```

This means we are missing out on performance, security, and additional features.

We should update to [5.1.5](http://weblog.rubyonrails.org/2018/2/14/Rails-5-1-5-has-been-released/), the newest stable version.

As we are moving from a rails 4 version it may make sense to first upgrade to 4.2.10 first and then follow [these instructions](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html) for moving to Rails 5.

We may want to increase our controller test coverage (and test coverage in general before kicking this off in earnest.)

**Comment by Ronaq13** [comment]
@ddmck I would like to take this issue.
