### ISSUE TITLE
Update React to v16.2.0

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3860]
Currently, we are using React 15.2.0.

This means that we are missing out on many of the performance improvements introduced in React 16 

Part of this upgrade means removing all code that uses React.createClass as that is no longer supported. This may be quickly fixed by setting up a linter that can auto convert these files.

Once we have upgraded we can audit the existing code and tidy up places where the new features of React 16 allow us to have much simpler code. This may include [fragments](https://reactjs.org/docs/fragments.html) and [portals](https://reactjs.org/docs/portals.html) (this could massively simplify our modal logic.)

**Comment by kartik-25** [comment]
Hi @ddmck , I would like to work on this

**Comment by kartik-25** [comment]
@ddmck  I think React.createClass has been migrated to a different package. So, should I include that in package or work on migrating it to React.Component ?

**Comment by vishalvrv9** [comment]
Hello @ddmck
I would like to work on this issue. Am I eligible for the same? If yes, what would be a good place to start at this point in time?

**Comment by pandeykartikey** [comment]
Hi @vishalvrv9,
There is currently an open PR for the same. If you have any suggestion, I would be happy to implement that.

**Comment by vishalvrv9** [comment]
Hey @pandeykartikey ,

So I went through the PR #3862. Going forward, should we move to ES6 classes everywhere, or functional components? 
Using codemod and jscodeshift would make the task easier but it is no magic wand. The parts that the codemod would miss could be fixed eventually for successful migration(I would be more than happy to collaborate and help 😄 )

FWIW, there are a couple of advantages I can foresee:
1. The biggest advantage, like most tech debt payments, would be that the code would now be brought up to date and this would allow us to normalize much of the code style. 
2. Implementing fragments and portals as pointed out by @ddmck would seem more intuitive imo
3. Incase of heavy use of React Native for cross-platform mobile apps in the future, this would greatly benefit in the long run.
4. Performance should be a bonus.

**Comment by pandeykartikey** [comment]
@vishalvrv9 I think ES6 are developers preference and also mixing up so many things in a PR would cause a lot of merge conflicts eventually and would be troublesome for anyone to review.

**Comment by vishalvrv9** [comment]
@pandeykartikey 
I agree how mixing so many things in one PR wouldn't be wise. But since this issue is listed under Google Summer of Code's projects. Hence, incremental migrations (along with feature additions) could be taken up over the 3 month time period & hence I'm willing to collaborate!

Stuff like arrow functions, the entire reactjs docs being majorly es6, etc will help in code legibility, developer productivity & enhanced stabililty/testability.
