### ISSUE TITLE
Migrate Existing React State Logic to Redux 

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3861]
A large amount of the logic in our React client is managed by the state of the top level component using a rudimentary implementation of flux.

Now as we have to start thinking about moving some of this logic to our ReactNative app the current state based system makes sharing the code difficult.

Following the [example of @tronroy](https://github.com/empirical-org/Empirical-Core/pull/3819) we should re-implement our logic in [Redux](https://redux.js.org/)

We should focus on moving all API calls to redux-thunk actions.

**Comment by kartik-25** [comment]
@ddmck Can I take this up?
