### ISSUE TITLE
Rewrite Quill Grammar And Quill Proofreader

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3868]
## THIS IS NOT TO BE WORKED ON, THIS IS JUST A PROPOSAL FOR GSOC 2018

Quill Grammar and Quill Proofreader are written in Angular 1 and use Firebase Real-time Database.

This is not ideal due to:
- @ddmck is the only member of the Quill team that knows Angular.
- We are using an old version of Angular
- We are moving away from Firebase in favor of Postgresql.
- The apps are in the same codebase when they could be separate allowing for easier development

We would like to move to:
- React 16
- Redux for state management
- Rails 5 backend with Postgres for Data storage (Would maybe consider Phoenix or Adonis.js)
- Typescript
- Individual apps for Grammar and Proofreader
- GraphQL?

This would allow for easier development due to the stacks similarity to the other apps built by Quill.

Proofreader recommends Grammar questions after the completion of the lesson, so the apps will need to be able to pass data to each other.

**Comment by pandeykartikey** [comment]
@ddmck Is this project available for gsoc proposal or is it still in the discussion phase?

**Comment by ddmck** [comment]
@pandeykartikey This is available for GSOC as a proposal, not to be worked on now.
