### ISSUE TITLE
Students on Assign Lesson Page are Out of Order

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#387]
To see go to http://www.quill.org/teachers/classrooms/89/activities/183 with U: Teacher PW: Demo

The students should be sorted alphabetically by their last name. Right now they are out of order.

To access this page, log in as a teacher, go to "Lesson Planner," select "Assign" or "Edit" and then a list of students should pop up.

**Comment by bobmazanec** [comment]
Just found you via [CodeMontage](https://www.codemontage.com/projects/quill); may I infer from "Level: Starter" tag that this is good issue for a newbie on the project? Any specific hints/suggestions/pointers?

TIA

**Comment by RyanNovas** [comment]
Hi @bobmazanec, welcome!

Generally, you could infer that from "Level: Starter." However, in this case we're about to totally overhaul this section in a looming update. So, I'm going to close this issue, but I'd be happy to suggest some others for you. Any thing you're specifically interested in? Otherwise I can just list some projects that should be relatively straight forward to jump into.

**Comment by bobmazanec** [comment]
Thanks for the quick response!

No preference; suggest away; thanks!

**Comment by RyanNovas** [comment]
#463, #438, #16, and #482 could be worth looking into. Please let me know if you have any other questions. We also have a community page you should sign up for (community.quill.org) and a chat room you can access here: http://community.quill.org/chat/

**Comment by bobmazanec** [comment]
Copy all; thanks.
