### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3870]
[This tool may be useful](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en) If you find a good tool share it here.

Not much attention has been paid to the accessibility of the site. Audit the site for Accessibility issues and list them in this issue, grouped by controller/URL. We can then split it up into smaller issues for fixing the issues.

**Comment by kartik-25** [comment]
Home Page
URL - [https://www.quill.org/] 
Tool used- Lighthouse by Google
- Images must have alternate text
- ARIA roles used must conform to valid values
- Links must have discernible text
- Form elements must have labels
- Text elements must have sufficient color contrast against the background
- <html> element does not have a [lang] attribute
