### ISSUE TITLE
Mobile Display Issue Audit

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3871]
While we will be releasing a dedicated mobile app soon, it is still important that the site displays well on mobile devices and tablets.

Using the Chrome/Firefox Responsive Display mode tools, conduct an audit of the site, focusing first on the pages accessible without authenticating, and then on the student & teacher profiles/pages.

Provide before and after screenshots of the changes made.

**Comment by Sid2217** [comment]
i have made little changes on one of the pages but as i dont know the class name which to enter i cant move in so it will helpful for some guidance 
![before changes](https://user-images.githubusercontent.com/35375727/37453854-02509132-285f-11e8-8d4b-94074f6caaaf.PNG)
![after changes](https://user-images.githubusercontent.com/35375727/37453867-0baa80b2-285f-11e8-98de-2f28439d8a91.PNG)
