### ISSUE TITLE
Administrators can view district/school wide concept reports.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3874]
Feature: School Dashboard Level Concept Results Report
  As a School Admin user
  I want to view the Concept Results of all students in the schools I administrate on one page
  Because viewing them while impersonating a teacher is slow and limiting.

Scenario: Viewing the Concept Results of all students.
  Given I'm logged in and I have administrator access to at least one school
  When I go to the "School Dashboard" Tab
  And I click on the "Concept Results" link in the sub-sub-nav
  Then I should be taken to a page that resembles the existing teacher Concept Results report
  And be able to see School, Teacher, Student, Correct, Incorrect, Percentage, and a link to the student's concept results report.

![image](https://user-images.githubusercontent.com/3110565/36678043-bb248d60-1add-11e8-9575-2fd1ac844299.png)

**Comment by Ronaq13** [comment]
@ddmck I would like to take this feature.
