### ISSUE TITLE
Grandfathering Subscription Rates

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3876]
Note: This should just be a function that returns true/false (The UI implications will follow in a separate issue)

Feature: Teacher eligibility for Grandfathering
As a teacher who bought a school subscription before 03/01/18
I should be able to continue to purchase subscriptions at the early rate
Because of the Grandfather clause.

Scenario: Teacher who has previously bought a Paid School Subscription before 03/01/18
Given I am a teacher who has previously purchased a Paid School Subscription before 03/01/18
And my subscription is still valid
Then I should be eligible for grandfathering
And I should be able to see the grandfathered rates.

Scenario: Teacher who has previously bought a Paid Teacher Subscription before 03/01/18
Given I am a teacher who has previously purchased a Paid Teacher Subscription before 03/01/18
Then I should not be eligible for grandfathering
And I should see the current rates.

Scenario: Teacher without any paid subscription history
Given I am a teacher who never purchased premium
Then I should not be eligible for grandfathering
And I should see the current rates.

Scenario: Teacher who has previously had a Free Subscription before 03/01/18
Given I am a teacher who has previously been given a Free Subscription before 03/01/18
Then I should not be eligible for grandfathering
And I should see the current rates.

**Comment by RyanNovas** [comment]
@ddmck i think we should punt on this until there is a difference in the school subscription pricing. Otherwise we are likely to forget about this code and make redundant features and/or need to rewrite it because some aspect of business logic has shifted.
