### ISSUE TITLE
Teacher Dashboard: Add "Add Co-Teachers" to Classes card

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3878]
- [x] Add "Add Co-Teachers" to the top left corner of any class card.

**Comment by hardy1334** [comment]
@amr-thameen  Can you tell more about this ,I have gone through that page,I want to work on it ,if you can give a bit more details it will be great
![gitask](https://user-images.githubusercontent.com/31733278/36855754-5f289cbc-1d9a-11e8-98c5-de0ca2a2d55c.png)

**Comment by hardy1334** [comment]
Are you talking about moving it to the top left of the webpage
