### ISSUE TITLE
Faq page: stylistic changes

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3912]
https://www.quill.org/faq

- [x] "Quill.org is a nonprofit, educational technology organization dedicated to improving student writing." bold and 16px 
![image](https://user-images.githubusercontent.com/25299820/36863826-d0e8df98-1d58-11e8-91e7-c03148680db5.png)

- [x] Head to our support page -> visit our support page
- [x] Clicking anywhere within the title of the question should expand and collapse
- [x] Bump Pedagogy section and Implementation section above Technical Questions
- [x] Add a firewall question to the to the top of Technical Questions: 
"Why am I getting a blank screen and my activities are not loading? Firewall Issues"
https://support.quill.org/technical-questions/why-arent-activities-loading-firewall-issues

**Comment by singhjp006** [comment]
Hey @amr-thameen ,
Hope I have done the changes required in the FAQ Page in #4006 
In case on anything else do let me know.
