### ISSUE TITLE
Incorrect student counts in assigned units

### ISSUE THREAD

**Issue by jaredsilver** [empirical-org/Empirical-Core#3915]
37 out of 20 students assigned? Wow, this teacher must really like this activity!

<img width="967" alt="screen shot 2018-03-01 at 2 31 57 pm" src="https://user-images.githubusercontent.com/1312199/36865394-66d14b90-1d5d-11e8-8bb9-613ea81dec59.png">

unit_id = 209786

**Comment by jaredsilver** [comment]
Update: it appears this occurs when `assigned_student_ids` contains more student IDs than there are students in a class -- probably due to moving students around or removing students from classes after assigning an activity.

**Comment by jaredsilver** [comment]
Another update: actually, it looks like every student included in `assigned_student_ids` but not assigned to the classroom has `active: false`.

**Comment by RyanNovas** [comment]
This occurs when an activity is assigned to students that are no longer part of the classroom - i.e., their StudentsClassrooms join is no longer visible or has been deleted.

We need to decide if it is more important to retain this data for historical needs, or to make the database accurately reflect the interface. If the former, then it will probably be easiest to just count the matches between students currently in the classroom and assigned to the activity. If the latter, then we should write an `after_commit` and `before_destroy` hook on the `StudentsClassrooms` model that will occur when `visible: false` and call a background worker. The worker which will go through the classroom activities of the classroom being hidden/deleted and remove the student from any assigned student arrays they are in.
