### ISSUE TITLE
Premium Trial: Number of days not showing in the tab

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3917]
![image](https://user-images.githubusercontent.com/25299820/36870407-fef6d232-1d6c-11e8-81b5-e8701754463a.png)

**Comment by ddmck** [comment]
Already fixed and will deploy later

—
Donald McKendrick	
Director of Technology @ Quill.org

**Comment by amr-thameen** [comment]
Thank you! 🙏

Amr Thameen
www.amrthameen.com
917-756-3318
@amrthameen <http://twitter.com/amrthameen>
