### ISSUE TITLE
Admin Accounts: Changes

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3919]
- [x] "School dashboard" tab instead of just "School"
- [x] These accounts may not have classrooms so let's just have them land on School Dashboard and they should not land on Create Class page

**Comment by ddmck** [comment]
@amr-thameen I'm not sure we have room for School Dashboard

**Comment by amr-thameen** [comment]
@ddmck 

Oh is it pushing the rest of the tabs outside of the 950? I just checked on my end and it seems like it fits. We also might get rid of Teacher Resources tab next to Student Reports so we would have some space. 


![image](https://user-images.githubusercontent.com/25299820/37104959-fc53d4a6-21fb-11e8-983a-da631cc92115.png)
