### ISSUE TITLE
Quill Teacher Subscription: Stylistic Changes

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3921]
## Teacher Trial:
- [x] We are showing School Invoice, it should be "No payment method on file"
- [x] Missing blue line next to You have a ....
- [x] You have a Trial Premium subscription should be "You have a Teacher Premium subscription"
- [x] Valid until box has 30px internal padding left and right
- [x] Lightbulb tip box has a gray line in the bottom no need to add that
- [x] Premium subscription is saying that I have 0 months in length, it should be 1. 
- [x] 15px top padding above the valid until box

![image](https://user-images.githubusercontent.com/25299820/36873407-688febc6-1d76-11e8-918b-847e39910299.png)

**Comment by hardy1334** [comment]
@amr-thameen  I'm working on this issue

**Comment by hardy1334** [comment]
@amr-thameen  what needs to be in blue line text

**Comment by singhjp006** [comment]
Hi @amr-thameen I want to take on this issue...

**Comment by hardy1334** [comment]
@amr-thameen I'm already working on it

**Comment by singhjp006** [comment]
@hardy1334 oh you are already working on it. Okay no problem I will take on any another issue.
Thanks
