### ISSUE TITLE
Homepage Navbar: Stylistic change

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3926]
- [x] font size of links and Sign up is 16px, Semibold
- [x] the spaces between the links is 25px
- [x] Button is 30px height, and 13px left and right padding.

**Comment by emilia-friedberg** [comment]
<img width="396" alt="screen shot 2018-03-08 at 5 16 16 pm" src="https://user-images.githubusercontent.com/18669014/37179696-7e7d2588-22f4-11e8-88c2-b2439b81f38e.png">
