### ISSUE TITLE
Renew School Subscription Modal

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3929]
- [x] Padding above "Quill School Premium" is 30px
- [ ] "Not the purchaser?" should be aligned left aligned with the copy below it. 
- [ ] Add font awesome icons 
- [ ] padding below "Next Years Rate ..." is 20 px and top padding is 15px
- [ ] Update X to the lighter gray and place it on the corner of the modal

![image](https://user-images.githubusercontent.com/25299820/36908662-de31918e-1e09-11e8-809f-7c535b82728c.png)

**Comment by hardy1334** [comment]
@amr-thameen I will like to work on this issue

**Comment by singhjp006** [comment]
Hey @amr-thameen 
It would be awesome if we implement these changes.
Our top most priority should be to align "Not the Purchaser?" with the text below it, its looking uglier without the alignment.
Secondly, we can add font awesome icons to the modal and can use  or  as cross button on top right side of the modal.
The modal will look nice after applying the required changes.
You can assign this work to me.
Thank you
