### ISSUE TITLE
Which credit card modal

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3930]
- [x] Capitalize "S" in School and center all the text in the modal
- [x] The modal size and structure should look like this: https://zpl.io/V1ery6Q
- [x] Add font awesome credit card icon to "Use A Different Card"
- [x] Logic: Currently I am seeing this modal even though I dont have a card on file, I should only get this modal if I have a card

![image](https://user-images.githubusercontent.com/25299820/36908929-b1fac04e-1e0a-11e8-9d33-26ddc2166e8e.png)

**Comment by hardy1334** [comment]
@amr-thameen i want to work on it,I have gone on that link it is saying that you need to contact project members for permission
