### ISSUE TITLE
As an admin level user signed in as a researcher, if I click on the School tab, tabs in the subnav should be underlined according to the one currently in use

### ISSUE THREAD

**Issue by buckmaxwell** [empirical-org/Empirical-Core#3958]
This is the current state of things.  Take note of the subnav (Admin Dashboard, Activity Scores, School Concept Reports).  The currently active subnav tab should be underlined to show it is active. In this example, the Activity Scores tab should be underlined.

![screen shot 2018-03-06 at 5 00 46 pm](https://user-images.githubusercontent.com/6210452/37061055-30c82404-2160-11e8-8098-12375cd1b49a.png)

**Comment by buckmaxwell** [comment]
take a look at react-router active link

**Comment by ddmck** [comment]
@buckmaxwell  Instead of an underline, it should share the style of the sub-sub-nav on the other pages.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/3110565/37101404-89bfe1da-21f3-11e8-9f07-4991b49f9258.png">

**Comment by buckmaxwell** [comment]
Great.

**Comment by singhjp006** [comment]
Hi @buckmaxwell @ddmck 
If nobody is working on this issue, I would be very happy to work upon this issue and solve it under your guidance.
