### ISSUE TITLE
As an Admin level user, I should be able to view school/district wide standards reports.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3959]
Feature: School Dashboard Level Standards Report
As a School Admin user
I want to view the Standards Reports of all students in the schools I administrate on one page
Because viewing them while impersonating a teacher is slow and limiting.

Scenario: Viewing the Standards Reports of all students.
Given I'm logged in and I have administrator access to at least one school
When I go to the "School Dashboard" Tab
And I click on the "Standards Reports" link in the sub-sub-nav
Then I should be taken to a page that resembles the existing teacher Standards report (/teachers/progress_reports/standards/classrooms when signed in as a premium teacher)  

![image](https://user-images.githubusercontent.com/3110565/37104526-ef472bf6-21fa-11e8-8574-f90be6510fdd.png)

**Comment by buckmaxwell** [comment]
@ddmck ,  "And be able to see School, Teacher, Student, Correct, Incorrect, Percentage, and a link to the student's concept results report." That sounds like the concepts reports table - not like the table there is a picture of here.  I am sorry, I am a bit confused about what this new Standards Report table will look like.

**Comment by ddmck** [comment]
I'm sorry, that's not supposed to be there. Removed now

**Comment by buckmaxwell** [comment]
@ddmck , are the filters for classrooms and students part of this feature? [the one's visible in the image].

**Comment by buckmaxwell** [comment]
Ignore above comment.  This issue will cover the fire hose (no filters).  Other issues will add filters for Schools, Teachers, and Classrooms.  Unlike Activity Scores and Concept Reports the filtering will happen server side. In the future, filtering for Activity Scores and Concept Reports may move to server side as well in which case the work in these issues can be used as a template.
