### ISSUE TITLE
As a researcher or school/district administrator, I want to be able to view all concepts results in a single table

### ISSUE THREAD

**Issue by buckmaxwell** [empirical-org/Empirical-Core#3960]
NOTE: The writing on this issue is still a WORK IN PROGRESS. Dev work has not begun yet.

@ddmck , according to Becca, the Concept Reports table in it's present form is not helpful to anyone.

In order to make it useful, she has suggested that the format mirror that of the concept results page at the teacher level that looks like this.

<img width="1179" alt="screen shot 2018-03-07 at 10 57 34 am" src="https://user-images.githubusercontent.com/6210452/37104778-9094aeca-21fb-11e8-829c-5c9b9e49b0f7.png">

The new table would look something like this

School | Category | Name   |  Number of students | questions completed | average  |
|---|---|---|---|---|
Springfield Elementary | Conjunctions  | Comma Before Coordinating Conj   |  30  | 250  | 76%  |

It should be noted that this table, unlike the one itemizing concept results for an individual student, applies school-wide [TBD: should it be chunked by school, or by classroom?]

In detail, the columns are:

Category, name (of concept), number of students (who actually completed 1 more questions on that concept), questions completed (in that name by all students), average (overall correctness by all students in that name).

---

Donald, I am assigning this issue to myself and beginning work on it after Becca let's me know whether to group by school, or classroom.  Please let me know if this is not a good priority - Becca told me that this would be a higher-priority item than standards reports in her opinion.

Max

**Comment by ddmck** [comment]
@buckmaxwell Hold off for now
