### ISSUE TITLE
As and Admin level user I should be able to view individual student activity scores reports.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3961]
Feature: Viewing Individual Student Activity Scores Report as a School Admin
  As a School Admin user
  I want to view the activity scores of an individual student in the schools I administrate
  Because viewing them while impersonating a teacher is slow and limiting.

Scenario: Viewing the activity scores of a student from the Activity Scores report from a school I administrate.
  Given I'm logged in and I have administrator access to at least one school
  When I go to the "School Dashboard" Tab
  And I click on the "Activity Scores" link in the sub-sub-nav
   When I click on a student row
  Then I should be taken to a page that resembles  (/teachers/progress_reports/student_overview?classroom_id=XXXX&student_id=XXXXX) 
  And be able to the page below.

![image](https://user-images.githubusercontent.com/3110565/37106372-aaa306c8-21ff-11e8-8004-aeeca5b31fec.png)

Scenario: Viewing the activity scores of a student from the Activity Scores report from a school I don't administrate.
  Given I'm logged in and I have administrator access to at least one school
  And I navigate to the URL of an activity scores report of a student/classroom that I don't administrate
  The I should not be able to view the students' report
  And should see a 404 page.

**Comment by tronroy** [comment]
PR https://github.com/empirical-org/Empirical-Core/pull/4010
