### ISSUE TITLE
Teacher Level Standards Reports doesn't load in staged branch

### ISSUE THREAD

**Issue by buckmaxwell** [empirical-org/Empirical-Core#3962]
feature/admin-can-view-district-concept-reports2 is currently in staging.  It appears to fail with a 500 (visible in the console) when 'Standards' is clicked under the student tab while signed in as a teacher.  The visible part of the page appears to endlessly load.

![screen shot 2018-03-07 at 1 15 38 pm](https://user-images.githubusercontent.com/6210452/37109996-ad990c38-2209-11e8-8ebf-8603cdc34e98.png)

**Comment by ddmck** [comment]
Non-replicable.
