### ISSUE TITLE
[Salesmachine] Required data for Schools (Accounts in Salesmachine)

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3967]
We currently have:

```
params: {
  name: self.name,
  city: self.mail_city,
  state: self.mail_state,
  zipcode: self.mail_zipcode,
  district: self.leanm,
  phone: self.phone,
  charter: self.charter,
  frl: self.free_lunches,
  ppin: self.ppin,
  nces_id: self.nces_id,
  school_type: ulocal_to_school_type,
  employee_count: self.schools_users.count,
  buying_stage: "green field"
}
```

In the schools model sync_salesmachine function: 

We need to add:
- [x] The school subscription name if it has one. (self.subscription?.account_type)
- [x] The number of paid subscription that the teachers in the school have. (Some reduce across schools.teachers where we count 1 for each active & paid teacher subscription)
- [x] The count of all of the active students in the school. (self.teachers.reduce {|teacher| teacher.(students with atleast one activity completed count)}) (we do this count in the sales machine function in the teacher concern too, so it might be worth making a new method that encapsulates it.)
- [x] The count of all the activity session completed by students in the school (self.teachers.reduce {|teacher| ActivitySession.unscoped.where(classroom_activity_id: ClassroomActivity.unscoped.where(unit_id: Unit.unscoped.where(user_id: teacher.id)).pluck(:id), state: 'finished').count}) (Again might be worth refactoring this in the teacher concern.)
- [x] a link to the cms page for the school ( https://www.quill.org/cms/schools/#{self.id})

**Comment by tronroy** [comment]
https://github.com/empirical-org/Empirical-Core/pull/3965
