### ISSUE TITLE
[Salesmachine] Add a rake task that imports active school and their teachers into Salesmachine

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3969]
We need to create a rake task that will:

- [x] Find all of the school that have a teacher associated with them (might be best starting from the schools_users table)
- [x] For each of the schools, call the sync_salesmachine function (Salesmachine handles batching itself, no need to worry about rate limits)

Then: 

- [x] Set up the scheduled job on Heroku that will run the rake task at midnight every night.

**Comment by tronroy** [comment]
PR https://github.com/empirical-org/Empirical-Core/pull/3965
Add `rake sync_salesmachine` to heroku scheduler to run nightly sync jobs
