### ISSUE TITLE
[Salesmachine] Setting Pipeline stages from the LMS CMS 

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3970]
We need to be able to set/store the sales pipeline stages in the LMS, so that we can use it in Salesmachine and anywhere else we want.

- [x] Create a new table called school_account_attributes, with school_id:integer(and index it) and attributes:json with the following defaults: 
```
{
  "Quill Basic": null,
  "Schools With Just Teacher": null,
  "In Conversation": null,
  "Quote Accepted": null,
  "Purchase Order Received - Temporary Stage ": null,
  "Invoice Sent Stage": null,
  "School Paid - Needs PD Session": null,
  "(or separate) Needs PD Session": null,
  "Successful Premium School": null
}
```

As a validation, the keys should be either null or an integer. The integer will represent the epoch time that the stage was entered. (I could consider 0 as the null value, but this might make things difficult.)

Feature: Setting the pipeline stage of a School (Account in SM)
As a member of the Quill Sales team
I need to be able to flag the state of a school in the sales pipeline
Because some of our pipeline stages happen in real-life rather than just in code

Scenario: Setting the pipeline stage of a School (Account in SM) from the Staff CMS
Given I am a signed in user with role staff
And I navigate to the CMS page of School (cms/schools/{school_id}?)
I should be able to select from a dropdown the stage I want to move the school to 
Then hit submit
And see confirmation that my change saved, and see it in Salesmachine too. 

Technical: 
- Upon hitting submit, the value corresponding to the selected stage key should be set to the current epoch time.
- The options in the dropdown should correspond to the keys in the attributes json.

**Comment by tronroy** [comment]
PR #3965
