### ISSUE TITLE
Featured Activity Packs: Quill staff image is pixelated

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#4019]
https://www.quill.org/teachers/classrooms/assign_activities/featured-activity-packs

- [x] Replace the current image with this new image on all featured packs: 

assets/images/authors/quill-staff.png

**Comment by RyanNovas** [comment]
@amr-thameen this is done, but for future reference, it is not a code issue. After logging in with a staff account, the images can be changed here: https://www.quill.org/cms/authors
