### ISSUE TITLE
Update School Manager and User Manager 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#4028]
# Sorting
- [x] Make each of the columns sortable in school manager 
- [x] Make each of the columns sortable in user manager 

# Default number of rows
- [x] Show 30 rows by default 

# Default sort by most active 
- [x] Order people by date last active. 
- [x] For schools, is there any easy way to show last action for the school? If there isn't a good way to sort by most recently active, default sort by number of teachers. 

# Technical specifics
- [x] Rewrite tables as React Table
- [x] Use serverside querying for sorting to avoid problem of only sorting records on front end

# Final steps
- [x] Handle pagination properly (page cut off?)
- [x] Add loading state

**Comment by emilia-friedberg** [comment]
we should use react table with serverside querying
