### ISSUE TITLE
Hamburger not required on sample activities

### ISSUE THREAD

**Issue by singhjp006** [empirical-org/Empirical-Core#4043]
## Expected Behaviour
We don't have anything to show in the Menu so instead of Hamburger Menu we should show Save & Exit like this
![screenshot from 2018-03-23 14-04-04](https://user-images.githubusercontent.com/17426705/37819311-10b44904-2ea3-11e8-9a1d-d2741fe6994d.png)

The correct versions of same kind of page can be seen here
https://grammar.quill.org/play/pf?anonymous=true&uid=-K0rnIIF_iejGqS3XPJ8
https://grammar.quill.org/play/sw?anonymous=true&uid=KfXZjcff6YVWh1fbRzGr4w

## Actual Behaviour
Screenshot Before Clicking the Hamburger Menu
![screenshot from 2018-03-23 13-53-29](https://user-images.githubusercontent.com/17426705/37819198-9f5b59a0-2ea2-11e8-91e4-c2d35371e3e9.png)

Screenshot After Clicking the Hamburger Menu
![screenshot from 2018-03-23 13-54-15](https://user-images.githubusercontent.com/17426705/37819200-9fb83ca6-2ea2-11e8-8561-a37afb3da1ed.png)

Can be seen in the links:
https://connect.quill.org/#/play/lesson/-KXHxOiPXAMZmQOGGer9?student=null
https://connect.quill.org/#/play/diagnostic/fNAwNLJDkc2T8O5lBeJQwg?student=null

## Steps to Reproduce
Before vs After comparison will be best here to show what exactly is required
Before 
![screenshot from 2018-03-23 14-06-45](https://user-images.githubusercontent.com/17426705/37819436-753ca5e2-2ea3-11e8-9612-dda669de0314.png)
After
![screenshot from 2018-03-23 14-04-04](https://user-images.githubusercontent.com/17426705/37819442-79c65676-2ea3-11e8-8d1a-0c381ee74df8.png)

**Comment by SabyasachiNITD** [comment]
I want to work on this issue. Can anyone assign me this?
