### ISSUE TITLE
Activity Summary: Saving dropdown preference

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#4050]
- [x] When a teacher selects an option from the drop-down, that option should be saved so when the teacher refreshes the page or leaves and come back, they should come back to the same option selected.

![image](https://user-images.githubusercontent.com/25299820/37910153-d7c55da6-30da-11e8-8886-8f18ed96a4ca.png)

**Comment by emilia-friedberg** [comment]
@amr-thameen making a PR that implements this for selected classrooms, not sure whether I should be doing this for selected unit too. seems like it could be annoying to have to manually change that every time, and less likely that they want to return to the same unit over and over? let me know if you want to add it for that too.

**Comment by amr-thameen** [comment]
@emilia-friedberg I think the default right now is All Activity Packs right? I think we should keep it that way and if a teacher wants to filter down to a specific one.

Side question: did we nix the All Classroom option from the classroom dropdown?

**Comment by emilia-friedberg** [comment]
@amr-thameen Yes, we default to All Activity Packs. I don't remember ever having All Classrooms as an option in the classroom dropdown for the Visual Overview.
