### ISSUE TITLE
Student joins a class -> profile

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#4063]
- [x] When a student joins a class, let's send them directly back to their profile without having to show them the page with (Class Added! and Back to Profile button)
- [x] Add a notification on the profile page zpl.io/295kYgl
- [x] The notification should disappear automatically after 0.7 seconds, slide to the top or fade out.

**Comment by ddmck** [comment]
My notes:
We should use the existing notification functionality, which places the notification at the top of the page. We will need to add the disappearing functionality.
0.7 seconds seems fast.
I've added the fact that you should be sent to the profile with the new class loaded.
