### ISSUE TITLE
Add Edit Function to Sections Manager

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#409]
If you log in as an admin, then select sections editor, there only options are to delete sections or make new ones, as shown in the image below. If possible, we should make an option to edit them (both their name and position). 

![screenshot 2014-10-15 at 12 20 18 pm](https://cloud.githubusercontent.com/assets/6655439/4649046/2f2e9fb4-5487-11e4-9976-394f3741f6eb.png)

**Comment by bobmazanec** [comment]
So 'Position' is so they're in some Admin-controlled order &mdash; _e.g._, maybe ascending grade level  in the list above (depending on what 'Quill Tutorial Lesson' is &mdash; as opposed to alphabetic?

Maybe replace 'Position' with 'Grade Level' & sort by (Grade Level, Name) in case there are several for a given Grade Level?

**Comment by RyanNovas** [comment]
Right now sections editor is just a 500 error, so let's hold off on
worrying about this until it is fixed.

On Sun, Mar 15, 2015 at 12:39 AM, Bob Mazanec <notifications@github.com>
wrote:

> So 'Position' is so they're in some Admin-controlled order — *e.g.*,
> maybe ascending grade level in the list above (depending on what 'Quill
> Tutorial Lesson' is — as opposed to alphabetic?
>
> Maybe replace 'Position' with 'Grade Level' & sort by (Grade Level, Name)
> in case there are several for a given Grade Level?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/409#issuecomment-80850978>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>
