### ISSUE TITLE
Bug Report: Diagnostic Recommendations won't assign

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4090]
https://docs.google.com/document/d/14qH_B-z5-StJgyXZcLSMvKQqCJQgNMMHlbc0yDfU6XQ/edit?usp=sharing

**Comment by ddmck** [comment]
updated with additional info from my assessment in the google doc.

**Comment by RyanNovas** [comment]
@maddymaher all activities have been assigned to the teacher. On the 'Assign Rec' page, the green checkmarks are not populating, despite successful assignment. I am now looking into this.
