### ISSUE TITLE
Blank Accounts In SalesMachine 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#4139]
It looks like we may be creating blank accounts for students in SalesMachine because of Segment. The one property for these accounts is the "Created at" date. 

Tom’s suggestions: Turn off created at for students? 

Other details: 
- This seems likely because there is no email associated with the account and during the nightly job the contacts are not being updated. 
- One easy way to test. We have 97k contacts in SM. How many teacher accounts do we have? 
We ran into this problem with intercom. Intercom enabled us to explicitly disabled students. I am not sure how we did this. 
- We use the “track” function segment to track “created at” (the only attribute these accounts have). Is there a way to disable segment tracking of student account creation?
- We still want to count the number of times students complete activities. We just don’t want to create new IDs for students. 

## Expected Behaviour
Only teacher accounts are created in sales machine 

## Actual Behaviour
- blank accounts are created 

## Steps to Reproduce
- go into sales machine to see the accounts. 

## Potential sources for the issue (filename, new features ect.)
- segment created at function?

**Comment by tronroy** [comment]
PR https://github.com/empirical-org/Empirical-Core/pull/4149
