### ISSUE TITLE
Contacts in SalesMachine missing accounts 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#4141]
Contacts in SalesMachine are not importing schools. 
Details are here: https://docs.google.com/document/d/1tGmPaylQhaz7mUtSoZDcESYDnvuCopOisu7IAoDEwsk/edit

**Comment by tronroy** [comment]
This user does not have a school in our database. It is a data integrity issue in the Quill LMS app not a Salesmachine data import issue. To get a school for this user it needs to be added to this user in the LMS which can be done by staff members.
