### ISSUE TITLE
Flagging users as auditors

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#4146]
Feature Spec
- [x] Quill staff should be able to designate user accounts as auditors, 
Because we don’t want all users to get teacher onboarding emails, 
And we can differentiate them in the code and in marketing.

Staff  updating an existing user as an auditor
- [x] Given I am a Quill Staff
When I am on the edit page of a user account
Then I should be able to designate the user as an auditor
And when I hit update
Then I should see that my changes have been saved.

Auditor logging in
- [x] Given I have a user account that is designated as an auditor
And I belong to a school premium account
When I login
Then I should be taken to the “My Subscriptions” page
And I should be able to view and update the subscriptions details. 

Searching for Auditors
- [x] Given I am a Quill Staff
When I visit the User search page
Then I should be able to query based on user flag
When I hit search
Then I should see only users with that kind of flag.

**Comment by RyanNovas** [comment]
Will need to run `User.where.not(flag: nil).each {|u| u.update(flags: [u.flag])}` previous to migraiton
