### ISSUE TITLE
visual overview only loading half the students on initial render

### ISSUE THREAD

**Issue by emilia-friedberg** [empirical-org/Empirical-Core#4180]
## Expected Behaviour

All of the students should load.

## Actual Behaviour

Only half the students load. However, after being selected on the dropdown menu, all of the students load.

**Comment by RyanNovas** [comment]
@emilia-friedberg I'm closing this as it seems to just pertain to the single user, is not replicable in my dev environment, and doesn't seem too serious. However, let's keep an eye out for other reports.
