### ISSUE TITLE
Bug Reports: Teacher unable to access classes page and student reports page

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4255]
https://docs.google.com/document/d/1fm8RJgUsDTk-8UQ3LuElspg5cV9oFzxTo8_s5s3uLa4/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
@maddymaher I'm closing this issue since we can't replicate it. I think it's most likely that the internet was slow and all of those teachers reporting it was coincidental. If the problem recurs we can investigate further but there isn't much to do when there doesn't seem to be a problem.
