### ISSUE TITLE
Error on posting to Google Classroom when lesson is launched

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#4371]
```
# if @classroom_activity.is_valid_for_google_announcement_with_specific_user?(current_user)
#   return post_to_google_classroom
# end
```
line 30-32  services/QuillLMS/app/controllers/teachers/classroom_activities_controller.rb:

This was being called when a lesson was launched, but the API for the GoogleClassroom::Announcements initializer expects different variable,s possible in the change from posting lessons to posting units.
/Users/donald/Programming/MonoQuill/services/QuillLMS/app/services/google_integration/announcements.rb

NewRelic Error here https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/5c1b5070-7495-11e8-a5bb-0242ac11000a_0_22507

Commented out for now, so not immediate

**Comment by tronroy** [comment]
finished, closing
