### ISSUE TITLE
Make spaces an invalid character in "Invite Students"

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#438]
Get to invite students by logging in as a teacher, then selecting "Invite Students" Tab.

Here you will see something similar to this:

![quill org interactive writing and grammar](https://cloud.githubusercontent.com/assets/6655439/4921720/4a0ed994-650c-11e4-873b-48a2b010d464.png)

M .honey@merry-honey has an unnecessary space in it. Teachers seem to be occasionally doing this accidentally, and it is causing confusion and problems with logging in. We should make spaces an invalid character in the first and last name fields to solve this issue. This should be resolved in conjunction with issue #344 as both simply involve making spaces invalid characters.

**Comment by bobmazanec** [comment]
Re: "make space an invalid character in the first and last name fields"...

If "Anne Marie van der Hook" is forced to "AnneMarie vanderHook," will Anne Marie will see it on any of her pages?

**Comment by RyanNovas** [comment]
Hi Bob,

Anne Marrie would be able to see that. I think a better solution would be
to make spaces an invalid character within the username.

On Sun, Mar 15, 2015 at 12:14 AM, Bob Mazanec <notifications@github.com>
wrote:

> Re: "make space an invalid character in the first and last name fields"...
>
> If "Anne Marie van der Hook" is forced to "AnneMarie vanderHook," will
> Anne Marie will see it on any of her pages?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/438#issuecomment-80836432>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>

**Comment by RyanNovas** [comment]
@bobmazanec made a good point, so closing this and opened #639 instead.
