### ISSUE TITLE
Bug Report: "Sign up with Google" looping back to Log in screen

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4397]
https://docs.google.com/document/d/1QTGlOabl3QXxvyzbyF8_ZjVtlPpXzRDyQBWTcPdHiEE/edit?usp=sharing

**Comment by tronroy** [comment]
on it! thanks

**Comment by tronroy** [comment]
https://github.com/empirical-org/Empirical-Core/pull/4402
