### ISSUE TITLE
Remove Previewable Lessons Section from Student Login Process

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#442]
Currently, when a new student create an account, the first page they are brought to is one for them to input their class code and select from a list of previewable lessons. They will almost never preview a lesson, so this is noisy, and the viewable lessons are lacking feature flags with a broken drop down menu #229.

Instead, let's just get rid of it, and add a line of copy in with a link to quill.org/lessons, as wire framed below:
![student sign in wireframe](https://cloud.githubusercontent.com/assets/6655439/5001105/b94fc7f6-69c0-11e4-97ca-f89a2f1483be.png)

**Comment by bobmazanec** [comment]
Superseded by #452?
