### ISSUE TITLE
EC Install Issues 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#443]
There are a number of quirks in the installation process that make it difficult to get set up. The goal is to have various people install the code and document each of the issues they run into. We will then look at how we can resolve each of these issues. 

**How to install: http://empirical-core.readme.io/v1.0/docs/install-empirical-core-on-your-local-machine**

*Ideas:*

### AWS issue
During install devs are getting an error for not having an AWS key. This key is for an aws gem developers don't need. It loads images on our homepage (the news items at the bottom of quill.org). 

You can see this uploader at www.quill.org/cms (requires an admin account). 

### Front Page Logic 
Matt: What I did have to do was disable the front-page logic that gets the demo activity going, because it looks like the seed files don't work anymore, but I think we expected this. 

### Set up Vagrant and Docker
Matt: I can't help coming to the conclusion (again) that it would just be so much better to have Vagrant or Docker available long-term for devs (with the option that people can install manually if they want, with our instructions on how to do that), especially if it's going to be using Rails AND Postgresql AND an initial seed AND Redis AND has to set up apps for testing.

### Separate empirical.org page from core

Matt: Also, has there been talk of separating the Empirical-org site from Empirical-core? It'd be less distracting for devs if they just got the app, instead of the empirical org home site as well, no?

**Comment by jluria** [comment]
I didn't have a problem working through the install, and it's up and running on my machine. I am getting one deprecation warning for `asset_url` saying that it has been deprecated to no longer take two args.

Also, the first time I load Quill, I get the following warning about 25 times in my server logs -

`Warning. Error encountered while saving cache c5b7bde44b172618aa895e64f3157d645714fe97/_navbar.scssc: can't dump anonymous class #<Class:0x007fbef3fcde88>`

**Comment by spacez320** [comment]
Thanks Josh. What system are you running, and what install method did you
use?

**Comment by jluria** [comment]
I'm running OSX 10.9.3 and simply followed the install method linked at the top by Peter. Already had everything installed, as well.

**Comment by jluria** [comment]
Also, I have this in my `bash_profile`:
    export AWS_ACCESS_KEY_ID=""
    export AWS_SECRET_ACCESS_KEY=""
    
    export FOG_DIRECTORY=""
