### ISSUE TITLE
Things to fix now that unit activity logic is in place

### ISSUE THREAD

**Issue by emilia-friedberg** [empirical-org/Empirical-Core#4487]
- [ ] teachers can now assign activities through any means (explore all activities, featured activity packs, entry diagnostics) without selecting a classroom
- [ ] we may actually be blocking teachers from getting to these pages at all without a classroom, which we should no longer be doing
- [ ] the first time a teacher assigns diagnostic recommendations, we can create every recommendation unit, with its unit activities, and populate the classroom units as necessary rather than whatever we're doing now to preserve the correct order
- [ ] we could investigate the possibility of creating a join table for assigned students, rather than keeping their ids in an array on the classroom unit
- [ ] we can allow activity reordering within a unit (order numbers on unit activities)

**Comment by ddmck** [comment]
Moved to Notion
