### ISSUE TITLE
Bug Report - Jumbled PDF text for Student Reports

### ISSUE THREAD

**Issue by rabhari** [empirical-org/Empirical-Core#4499]
https://docs.google.com/document/d/19NgnT1_l9BKZpaz99BiYPUSlEh7r_7lPbXpyUoWp8NE/edit

**Comment by emilia-friedberg** [comment]
@rabhari can you find out what browser she's using? I can't reproduce this. maybe suggest that she use Chrome?

**Comment by rabhari** [comment]
Alright, I'll let her know!

Thanks!
-Rod
