### ISSUE TITLE
trailing "\t" being added to usernames

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#450]
Studenst were unable to login, they didnt know that the system had appended a "\t" to their usernames (so were not entering the 'correct' username). May have to do with certain browsers recording tab keypress instead of just moving user to next input...

**Comment by RyanNovas** [comment]
@marcellosachs I've had no new reports of this -- but did you fix it? If not, maybe you want to do an SQL query and see if any usernames have "\t" in the last couple of months.

**Comment by marcellosachs** [comment]
@RyanNovas I checked - there is 1 classroom with students that have this problem (created in last december). The teacher deliberately used tabs in the students names, which caused the issue. This will be prevented in the future as of  c887998c23d9553430a60d292b6f8c8522e834bb, which does not allow tabs in names.
