### ISSUE TITLE
Bug report: "Watch Video" button broken in Teacher Center

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4514]
https://docs.google.com/document/d/1sq6s-tmlnb8o78ct5hoqC4GQs3ZypnvmMgh3dLY5Kj4/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
@maddymaher - I'm fixing the HTML for the existing videos. The problem here I think is that the external link has to be added *before* the button gets added, due to some weird structural decisions made when this page was being created. I will add instructions to that effect to the page.
