### ISSUE TITLE
Eliminate Option to Preview Lessons During Initial Sign-in

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#452]
Right now, after a student registers, the first screen they get is this: 
![screenshot 2014-12-03 at 5 57 29 pm](https://cloud.githubusercontent.com/assets/6655439/5290570/ff90b53e-7b15-11e4-82dd-af062922b4bf.png)

Student's aren't going to want to preview lessons, they just want to get into their classroom. Let's streamline this process and just have a single call to action.

**Comment by bobmazanec** [comment]
Dup of #442?
Supersedes it?

**Comment by RyanNovas** [comment]
Yes, those were redundant. Good catch.

On Sat, Mar 14, 2015 at 11:38 PM, Bob Mazanec <notifications@github.com>
wrote:

> Dup of #442 <https://github.com/empirical-org/Empirical-Core/issues/442>?
> Supersedes it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/452#issuecomment-80823087>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>

**Comment by petergault** [comment]
close this?

On Mon, Mar 16, 2015 at 10:59 AM, Ryan Novas <notifications@github.com>
wrote:

> Yes, those were redundant. Good catch.
>
> On Sat, Mar 14, 2015 at 11:38 PM, Bob Mazanec <notifications@github.com>
> wrote:
>
> > Dup of #442 <https://github.com/empirical-org/Empirical-Core/issues/442
> >?
> > Supersedes it?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/empirical-org/Empirical-Core/issues/452#issuecomment-80823087
> >
> > .
> >
>
>
>
> --
> Ryan Novas
> Director of Operations
> Quill — Interactive Writing and Grammar
>
> @Quill_Org <https://twitter.com/quill_org>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/452#issuecomment-81716879>
> .
>



-- 
Peter Gault
Quill Co-Founder and Product Director
http://quill.org

Learn more about Quill: http://youtu.be/BA6jaeberMg

**Comment by RyanNovas** [comment]
I closed one of them. The open one should stay open.

On Mon, Mar 16, 2015 at 12:32 PM, Peter Gault <notifications@github.com>
wrote:

> close this?
>
> On Mon, Mar 16, 2015 at 10:59 AM, Ryan Novas <notifications@github.com>
> wrote:
>
> > Yes, those were redundant. Good catch.
> >
> > On Sat, Mar 14, 2015 at 11:38 PM, Bob Mazanec <notifications@github.com>
> > wrote:
> >
> > > Dup of #442 <
> https://github.com/empirical-org/Empirical-Core/issues/442
> > >?
> > > Supersedes it?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/empirical-org/Empirical-Core/issues/452#issuecomment-80823087
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Ryan Novas
> > Director of Operations
> > Quill — Interactive Writing and Grammar
> >
> > @Quill_Org <https://twitter.com/quill_org>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/empirical-org/Empirical-Core/issues/452#issuecomment-81716879
> >
> > .
> >
>
>
>
> --
> Peter Gault
> Quill Co-Founder and Product Director
> http://quill.org
>
> Learn more about Quill: http://youtu.be/BA6jaeberMg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/452#issuecomment-81779092>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>

**Comment by aliciasedlock** [comment]
Submitted a pull request for this issue.
