### ISSUE TITLE
Bug Report: Trouble Launching Lessons 

### ISSUE THREAD

**Issue by katherineziegler** [empirical-org/Empirical-Core#4529]
## Potential sources for the issue (filename, new features ect.)
General Trouble Launching (Spinning Green Wheel) 
https://docs.google.com/document/d/1eB9k8Fbuboj-XNhiyiaxSzt-n_-tfssinzq2RB_hyU8/edit

Stuck on Tutorial Slides: 
https://docs.google.com/document/d/1M4UGXdOY6lPmiUGjkzdEiSGx_j7sKO86YkSlCaoG5r8/edit?usp=drive_web&ouid=116338761977042753290

**Comment by maddymaher** [comment]
Bug Report Updated for "General Trouble Launching" 8/29 by Maddy

**Comment by ddmck** [comment]
Tutorial slides are fixed, general trouble remains in other issue
