### ISSUE TITLE
Bug Report: Unable to change diagnostic landing page

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4534]
## Expected Behaviour
I can change the text on the landing page of a new diagnostic

## Actual Behaviour
The standard landing page from the original sentence structure diagnostic remains even if I add text to the landing page content field in "Add New Lesson"

## Steps to Reproduce
Create a new diagnostic in staging and try to change the landing page.

## Potential sources for the issue (filename, new features ect.)
https://docs.google.com/document/d/1DPKIN2gjToyTyGsEbYZXJya4JXXn-z7KUoaLWw69vMQ/edit

**Comment by ddmck** [comment]
Probably still hard-coded.
