### ISSUE TITLE
Concept Tags Design Document 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#455]
This doc details how the concept tags will work:
https://docs.google.com/document/d/1bhPjWoNcdH58Z0SFlZdwYJ96FT77bbgVJ-CoeZ5ZH8Y/edit?usp=sharing

- Each app developer can embed multiple tags into their app. These tags track various aspects of the student experience.

- App developers are required to use the same terminology for the same concepts. For example, the tag "Writing_Grammar" is used for when students make grammar errors in their free writing. 

- Each concept tag will have unique information about it. For example, a grammar tag will have the grammar rule that it refers to. A tag to track the typing speeds of the students doesn't care about the grammar concept. Perhaps each tag can be handled through its own data (tread as nosql data?) 

- Concepts will have a concept tag taxonomy editor where you can create a hierarchy of concepts. This will come later. For now there will be a a concept_category (parent) and concept) and a concept_name (child)

- How is this data written to the database? James was working on a feature where in real time the application would, on the fly, write new data into a user profile. It would then print a CSV once every week. Would just be additional data piggy backed onto the percentage?

**Comment by RyanNovas** [comment]
@petergault can this be closed?

**Comment by petergault** [comment]
-- As I understand it, you'll be collecting two types of success information under this new regime: both the success/failure, and the actual sentence entered by the student. I think this is a great idea, since even if we don't currently have a plan for approaching that from a textual point of view, keeping it now keeps that option open for us in the future 

-- A question: In the example given in the google document, is there any hierarchy of rules? I.e. are At (Place) and In (Place) completely separate rules, or is there some way of tracking the fact that both At (Place) and In (Place) involve "Place" 

-- Clarifying the "Question 3" example: will the app store the information that a student missed a period? (i.e. the general error vs concept error)? Or will that information just be inferred from the fact that the input didn't match the desired input, despite the binary success being set to 1? I see that that information is showing up in "Student Results" but wasn't sure if it was being stored in the same place as student input/student input result, etc. Will there just be an "extra tags" section at the end of each record where typing accuracy and misc. grammar tag mistakes show up

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi
