### ISSUE TITLE
Bug Report: Favicon missing from Quill Proofreader

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#4557]
#### Expected Behaviour
Favicon from quill.org should display:
![screen shot 2018-08-28 at 5 22 54 pm](https://user-images.githubusercontent.com/8131465/44752167-3d288380-aae8-11e8-83fa-9483fc7c29e5.png)

#### Actual Behaviour
Favicon is not displaying:
![screen shot 2018-08-28 at 5 22 46 pm](https://user-images.githubusercontent.com/8131465/44752141-2eda6780-aae8-11e8-9de8-1fc9b72b0626.png)

#### Steps to Reproduce
1. Go to https://www.quill.org/tools/proofreader
2. Click "Try Proofreader Now" button
3. See the missing favicon

**Comment by ddmck** [comment]
@emilia-friedberg Can we make sure the new app has a favicon? If you want to add this to your notion doc you can close this.
