### ISSUE TITLE
Bug Report: Janie Martinez "My Activities" and "Student Reports" tabs won't load

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4563]
A teachers "My Activities" tab, "Diagnostic Report," and "Activity Analysis" won't load. 

#### Link to any private details (teacher/student names and emails)

https://docs.google.com/document/d/1c8T3Of48CUbV2s8qNcBG_6i89aVukfzaLv38Ec-T4p8/edit

**Comment by ddmck** [comment]
Timing out on units request.
