### ISSUE TITLE
Bug Report: Student able to access her teacher's class roster 

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4567]
When a student switches to a teacher account, she has half of her teacher’s 2018-2019 AP Literature and Composition roster in her “Classes” tab.

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1PC9VD37zc2FQftecYA8bpcG8J7zTQ53Rf5kgkIjy4LI/edit?usp=sharing

**Comment by ddmck** [comment]
Can we confirm that she doesn't have some sort of access on google classroom to the class?

**Comment by emilia-friedberg** [comment]
Closing because we made it impossible for students to switch to a teacher account.
