### ISSUE TITLE
Classroom dropdown not expanding to width of classroom name

### ISSUE THREAD

**Issue by emilia-friedberg** [empirical-org/Empirical-Core#4569]
On the Edit Students page under "Manage Classes":

![screen shot 2018-08-30 at 2 50 38 pm](https://user-images.githubusercontent.com/18669014/44872658-24dd7380-ac64-11e8-97a0-0d052734d4d7.png)

**Comment by hmesander** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!
