### ISSUE TITLE
Bug Report: Title Cards and Landing Page Not Appearing in Diagnostics

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4571]
#### Expected Behaviour
I create title cards and add them to a diagnostic. The title cards display when I play the diagnostic. I can edit the landing page when I click "Edit Lesson" 

#### Actual Behaviour
The title cards are showing as part of the diagnostic from the admin panel, but when I click the "Play Diagnostic" button, none of them are there
I update the landing page from the "Edit Lesson" button, but when I play the diagnostic, it's not there

#### Steps to Reproduce
Go to this link: https://staging-diagnostic.quill.org/?#/admin/lessons/-LKX2sTTnPVhTOrWyUx9
Try to update the landing page, look at the title cards; then play the diagnostic

#### Potential sources for the issue (filename, new features ect.)
NA
#### Link to any private details (teacher/student names and emails)
NA

**Comment by ddmck** [comment]
Also appears to have been resolved, chatted with Emilia.
