### ISSUE TITLE
Bug Report: Diagnostic title card text disappears when I click "Edit Title Card"

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4572]
#### Expected Behaviour
When I click "Edit Title Card" in the diagnostic admin panel, the title card text is there, and I can edit it

#### Actual Behaviour
When I click the "Edit Title Card" in the diagnostic admin panel, any text that was there originally is gone, and the title card is blank

#### Steps to Reproduce
Go to: https://staging-diagnostic.quill.org/?#/admin/title-cards/new
Create a new title card
Click "Edit Title Card"

#### Potential sources for the issue (filename, new features ect.)
NA

#### Link to any private details (teacher/student names and emails)
NA

**Comment by ddmck** [comment]
This appears to be fixed, chatted with Emilia, and can no longer be replicated.
