### ISSUE TITLE
Bug Report: "Launch Projector" window not loading on Lessons

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4574]
Lessons will load teacher-facing page, but not student-facing “launch projector” window.

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1nvvb9GDYm9flBBBI6K-nQMy1-I0ZTdqxzmZIZOw3WCc/edit?usp=sharing

**Comment by ddmck** [comment]
@maddymaher  I'm just getting a green spinner when the projector modal opens, is that what she was reporting?

**Comment by maddymaher** [comment]
@ddmck Yes

**Comment by anathomical** [comment]
We're going to bulk-close outstanding Lessons bugs until the release of Donald's updates to Lessons go live.  If bugs recur after that, we'll re-open them as necessary.
