### ISSUE TITLE
Bug Report: Student has extra tab on dashboard

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4578]
A student shows up as in their own class, but they do not have a second teacher account

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/10Ewlcob01nLsPvD4izK7UnEyPUoKTGB_YH1Z1XGxbLI/edit?usp=sharing

**Comment by ddmck** [comment]
Removed via command line.
