### ISSUE TITLE
Bug Report: https security error for community.quill.org

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#4583]
#### Expected Behaviour
When I visit a page on community.quill.org I should be able to view the page without clicking "Proceed to community.quill.org (unsafe)"

#### Actual Behaviour
When I visit a page on community.quill.org I recieve an error message. Perhaps we didn't pay for the https certification? 

#### Steps to Reproduce
- Visit any page on https://community.quill.org/ I went to https://community.quill.org/donate

#### Potential sources for the issue (filename, new features ect.)
![screen shot 2018-09-10 at 11 23 19 am](https://user-images.githubusercontent.com/8131465/45307337-c8444900-b4ec-11e8-9c89-280034967c59.png)

**Comment by ddmck** [comment]
fixed!

**Comment by tomcalabrese** [comment]
yay!
