### ISSUE TITLE
Bug report: Diagnostic data is disappearing

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4584]
The diagnostic data will show up for teachers at first, but will disappear after they log out and log back in. We can restore it in “teacher fixes,” but it happens frequently enough that it may be worth looking into.

#### Link to any private details (teacher/student names and emails)

https://docs.google.com/document/d/1XlH9HD5pHgA-cQwyIHBYnKr_I584ZxgCUnVGz9sMcUU/edit?usp=sharing
https://docs.google.com/document/d/1C0LQauxbC6aBZYuonPiYDLGDqk4N12KPzoCHbPBdnos/edit?usp=sharing

**Comment by ddmck** [comment]
We don't have any magical archive the diagnostic functionality. Are these teachers editing who it is assigned to/assigning it to more classes and not realizing that they are unassigning the others?
