### ISSUE TITLE
Bug Report: Activity Summary not displaying Demo account

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#4592]
#### Expected Behaviour
When a user visits quill.org/demo they should be able to see the activity summary report for the class "Quill Classroom"

#### Actual Behaviour
When a user visits quill.org/demo they are displayed with a missing table for the class "Quill Classroom"

If you select "Quill Classroom" from the drop-down it appears.

#### Steps to Reproduce
- Go to quill.org/demo

![jtszmchpnn](https://user-images.githubusercontent.com/8131465/45498766-d098c000-b748-11e8-9545-c250385ca9d3.gif)

**Comment by ddmck** [comment]
Not a bug, this is just a problem with a teacher using the demo and creating an empty class. All demos are a shared session.

**Comment by tomcalabrese** [comment]
But isn't the problem that "Quill Classroom" is not visible when you first visit quill.org/demo? This happens every day when I visit it. @ddmck
