### ISSUE TITLE
Bug Report: Students Cannot Log in with Google

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4595]
Only half of a teacher's students could get logged in with Google. Teacher is synced with Google Classroom

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/18i2e0HSnOA1adK_MhIE3jsrnZUVA2DklWqtNBvss8bc/edit?usp=sharing

**Comment by SaraQuill** [comment]
Closing this to merge w/ 4596.
