### ISSUE TITLE
Bug Report: Students Not Synching from Google Classroom [*3 reports*]

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4596]
At least 2 teachers have reported, here is 1:

"My students from my 4th-grade classroom won't all load into quill when I sync from google classroom. It seems to sync but then my students cannot sign in with their Google accounts and half of my class hasn't appeared in the class account."

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1jE5Xwhsh8IF7VtFCXQ_VzAKsipyv5uzUwmosXwUdwEY/edit?usp=sharing

---

Here is the same bug, previously #4595 

Only half of a teacher's students could get logged in with Google. Teacher is synced with Google Classroom

Expected Behaviour
Actual Behaviour
Steps to Reproduce
Potential sources for the issue (filename, new features ect.)
Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/18i2e0HSnOA1adK_MhIE3jsrnZUVA2DklWqtNBvss8bc/edit?usp=sharing

**Comment by SaraQuill** [comment]
This one came up a few times over the weekend, so we should try to see if we can replicate if we have a google classroom acct for a test user. If not I can make one.

**Comment by SaraQuill** [comment]
Report 4595 is the same bug.

**Comment by SaraQuill** [comment]
@maddymaher Donald is aware of this and is investigating.

**Comment by ddmck** [comment]
@SaraQuill @maddymaher can we get an idea of how many students are missing/should be there? This could be a pagination issue with a change on Googles end, if theres some pattern to the number that are/n't imported it would help me narrow this down.

**Comment by ddmck** [comment]
@SaraQuill @maddymaher https://docs.google.com/document/d/1jE5Xwhsh8IF7VtFCXQ_VzAKsipyv5uzUwmosXwUdwEY/edit?usp=sharing

update report 1 to show that the teacher has multiple accounts and may have had a name change during the summer.

**Comment by ddmck** [comment]
@maddymaher @SaraQuill Second issue appears to be to do with students signing in, not them being synced, appears the rosters are full. Knowing who can and can't sign in would help.

**Comment by SaraQuill** [comment]
Note: These will be tagged in Intercom as Bug: GC. Adding a third report now. Also, questions I'm asking going forward are:
Number of students in Google Classroom?
Browser?
Are any students able to log in? If so, which students?

**Comment by SaraQuill** [comment]
Note: Closing this as we learned that it was an issue with multiple accounts rather than a bug.
