### ISSUE TITLE
Submit button in Sentence Structure Diagnostic not working. 

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4597]
Some users are reporting that during certain questions on the sentence structure diagnostic, the submit button does not work, which halts their progress during the diagnostic.

**Comment by ddmck** [comment]
@MacBlauner was there a question in particular that this occurred on?

**Comment by MacBlauner** [comment]
@ddmck unfortunately failed to take note of that this time. My mistake. In the future will be sure to document more specific details.

**Comment by MacBlauner** [comment]
@ddmck Another teacher reporting same issue, says it is happening on questions 3,6, 7, 16.
