### ISSUE TITLE
unending loading screen for student attempting to join Lesson 1: And, Or, But, So

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4598]
unending loading screen for student attempting to join Lesson 1: And, Or, But, So. The teacher said both she and her students experienced it, but I was only able to replicate it with the students account. 

#### Link to any private details (teacher/student names and emails)- See google doc: https://drive.google.com/open?id=1Mu7JlQ-TGw0yy0aZGEc6vSaAiubsu_l59FriA3pWvoE

**Comment by anathomical** [comment]
We're going to bulk-close outstanding Lessons bugs until the release of Donald's updates to Lessons go live.  If bugs recur after that, we'll re-open them as necessary.
