### ISSUE TITLE
Lessons Not Loading - Needs Server Fix

### ISSUE THREAD

**Issue by SaraQuill** [empirical-org/Empirical-Core#4607]

**Comment by SaraQuill** [comment]
@ddmck creating a task for the lessons bug. Per our chat on slack you've been restarting the server when it crashes, but we need a fix to stop the crashes. 


Expected Behavior: When someone tries to launch a lesson, it should load. 
Actual Behavior: When some users click to launch a lesson, they get stuck at loading. 
Steps to Reproduce: Unable to repro right now so it seems like earlier reports were the result of a server crash.

**Comment by ddmck** [comment]
Installed Papertrail to try and isolate the cause of the crash

**Comment by ddmck** [comment]
Installed socket-io.redis and downsized the dynos to 1x and scaled to 4 dynos. this should prevent a crash from taking us down.

**Comment by ddmck** [comment]
Closing for now. Installed socket-io.redis and set up heroku to run across 4 dynos for redundancy.
