### ISSUE TITLE
Cannot advance beyond first question in activity 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#4612]
Please try and explain the issue here. If you need to add any personal information for users, add that info to a google doc and link to it here. Restrict it to quill.org staff.

#### Expected Behaviour
When I complete the question, I should be able to advance beyond the next button. 

Link to activity: https://connect.quill.org/#/play/lesson/-LBSRdcmutsxl0OMK2Nk?student=nullhttps://grammar.quill.org/play/sw?anonymous=true&uid=-pDVJoysqQwbsmrzdxnFzg

#### Actual Behaviour
At the end of the first question, I am stuck on this page. 

![screen shot 2018-09-18 at 10 25 30 pm](https://user-images.githubusercontent.com/3667179/45727443-c5eb8a00-bb91-11e8-8550-1cda41af0c3e.png)

#### Steps to Reproduce

Complete the sentence with the correct answer.

**Comment by ddmck** [comment]
@petergault  I don't know where you got that URL from, but the student value is completely incorrect and preventing the session from being saved. You have an entire grammar activity url stuck on the end.

**Comment by petergault** [comment]
@ddmck These are the links that Nearpod is using for the embedded activities. It looks like they screwed up by adding the url to the end. I'll let them know. Thanks!
