### ISSUE TITLE
Teacher gets blue circle of death/error message when trying to access diagnostic reports

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4614]
A teacher reported getting a blue circle of death and then a subsequent error message when they tried to access their diagnostic reports. I was able to replicate this same error on their account. 

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/13JDcCRRhUsDAOshAHemN69guz2np0ZkV0syRzJ8z11k/edit

**Comment by emilia-friedberg** [comment]
This query is timing out, it sounds like @buckmaxwell and @ddmck have discussed a possible way to speed up this problem. It sounds like @tomcalabrese needs to be involved in this discussion.

**Comment by buckmaxwell** [comment]
@emilia-friedberg @MacBlauner this deploy @ddmck is making right now closes this.
