### ISSUE TITLE
Launch Lesson button not appearing for teacher after assigning lesson. 

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4615]
A teacher reached out via intercom, complaining that she was unable to launch lessons. Upon testing her account, I found that even after assigning a test lesson, the launch lessons page still did not give the option to launch and prompted her to assign a lesson (see screenshot below)

#### Link to any private details (teacher/student names and emails)-https://docs.google.com/document/d/1G26Uq2mocpOxJOFAImFlhEwpMgoo18iceu7xHBy2jY0/edit

**Comment by anathomical** [comment]
We're going to bulk-close outstanding Lessons bugs until the release of Donald's updates to Lessons go live.  If bugs recur after that, we'll re-open them as necessary.
