### ISSUE TITLE
Get a container installation procedure up-to-date and working

### ISSUE THREAD

**Issue by spacez320** [empirical-org/Empirical-Core#462]
Here are my proposed goals for the installation process and motivations behind getting a container/VM solution up;

- targetting developers who know ruby and at least some experience with the command line, but not assuming strong tooling experience or knowledge of database or server management
- workflow agnostic
- OSX and Linux similar instructions
- less than 30 minutes set up time

**Comment by spacez320** [comment]
I've ported the provision from shell to Puppet. Headless Puppet takes the place of Chef in the previous iteration. As long as people are fine moving forward with this setup, I can start to work on other things. 

https://github.com/spacez320/Empirical-Core/tree/issues/443

There are some remaining issues;
- still needs testing on various base environments, particularly Mac
- right now it's rather slow, and it looks like Rake, Bundler, and Rails tasks take up most of the provisioning time

Some pros we could potentially get out of this;
- use the `config/hiera.yml` file for developers to define application configuration things for their Vagrant setup
- we can use the Puppet provisioning to stand up the application in other places

I think we can close this after I address some of the slowness mentioned above and some other people have a chance to try it out.

**Comment by petergault** [comment]
Thanks so much for getting this up! We're pretty active in the Slack chat
room, feel free to message me there if you'd like to discuss this further.

Bob has been helping write unit tests, and it might be helpful to look at
where we should focus in our test suite. At some point I'd like to set up
SourceGraph so that we can embed terminology definitions into the code.
Have you seen this? https://www.youtube.com/watch?v=dCBQemvhEK4


On Wed, Feb 4, 2015 at 5:54 AM, Matthew Coleman <notifications@github.com>
wrote:

> I've ported the provision from shell to Puppet. Headless Puppet takes the
> place of Chef in the previous iteration. As long as people are fine moving
> forward with this setup, I can start to work on other things.
>
> https://github.com/spacez320/Empirical-Core/tree/issues/443
>
> There are some remaining issues;
>
>    - still needs testing on various base environments, particularly Mac
>    - right now it's rather slow, and it looks like Rake, Bundler, and
>    Rails tasks take up most of the provisioning time
>
> Some pros we could potentially get out of this;
>
>    - use the config/hiera.yml file for developers to define application
>    configuration things for their Vagrant setup
>    - we can use the Puppet provisioning to stand up the application in
>    other places
>
> I think we can close this after I address some of the slowness mentioned
> above and some other people have a chance to try it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/462#issuecomment-72835658>
> .
>



-- 
Peter Gault
Quill Co-Founder and Product Director
http://quill.org

Learn more about Quill: http://youtu.be/BA6jaeberMg

**Comment by spacez320** [comment]
Sounds interesting.

If you have any other infrastructure related projects, I'd be better suited
for those. Deployment, CI, server management, performance...it'd be great
to extend this to making the central Empirical deploy a managed thing.

Hope all is well.
