### ISSUE TITLE
Update placeholder text in Connect

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4620]
Update the placeholder text in Connect to only say "Type your answer here." 

![screen shot 2018-09-21 at 10 58 02 am](https://user-images.githubusercontent.com/20426718/45888967-488c6900-bd8d-11e8-8428-aea47d4c8f69.png)

Update the feedback for the "Not Concise" algorithm to say: "Revise your work. How could your response be shorter and more concise?"

**Comment by ddmck** [comment]
Not a bug, put it notion as a feature request.
