### ISSUE TITLE
Pages with no url lead to timeout not 404

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#4623]
Please try and explain the issue here. If you need to add any personal information for users, add that info to a google doc and link to it here. Restrict it to quill.org staff.

#### Expected Behaviour
When I go to a page that doesn't have a URL, I should get a 404 page:
https://www.quill.org/210321031
https://www.quill.org/connect
etc. 

#### Actual Behaviour
I see the Heroku application error page

#### Steps to Reproduce
Go to one of these links:
https://www.quill.org/210321031
https://www.quill.org/connect

**Comment by emilia-friedberg** [comment]
Closing because I can't replicate this - the 404 page appears on these links.
