### ISSUE TITLE
Bug report: Diagnostic Data will not restore with Teacher Fix

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4628]
A teacher accidentally deleted diagnostic results, but none of the "teacher fixes" will restore the results. I checked to see if the teacher has multiple accounts, and she does not. 

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1IcFOFcc8kwu0P58R_Er7UjH80QoJI6iL4mhlORL4nQo/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
Closing this issue. Have made a feature request for adding a teacher fix which will allow non-devs to fix this problem (archived activities).
