### ISSUE TITLE
Bug Report: Teachers unable to send back incorrect student responses in Lessons - Updated Feb 4th.

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4629]
Teacher unable to have students "retry" a response if they have gotten a question incorrect in Lessons. Everytime they click on the "send back" button, it does not reload the page for students. 

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1ve3WR805AMD-nmkZMWgyoryRUGJJFGrIGfA1Y1ljEGE/edit?usp=sharing

**Comment by anathomical** [comment]
We're going to bulk-close outstanding Lessons bugs until the release of Donald's updates to Lessons go live.  If bugs recur after that, we'll re-open them as necessary.
