### ISSUE TITLE
Favicon doesn't work when logged into profiles

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#463]
The Quill.org favicon only works when you are not logged into a profile.

**Comment by aliciasedlock** [comment]
Hello! I think I'd like to tackle this issue. :) I imagine I should change the label to reflect that this is in progress?

**Comment by petergault** [comment]
@aliciasedlock yes this is still an issue. We're having some weird issues with the favicon being replaced on certain browsers. Maybe we want to use something like this?

http://lab.ejci.net/favico.js/
http://blog.tommoor.com/tinycon/

Would this fix it?

**Comment by marcellosachs** [comment]
fixed as of 81c5d62ed541aac6dba73fc24670454fd8319887
