### ISSUE TITLE
Bug Report: students unable to type responses on Lesson 1 and, or, but so

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4630]
Teacher reported that during Lesson all students were unable to type in responses to prompts. I was able to replicate this bug in Lesson 1: and, or, but, so. 

#### Link to any private details (teacher/student names and emails) https://docs.google.com/document/d/1p_hBZPhmZa9OH6iWl4Nkl1BZmy1Nu-whftPSNQCoBs0/edit

**Comment by anathomical** [comment]
We're going to bulk-close outstanding Lessons bugs until the release of Donald's updates to Lessons go live.  If bugs recur after that, we'll re-open them as necessary.
