### ISSUE TITLE
Bug Report: Diagnostic Results not showing up [**4 students impacted **]

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4635]
Teacher has administered Diagnostic for students 3 times. Their student dashboards do not indicate that they have taken the assessment at all, and neither does the teacher dashboard

#### Link to any private details (teacher/student names and emails)

https://docs.google.com/document/d/1Sn_cCLI4uWJl0fJvgEY5kWrOyeBN5L00bfBQiMzjoW0/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
Sent Maddy a message about this issue. It was due to a multiple accounts issue in one of the instances and we have no record of the students having completed the diagnostic in the others.
