### ISSUE TITLE
Bug Report: Student Username change not reflected on Teacher Roster

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4638]
We tried to manually change a student's username, and the change reflects on our end but not on the teacher's dashboard. 

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1-AlSLOuGYaLD9AEbpbi6u3qb5z2RHhPp6owtXO8Jjds/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
There were two different student accounts with each of the usernames listed here. When I went to go see which one was in her class, the correct account was, so my guess is that they realized there were two accounts and switched it. In any case, closing this issue.
