### ISSUE TITLE
Bug Report: Teacher cannot assign featured activity packs, gets spinning wheel of death

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4640]
A teacher reached out saying that he was getting an unending loading screen after clicking on a featured activity pack. I was able to replicate this with every featured activity pack using his account. 

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1iUrlITqo1PpSmJYW32yIUmG2Ljm2ZB7whdmH2JU-kNM/edit

**Comment by MacBlauner** [comment]
@buckmaxwell now have two different teachers reporting this issue

**Comment by buckmaxwell** [comment]
@MacBlauner - I think we shouldn't be seeing this anymore. does this issue persist for any users? closing for now.
