### ISSUE TITLE
Bug Report: Teacher unable to type in teacher responses during "watch teacher" function

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4642]
I was able to replicate an instance of a teacher complaining that after activating the "watch teacher" function, they were unable to type in the answers box. Occurred in Lesson 1: and, or, but, so. Teacher also reported that they were unable to see student responses. 

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1NST4ybyuUXeBHo6jbLdsvBjYgFP-3gxlJ_drbtNaS2U/edit

**Comment by anathomical** [comment]
We're going to bulk-close outstanding Lessons bugs until the release of Donald's updates to Lessons go live.  If bugs recur after that, we'll re-open them as necessary.
