### ISSUE TITLE
Bug Report: Broken link on quill.org/premium

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#4645]
#### Expected Behaviour
If I click the button "Try the demo" on quill.org/premium I should be taken to quill.org/demo

#### Actual Behaviour
If I click the button "Try the demo" on quill.org/premium I'm taken to https://www.quill.org/demo?name=demoaccount which takes me to the sign in page

#### Steps to Reproduce
- Be signed out
- Go to quill.org/premium
- Click on "Try the demo"

#### Potential sources for the issue (filename, new features ect.)
Wrong link?

**Comment by buckmaxwell** [comment]
@ddmck  -- this issue persists; any thoughts?

**Comment by buckmaxwell** [comment]
Just tested in staging. It's working there so closing this for now.
