### ISSUE TITLE
Bug Report: Teacher receives 500 error message on "My Subscriptions" page

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4649]
When the teacher tries to view “My Subscriptions,” she gets a 500 error message. I can replicate it on the teacher's account, but not on other accounts.

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1gLfi7ceva_m9ixeDASsihyNr-kn9jKxPUIX-HKLgavw/edit?usp=sharing

**Comment by ddmck** [comment]
@emilia-friedberg probably something we can sort quickly at the DB level.

**Comment by emilia-friedberg** [comment]
Fixed the issue, talking to Maddy about a possible cause.
