### ISSUE TITLE
Add Date Picker to the Teacher Scorebook 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#465]
Teachers can select a date range and filter the activities by date completed. 

![select-dates-2](https://cloud.githubusercontent.com/assets/3667179/5421139/e65892c6-822c-11e4-85ee-2b256999c76b.png)

![select-dates-1](https://cloud.githubusercontent.com/assets/3667179/5421137/e6579998-822c-11e4-891c-729678606611.png)

![select-dates-3](https://cloud.githubusercontent.com/assets/3667179/5421146/07435e9e-822d-11e4-9459-04dae1638f9a.png)

**Comment by RyanNovas** [comment]
let's hold off on fixing this until the progress reports are refined. they may overlap too much.
