### ISSUE TITLE
Teacher cannot launch lessons with one of her class periods **3 reports**

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4657]
A teacher reached out saying that they were unable to launch lessons with one of their class periods. Lessons appeared to launch normally with other class periods. Teacher reported that it just reloaded the page. I was able to replicate this, and launch lessons with her other class periods with no issue.

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1wgMbaggb87kDF_Gy9rp3XOwLL2__CZ9vybsMHAQRBe0/edit

**Comment by alysiabellequill** [comment]
This teacher sent another email. I was able to replicate the issue and record it. Please see below.

http://g.recordit.co/N4MO3qSKhG.gif

Thanks.

**Comment by MacBlauner** [comment]
@ddmck
