### ISSUE TITLE
Bug Report: Straight apostrophe not recognized in Connect question

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#4659]
#### Expected Behaviour
If a student types in a straight or curly apostrophe their response she be marked as correct.

#### Actual Behaviour
When I typed in the correct answer with a straight apostrophe, it marked the response as incorrect. Then when I copy and pasted in a curly apostrophe it marked the response as correct.

#### Steps to Reproduce
- Go to this specific question in Quill Connect: https://connect.quill.org/#/admin/questions/-KzV1VTOG6ptMINnvQTx/responses
- Answer as a student
- Use a straight apostrophe instead of a curly apostrophe

#### Potential sources for the issue (filename, new features ect.)
![screen shot 2018-09-25 at 11 50 49 am](https://user-images.githubusercontent.com/8131465/46300807-9fa2f280-c572-11e8-82dc-961a4eec0938.png)

**Comment by tomcalabrese** [comment]
@emilia-friedberg this is the bug I was telling you about on slack last week by the way. Thanks!

**Comment by emilia-friedberg** [comment]
Tom, I can't replicate this, can you send me the punctuation you were using when it got marked wrong? I can add it to the file we're using the normalizer if it's missing.
