### ISSUE TITLE
Scorebook - Legend for Apps 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#466]
Under the explanation for the colors we also include an explanation of the apps by name. 

![app legend](https://cloud.githubusercontent.com/assets/3667179/5421151/1f988a96-822d-11e4-8ac2-80477acf3fd6.png)

**Comment by marcellosachs** [comment]
fixed as of 69140fb2a9ff45e3cf77cec064965c2aa11bbc91
