### ISSUE TITLE
Duplicate students in diagnostic reports, not in class roster. 

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4660]
had a teacher report missing diagnostic data+duplicate student names appearing in the diagnostic report page (duplicate names for that student were not present in the class roster). Recovering the activity session fixed the missing data issue, as well as the issue of duplicate student names. 

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1btewv-rrjfd-9qZ0sxE4oxBwHERoKZmxa16l0tAltN8/edit

**Comment by MacBlauner** [comment]
@ddmck

**Comment by emilia-friedberg** [comment]
I'm going to close this issue for now since the relevant instance has been fixed. If this occurs again, please notify us before updating the data so we can see what's going on.
