### ISSUE TITLE
User Manager - Last Sign In Does Not Sort Properly

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#4662]
Please try and explain the issue here. If you need to add any personal information for users, add that info to a google doc and link to it here. Restrict it to quill.org staff.

#### Expected Behaviour
When I click on last sign in, I should see users sorted by their last sign in date. 

#### Actual Behaviour
The way dates are sorted now:
![screen shot 2018-10-04 at 12 24 03 am](https://user-images.githubusercontent.com/3667179/46452814-df80fa00-c76b-11e8-9151-9308ddd6232c.png)

#### Steps to Reproduce
Go to user manager

**Comment by emilia-friedberg** [comment]
@petergault, do you know what you were searching for when this happened?

**Comment by emilia-friedberg** [comment]
This feature is working correctly. It defaults to sorting by Last Sign In, in descending order, so the most recent dates are at the top. If you click it, it will change to sorting in ascending order, which is what you have a screenshot of here. I'm added indicators to make it easier to tell which order it's being sorted in.

**Comment by SaraQuill** [comment]
@emilia-friedberg should we close this since it isn't actually a bug, or is it helpful to have open for the reference?
