### ISSUE TITLE
Unable to paste text into Title Card and Landing Page fields

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4668]
#### Expected Behaviour
I can paste text into landing page and title card fields on the diagnostic and Connect.

#### Actual Behaviour
If you paste text into the landing page or title card fields and save it, it will not update. Either it will be blank, or the original text will be displayed. This is happening in connect and in staging-diagnostic.

The landing page and title card text I had added a few weeks ago to the new diagnostics is gone. I played through the diagnostic a couple weeks ago and the title card and landing page text displayed. Now they are all blank.

The hardcoded intro to the diagnostic is still displaying when I play the diagnostic through the LMS. (https://www.quill.org/cms/activity_classifications/4/activities?flag=alpha)

#### Steps to Reproduce
Go here: https://staging-diagnostic.quill.org/?#/admin/title-cards/-LLFyjUOCox_mx4fPk4x
Try pasting text into the title card field.

**Comment by emilia-friedberg** [comment]
@Hannahmonk, I can't replicate the issue with pasting the text into the title card you linked to. Are you still having that issue? Did you update the landing page and title card text by copy and pasting or did they just disappear?

I'll update the LMS diagnostic link now, I think it's just going to the wrong place.

**Comment by emilia-friedberg** [comment]
@ddmck, the landing page text isn't displaying on diagnostic.quill.org, but it is displaying on staging-diagnostic.quill.org. is it possible some updates got deployed to staging but not production?
