### ISSUE TITLE
Tool icons missing from activities in Activity Pack Editor

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4670]
#### Expected Behaviour
An icon that indicates which tool an activity is part of is displayed to the left of the activity in the activity pack editor.

#### Actual Behaviour
Activities are missing their icon.

![screen shot 2018-10-05 at 12 22 16 pm](https://user-images.githubusercontent.com/20426718/46547349-a8106b80-c899-11e8-9929-3d1b2012fcdf.png)

#### Steps to Reproduce
Go here and see it: https://www.quill.org/cms/unit_templates

**Comment by ddmck** [comment]
@Hannahmonk I was able to replicate this, but then it started working again... I thought it started working after I removed some of them from the pack and then re-added, but then on refresh it worked from the get-go. Have you noticed any pattern to when this happens?

**Comment by ddmck** [comment]
Were you editing an existing pack? I can replicate it that way, but when they get added for the first time the seem to show icons

**Comment by ddmck** [comment]
Details for whoever deals with this: The activity classification id/key is not being passed when we are building the table for editing the pack.
