### ISSUE TITLE
Bug Report: Deleted student account keeps appearing in class roster

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4687]
A student had two accounts. We merged the data and deleted the extra one, but now a Deleted User account shows up on the class roster. We went in and deleted the Deleted User account from the class roster through the “Manage Classes” page. The Deleted User account will disappear from the roster after we delete it, but the account keeps re-appearing when the teacher logs back in. 

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1jPel0o9TQYaFSq8vvP1qppFdK3xJ1UTMNlLE4yJiW9c/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
This user isn't in that class now, so it seems like it has been resolved. Closing the issue for now.
