### ISSUE TITLE
Bug Report: Format Scrambled on Ipad

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4706]
A teacher reached out saying that, in addition to students having extremely long load times on both desktop and ipad, one student was getting a buggy looking interface upon logging in on ipad. I was unable to replicate this without an ipad, but the teacher provided a screenshot

#### Link to any private details (teacher/student names and emails)

https://docs.google.com/document/d/1CCAejZVdV7yb_ErWkyR9PIrRYhpraEMi2kA0yyVw6Hg/edit

**Comment by emilia-friedberg** [comment]
@MacBlauner can you ask what iPad and what browser they're on? I just logged in on an iPad and couldn't replicate this.

**Comment by ddmck** [comment]
This was around the time I deployed, and it kind of just seems like the css was missing from the CDN? closing for now.
