### ISSUE TITLE
incorrect sequences search bar no longer sensitive to punctuation or cap

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4712]
#### Expected Behaviour
When you add a new incorrect sequence in Connect or Diagnostic, the search bar in the incorrect sequence page is sensitive to capitalization, spacing, and punctuation

#### Actual Behaviour
It's not sensitive to capitalization, spacing, or punctuation.

#### Steps to Reproduce
Go here: https://diagnostic.quill.org/#/admin/questions/-KP-MEpdOxjU7OyzL6ss-esp/incorrect-sequences/new

**Comment by emilia-friedberg** [comment]
this is also true on the regular response search. I think it's an ElasticSearch issue.
