### ISSUE TITLE
Bug report: some lessons linking to Grammar instead of lesson preview

### ISSUE THREAD

**Issue by emmavolk** [empirical-org/Empirical-Core#4735]
The preview links for at least three lessons seem to be broken on both the Explore Activities and My Activities pages. They can be assigned and launched without issues. 

#### Expected Behaviour
When I click on the lesson name from either the Explore Activities page or the My Activities page, I'm taken to a preview of the lesson.

#### Actual Behaviour
When I click on the lesson name from either the Explore Activities page or the My Activities page, I'm taken to https://grammar.quill.org/

#### Steps to Reproduce
- Log into the demo account and go to [this page](https://www.quill.org/teachers/classrooms/assign_activities/create-unit?tool=lessons).
- Search "Apostrophes"
- Click the hyperlinked activity name "Lesson 1: Apostrophes"

#### Potential sources for the issue (filename, new features ect.)
Two of these lessons I just put into production today, but the other lessons I put into production today are fine. I don't know when Punctuating Quotations was put into production.

#### Impact
This is only impacting the Apostrophes, Pronoun Number and Case Errors, and Punctuating Quotations lessons. Reproduced in both a teacher account and the demo account.

**Comment by ddmck** [comment]
Fixed
