### ISSUE TITLE
Bug Report: inaccurate 100% average score on sentence structure diagnostic

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4739]
A teacher reached out saying that on the student reports>activity analysis page, the sentence structure diagnostic was incorrectly showing an average score of 100%. I was able to replicate the teachers account, and then on a number of other different teacher accounts, with both the sentence structure and ELL diagnostics, 

#### Impact
Appears to be a impacting all teachers who look at this page after having students complete either diagnostic, but is not blocking. 

#### Link to any private details (teacher/student names and emails)https://docs.google.com/document/d/1-XKZYurtIj1NIOs-HlBSORIeNli3ekc0GS0VPx2u9c0/edit

**Comment by emilia-friedberg** [comment]
This is actually not a bug. We save all diagnostic scores as 100% in the system. For the individual activity pages, we do display other scores which are calculated from their concept results, but calculating each score this way and then calculating an average of them for this page is too inefficient.

**Comment by SaraQuill** [comment]
@emilia-friedberg thanks for this context, it is very helpful!
