### ISSUE TITLE
Bug Report: Activities out of order on Student Dashboards

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4743]
A teacher assigned due dates to all of her activities, but the activities do not appear chronologically on student dashboards, so students are completing the activities in the wrong order.

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1ee5oNY996HRRk8y_Zgbbr8nDE_p3E8BuO5at-BUhi7M/edit?usp=sharing

**Comment by buckmaxwell** [comment]
@maddymaher , @emilia-friedberg I am looking at this now.  Do we know if it was ever displaying them ordered properly? If so, a guess at a date?  It appears the backend is returning the results in the correct order but somehow the front-end is shuffling them.

**Comment by buckmaxwell** [comment]
a PR has been made for this. closing.
