### ISSUE TITLE
Bug Report: Student Reports > Activity Summary page not loading properly

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4753]
When you first go to the activity summary, you get the green spinning wheel indefinitely until you go to the “Quill Classroom” dropdown bar and select a class. You cannot use any of the other dropdown menus or filters on that page unless you select a class first.

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1qG_bYeBUztAtcviEMx2e0GI4F_1X6KzTD2msmIa0bP8/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
@maddymaher, I think this only occurs when you're switching between teacher accounts because your local state has a different classroom saved as the last visited (which we normally try to default to). Have we had teachers reporting this?

**Comment by emilia-friedberg** [comment]
@maddymaher that doesn't mean we shouldn't fix it, I'm just pretty sure this is impacting staff but not teachers.
