### ISSUE TITLE
Bug report - activities out of order in the pack. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#4757]
Please try and explain the issue here. If you need to add any personal information for users, add that info to a google doc and link to it here. Restrict it to quill.org staff.

#### Expected Behaviour
Certain activity packs, but not all activity packs, are consistently assigning packs in the correct order from the stated order in the featured activity pack. 

![screen shot 2018-10-31 at 10 58 46 pm](https://user-images.githubusercontent.com/3667179/47830109-d1210080-dd60-11e8-89c3-004bb8d13207.png)

 

#### Actual Behaviour

The assignment order for the activity pack:
![screen shot 2018-10-31 at 10 58 57 pm](https://user-images.githubusercontent.com/3667179/47830093-c1092100-dd60-11e8-94cb-3c14415202ac.png)

#### Steps to Reproduce

Assign the featured pack. Delete it and re-assign, and the same order appears. 

#### Instances of bug
https://www.quill.org/teachers/classrooms/assign_activities/featured-activity-packs/47

## Appositives instance

https://www.quill.org/teachers/classrooms/assign_activities/featured-activity-packs/27

## Expected
![screen shot 2018-10-31 at 10 57 26 pm](https://user-images.githubusercontent.com/3667179/47830140-fb72be00-dd60-11e8-9cd8-2964e8f1f051.png)

## Assignment
![screen shot 2018-10-31 at 10 57 52 pm](https://user-images.githubusercontent.com/3667179/47830143-00d00880-dd61-11e8-8d2c-a38e949714d0.png)

## Using Commas
https://www.quill.org/teachers/classrooms/assign_activities/featured-activity-packs/3

## Intended
![screen shot 2018-10-31 at 10 56 18 pm](https://user-images.githubusercontent.com/3667179/47830202-3c6ad280-dd61-11e8-88ab-90242904d9f9.png)

## Actual 
![screen shot 2018-10-31 at 10 56 09 pm](https://user-images.githubusercontent.com/3667179/47830238-6f14cb00-dd61-11e8-9020-774541eb44f3.png)

# Since & Because Packs

## Intended
![screen shot 2018-10-31 at 11 14 15 pm](https://user-images.githubusercontent.com/3667179/47830557-c1a2b700-dd62-11e8-9478-0914b39ea31d.png)

## Actual
![screen shot 2018-10-31 at 11 16 54 pm](https://user-images.githubusercontent.com/3667179/47830625-16463200-dd63-11e8-93fe-7e254ec064ba.png)

Note: there are a number of packs where the assignments are in the correct order. These are the one that I found that are not in order.

**Comment by buckmaxwell** [comment]
@petergault , can you tell me which account you were logged into when you saw this?

**Comment by petergault** [comment]
@buckmaxwell It's a new account that I created last night. Here's a link to the account info:
https://docs.google.com/document/d/1hlKOswB4FesC28iKPvvaxdYgytjiQmWKfsESPB6f_2Q/edit

Some additional details:

1. I looked at about 8 packs, and only these 3 were out of order. 
Not all packs are out of order, but these 3 are. If this is a bug that is related to specific packs, we'll need to do an audit of all of the packs. Please let @Hannahmonk know if there is something that is specific to those packs that can be fixed by re-ordering. 

### How many teachers have reported this? Does the number seem to be increasing quickly?

It presumably impacts every teacher who has assigned the pack since the bug was introduced. 

### If there are multiple reports, are they clustered together (e.g. they all came in this week), or do they appear to be more isolated (e.g. 2 separate reports 3 months apart)?

No bug reports -found it myself through testing the site. 

### When do you think the bug was introduced? E.g. We saw this today vs we've been seeing for five years.

Not sure 

### In your opinion, is this sitewide or limited to the teachers who are reporting? If limited, approximately how many people are affected? E.g. "This applies to all teachers using Google classroom, but not teachers using other sign-in tools."

Site wide for everyone assigns these packs. 

### What is the scope? E.g. Is it limited to people using one question in one activity pack, or does the error occur for all activity packs on Quill?

It is not all activity packs. Of the 8 packs I looked at, it impacted 3. 

### Is the a workaround, or does the bug completely prevent those affected from using Quill in their desired way? For example, if there is a bug in the preview bar for diagnostics, students can still do the diagnostics. This would still be high priority, but not as high as a bug that prevented students from taking the diagnostics.

This is high priority because the students are receiving their assignments out of order. It's very important that students receive their lessons in the correct order as the lessons build on each other.

### Are there related bugs that we have open?

Not Sure

### Is this related to an issue that we've had recently? E.g. "Last week we had several complaints about the lessons projector. It's fixed now, but there's another error in lessons preventing teachers from using it, and when they talk to support they are noting that lessons has not been reliable this month."

not sure.

**Comment by buckmaxwell** [comment]
activities_units_templates is a join table that has no incrementing primary key. we rely on the order or results from this table to create activities in the correct order - miraculously they often come back in the right order, but they don't always because there is no field to order them on.  Adding an incrementing pkey to make this table operate as a log should allevieate the issue. I'll make a PR for this tomorrow.
