### ISSUE TITLE
Setup Intercom.io to track engagement

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#476]
We should set up intercom.io to track our conversion, handle support, and enable feedback. 

In particular, we should map out the five stages of sign up, and see how far they are getting in the process. 

We can then set up a drip campaign on top of that for emailing to teachers that have not followed through. 

https://www.sendwithus.com/resources/guide/

**Comment by petergault** [comment]
The key thing here is to track the entire sign up process - how many people sign up, how many people create a class, how many people assign an activity, how many people invite a student, how many people have students that complete an activity, how many complete multiple activities? 

We should be able to see all of the breakdowns in the funnel to activation. This can be accomplished either through Intercom or Mixpanel. 

Here is some additional advice: 

> Thanks!  I would send a custom user id -- it makes it easier to keep track of logins.  I would also try to find ways to keep user # down -- intercom is really expensive.  Producthunt had a 3 month trial code -- I think it was IntercomLovesProductHunters.  Delete old users, etc.  Sending analytics events their way is also a good idea, because it lets you do targeted messaging.

**Comment by petergault** [comment]
From here, we will then look at the following stats:
- How many activities completed per day
- How popular each activity is. 
- How much time is spent
- How many active classrooms
- How many active schools.

**Comment by petergault** [comment]
@kriskelly 

For starting off this project, here are the following stats I'd like to see:

1. Sign up - from this page, how many people register a teacher account or student account?
http://www.quill.org/account/new

2. Create a classroom.
The second property of the teacher is that the teacher has created a classroom. We should see how many classrooms each teacher has created. 
http://www.quill.org/teachers/classrooms/new
Username: Teacher, password: Demo

3. Assign an Activity
On the new staging page, there is the activity planner:
http://staging.quill.org/teachers/classrooms/lesson_planner

See how many teachers assign an activity to students. 

4. Create Student accounts
Teachers can create accounts for their students. Record each account the teacher has created. 
http://staging.quill.org/teachers/classrooms/89/invite_students

5. Complete an Activity
Can we see when a teacher's scorebook has at least one activity in the completed state?

**Comment by kriskelly** [comment]
As far as capturing user data to send to segment.io, I am currently implementing it to send the same subset of user data that gets sent to Keen, i.e. most of it except the email address and hashed password. Did you want to capture the email address as well?

**Comment by petergault** [comment]
Yes, I think intercom needs email addresses to handle transactional emails.
One of the big goals is to create automated drip campaigns in intercom
based on user behavior.

On Wed, Jan 28, 2015 at 3:00 PM, Kristopher Kelly <notifications@github.com>
wrote:

> As far as capturing user data to send to segment.io, I am currently
> implementing it to send the same subset of user data that gets sent to
> Keen, i.e. most of it except the email address and hashed password. Did you
> want to capture the email address as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/476#issuecomment-71904658>
> .
>



-- 
Peter Gault
Quill Co-Founder and Product Director
http://quill.org

Learn more about Quill: http://youtu.be/BA6jaeberMg

**Comment by kriskelly** [comment]
Another question, for teachers assigning an activity to students, which of the following stats would you like to track:
- Every instance of a teacher assigning a set of activities to a set of students (creating a new unit). E.g. a teacher creates 1 new unit (5 activities to 5 students), 1 event goes to segment, contains the full list of assigned students, activities.
- Every activity, student, teacher combination. E.g. for assigning 5 activities to 5 students, it would send 25 events to segment.

**Comment by kriskelly** [comment]
@petergault You can ignore my previous question, just sending an event for now called "Teacher assigned an activity". As far as metadata attached to events, it seems to be very limited for intercom.io, see here for details: https://segment.com/docs/integrations/intercom/#track 

As of fa642ee352fa789a177445c762a51f26d468e27d, here is the list of events that are being tracked:

- Student created an account
- Teacher created an account
- Teacher created a classroom
- Student completed an activity
- Teacher assigned an activity
- Teacher created an account for a student

Let me know if you want to change any of the wording for these events. 

One more question: do you want to import all existing users into intercom.io, or just have them trickle into the system each time a user logs in? I can do the former by adding a rake task to basically batch import all users, or I just start tracking login events and handle it there.

**Comment by kriskelly** [comment]
Merged into develop as of 6a966ed4d801f98622a8657112a0b9e0f7d04651. Let me know if you want to keep this issue open. I recommend closing this one and creating a new issue for tracking additional events.
