### ISSUE TITLE
Admin Page returns 500 error

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#4766]
**Describe the bug**
From user manager > sign in as an admin. 
Page returns 500. 

**To Reproduce**
1. Go to user manager
2. Click on admin flag
3. Click to load account.

**Expected behavior**
Load page

**Impact**
Reproducible with multiple accounts - seems to be every account.

**Comment by ddmck** [comment]
Admin’s haven't been a thing for over a year, we should remove the option to filter them.

**Comment by buckmaxwell** [comment]
fixing now

**Comment by buckmaxwell** [comment]
this is fixed in production, @ddmck @emilia-friedberg -- when you get the chance update your local databases so that this change is reflected. If you have questions about how to update your local database to reflect staging, ask me!
