### ISSUE TITLE
Bug Report: Connect Fill in the Blank requiring 5 attempts even with optimal responses

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4770]
**Describe the bug**
When a student inputs an optimal response to a fill in the blank question on Connect, the student is not moved on to the next question. The student is required to recheck answer up to 5 times. 

**To Reproduce**
1. Go to https://connect.quill.org/#/admin/fill-in-the-blanks/-LFrRT8PtwWFp0DPzGEf/test
2. Submit an optimal response

**Impact**
Low impact currently. We only have a handful of fill in the blank activities, and I've moved them out of production until the issue is resolved. 

**Screenshots**
Recording: http://recordit.co/RjUAKReav8

**Comment by buckmaxwell** [comment]
@Hannahmonk , I am aware of this issue (stumbled upon it myself recently).  Depending on how things go today I can try to look into it and give you an update.  I imagine this is not a difficult fix.
