### ISSUE TITLE
Bug Report: Quill.org Announcements Page Link Broken

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4778]
**Describe the bug**
The https://www.quill.org/announcements link brings you to an "Oops! We can't seem to find what you're looking for!" page.

**To Reproduce**
1. Go to quill.org
2. Click on "Our Story"
3. Click on "Announcements"

**Impact**
This is an important bug because we use this page to announce all of our new features. We also link this page to our social media accounts.

**Screenshots**
<img width="1155" alt="screen shot 2018-11-13 at 4 25 47 pm" src="https://user-images.githubusercontent.com/35699056/48444122-09610f80-e761-11e8-97fe-9e27023b7449.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by buckmaxwell** [comment]
looking at this now.... do you know the last (approximate) date / time that announcements was working?

**Comment by maddymaher** [comment]
@buckmaxwell I don't know for sure, but I know it was working in September, so as early as October.

**Comment by maddymaher** [comment]
@buckmaxwell @ddmck thanks!!
