### ISSUE TITLE
Teachers and Students unable to login with clever 

### ISSUE THREAD

**Issue by MacBlauner** [empirical-org/Empirical-Core#4785]
**Describe the bug**
both teachers and student clever users report being unable to log in. Clever users via clever support reported experiencing an error message that says their teacher is not signed up for quill (see attached google doc). Clever support stated that while the error message says the teacher has not signed up for quill, the user seems to have data shared with Quill.

**To Reproduce**
Was not able to reproduce as its idiosyncratic to clever users. 

**Expected behavior**
Clever users should be able to log in normally.

**Impact**
Unclear if it is effecting all clever users. Had one support request via intercom, and an email from Clever support responding to a request from a different user. Both are teachers. 

**Screenshots**
See attached Google Doc

**Desktop (please complete the following information):** UNKNOWN, will add info if possible

**Smartphone (please complete the following information):** UNKNOWN, will add info if possible

**Additional context**
Google Doc with screenshots below!
https://docs.google.com/document/d/17cC9Ut4gWfLLBxguDsbyjiywpip1RBjBZARFOoH1f-Y/edit

**Comment by MacBlauner** [comment]
@ddmck

**Comment by emilia-friedberg** [comment]
I'm going to assume that this issue
