### ISSUE TITLE
Add first & second grade to grade selector

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#479]
When a teacher adds a classroom, they currently get the screen shown below, with grade 3 the lowest on the drop down. Grades 1 and 2 should be added as options.
![screenshot 2015-01-07 at 1 38 09 pm](https://cloud.githubusercontent.com/assets/6655439/5651091/792db49c-9672-11e4-86e1-a128c55de825.png)

**Comment by petergault** [comment]
Completed by @bobmazanec
