### ISSUE TITLE
Style Issue, download report button has wrong color link post click

### ISSUE THREAD

**Issue by buckmaxwell** [empirical-org/Empirical-Core#4792]
The "Download Report Button" displays black text on green (perhaps after it's been clicked). The color does not match our styleguide.
![screen shot 2018-11-16 at 11 54 54 am](https://user-images.githubusercontent.com/6210452/48635634-b07abc80-e996-11e8-8221-b48534560b50.png)

**Comment by Kstheking** [comment]
Hi, I'd like to fix it.
