### ISSUE TITLE
"undefined" instructions for ELL diagnostic question

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4817]
**Describe the bug**
Instructions not displaying for one ELL diagnostic question (-LP2d-AypvpZosEnFVv4). Instructions say "undefined"

I think the instructions for this question just need to be added to the code in all the supported languages. The instructions should be the exact same as for this question: -KOqMWRFOrYgv-KjRYdy-esp

**Impact**
Any students taking the ELL diagnostic now are not getting instructions for this question.

**Screenshots**
![screen shot 2018-11-26 at 12 53 52 pm](https://user-images.githubusercontent.com/20426718/49033340-ebda6f80-f17c-11e8-98dd-bdc8dfe019dd.png)

**Comment by ddmck** [comment]
@emilia-friedberg Could this be related to the change in default prompts?
