### ISSUE TITLE
Prohibit Multiple Classrooms with the Same Name From Being Created

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#482]
There have been several teachers that have made duplicate classrooms with the same name. E.g, two classes named Period 5.

This causes confusion among teachers and students, with lessons and class rosters becoming fragmented between the two identical classes.

When a teacher names a classroom, we should make sure that no other classrooms with identical names are associated with that teacher's account. If there is, then we should give an error message stating "A classroom called XYZ already exists. Please rename this classroom to a different name."

**Comment by dalrayes** [comment]
Hi - is this still happening?

**Comment by s12dsow** [comment]
Will work on this! with @alcastaneda

**Comment by s12dsow** [comment]
I will work on this witih @alcastaneda

**Comment by bobmazanec** [comment]
Functionality & unit spec added in 7a53d2b9
`feature` spec examples added in 9072f60

Closable?

**Comment by petergault** [comment]
@RyanNovas can you confirm this is fixed by @s12dsow 's pull request?

**Comment by marcellosachs** [comment]
it works! thanks @s12dsow and @bobmazanec !
