### ISSUE TITLE
Students receive "Student does not exist" message when trying to join lesson

### ISSUE THREAD

**Issue by emmavolk** [empirical-org/Empirical-Core#4822]
**Describe the bug**
A teacher reported that five of her students in one class are receiving the message "No such student. Student with id '[id]' does not exist" when they attempt to join a lesson. I was able to replicate this and confirm that the students can access activities, just not lessons.

**To Reproduce**
See doc here: https://docs.google.com/document/d/1X4tXfT7iar2zihdqJVs84HLl2eUfg53UKkferAjHMz4/edit

**Expected behavior**
When a student joins a lesson, they are taken to the Lobby slide where they see the message "You've joined this lesson."

**Impact**
This is the only report we've received.

**Screenshots**
See doc.

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by ddmck** [comment]
@emmavolk following the changes I made to the database, I was able to log in as the student named in the google doc. closing for now.
