### ISSUE TITLE
Update Metabase Query to display current data

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4837]
**Describe the bug**
The metabase query Quill Activity List - List of teachers who have completed an activity (https://data.quill.org/question/253?activity_id=873) seems to only be displaying data from before August

**To Reproduce**
1. Go to https://data.quill.org/question/253?activity_id=873
2. Input 858 as the activity ID; this activity was published in October, and the first question has almost 4,000 student responses, so we know students have completed it. However, the query is not displaying any results.
3. Input 777 as the activity ID; this activity was published in June but is only showing teachers who have assigned it before August. 

**Expected behavior**
The query shows which teachers have assigned an activity and have had students complete it to date.

**Impact**
The content team uses this query to monitor the grading of new activities--in particular, we'd like to use it now to monitor the grading of the new diagnostics before they are publicly launched.

**Comment by ddmck** [comment]
Fixed, sorry, that was due to the rewrite to classroom assignment logic.
