### ISSUE TITLE
Concept Report in Mouseover

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#484]
When a teacher mouses over a student score, the teacher sees the breakdown of the concept tags. 

![screen shot 2015-01-14 at 12 37 21 pm](https://cloud.githubusercontent.com/assets/3667179/5743899/491ce994-9bea-11e4-991d-12bf21a49a76.png)

**Comment by petergault** [comment]
Moving forward, the thing that seems like the biggest priority now is getting the concept tags to display in the teacher dashboard. Do you want to focus on the WPM counter? Essentially what this means is that you would have to have the following parts:
1. Create a concept result for each word per minute entry. 
2. Send the JSON data to Empirical Core. 
3. Have Empirical Core understand that Typing_Speeds is a type of concept where it takes all of the concept results for a session, and it calculates the average WPM. 
4. It displays the WPM average as a text field below the activity session. 

> It seems like rather than the calculation of average WPM happening on the Quill Writer end, it instead makes sense for the Quill LMS to handle the calculations for each Concept_Category. This way the same calculation process will happen regardless of which app is using the Typing_Speeds concept category.

**Comment by petergault** [comment]
From @kriskelly 

> One question I had: should the concept tag category be called Typing_Speeds, Typing Speeds, or Typing Speed? Basically should there be underscores, and I'll need the exact naming scheme you'd like to use for each category, e.g. Grammar Concepts, Grammatical Concepts, etc.

I've got no preference on the naming scheme. It probably makes the most sense to simply call it "Typing Speed." 

The key terms so far:
Concept Class: (previously Concept Category). A class of concepts. I prefer the term class to category because the term class seems to imply dissimilar items. Conversely, concept category seems to apply a series of things that are similar to each other.  We can continue to discuss this term. 

Specific Concept Classes:
Typing Speed 
Grammar Concepts
Punctuation Concepts

**Comment by kriskelly** [comment]
Ok, I will use those concept class names going forward.

**Comment by marcellosachs** [comment]
@kriskelly implemented this for the old scorebook, but i have to put it in the new (react) scorebook. I'm waiting to do this because it may be the case that Kris is implementing a similar thing for the progress report, so I'm going to wait until the dust settles on that...

**Comment by kriskelly** [comment]
@marcellosachs, I don't think there are any tooltips coming for progress
reports, so feel free to go ahead and do that.

**Comment by marcellosachs** [comment]
think its best to do this after integration and concept reporting occurs
