### ISSUE TITLE
Bug Report: Accounts drop down button doesn't work

### ISSUE THREAD

**Issue by racheldantzlerquill** [empirical-org/Empirical-Core#4842]
**Describe the bug**
This is about clicking on the account button in the upper right hand corner of the screen. When you click on the little book or the arrow, the drop down list appears, but when you click on the name, nothing happens.

**Impact**
The impact is that teachers expect that clicking their name will make the drop down list appear, so they might think that it is broken when clicking their name doesn't work.

**Comment by SaraQuill** [comment]
Closing as I believe this was addressed in pull request #4883
