### ISSUE TITLE
Bug Report: Focus points and incorrect sequences aren't recognizing curly apostrophes

### ISSUE THREAD

**Issue by emmavolk** [empirical-org/Empirical-Core#4843]
**Describe the bug**
Focus points and incorrect sequences written with a straight apostrophe (') aren't recognizing responses written with a curly apostrophe (’). 

**To Reproduce**
1. Go to https://connect.quill.org/#/admin/questions/-LNuOsH958jJBKEeFsa3/focus-points
2. Click on Play Question
3. Paste this phrase into the response box: the tiger naps by the lion’s cave
4. Receive incorrect feedback.
5. Paste this phrase into the response box: the tiger naps by the lion's cave
6. Receive correct feedback.

**Expected behavior**
A response written with a curly apostrophe should receive the focus point or incorrect sequence feedback even if the focus point or incorrect sequence is written with a straight apostrophe.

**Impact**
This seems to be affecting all questions with apostrophes in the focus points or incorrect sequences, so students who answer with incorrectly placed curly apostrophes are receiving unhelpful or frustrating feedback. Optimal responses accept either curly or straight apostrophes.

**Screenshots**
<img width="825" alt="screen shot 2018-12-05 at 10 42 34 am" src="https://user-images.githubusercontent.com/43547787/49524981-c59e8900-f87a-11e8-81c6-a7e209b1dd29.png">
<img width="828" alt="screen shot 2018-12-05 at 10 42 50 am" src="https://user-images.githubusercontent.com/43547787/49524985-c7684c80-f87a-11e8-961a-7e7c3783a5eb.png">
<img width="944" alt="screen shot 2018-12-05 at 10 42 57 am" src="https://user-images.githubusercontent.com/43547787/49524987-c8997980-f87a-11e8-937a-c6ddae2b6888.png">

**Desktop (please complete the following information):**
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ddmck** [comment]
Hmm ok, we normalize the student answers to account for the many different variations of punctuations, but it’s looks like we will need to do the same for the focus points. 

—
Donald McKendrick	
Director of Technology @ Quill.org

**Comment by Hannahmonk** [comment]
Affecting a couple diagnostic questions, so we'll have to push the launch of the new diagnotics until it's fixed. Let me know if you need any other examples!
