### ISSUE TITLE
Bug Report: activities won't load for students

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4845]
**Describe the bug**
Random students at random times are unable to access their activities on Quill because the activities won’t load. Some eventually get an error message that the web response time is too slow. 

**Impact**
It's difficult to gauge the frequency of this bug, and it's hard to figure out why its happening, but it blocks students from being able to do their work, so it's important to solve. 

**Screenshots**
see doc

**Additional context**
https://docs.google.com/document/d/1cN98eQvJPuymXVmAZ_48IRNiuSmWJs8TNjyzpbbX9YU/edit?usp=sharing

**Comment by anathomical** [comment]
While this is clearly an issue, it isn't clear that we can address it given how little we currently understand about it.  Without a pattern to home in on, it's not really possible to fix this other than to look at general website performance improvements (which may be worth doing).  I'm going to close this, but we should re-open it if we get additional reports with a bit more detail in them.
