### ISSUE TITLE
Stale README links

### ISSUE THREAD

**Issue by bobmazanec** [empirical-org/Empirical-Core#485]
Some of the README links appear to be stale:
* **Cofactor Empirical Core:** [Our project management HQ](http://www.empirical.org/cofactor/teams/compass)
* **Mailing List:** [Compass developers mailing list.](https://groups.google.com/forum/#!forum/empirical-compass)
* **Real Time Chat:** [Join us in the Compass Gitter room.](https://gitter.im/empirical-org/Compass)

(hoping I'm not missing something obvious-ish...)

**Comment by petergault** [comment]
Readme is updated, all of the new info lives in the LMS team page.
