### ISSUE TITLE
No GIF on Quill Lessons Overview Page

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#4852]
https://www.quill.org/tools/lessons No GIF in box that should demo the activity

#### Expected Behaviour

a gif loads

#### Actual Behaviour

no gif loads

**Comment by RyanNovas** [comment]
@emilia-friedberg what GIF is supposed to go there?

**Comment by emilia-friedberg** [comment]
@RyanNovas https://assets.quill.org/videos/tools/lessons.mp4, which is the one that's linked there. it seems like it starts inconsistently.

**Comment by emilia-friedberg** [comment]
I can't reproduce this at all any longer so I'm closing it. If it recurs we can try to investigate again but I see no reason for this to not be working.
