### ISSUE TITLE
Rspec produces "Shared example group '...' has been previously defined" warnings

### ISSUE THREAD

**Issue by bobmazanec** [empirical-org/Empirical-Core#486]
Running `bin/rake spec` produces a number of warnings from Rspec:

        % bin/rake spec
        [...]
        WARNING: Shared example group 'flagged' has been previously defined at:
          /Users/bob/dev/Empirical-Core/spec/support/shared/flagged_spec.rb:1
        ...and you are now defining it at:
          /Users/bob/dev/Empirical-Core/spec/support/shared/flagged_spec.rb:1
        The new definition will overwrite the original one.
        WARNING: Shared example group 'student' has been previously defined at:
          /Users/bob/dev/Empirical-Core/spec/support/shared/student_spec.rb:3
        ...and you are now defining it at:
          /Users/bob/dev/Empirical-Core/spec/support/shared/student_spec.rb:3
        The new definition will overwrite the original one.
        WARNING: Shared example group 'teacher' has been previously defined at:
          /Users/bob/dev/Empirical-Core/spec/support/shared/teacher_spec.rb:3
        ...and you are now defining it at:
          /Users/bob/dev/Empirical-Core/spec/support/shared/teacher_spec.rb:3
        The new definition will overwrite the original one.
        WARNING: Shared example group 'uid' has been previously defined at:
          /Users/bob/dev/Empirical-Core/spec/support/shared/uid_spec.rb:3
        ...and you are now defining it at:
          /Users/bob/dev/Empirical-Core/spec/support/shared/uid_spec.rb:3
        The new definition will overwrite the original one.

Easy fix per https://github.com/rspec/rspec-core/issues/828#issuecomment-38789977

PR imminent...

**Comment by petergault** [comment]
Great, thanks so much bob! If you'd like to chat with us feel free to join us here: 

http://community.quill.org/chat/

This chat room connects to our Slack room, and most of the team is always available there. 

Best,
Peter

**Comment by bobmazanec** [comment]
Thanks.

At the risk of embarrassing myself (further...?), I'm not quite sure what to do next there.

It asks for a username; I give it 'BobMazanec' (who saw that coming, right? :-))
Nothing between 'CHAT' & the 'message' entry at the bottom
I enter some text & hit Return; I get a

    https://quill-chat.herokuapp.com

    Please wait while we reconnect
    [OK]

popup (alert?); same again if it close it and hit Return in the message box again.

FWIW, OS X Yosemite (10.10.1) & Safari 8.0.2

Thanks!
