### ISSUE TITLE
Bug Report: Teacher's School Dashbaord Won't load for Admins

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4884]
**Describe the bug**
Teachers with a school administrator accounts cannot access their "School Dashboard" tabs. The green loading circle just keeps spinning.

**To Reproduce**
See doc

**Expected behavior**
The teacher will click on the "School Dashboard" tab, and the school

**Impact**
The School Dashboard tab is a big selling point for Premium, and it's important that the admins can access this data and keep track of how their students and teachers are doing.

**Screenshots**
See doc

**Additional context**
https://docs.google.com/document/d/1Zt86-QI9kt6ZHJF2bzTMttolQtkb8ST2SjGn_xc-8tg/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
Looks like we're timing out on all the pages except Activity Scores. I'm going to talk to @ddmck about the best way to handle this. I think Max did some work on speeding up these queries a while back but if they're still not fast enough we may need to start caching them or something.
