### ISSUE TITLE
Copying text in proofreader causes words to be considered edited

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#4898]
**Describe the bug**

**To Reproduce**
1. Go to https://proofreader.quill.org/#/play/pf?anonymous=true&uid=-K0rnIIF_iejGqS3XPJ8
2. Highlight all of the passage of text
3. Press command + c
4. Click out of the highlighted text
5. See that the passage turns all of the text to bold and considered edited

**Expected behavior**
If a user copies text it should not consider it edited

**Impact**
Happens for all of the proofreader activiteis

**Screenshots**
![iyzqmduv58](https://user-images.githubusercontent.com/8131465/50306283-2923db80-0463-11e9-8f51-f0238d6e1a5a.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**

**Comment by tomcalabrese** [comment]
@emilia-friedberg tagging you on this in case it's helpful while you're working on other Proofreader fixes. Thanks.

**Comment by emilia-friedberg** [comment]
Thanks Tom! I've fixed this as part of the Proofreader update.
