### ISSUE TITLE
Spec failures on develop

### ISSUE THREAD

**Issue by bobmazanec** [empirical-org/Empirical-Core#490]
`rake spec` produces these failures for me on develop f5436ec:

    [...]
    Finished in 2 minutes 35.8 seconds (files took 18.24 seconds to load)
    250 examples, 19 failures, 5 pending
    
    Failed examples:
    
    rspec ./spec/serializers/activity_session_serializer_spec.rb:15 # ActivitySessionSerializer has expected attributes should contain a root attribute
    rspec ./spec/serializers/activity_session_serializer_spec.rb:22 # ActivitySessionSerializer has expected attributes activity_session object should have these keys
    rspec ./spec/serializers/activity_session_serializer_spec.rb:28 # ActivitySessionSerializer has expected attributes activity_session object should have a properly formatted concept tags response
    rspec ./spec/models/activity_spec.rb:28 # Activity#form_url must not include uid if hasn't been validated
    rspec ./spec/models/activity_spec.rb:32 # Activity#form_url must include uid after validate
    rspec ./spec/models/activity_spec.rb:52 # Activity#module_url must add student param of it's a valid student session
    rspec ./spec/models/activity_spec.rb:42 # Activity#module_url must add anonymouse param if arg is included
    rspec ./spec/models/activity_spec.rb:46 # Activity#module_url must add uid param of it's a valid student session
    rspec ./spec/models/user_spec.rb:563 # User clever setup from clever passes an auth hash for a user to be setup
    rspec ./spec/requests/sign_up_spec.rb:34 # Sign up Connect Student account to teacher account via class-code allows them to fill in a classcode
    rspec ./spec/requests/sign_up_spec.rb:73 # Sign up Create New Student Account (from teacher interface) allows the teacher to accidentally enter the full name in the first name field
    rspec ./spec/requests/sign_up_spec.rb:61 # Sign up Create New Student Account (from teacher interface) generates username
    rspec ./spec/requests/sign_up_spec.rb:5 # Sign up Create New Teacher Account requires unique email
    rspec ./spec/requests/sign_up_spec.rb:16 # Sign up Create New Student Account (from sign up) requires unique username
    rspec ./spec/requests/sign_up_spec.rb:25 # Sign up Create New Student Account (from sign up) does not require email
    rspec ./spec/requests/assign_lessons_spec.rb:48 # assignments Teacher assigns new lessons to student doesn't show up if the teacher didn't select the student
    rspec ./spec/requests/assign_lessons_spec.rb:28 # assignments Teacher assigns new lessons to student shows up in the student account
    rspec ./spec/requests/assign_lessons_spec.rb:40 # assignments Teacher assigns new lessons to student shows up in the scorebook
    rspec ./spec/models/section_spec.rb:21 # Section when it's created/updated when it runs validations must have a workbook
    
    Randomized with seed 25804

Any reason to think they're personal problems & look at my setup rather than fix 'em (*e.g.*, PR #489 is meant to address the `spec/requests/sign_up_spec` failures) as I learn my way around?

**Comment by kriskelly** [comment]
I think I broke the activity_session_serializer_spec, but it's a test setup problem rather than an actual bug. The rest of them have always been failing for me.

**Comment by bobmazanec** [comment]
Thanks for the "it's probably not a personal problem" data point :-)

I've submitted PRs #488 & #489 so far.

Maintainers: please wave me off if you're not interested in more like them...

**Comment by bobmazanec** [comment]
...or not...I had planned to use fixing them as a way to learn my way around some, but all are fixed as of 829a474f -- thanks! :-)
