### ISSUE TITLE
Bug Report: teacher receives 403 error message from google when assigning activities

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4908]
**Describe the bug**
When a teacher tried to assign work, he received a 403 error message from google. 

**To Reproduce**

**Expected behavior**

**Impact**
Provide as much context as you can to explain the bug's affect on Quill. E.g. number of people affected, whether it causes a site-wide error, whether there is a workaround, if this relates to another bug, when you think the bug was introduced. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
https://docs.google.com/document/d/1dHZJs5lfdsbtQoDlFoxns7acenPb-eNAZSNq8D-bszY/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
going to close this since I believe the issue has been resolved.
