### ISSUE TITLE
Bug Report: Teacher unable to assign diagnostic recommendations

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4916]
**Describe the bug**
When she tries to assign the recommendations, the button just reads “assigning…” but nothing assigns. Clearing the cache and hard refreshing do not help. Occurs on both safari and chrome.

**Additional context**
https://docs.google.com/document/d/1gaiXqw95qJxtEpK3A5f7wiYLYOM2doDsj0M2jANvV9Q/edit?usp=sharing

**Comment by racheldantzlerquill** [comment]
Other teachers who have had the same issue: 
Janie Martinez janie_martinez@mma-tx.org
Tarah Heinzl theinzl@sppswaterloo.com
Lucina Hendricks lucina_bess@yahoo.com
Amy Velder amy.velder@beaufortschools.org
Ashley Harris harrisa@cfbisd.edu
Marsha Thibodeaux mthibodeaux@bensfordchristianschool.org
Dhugal Gardner gardnedz@scps.k12.fl.us
Dawn Wayant dwayant@usd345.com
Andrew Bradshaw andrew.bradshaw@pinnaclecharterschool.org

**Comment by emilia-friedberg** [comment]
I believe this has been fixed by restoring the queue logic for background workers so I'm going to close the issue.
