### ISSUE TITLE
Bug Report: School in system not showing up under "add school" option on teacher account

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4918]
**Describe the bug**
When the teacher tries to add her school to her account, it does not come up under the “add school” search option on the “my account” page. The school is in the system and comes up in user manager.

**Additional context**
https://docs.google.com/document/d/1ytXVRSHuqCowstQh4xa6wY2hVZCycOv4jFfuFYu6Vg4/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
@maddymaher can you put the name of the school in the Google doc?

**Comment by anathomical** [comment]
Engineering needs to follow up with @maddymaher to get the name of the school, and we probably want to establish a customer service policy for bugs that prevent teachers from accessing their paid-for Premium.  Maybe we should give them Quill Credits while the bug fix is worked on?

**Comment by maddymaher** [comment]
@anathomical @emilia-friedberg  school name added to google doc!
