### ISSUE TITLE
Usernames May be Getting Overwritten

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#492]
To reproduce:
1. Log in as teacher.
2. Go to manage profiles.
3. Go to Edit Student's profile
4. Edit Username.
5. Put in a different student's username (from a demo account, not a real one).

You should see a warning stating that the username has been taken, but then the username will change anyway.

**Comment by mrvp194** [comment]
I'm going to take a stab at this today

**Comment by mrvp194** [comment]
I can't replicate this issue.  I get to a screen with the warning but when I go back the username hasn't been changed.  I believe this issue should be closed

**Comment by RyanNovas** [comment]
@mrvp194, you are right. We recently launched a whole redesign of the site and this may have been incidentally taken care of. Thank you for letting us know!
