### ISSUE TITLE
Bug report: Teacher unable to update student names or passwords

### ISSUE THREAD

**Issue by emmavolk** [empirical-org/Empirical-Core#4926]
**Describe the bug**
A teacher reported that his is unable to change students' names. For one student, he can change neither the name nor reset the password. The boxes where he should be able to type are greyed out. These are teacher-created accounts. I can replicate this issue on his account only.

**To Reproduce**
See doc: https://docs.google.com/document/d/1YBKd9igdxGr1qmkYEekprYPmCG0PMv1NF-IY2Qo9qhc/edit?usp=sharing

**Expected behavior**
After a teacher creates student accounts, they are able to change the students' names and reset the passwords.

**Impact**
This is the only report we've received. I can't replicate on other teachers' accounts.

**Screenshots**
See doc.

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by emilia-friedberg** [comment]
@emmavolk, I can't replicate this. in the screenshot, it looks like you were looking at the page of a student who had created their own account, because their username did not contain a classcode. are we sure he wasn't just trying to edit the accounts of students he shouldn't be able to edit?

**Comment by emmavolk** [comment]
@emilia-friedberg the accounts are listed as "teacher created," so he should be able to edit. I'll update the doc with the name of the class it's affecting—it looks like a bunch of new classes have been created since I made the report, and those classes aren't affected.

**Comment by emilia-friedberg** [comment]
@emmavolk, not sure what happened but it no longer appears to be the case that he can't edit their passwords so I'm going to close this issue for now.
