### ISSUE TITLE
Delete Classroom Needs Confirmation Step

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#493]
Currently, the Delete Classrooms function in the new teacher profile instantly deletes a classroom. There needs to be another step here to prevent teachers from doing this accidentally.

There should be a popup that states the following:
"Deleting a classroom is a permanent action and cannot be reversed. All data and student profiles associated with the classroom will be deleted. Are you sure that you want to delete this classroom?"

And then have the following buttons:

"No, send me back to my profile."
"Yes, I would like to permanently delete the classroom and all associated information."

**Comment by marcellosachs** [comment]
this is solved for now with a javascript confirm box. in future can style it up.
