### ISSUE TITLE
Google icon not displaying on the teacher sign up page on mobile

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#4938]
**Describe the bug**
Google icon in the "sign up with Google" button is not displaying on the teacher sign up page

**To Reproduce**
1. Go to https://www.quill.org/sign-up/teacher
2. See error

**Expected behavior**
The Google icon should display

**Impact**

**Screenshots**
![img_1438](https://user-images.githubusercontent.com/8131465/51144901-54120d00-1820-11e9-9fc7-75b32a729d8c.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 12.1.2
 - Browser: Safari
 - Version: 12.1.2

**Additional context**

**Comment by ddmck** [comment]
Possible connectivity issue? Appears to work for me.
—
Donald McKendrick	
Director of Technology @ Quill.org
