### ISSUE TITLE
Admin CMS Timeout Error

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4946]
**Describe the bug**
The Admin CMS times out before it loads. It works inconsistently. Sometimes it's not accessible for a few days at a time while other times it will load after refreshing the page.

**To Reproduce**
1. Go to https://www.quill.org/staff/user

**Expected behavior**
The page loads consistently.

**Impact**
The Admin CMS is still currently the only way to put new activities into production, and it's still the way to get activity IDs and other information about activities and packs. When it's not accessible, it delays the content team's progress.

**Screenshots**
![screen shot 2019-01-15 at 12 36 35 pm](https://user-images.githubusercontent.com/20426718/51270226-5b592800-1992-11e9-903c-7229c76b45e3.png)

**Comment by ddmck** [comment]
Do you have the same issue going to https://www.quill.org/staff/activity <https://www.quill.org/staff/activity> ? It might be that we have too many users now for that page to load consistently.

If updating activities is the main workflow, and that page consistently loads I can change the behavior.
