### ISSUE TITLE
Connect prompt does not recognize percent symbol or hyphen

### ISSUE THREAD

**Issue by emmavolk** [empirical-org/Empirical-Core#4948]
**Describe the bug**
On [this](https://connect.quill.org/#/admin/questions/-L4rUP5Sp9v0looHAeQh/responses) Connect question, students are incorrectly receiving the feedback "Revise your sentence to include the word 15%. You may have misspelled it." when they already have 15% in their response.

On [this](https://connect.quill.org/#/admin/questions/-LVyc0iET4KbkhY66yZM/responses) question, incorrect missing word feedback is occurring with the word "long-lasting." 

On [this](https://connect.quill.org/#/admin/questions/-LYDgYejCyI51Q592jse/responses) question, incorrect missing word feedback is occurring with the word "Amelia's."

**To Reproduce**
1. Go to https://connect.quill.org/#/admin/questions/-L4rUP5Sp9v0looHAeQh/responses
2. Click Play Question and enter this: "Even though lightning strikes the earth 100 times a second, only 15% of it cause fires."
3. Receive incorrect feedback

1. Go to https://connect.quill.org/#/admin/questions/-LVyc0iET4KbkhY66yZM/responses
2. Click Play Question and enter this: "There was strong interest in women't basketball for many years, but there was no long-lasting women't professional league until 1996."
3. Receive incorrect feedback

1. Go to https://connect.quill.org/#/admin/questions/-LYDgYejCyI51Q592jse/responses
2. Click Play Question and enter this: "People wonder if Amelia's plane may have landed on a deserted island or crashed."
3. Receive incorrect feedback

**Expected behavior**
Students are only told to include a missing word if they are in fact missing a word.

**Impact**
This is impacting the grading of all questions with hyphens, percentage signs, numbers, and apostrophes, including several questions in the advanced diagnostic recommendations sequence that we launched today.

**Screenshots**
<img width="828" alt="screen shot 2019-01-23 at 11 10 27 am" src="https://user-images.githubusercontent.com/43547787/51620377-3e77a400-1f00-11e9-8710-fb04ba85a3c8.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by emilia-friedberg** [comment]
@ddmck can we look at this together? it's not quite as simple as the numbers fix because in packages/quill-spellchecker/src/processSentence.ts we are stripping out percentage symbols. not sure whether it's okay to just stop stripping them and add them to the letters file or not.

**Comment by emmavolk** [comment]
@emilia-friedberg also experiencing this issue with numbers and apostrophes, so I've updated the report with another example. let me know if it's helpful for me to keep adding examples as I come across them!
