### ISSUE TITLE
Bug report: Student scores not showing up in teacher's report

### ISSUE THREAD

**Issue by emmavolk** [empirical-org/Empirical-Core#4960]
**Describe the bug**
A teacher reported that many of her students that have completed activities are being listed as “Not Started” in her grade reports. The activities are marked as complete on the student’s end.

This seems to be happening in conjunction with the bug reported in Issue #4937 where some previously duplicate accounts that had previously been removed from the classroom are appearing multiple times in the reports. 

I was able to replicate this problem on her account, including in the instance I screenshotted in the doc. She says this is happening to all her classes but 5th period.

**To Reproduce**
See doc: https://docs.google.com/document/d/1m5AzGgMoopbpIAC5B_FfoXgADuP-0GwwP8VkvItxJA0/edit?usp=sharing

**Expected behavior**
When a student completes an activity, the teacher can see their results from the Student Reports tab.

**Impact**
This is preventing the teacher from seeing many of her students' results or knowing if they've completed their assignments or not. This is the only report I've seen.

**Screenshots**
See doc

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This seems to be happening to this teacher in conjunction with the bug reported in Issue #4937

**Comment by emilia-friedberg** [comment]
@emmavolk, it looks like Isaiah is listed as "Not Started" for the class that he is no longer in (3rd hour), but it does have his score for the class that he is in (1st Hour English). I think the problem here is the other bug you reported, which I have made a PR for, so when that is deployed it should resolve this confusion as well.

**Comment by emilia-friedberg** [comment]
@emmavolk this looks like it was in fact resolved by that PR so I'm going to close this issue.
