### ISSUE TITLE
Develop a 9 Second Animation 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#497]
We're looking for an animator who can help us animate this page: http://i.imgur.com/C1HSmYo.png 
This gif is a sample of what the first half second would look like: http://i.imgur.com/ZkyaKYG.gif 

Our goal is to show the process of editing a story and seeing the results. If you go to http://www.quill.org, you can proofread a story by clicking on the words to edit them. You can then press check answers to see your results.

We're about to launch 2 new apps, and what we will do is show a 3-4 second clip for each app. The goal is to reveal the main interaction pattern behind each app (e.g. in the proofreading app that main interaction is proofreading a passage and then getting instant feedback).

Our Creative Director, Tom Calabrese, will put together the assets for the animation, and it'd be great if you could help us add the animate these assets. 

We're looking to develop three GIFs that are 3 seconds a piece, similar to what Invision features on their homepage: http://www.invisionapp.com/

The key thing to this job is producing a high quality GIF that is also a relatively low file size. Each of the invision animations are around 800kb, so hopefully we could also make each of the 3 clips clock in around that speed. Is this something you have experience with?

**Comment by petergault** [comment]
Quill Proofreader 

Text: “There ship sank, and 
it’s crew was stuck”

1. Mouse starts in the upper right corner, and it moves left to the word “There”
2. The user clicks on the word there, and the cursor changes from a mouse pointer to the blinking bar. 
3. The user deletes the characters “ereh” (reverse of here”) so that it goes down to just the T, and then it writes out “Their”. 
4. The text changes to bold, and the cursor changes back to an arrow. 
5. The cursor moves to the right, over the text, and then swoops down and to the left (like a U pointing to the right), to click on the word “it’s”
5. The cursor changes to a blinking bar, and the apostrophe is deleted. 
6. The word “it’s” is turned into bold text, the cursor returns to a arrow icon.
7. The pointer moves over to the “check” button (not as a straight line, but it arcs like how a person would move a cursor), and it presses check answer. 
8. The red and green boxes pop up. 

At this point the animation is finished, and it moves on to the next slide. It will probably swipe off to the right, and the next animation will slide in from the left. It will be very similar to mapbox.com, where it dissolves in with a small animation. (For MapBox it animates from the bottom to the top). 

———

Quill Writer 

1. First show the blank screens of the two devices with just the app logo. 
2. Quick fade to the text “Write a story using these words” 
3. Pop up the words Periphery and Canteen
4. Pop up Sarah and Frank 
5. Have the text “Write a story using these words” fade + fade Sarah and Frank) keep the Story Words. 
6. Have the white box pop up and the words typed out “I had my trusty canteen.”
While the text is being written out, on the iPad there are three dots to indicate writing is happening. 
7. As soon as the word canteen is written, have it covert to bold text. 
8. The word “Canteen” on the top will be stricken out, by a line that starts on the left and extends to the right. 
9. The white then will disappear, and the text will be shown on the grey background. At the same time, the words pop up on the tablet as well “I had my trust canteen”. The word canteen is in bold. 
9. The tablet user starts typing the words “Then we were off to the periphery “of the island” 
At the same time, the other screen shows the 3 dots. 
As soon as the word periphery is finished being typed, it should pop into bold. 

As the words “to meet a” are shown, the whole thing then fades out, and the animation is finished. Rather than registering the second student’s sentence, we cut it off as soon as the words “of the island” is typed we fade out.

**Comment by tomcalabrese** [comment]
Quill Proofreader storyboard: https://drive.google.com/file/d/0B1RagCbDewKWNGdVNmtZYkFNV00/view?usp=sharing

Quill Writer storyboard:
https://drive.google.com/file/d/0B1RagCbDewKWaGhTT0tja1Jhb1E/view?usp=sharing

**Comment by petergault** [comment]
1 - Emma
2 - Felipe
3 - Jordan

Frame 1 = 
O X X 
G X X 
G X X

In this frame all 3 scores appear at the same time. 

Frame 2: 
O G X 
G R X 
G O X

In this frame all 3 scores appear at the same time. 

Frame 3:

G G X 
G G X 
G O G

In this frame they appear individually. 
First Jordan’s green appears.
Second Emma’s Orange (top) turns into a green. 
Third Jordan’s Red (middle) turns into a green.

**Comment by tomcalabrese** [comment]
**Quill Teacher Dashboard**

1. Start with a blank grey screen.
2. Fade in artboard 2 (same as done with Quill Proofreader)
3. Mouse starts in the upper right corner, and it moves left over the first checkbox, irregular verbs. Artboard 3.
4. Mouse clicks the checkbox, a check appears, and the box is highlighted white. Artboard 4.
5. Mouse moves down to the last checkbox, Your vs. You're, and checks it the same as the last one.
6. The screen fades to gray for a moment.
7. Then dissolves in artboard 8. 
8. Artboard 9 - 17 are straightfoward in the order we want the colored boxes to appear. The goal of this sequence is to show how a students progress gets updated in realtime so a teacher can monitor their performance. 

Link to files: https://drive.google.com/folderview?id=0B1RagCbDewKWfjBKclU1OXRHbUl1NGQ4WWE5VzNDVVpaZUx3Wnh1ZnpPSC02cnlibGt6ZUk&usp=sharing

**Comment by tomcalabrese** [comment]
**Quill Writer**

1. Start with a blank grey screens. (artboard 1)
2. Words *periphery* and *canteen* appear in both screens. (artboard 2)
3. The message bubbles with *Frank* and *Sarah* appear. (artboard 3)
4. White box with line appears (artboard 4)
5. The message bubble *Frank* disappears. The sentence "I had my trusty canteen" begins to be typed. While it's being typed the tablet has three circles that change order like the example here: https://drive.google.com/file/d/0B1RagCbDewKWVWZ6ZDBTblBkNWc/view?usp=sharing to indicate that the other person is typing. (artboard 5 - 7)
6. White box with line, and typing graphic disappear. (artboard 8)
7. *Canteen* becomes bold. (artboard 9)
8. *Canteen* gets crossed off from left to right in both screens. (artboard 10)
9. The message bubble *Sarah* disappears and the message bubble *Frank* appears. The sentence "I had my trusty canteen" appears on the tablet as well. (artboard 11)
10.  White box with line appears. (artboard 12)
11. The sentence "We traveled to the periphery." begins to be typed. While it's being typed the laptop has three circles that change order like step 5 above. (artboard 13 - 15)
12. White box, line, and the sentence "We traveled to the periphery." disappears. (artboard 16)
13. The sentence "We traveled to the periphery." appears after the previous sentence "I had my trusty canteen." with the word *periphery* now bold. (artboard 17)
14. The word *periphery* gets crossed off in both devices. (artboard 18)

*Note there is not a mouse / cursor in this animation. 

Link to files: https://drive.google.com/folderview?id=0B1RagCbDewKWfmI1ZE5zTEpwaGt5b05fRkdtcW80X1NJSGJ0ZmUwN3VmeDdkTjZTWXZzYXc&usp=sharing

**Comment by petergault** [comment]
Thoughts on writer:
1. We need to show the second sentence on Frank's screen. This is really key for conveying that both students are paired together. 
2. We may want to strip out the blinking cursor, make it less noisy. 
3. Are chosen sentences are somewhat incoherent. Let's see if we can scratch together something better.
