### ISSUE TITLE
Mouseover on completed proofreading activity in student profile should display info for most recent session

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#499]
Steps to reproduce:

- Login as a student
- Complete an activity with a certain score, e.g. 0%, 100%
- Go back to student profile, mouse over that activity session, see that score
- Retry the lesson, complete it with a different score
- Go back to student profile, verify that the older score still displays.

**Comment by kriskelly** [comment]
I haven't been able to verify this on staging bc I can't seem to login as a student.

**Comment by kriskelly** [comment]
Verified on staging (latest version of develop).

**Comment by RyanNovas** [comment]
This is not occurring for me on staging.

**Comment by RyanNovas** [comment]
This issue is occurring on passage proofreading activities, but not sentence writing.
