### ISSUE TITLE
Figuring out the Great Crash of 1/22/15

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#500]
Why did quill-grammar crash on 1/22/15? Likely because of an issue with EC on ProfilesController#show

Details : 

https://docs.google.com/document/d/186NCw-gnZIIJEUZHkjrU9iMHeJ7Vr4SkOkto0Cvtz0w/edit

**Comment by marcellosachs** [comment]
fyi @petergault

**Comment by petergault** [comment]
Ok so we can close this now. The main takeway was that the student profiles were weird. They seem to be better now.
