### ISSUE TITLE
Bug Report: Grammar Activity Questions Wrongly Marked as Incorrect *3 reports*

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#5007]
**Describe the bug**
On some connect activities, students write correct submissions, but Quill gives them the "Check your answer. Look at the hint." message. When students log out and then log back in, it marks their submissions as correct.

**Additional context**
https://docs.google.com/document/d/1aO2sLFTwGGPot-xoOasSDq_aoYYP6fmv6u_ra_belkg/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
@maddymaher these are Connect activities, right? when did these reports come in?

**Comment by emilia-friedberg** [comment]
@emmavolk, @maddymaher do you know if these students are always seeing the "look at the hint" feedback or is it variable?

**Comment by emmavolk** [comment]
@emilia-friedberg I just found a grade report that seems to be related to this bug and updated the doc with screenshots and more info! The student is incorrectly receiving the first focus point feedback despite having entered an optimal response; they then are forced to enter 4 more responses but receive 100% on the question anyway.

(Let me know if this is actually a separate issue and I'll open a new bug report instead.)

**Comment by emilia-friedberg** [comment]
Plan for now: we are going to use the top optimal response that we get from the CMS as the "Correct Response" value, rather than the optimal answer stored on the question object, to hopefully help us solve this bug.

**Comment by emilia-friedberg** [comment]
Implemented the comment above in PR #5055
