### ISSUE TITLE
Lesson Planner JavaScript runs everywhere (not only on lesson planner view)

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#501]
Steps to reproduce:

- Go to staging (staging.quill.org)
- See that you are not on the lesson planner page
- Open up chrome debugger tools and see the following error:
```
Uncaught TypeError: Cannot read property 'length' of undefined
```

This error comes from lesson_planner.js, which currently runs (and errors out) on every page of the app.

**Comment by marcellosachs** [comment]
this has been fixed
