### ISSUE TITLE
Bug Report: Missing Activities on Student Dashboard

### ISSUE THREAD

**Issue by oteroe** [empirical-org/Empirical-Core#5015]
**Describe the bug**
A teacher's students--in all her classes--are unable to access their assigned activities on their dashboard. Nothing except the starter diagnostic appears on students' dashboards, even though the teacher has assigned them other activities.

**Expected behavior**
When replicating the issue, I expected students' activities to show up on their dashboard. However, nothing showed up, just like the teacher said. 

**Impact**
Students are unable to access and complete their assignments, which hinders them and their teachers from using Quill. This is related to bug #3978. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46938401/52655529-5e2c3780-2ec2-11e9-8859-f95c16d6995c.png)
![image](https://user-images.githubusercontent.com/46938401/52655585-78661580-2ec2-11e9-9e5d-2ae096eeb837.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
To be included as new information comes along.

**Comment by oteroe** [comment]
https://docs.google.com/document/d/1wFcYGQVUDV5BPO3wRQpb85Lsbn7qdCGgvzXYCIj-igU/edit

**Comment by emilia-friedberg** [comment]
hi @oteroe, I can't reproduce this. if you try logging into the student whose account is in the Google Doc screenshot, do you still see that they only have one activity assigned.
