### ISSUE TITLE
Bug Report: Diagnostic Recommendations not assigning to 4 students in a class

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#5019]
**Describe the bug**
A teacher was able to assign the Intermediate Diagnostic Recommendations to all students in her class except for 4. The button gets stuck on "assigning..." Their names are in the Google doc. 

**Additional context**
https://docs.google.com/document/d/1S-PXQdx1955FENDULX68HAkH-ImbtMkjkFoQ7YTJvC4/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
@maddymaher closing this issue because the activities have been assigned now.
