### ISSUE TITLE
Bug report: Download login PDF button is displaying the incorrect color

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#5025]
**Describe the bug**
Om the edit students page the "download login PDF" button is displaying black when it should be white.

**To Reproduce**
1. Go to 'quill.org/demo'
2. Click on 'classes'
3. Then click on 'edit students'
4. See the black button

**Expected behavior**
The button should be a white background

**Impact**

**Screenshots**
![screen shot 2019-02-20 at 10 41 10 am](https://user-images.githubusercontent.com/8131465/53109355-b5f02180-3506-11e9-8b80-f65a6a4a960a.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by manangoel99** [comment]
Can I work on this issue?

**Comment by emilia-friedberg** [comment]
@tomcalabrese this was on your laptop? I can't reproduce

**Comment by anathomical** [comment]
Attempted replication on two machines was unsuccessful
