### ISSUE TITLE
Bug Report:  Wrong credentials get accepted for signing up for teacher

### ISSUE THREAD

**Issue by singhrohan62** [empirical-org/Empirical-Core#5040]
**Describe the bug**
If you select sign up option for teacher and you enter incorrect information about you, it gets ignored and your account gets created.

**To Reproduce**
1. Go to 'Sign Up' option on the home page.
2. Click on 'Teacher' option.
3. Instead of using Google or Clever, enter wrong credentials for the user.
4. Account gets created for a fake user.

**Expected behavior**
It should not accept invalid email addresses as in student section.

**Impact**
Multiple fake accounts will lead to increase in number of users leading to storage issues and then adversary can enjoy the benefits of teacher facilities provided to it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Developer Edition
 - Version: 66.0

**Comment by anathomical** [comment]
Escalating this from a bug to a feature request to implement email verification steps to the onboarding process.
