### ISSUE TITLE
Bug Report: Save Changes button not saving in Lessons

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#5045]
**Describe the bug**
When editing a Quill Lesson, the save changes button on the page where you add the title, lesson number, and topic does not save any changes.

**To Reproduce**
1. Go to https://lessons.quill.org/#/admin/classroom-lessons/005b345a-6d54-4bdd-a1f8-dd0517f434cd
2. Update the text in the lesson number box
3. Click the "Save Changes" button
4. Refresh the page--the changes will not have been saved

**Expected behavior**
Clicking "Save Changes" saves any changes made to those fields. 

**Impact**
There are a couple lessons in production that say Lesson 1000 and that have titles that don't match the lesson. 

**Screenshots**
![screen shot 2019-02-28 at 12 55 31 pm](https://user-images.githubusercontent.com/20426718/53587806-5246a380-3b59-11e9-8802-b7ec30315f1a.png)

**Comment by emilia-friedberg** [comment]
@Hannahmonk were you logged in as a staff member?

**Comment by Hannahmonk** [comment]
I was, yes, because I was editing other parts the lesson without any issues. But I just tried it now, and it seems to be fine?

**Comment by emilia-friedberg** [comment]
Hmm. Are you okay with closing this for now then and we can reopen if it recurs? @anathomical is finishing up some updates to Lessons that might impact this so I'm not sure if it's worth investigating further right now.
