### ISSUE TITLE
Bug Report: Connect Activity marking correct responses as incorrect

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#5067]
**Describe the bug**
Comparative and superlative adjectives: more vs most connect activity are marking the correct responses to the “I thought the book was more exciting than the movie” question as incorrect. This happens to every student in the teacher's class.

The students use Safari and iPad, and I could not replicate it, so I’m wondering if it has to do with the browser/ device compatibility.

**Additional context**
https://docs.google.com/document/d/1vML5ZiBWSufIckel7Tz4FXhP5_IytvP2Wzs-v2JuryQ/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
This turned out to not be a bug - the student in question had typed lowercase "L"s rather than capital "I"s in their responses. discussed the possibility of using a font that more clearly differentiates between the two with @tomcalabrese.
