### ISSUE TITLE
Bug report: Teacher cannot add a student to pre-existing assignments

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#5068]
**Describe the bug**
None of this teacher's assigned activities will assign one of her students. When I try to edit the assignments to add him, the Activity Packs Editor will not let me. see bug report google doc for videos.

I can, however, create a new activity and assign it to him. 

**Additional context**
https://docs.google.com/document/d/1YiaxMJZcPLw76X36Gto0QPC05258Rnw3Kxxukh6G1Ds/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
Hey @maddymaher, I can fix the data here but I'm not sure how this problem came about. can you find out when this student joined the class? was it after when this pack got assigned initially?

**Comment by maddymaher** [comment]
@emilia-friedberg will do!

**Comment by maddymaher** [comment]
@emilia-friedberg the teacher got back to me! She said that some students forgot log-in credentials and created new accounts before she was able to reset their first accounts. She wasn't sure if this happened to the student in question here, but we do have two accounts under that student's name in our system.  None of her other students, however, experienced this issue.
