### ISSUE TITLE
Bug report: Grammar activity not loading for one student

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#5077]
**Describe the bug**
The grammar activity Activity “Recognize Inappropriate Shifts in Pronoun Number or Gender” is not loading on this student's account. Other Grammar activities will load without issue. I successfully replicated the issue, and there are screenshots in the google doc.

https://docs.google.com/document/d/19VDRZl-Dlm3IcQoMpbkI3743DzVVSp5ZO88jtKQfmW8/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
@maddymaher, this was one of the archived activities, which I believe is why it wasn't loading and now is not showing up on her dash. closing this issue since the problem should be remedied by hiding archived activities!
