### ISSUE TITLE
Teacher Center 500 Bug

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#5088]
**Describe the bug**

All teacher center pages return a 500 error. 
e.g. https://www.quill.org/teacher-center/topic/getting-started

**To Reproduce**
1. Go to: https://www.quill.org/teacher-center/topic/getting-started

**Impact**
Provide as much context as you can to explain the bug's affect on Quill. E.g. number of people affected, whether it causes a site-wide error, whether there is a workaround, if this relates to another bug, when you think the bug was introduced. 

100% of teacher center pages return a 500 error. 

As a follow up project, is there something that is causing the 500 error where we could make Quill fail gracefully if that error happens again?

**Comment by emilia-friedberg** [comment]
fixed by #5087
