### ISSUE TITLE
Only teachers should be able to create a unit

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#510]
Creating a new unit via the lesson planner eventually calls Teachers::UnitsController#create, which does not have authorization or teacher verification checks in it. These can be seen in other controllers containing the following code:

```
  before_filter :teacher!
  before_filter :authorize!
```

Not putting these checks in the controller(s) could potentially allow a student or non-user to create a unit.

**Comment by marcellosachs** [comment]
fixed via pull request #633
