### ISSUE TITLE
Suggested answer displaying '</span>'

### ISSUE THREAD

**Issue by Wakeful-Cloud** [empirical-org/Empirical-Core#5111]
**Describe the bug**
`<span>` element as possible/suggested answer.

**To Reproduce**
Only happened once, so I have no clue what caused it.

**Expected behavior**
Actual sentences being displayed in place of a `</span>` closing tag.

**Impact**
Prevents users from seeing other accepted answers.

**Screenshots**
[https://ibb.co/dfpQzX9](https://ibb.co/dfpQzX9)

**Info**
 - OS: Windows 10.0.17134
 - Browser: Chrome 72.0.3626.121
 - Version: unknown

**Comment by emilia-friedberg** [comment]
Hi @Wakeful-Cloud, I can't see this screenshot, could you attach it directly to the issue?

**Comment by Wakeful-Cloud** [comment]
Sorry

**Comment by Wakeful-Cloud** [comment]
![Quill Error](https://user-images.githubusercontent.com/38930607/54718106-0020ee80-4b17-11e9-88b7-5808ca973466.png)

**Comment by emilia-friedberg** [comment]
@Wakeful-Cloud thanks!

**Comment by emilia-friedberg** [comment]
Fixed by manually deleting blank responses from CMS database, and adding code to make sure that we no longer save blank responses to the database in #5151
