### ISSUE TITLE
500 error on Add New Activity page on Master CMS

### ISSUE THREAD

**Issue by emmavolk** [empirical-org/Empirical-Core#5114]
**Describe the bug**
The page to add a new activity (Rails Admin - Master CMS > Activities > Add New) is returning a 500 error (see screenshot below).

**To Reproduce**
1. Go to https://www.quill.org/staff/activity/new
2. See error

**Expected behavior**
Clicking Add New takes you to a page to add a new activity

**Impact**
This is preventing the content team from putting new activities into production.

**Screenshots**
![Screen Shot 2019-03-21 at 2 10 22 PM](https://user-images.githubusercontent.com/43547787/54774604-86563700-4be2-11e9-9b2b-9a09d91e74a9.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**

**Comment by emilia-friedberg** [comment]
Workaround for now: go to the Activities Editor under "Activity Management System" on the main staff page, click "activities" in the row for the activity classification you want to add an activity to, and then scroll down to "Add a new activity" on the list of activities page that appears.

**Comment by emilia-friedberg** [comment]
This 500 is no longer appearing, so it is probably a result of too much traffic on the website.

**Comment by emilia-friedberg** [comment]
@emmavolk, I think this was a result of the memory overload yesterday, so I'm going to close this issue. If the problem reoccurs we can reopen it.
