### ISSUE TITLE
Sign Up — Login — Password Pages

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#514]
1. Need to select teacher, student or contributor. 
http://community.quill.org/signup/
Based on this:  https://newsela.com/signup/#/user_type/

If you click contributor, you go to the wordpress sign up. http://community.quill.org/signup/cla/

If you are a student or teacher, you go to the student and teacher sign up page. Let's keep all of the details as they are now. 

2. from the sign up, tell people they can also sign in and vice versa.

**Comment by tomcalabrese** [comment]
# Mockups

* [Login](https://drive.google.com/folderview?id=0B1RagCbDewKWfjBmcUxzcVdwZ3hTeTc2N0FCd1c5cDdEaUR4RmZTYi1qdWV6VHRXSHN1NFE&usp=sharing) Page
* [Sign Up](https://drive.google.com/folderview?id=0B1RagCbDewKWfm9fWVhiMVQwVk1JM3FTeWtWTlpkUXFqQ3pybXVad0lqNDM4by1aNHhTOW8&usp=sharing) Pages.
* [Password Reset](https://drive.google.com/folderview?id=0B1RagCbDewKWfjFqVjR2dUc3ZEc2ZzVQQkxUa1pRSDdYb05hQ0lObWxUVWpxN2ZxMjI0WDA&usp=sharing) & [Password Set](https://drive.google.com/folderview?id=0B1RagCbDewKWfmlMYjVGLWFZQWVFLVRhVmZoS0ZkeFFMOTlCWTZqTW43NGpmQ0dEVlBCV1U&usp=sharing) Pages. 

## Problems
Currently students can't reset passwords themselves, which results in teachers or us reseting them. 

__Solution:__

* Have students fill out security questions, which they can use to reset their password. We'd have to have to have all students without email addresses do this. Is there a better way?

Currently when a student signs up they are welcomed to [this screen](http://imgur.com/B3JI97W). Which asks them to enter their class code.

__Solution:__

* We can avoid redesigning this page if we add class code into the student sign up page, like this [mockup shows](https://drive.google.com/open?id=0B1RagCbDewKWWDFObmlrUUZReG8&authuser=0).

**Comment by petergault** [comment]
https://dev.clever.com/sso/log-in-with-clever

We should work Clever into the sign in and sign up fields. We could include copy such as "Skip passwords using Clever. Free for schools."
