### ISSUE TITLE
Padding Issue with Blog Pages 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#5152]
**Describe the bug**
On the pages that use the "cards" there is a bug impacting the padding. 

https://www.quill.org/teacher-center/topic/teacher-stories
https://www.quill.org/announcements
https://www.quill.org/press

**Comment by emilia-friedberg** [comment]
Hey @petergault, I'm not actually seeing this on my laptop, what device were you using?

**Comment by dandrabik** [comment]
I'm seeing this issues as well on any page that uses a "card" for a blog post, press release. Latest Chrome, Mac Mojave. Screens below.

![Screen Shot 2019-04-09 at 11 38 36 AM](https://user-images.githubusercontent.com/1304933/55815057-b2682800-5abd-11e9-9122-084185e3cf0a.png)

![Screen Shot 2019-04-09 at 11 51 30 AM](https://user-images.githubusercontent.com/1304933/55815143-d7f53180-5abd-11e9-9278-40a804ec4eb1.png)
