### ISSUE TITLE
Connect Activity Not Counting Answer as Correct

### ISSUE THREAD

**Issue by oteroe** [empirical-org/Empirical-Core#5171]
**Describe the bug**
When typing the correct response for the first question in the activity, the response is counted as incorrect and will not allow the student to move on until selecting the correct response in multiple choice.

**To Reproduce**
1. Search for the "Parallel Structure (Advanced)" activity in the "Explore All Activities" section on the website.
2. Click on "Parallel Structure (Advanced)" to play through the activity.
3. Attempt to answer the question correctly. The program will not count your answer as correct, even when it is.

**Expected behavior**
I expected to be able to move on after typing in the correct response for the first question, but I was unable to because the response kept being counted as incorrect.

**Impact**
This affects all Quill students. The only way to move on to the next question is to keep attempting to respond correctly until the program allows you to select the correct answer in multiple choice. 

**Screenshots**
See attachment.

**Desktop (please complete the following information):**
 - OS: PC
 - Browser: Chrome
 - Version: 73.0.3683.86

**Additional context**
https://docs.google.com/document/d/1hTeLAVObOAPumDf42H8R4faQf3K6t3lAKETz_qexONE/edit

**Comment by emilia-friedberg** [comment]
@oteroe, this isn't happening to me. are you sure the response you submitted is one of the correct ones? it may be something to refer to the content team.

**Comment by emilia-friedberg** [comment]
@oteroe There are errors in both of the answers pictured in the Google doc: in the first case, the student wrote "1987", which is being picked up as a spelling error, and in the second the student is using a comma to separate the second clause, but it is not independent and therefore should not have a comma, hence the punctuation hint. You can see in the final screenshot that it is not one of the correct answers to the question.

**Comment by emilia-friedberg** [comment]
closing this issue because there doesn't appear to be a bug or a grading issue.
