### ISSUE TITLE
Update all Brand Assets Via Brand Touchpoints

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#518]
This doc outlines most of the places where we have a public internet presence. Let's try to update all of these pages with the proper assets + copy for each one. 

A great starting point is the email newsletter, which is a key item once we start doing weekly emails + transactional emails via intercom. 

https://docs.google.com/a/quill.org/document/d/11OfkBGE04dLT_uk1TDZsU3vuE813f3H1pFgJM3sSbXk/edit

Tom can put together the files in the right resolutions, and Ryan can help with tracking down all of the different dimensions we need + getting in contact with the people who can swap some of these things we don't control.

**Comment by RyanNovas** [comment]
@tomcalabrese said he did all this
