### ISSUE TITLE
Require teachers to add a name to a classroom

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#528]
Right now teachers can create classrooms for their students without a name. We should require a name to create a classroom. The alert can state: "Please enter a name for your classroom."

**Comment by alcastaneda** [comment]
@s12dsow and I can fix this issue

**Comment by petergault** [comment]
Awesome, thanks for the help!

**Comment by petergault** [comment]
We'll review the pull request shortly.

**Comment by RyanNovas** [comment]
@alcastaneda @s12dsow, great job, thank you!
