### ISSUE TITLE
Cache the Tooltip pages

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#529]
Right now the tooltip is the most time-intensive component of the site. We should look into how we can cache these tooltips. We may want to bring James on board for help with this. 

Sign into Heroku and then click here to load this page. 

https://rpm.newrelic.com/accounts/770600/applications/3825541/transactions#id=589467029&sort_by=slowest

**Comment by marcellosachs** [comment]
ok im taking out the concept_tag_results section for now as a short term solution, this will reduce expense; in the meantime looking into caching solution
