### ISSUE TITLE
Issues with SideKiq worker

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#530]
It seems we are getting a large number of errors through sidekiq. It is creating the student accounts as a background job. 

See here: 
https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors
https://addons-sso.heroku.com/apps/empirical-grammar/addons/sentry

**Comment by marcellosachs** [comment]
ok im taking out the concept_tag_results section for now as a short term solution, this will reduce expense; in the meantime looking into caching solution

**Comment by petergault** [comment]
Fixed by upgrading mailgun
