### ISSUE TITLE
Create My Units Page - Allowing Deletion of Units

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#533]
We received a lot of feedback from teachers who wanted to delete a unit / activity. Either because it was finished, or because they accidentally created a unit / activity. 

This page will be located before the 'create new unit' in the subnav of 'activity planner' 

The calendar and 'x' elements can be found in the 'create new activity' page, while the other elements of the page mimic the student dashboard. 

'Create New Unit' button on the top right is just to draw attention again to the ability to create a unit, it will take them to that page. 

When a user clicks 'x' or 'delete unit, a pop-up box will appear for user's confirmation. Similarly to the class manager page when a user also clicks 'delete'. 

![quill_website_activity_planner_my_units](https://cloud.githubusercontent.com/assets/8131465/6120591/d52c337a-b0a5-11e4-99af-c36f566e3747.png)
![screen shot 2015-02-09 at 9 43 15 pm](https://cloud.githubusercontent.com/assets/8131465/6120592/d52df340-b0a5-11e4-972c-3fa18b5faea2.png)

**Comment by petergault** [comment]
This is live! Thanks @marcellosachs for awesome turn around on a key feature
