### ISSUE TITLE
Final updates to Quill v2 Launch. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#549]
# Updates to the Terms Page
- [x] Ensure this new page is live on production and is properly formatted. 
https://github.com/empirical-org/Empirical-Core/blob/develop/app/views/pages/tos.html.slim

# Update to the Discover Page
- [x] On the discover page, where it links to Meet the Team, FAQ, etc. there should be a link called "news" which loads http://news.quill.org

# Updates to the Impact Page 
- [x] The impact page needs to have a slightly different background to match the geckboard color  - #F0F0F0. The background color should only be changed for this one page. 

# Login Page 
- [x] Update the Login page to have adelle sans font. 
- [x] Remove the white box around sign in. The page should be uniformly grey. 
- [x] Change the sign in button to #FC3E3B. 

# Sign Up Page
- [x] Change the font to adelle sans. 
- [x] Change the sign up button to this color. #FC3E3B
- [x] Remove the white box around the sign up. 
- [x] Remove the bold text around the check boxes at the bottom of the screen. 
- [x] Fix the zip code enter. When you enter a zip code, the box displays in the upper left corner of the screen, rather than next to the box. 

# Updates to the old Bootstrap 2.0 Page 

**We are still using a number of pages that are on bootstrap 2.0, from the old design. Peter has been a made bunch of edits to the colors on these pages so that they mimic the new colors. Overtime these old pages will all be deprecated by new ones. 

For now, the goal is to make sure each of these changes were implemented. A good test case for this page is here: 

http://www.quill.org/activities/1?anonymous=true

- [x] the header should be our green color. (see peter’s pull request)
- [x] the links should be removed except for community and discover.  (see peter’s pull request)
- [x] the header logo should be updated (see peter’s commit a1d307f) 
- [x] the background color of the page should change from blue to grey. (see peter’s pull request)

# Update to teacher scorebook 

The teacher scorebook’s header should reflect the the other headers. To do so, the following needs to happen.

- [x] the header logo has been swapped so that it should be the new logo.  (see peter’s commit)
- [x] the links should be stripped down to Discover, Community and Support if a teacher is signed in. (See peter’s pull request for this). 
- [x] the color’s need to match the discover pages. There are two ways of doing this: 

**1. Use the header used on the rest of the site (i.e. the discover pages). Since these pages are both Bootstrap 3.2., maybe all you need to do is tell the scorebook pages to utilize that header and footer.**

2. Make the following edits: 
1. The color of the header needs to be changed to Quill Green: 
2. The color behind the tabs needs to change to green. 
3. The tab that is selected needs to turn to dark green. 

![updates-to-scorebook](https://cloud.githubusercontent.com/assets/3667179/6201506/94771162-b47c-11e4-943c-077a9be318c7.png)

# Review Branches and Pull Requests
- [x] Make a sweep of the branches and pull requests to see which ones can be easily merged in. Ignore any branch or pull request that will take a bit of digging into to review.

**Comment by petergault** [comment]
Final updates to the page:

# Sign in Page 
- [ ] Change the sign in button to the green quill color. 
- [ ] Change the text color of sign in to white. 
- [ ] Remove the black background around the sign in button or change it to green. 

# Sign up Page 
- [ ] Change the sign up button to green

# Header / Footer Issues 
- [ ] The header for when you are signed does not allow the user to click on the Quill logo. 
- [ ]In the header there should be a button called “Profile” that is in a rounded rectangle (similar to sign up button). It is to the left of Logout and to the right of 
- [ ] The footer for when you are signed in is missing the social media links.

**Comment by kriskelly** [comment]
This seems to be functioning already on staging: "The header for when you are signed does not allow the user to click on the Quill logo." What page are you viewing where the header isn't clickable?

**Comment by kriskelly** [comment]
@petergault: For "In the header there should be a button called “Profile” that is in a rounded rectangle (similar to sign up button). It is to the left of Logout and to the right of" Do you mean that the header for students should have a "profile" button? Since there is no profile for teachers.

**Comment by kriskelly** [comment]
@petergault: "The footer for when you are signed in is missing the social media links." This also seems to be functioning on staging. Please check again and let me know if it's still not displaying for you.

**Comment by petergault** [comment]
@kriskelly here is an example of where the logo is not clickable and the social media does not work:
http://staging.quill.org/session/new

@kriskelly This should only exist for teachers. It should state profile, but the page it is going to is scorebook. Student should not have a header. Thanks!

**Comment by kriskelly** [comment]
@petergault: Everything is done except "The header for when you are signed does not allow the user to click on the Quill logo.". This affects a subset of views (only older pages that haven't been switched away from the old stylesheets) and the fix is a bit involved, so I think maybe hold off for now?

**Comment by petergault** [comment]
Okay yeah let's avoid this for now then, it isn't that important.

**Comment by petergault** [comment]
Awesome, the new homepage is live!
