### ISSUE TITLE
Date Picker Bug in Firefox

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#554]
On FireFox the dates are shown like this: 
![screen shot 2015-02-14 at 8 29 59 pm](https://cloud.githubusercontent.com/assets/3667179/6201732/7c09d464-b488-11e4-9bc0-84d2ddaae264.png)

**Comment by thatkaiguy** [comment]
Hello! I'm looking to contribute but have a question. Is there a way to import dummy data for the app (activities, classes, etc.)? I've just successfully installed Empirical Core thus far.

**Comment by petergault** [comment]
@thatkaiguy Hey, thanks for checking this out. Please let me know if you'd like to continue looking at this. You can reach me at peter ( at ) quill ( dot ) org or find us on Slack. 

Teachers are reporting a general set of issues with Firefox. It may be something related to Firefox and Bootstrap 3.2. 

Here is a screenshot from a teacher using Vista + Firefox. 

![quill 20screen 20shot 20- 20using 20mozilla](https://cloud.githubusercontent.com/assets/3667179/6471654/ee6d7698-c1ba-11e4-8343-4efae2797322.jpg)

**Comment by bobmazanec** [comment]
I see something like the first screenshot in Firefox 35.0.1
I'll take a swing at it

**Comment by bobmazanec** [comment]
Looking at `/teachers/classrooms/lesson_planner`, the date-string element in the picker is

```html
<input type="text" class="railsFormatDate" id="railsFormatDate1" data-reactid=".0.1.0.1.0.2.0.2.1">
```

presumably from `EC.ActivityDueDate` in `app/assets/javascripts/scorebook/lesson_planner/create_unit/activity_due_date.jsx`

Safari 8.0.3 (10600.3.18) shows the content size as 'NaN x NaN'
Firefox 35.0.1: '-26 x -20'

Looks odd to me, but CSS isn't my strong suit.

All of the examples on http://www.eyecon.ro/bootstrap-datepicker/ look OK in Firefox...but most/all have computed size '126 x 20'

I'll keep digging & learning, but if that's enough of a clue for anyone else, don't be shy!

**Comment by bobmazanec** [comment]
Interestingly (annoyingly?), Firefox puts the calendar icon on the left &mdash; partially obscuring the date string, where Safari & Chrome put it (correctly?) on the right.
