### ISSUE TITLE
Ultra MVP for Progress Reports

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#555]
The ultra MVP for the keen report is to show a listing of each completed activity session, filtered by student. 

Here is what the page should look like: 
https://moqups.com/gault8121/6RLG73bg/p:afe9294a1

Here are the notes on each of the fields: 
https://moqups.com/#!/edit/gault8121/6RLG73bg

The table, sort buttons, and pagination should be reused from the Activity Planner. The drop down menus should be re-used from the scorebook page.

**Comment by RyanNovas** [comment]
Issues I've noticed:

- [ ] standards not showing
- [ ] time spent being reported in multiple ways -- for activities: as blank. as a dash, and as minutes -- for CCSS numbers that equal unknown units.
- [ ] same activity being reported multiple times (maybe we want this, for retries, but then we should show which one is most recent at a level beyond date completed, i.e. time completed or retry #)
- [ ] when standards are looked at at the grade level, the numbers are shown on the headers row as well as in the columns.
![screenshot 2015-02-25 at 11 30 27 am](https://cloud.githubusercontent.com/assets/6655439/6374909/dae7b0ee-bce1-11e4-83a7-0565c06cab58.png)

**Comment by RyanNovas** [comment]
- [ ] units listed in non-alphabetical order
![screenshot 2015-02-25 at 12 06 55 pm](https://cloud.githubusercontent.com/assets/6655439/6375718/e3fb0c8a-bce6-11e4-8272-19a0a3caa793.png)
- [ ]  students listed in non-alphabetical order on some views, alphabetical in others.

**Comment by petergault** [comment]
@kriskelly are Ryan's edits fixed?

**Comment by kriskelly** [comment]
@petergault Yes, this should be done now. Also pretty sure units are ordered first by creation date, then alphabetically by name. Just wanted to check to make sure this is the desired behavior.
