### ISSUE TITLE
Duplicate Assignments Posting to Units in Student Accounts

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#556]
I am receiving reports of duplicate assignments when students view their units, but they are not visible when teachers view assigned units from the teacher account. I have no been able to replicate this. Screenshots below.

![screen shot 2015-02-17 at 10 57 39 am](https://cloud.githubusercontent.com/assets/6655439/6238171/f384e7fa-b6c6-11e4-9032-3073c100c851.png)

![screen shot 2015-02-17 at 10 57 46 am](https://cloud.githubusercontent.com/assets/6655439/6238174/f609fa9c-b6c6-11e4-9ad3-42e0b631d556.png)

**Comment by RyanNovas** [comment]
I have not seen this on the student side, but on the teacher scorebook side there was just a duplicate lesson that popped up in the scorebook on staging. Teacher test12345 with student test12 for the Apple's Apple's story.

**Comment by marcellosachs** [comment]
@ryannovas I fixed the bug that was causing this for apples to apples (once again, a case of not filtering out interrupted retries). The fix is now on staging.

**Comment by marcellosachs** [comment]
@RyanNovas going to look into if anything might be causing similar bugs on student side...

**Comment by marcellosachs** [comment]
@RyanNovas do you know any of the user names that were reporting this?
