### ISSUE TITLE
Alert message for teachers in activity planner. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#559]
On the activity planner page there is a button called continue that pops up once a user inputs a name into the unit. We need a message that states "Please enter a name to continue."
This message should be displayed to users at the bottom of the page until a user inputs a name.

**Comment by aliciasedlock** [comment]
Submitted a pull request for this issue.

**Comment by petergault** [comment]
Confirm this is done Marcello?
