### ISSUE TITLE
Wireframe needed - On the user planner page we show how many activities completed per student

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#560]
How many activities each student account has completed. This way when students create multiple accounts they can delete the accounts with no progress.

**Comment by petergault** [comment]
http://www.quill.org/teachers/classrooms/565/students

**Comment by marcellosachs** [comment]
@RyanNovas @petergault implemented as of c4769babd63ed800003a1e0a4bbb9f9d073a96e6
will be on forthcoming staging deploy
