### ISSUE TITLE
Display classes that units were assigned to

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#561]
Teachers can't tell which classes received which assignments. Wireframe below:

![list assigned classes](https://cloud.githubusercontent.com/assets/6655439/6273014/0d19bfa0-b83a-11e4-86c1-e02d542f098a.png)

**Comment by marcellosachs** [comment]
@RyanNovas fixed as of 59674ed160901cc04a471e6585c6e5cd1cfa97a0, should be on forthcoming staging deploy...
