### ISSUE TITLE
New Relic Security Alert

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#570]
This is an important message related to the status of your account:

Dear valued customer,

As part of a security update, New Relic has deprecated a feature that allows server side configuration of HTTP parameters. For customers who want to utilize this feature and send HTTP parameters to New Relic, you will need to enable it in the agent configuration file.  Effective today, all server-side configuration for capturing parameters has been removed.

For assistance on how to do this, please visit our documentation:

Python : https://docs.newrelic.com/docs/agents/python-agent/troubleshooting/emulating-legacy-server-side-parameter-configuration-python

Ruby : https://docs.newrelic.com/docs/agents/ruby-agent/troubleshooting/emulating-legacy-server-side-parameter-configuration-ruby

Node : https://docs.newrelic.com/docs/agents/nodejs-agent/troubleshooting/emulating-legacy-server-side-parameter-configuration-nodejs

If you have questions, please contact New Relic Support.   

Regards,
New Relic Technical Support

**Comment by kriskelly** [comment]
Based on how we're using the New Relic monitoring, I don't think this affects the LMS. Closing
