### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#573]
We could benefit from some unit tests (rspec) for the functionality pertaining to the teacher UI (on the develop branch).

Some parts of the teacher UI that could use tests in particular : 

### the activity planner ("My Units" and "Create a Unit").
  1. Are validations enforced on the creation or update of new units ? 
  2. Do the activities presented in "Create a Unit" as search results accurately reflect the search?
  3. Does assignment to particular students work?

### the scorebook 
  1. Do the newly implemented caches on methods in app/models/concerns/student.rb and on app/views/teachers/classroom_manager/scorebook.html.erb work ?
  2. Does the scorebook always present the desired information ? 
  3. Do all of the methods in student.rb work as desired ? (Not all of them have unit tests)

**Comment by bobmazanec** [comment]
FWIW, I'm headed (at least partially) in that direction:
* PR #566 adds sign-up & sign-in feature specs & infrastructure
* I've been working on Teacher - Class Manager - Create Class feature specs & infrastructure (PR soon?)
* I was planning on feature specs on/for the other Class Manager 'sub-tabs'

If someone else jumps into the specs you're describing, maybe/hopefully the framework/infrastructure I've been adding could give them a boost and inspire further investment...

**Comment by RyanNovas** [comment]
@marcellosachs do we still need tests for these or should this be closed?

**Comment by petergault** [comment]
1. Fix spec requests that are broken with MixPanel by using VCR (at /spec/requests/)

2. Add controller tests for the most-used controllers, like:
 * cms/activities_controller
 * cms/activity_classifications_controller
 * teachers/classroom_activities_controller
 * teachers/classom_manager_controller
 * teachers/classrooms_controller
 * teachers/students_controller
 * teachers/units_controller

3. Add in more request specs and fix up the examples that are already there to use FactoryGirl (at /spec/requests/)

4. Adding in some caching in controller requests might be easy and fast depending on their experience level
