### ISSUE TITLE
Better seed for development and staging

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#574]
Our seed file lacks certain data. The goal is expand the seed file to include all of the data the database needs. 

Here is a doc with the desired changes : 
https://docs.google.com/document/d/15wuteXhuJc5ja8Ho56sUuRIzaSO69GuXWzM110_ZTGY/edit

**Comment by jstrocel** [comment]
Do you want to keep using the sql scripts you have in place, or do you want to start relying more on FactoryGirl?

**Comment by petergault** [comment]
@marcellosachs thoughts on this?

**Comment by petergault** [comment]
We should look at which elements we can strip out (such as the AWS gem, which isn't needed),
