### ISSUE TITLE
Create Calls to Action on Progress Reports and Landing Page for Quill Premium

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#578]
Before we push the progress report trial live, we need to build a customer acquisition channel. 

This requires a few things:
1. In app-notification that the teacher is receiving temporary complementary access to a paid product. (This could be done via a popup, on page banner, or intercom message.)
2. In app call to action to learn more that directs them to a landing page
3. A landing page that details the full features of Quill Premium
4. A button on the landing page to get a quote/phone call/whatever brings them into direct contact with a person (ideally Collin) who can close the deal.
5. A 1 page PDF with all the info for people to print, give to their administration, etc....

**Comment by petergault** [comment]
https://moqups.com/#!/edit/gault8121/6RLG73bg

Here is a wireframe of some of these issues. @RyanNovas and  @tomcalabrese will look at this with Peter on Friday.
