### ISSUE TITLE
Classroom menu inconsistencies (nits?)

### ISSUE THREAD

**Issue by bobmazanec** [empirical-org/Empirical-Core#580]
Both the Teachers' "Manage Classes - Invite Students" and "Scorebook - Student View" pages include a menu of Classes/Classrooms.

1. both appear to be sorted by creation order; alphabetic would be more intuitive?
2. they appear & work slightly differently &mdash; given _N_ classes/classrooms, ...
 * the invitation page's menu lists all of the choices below the current selection, giving _N_ choices
 * the scorebook's menu doesn't repeat the current selection, giving _N - 1_ choices

**Comment by RyanNovas** [comment]
Good catch.

Classes should be in alphabetical orders and the current selection should
be repeated in the menus.

On Fri, Feb 27, 2015 at 11:50 AM, Bob Mazanec <notifications@github.com>
wrote:

> Both the Teachers' "Manage Classes - Invite Students" and "Scorebook -
> Student View" pages include a menu of Classes/Classrooms.
>
>    1. both appear to be sorted by creation order; alphabetic would be
>    more intuitive?
>    2. they appear & work slightly differently — given *N*
>    classes/classrooms, ...
>       - the invitation page's menu lists all of the choices below the
>       current selection, giving *N* choices
>       - the scorebook's menu doesn't repeat the current selection, giving *N
>       - 1* choices
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/580>.
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>

**Comment by bobmazanec** [comment]
FWIW, PR #566 has a `pending` example for the sort order

**Comment by marcellosachs** [comment]
fixed as of bob's contributions...thanks bob!
