### ISSUE TITLE
Inconsistent Class Manager tab navigation

### ISSUE THREAD

**Issue by bobmazanec** [empirical-org/Empirical-Core#581]
When a Teacher has no Classes/Classrooms, ...
* 'Class Manager' offers only the 'Create a Class' button/sub-tab ('Manage Classes' & 'Invite Students' appear when the Teacher has >= 1 Class/Classroom)
* clicking either the Scorebook or 'Activity Planner' tab navigates to 'Create Your Class'
* clicking 'Class Manager,' however, navigates to the 'Manage Classes' page, even though its button/sub-tab isn't visible

**Comment by bobmazanec** [comment]
FWIW, PR #566 has an example for the current behavior

**Comment by RyanNovas** [comment]
Nice catch @bobmazanec

**Comment by marcellosachs** [comment]
fixed as of  ee87d1bd2909a9028d0b35c0d9640e938c2d6a49
