### ISSUE TITLE
Arrange students by last name

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#584]
Can we set it up so that students are arranged by the first character of their last name? Since we don't ask students to input both a first and last name, some may not have both. @bobmazanec

**Comment by bobmazanec** [comment]
So if these students were in a Class, we'd see them as...

* Christopher Brown
* Chris
* Christine
* Christopher Robin
* Alex Smith

in every view of that Class when sorted by 'name'?

**Comment by petergault** [comment]
Hi Bob. 

This is a good question. @tomcalabrese do you have an opinion on this? We could, for example, show all of the students without last names either before or after the students with them.

**Comment by bobmazanec** [comment]
On the "we don't ask students to input both a first and last name" front...I just "signed up" this student on my local instance (696dbea):
- First name: `Arnold`
- Last name: `<blank>`
- User name: `horshack`

and joined a class.

Logged in as its Teacher, I see

First name | Last name | Username
-------------- | -------------- | --------------
Arnold | Arnold | horshack

Expected?
Related but separate issue?

**Comment by tomcalabrese** [comment]
I think if we're able to start having students input their first and last name that we should require it, and then sort by last name first. But if we can't do that, then we should probably do first name, to keep them consistent. 

Was it a privacy/tos reason why we didn't require last names?

**Comment by RyanNovas** [comment]
This is expected, but I don't see a reason not to require the last name (in fact, we already do when a teacher creates a student account from within their classroom). Let's just make it mandatory for when students/teachers sign up themselves.

**Comment by bobmazanec** [comment]
In case it helps/matters, the User model has had the "infer last name" behavior since its introduction in 6371a8d2

**Comment by petergault** [comment]
@bobmazanec okay so for now let's sort by first character of last name, and students that do not have a last name will just be duplicated. @marcellosachs is going to create the new sign up page next week, so he can add the first and last name field when he creates that update.

**Comment by bobmazanec** [comment]
So my my example (test case) becomes...

First name | Last name
-------------- | --------------
Christopher | Brown
Chris | Chris
Christine | Christine
Christopher | Robin
Alex | Smith

in every view of that Class when sorted by 'name'?

**Comment by petergault** [comment]
Yep that's it. We can make it though so that we only show the first name to the teacher?

**Comment by bobmazanec** [comment]
Still learning my way around the pages & views...I see several `.../teacher/...` views which list a class(room)'s students...any examples of student views which show other students' names?

**Comment by bobmazanec** [comment]
Deleted my last comment as it was the wrong question.

@petergault - you'd want to omit the last name

So my my example (test case) becomes...

First name | User name
-------------- | --------------
Christopher | cbrown
Chris | christine
Christine | christine@word-pair
Christopher | christopher
Alex | cooldude75@goohoo.com

in every view of that Class when sorted by 'name'?

**Comment by bobmazanec** [comment]
After consultation w/ @petergault, I understand now it should be...

First name | Last name | User name
-------------- | -------------- | ---
Christopher | Brown | cbrown
Chris | Chris | christine
Christine | Christine | christine@word-pair
Christopher | Christopher | christopher
Alex | Smith | alexsmith@word-pair

On the Invite Students page; same order but w/out the 'User name' column on the scorebook

**Comment by bobmazanec** [comment]
I've found and touched these so far:

Tab | Sub-tab | `path`
--- | ------- | ----
Class Manager | Invite Students | `teachers/classrooms/:id/invite_students`
Class Manager | Manage Classes | `teachers/classrooms/:id/students`
Scorebook | Student View | `teachers/classrooms/:id/scorebook`

I'm still getting familiar with the Teacher workflows; @petergault: have I missed any here?

**Comment by petergault** [comment]
Awesome! 

@bobmazanec There is possibly one more page. In the "activity planner" on the second page is a drop down where all of the students are listed. You can see this by going to quill.org, signing in with "Teacher" and pw "Demo", clicking on activity planner, adding in some details, and going to the second page, where you select students.

**Comment by bobmazanec** [comment]
Tunnel vision!
I expect this should really be 'sort by last, then first name' &mdash; _e.g._

First name | Last name | User name
-------------- | -------------- | ---
Alex | Brown | alexbrown
Christine | Brown | christinebrown@word-pair
Christopher | Brown | cbrown
Chris | Chris | christine
Christine | Christine | christine@word-pair
Christopher | Christopher | christopher
Alex | Smith | alexsmith@word-pair

(with/out the **User name** column as appropriate for the page)

Updated PR soon...
