### ISSUE TITLE
Bug - Next Activity broken when no more activities are available 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#585]
When students complete all of their activities they see their first activity session within the "start my next activity" portion of the student scorebook. 

Instead, we should show nothing to them. What happens when this section is blank.

In the screenshot below you can see that the first student see's the Oedipus activity as the next activity when it is actually completed. 

![screenshot 202015-03-03 20at 202 11 57 20pm](https://cloud.githubusercontent.com/assets/3667179/6471334/f122bce8-c1b7-11e4-97a6-30a7f41a6986.png)
![screenshot 202015-03-03 20at 202 12 06 20pm](https://cloud.githubusercontent.com/assets/3667179/6471335/f1244658-c1b7-11e4-9c01-2baa12dbb5e8.png)

Best,
Peter

**Comment by bobmazanec** [comment]
Unable to repro on `develop` 7e2c49d &mdash; with only **Completed Activities** entries, no unit is offered with a **Start Your Next Lesson** button.
