### ISSUE TITLE
Bug - Assigning an activity to multiple classrooms creates multiple copies of it 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#588]
When a teacher assigns an activity to multiple classrooms, it creates multiple copies of that activity on the unit. This makes it look like the activity has been assigned multiple times. 

# First Instance

One activity assigned to 3 classrooms - on staging. 
![screen shot 2015-03-03 at 5 03 36 pm](https://cloud.githubusercontent.com/assets/3667179/6474072/c89a0b8c-c1cb-11e4-8117-105d66bb57ae.png)

# Second Instance

One activity was assigned to two classrooms 

![screen shot 2015-03-03 at 5 04 35 pm](https://cloud.githubusercontent.com/assets/3667179/6474060/b9194e98-c1cb-11e4-962d-5de768e5ad5f.png)

# Third Instance

This is also happening on production. When a teacher assigned the two activities ("Possessive nouns" and "singular and plural nouns with matching verbs") to 3 classrooms, it created 3 instances of each activity. 

![screen shot 2015-03-03 at 5 33 01 pm](https://cloud.githubusercontent.com/assets/3667179/6474033/99b94634-c1cb-11e4-9f91-533d54bb38b3.png)

**Comment by bobmazanec** [comment]
Unable to report on `develop` 7e2c49d:

Given a Teacher with several Classrooms with Students
When
- I am logged in as the Teacher and
- I assign an Activity to my Classrooms

Then I see only 1 entry in the Unit
