### ISSUE TITLE
Remove Grade Level From Student Tool Tips

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#589]
Teachers are complaining about students seeing the grade level of the activities they are assigned, particularly in remedial classes. When a student is logged in, we should remove this field from the tool tips they see -- screenshot with relevant info crossed out below.

![screenshot 2015 03 04 at 9 35 58 am png 418x353](https://cloud.githubusercontent.com/assets/6655439/6485572/aa87be82-c252-11e4-8960-ab3fb8753b05.png)

**Comment by bobmazanec** [comment]
The same tooltip is used for both Teachers (_i.e._, Scorebook view) and Students.
- remove in both contexts?
- remove only from Student view?

**Comment by RyanNovas** [comment]
We would want to remove only for student view.

On Mon, Mar 16, 2015 at 12:01 AM, Bob Mazanec <notifications@github.com>
wrote:

> The same tooltip is used for both Teachers (*i.e.*, Scorebook view) and
> Students.
>
>    - remove in both contexts?
>    - remove only from Student view?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/589#issuecomment-81395388>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>

**Comment by marcellosachs** [comment]
@RyanNovas @bobmazanec as of now I'm re-writing the (teacher facing) scorebook in react.js. After this is done, the tooltip erb partial will only be used for the (student facing) profile, in which case we can just remove the mention of section.name (which states the grade level) from that partial.

**Comment by RyanNovas** [comment]
Ok. Great.

On Mon, Mar 16, 2015 at 12:51 PM, marcellosachs <notifications@github.com>
wrote:

> @RyanNovas <https://github.com/RyanNovas> @bobmazanec
> <https://github.com/bobmazanec> as of now I'm re-writing the (teacher
> facing) scorebook in react.js. After this is done, the tooltip erb partial
> will only be used for the (student facing) profile, in which case we can
> just remove the mention of section.name (which states the grade level)
> from that partial.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/589#issuecomment-81797953>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>
