### ISSUE TITLE
Force everything over SSL

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#592]
Quill does not currently operate over SSL by default, it'd be good to force it to do that.

- Set force_ssl in production/staging configs:
```
config.force_ssl = true
```

- Make sure all assets loaded in the UI are scheme-agnostic or otherwise work with both SSL / non-SSL. The app should still work without SSL because it's a pain to set up a self-signed certificate when developing on localhost.

Feel free to add comments with additional considerations.

**Comment by marcellosachs** [comment]
this is completed on staging. 
in order to enact on production (in addition to merging develop into production ), 
make sure that all heroku config vars are https, not http

**Comment by marcellosachs** [comment]
also use this http://stackoverflow.com/questions/15692601/links-without-http-like-code-jquery-com-etc
