### ISSUE TITLE
Delete Quill.org/about and any other redundant pages

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#604]
The old About us page is still live at http://www.quill.org/about. It has been replaced by http://www.quill.org/team and should be deleted, along with any other old pages. This is important to do because Google gives SEO penalties for duplicate content.

**Comment by petergault** [comment]
quill.org/about should redirect to quill.org/mission. Right now it leads to a 500.

**Comment by RyanNovas** [comment]
that is because i deleted it. it was orphaned, so the only way anyone would ever get to it is if they entered it into the URL.

**Comment by RyanNovas** [comment]
closing this. reopen it if there is a compelling reason for redirect.
