### ISSUE TITLE
Intermittent capybara spec failure

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#613]
create_unit_spec is failing intermittently on CI (and differently on my local machine), here are the relevant lines:

```
lesson_planner_page.create_unit 'some new unit name', activity

lesson_planner_page.show_students

expect(lesson_planner_page.students)
            .to sort_fodder_sorted.map(&:name)
```

Fails thusly on CI:

```
  1) Teacher Activity Planner - Create a Unit given a selectable Activity and a classroom with students when signed in as the Teacher shows the students, sorted by last name
     Failure/Error: expect(lesson_planner_page.students)
       
       expected: ["Alex Brown", "Christine Brown", "Christopher Brown", "Chris", "Christine", "Christopher", "Alex Smith"]
            got: []
       
       (compared using ==)
     # ./spec/features/teacher/activity_planner/create_unit_spec.rb:24:in `block (5 levels) in <top (required)>'
```

Occasionally fails thusly on my machine:

```
  1) Teacher Activity Planner - Create a Unit given a selectable Activity and a classroom with students when signed in as the Teacher shows the students, sorted by last name
     Failure/Error: expect(lesson_planner_page.students)
       
       expected: ["Alex Brown", "Christine Brown", "Christopher Brown", "Chris", "Christine", "Christopher", "Alex Smith"]
            got: ["Christine Brown", "Christopher Brown", "Chris", "Christine", "Christopher", "Alex Smith"]
       
       (compared using ==)
```

Note how all the correct names are there, but they aren't in the right order. I have no idea if this is related to the failure on CI.

Since the list of names seems to be entirely empty on CI, I'd check to see whether the assertions in lesson_planner_page are blocking correctly (waiting until the JS finishes running). Otherwise IIRC there were tools to take screenshots of spec failures, which may give a better sense of what went wrong. I have no idea whether this sort of thing works on Travis.

**Comment by kriskelly** [comment]
This is now failing full-time (as opposed to part-time) since a282e1e. That commit merged develop into @marcellosachs reactscorebk branch, which is a rewrite of the scorebook in React.js. This is most likely strictly a test failure since the scorebook seems to be working IRL. 

I tried running that spec with js: true and with VCR ignoring localhost, but it still fails. Tempted to delete that spec entirely in order to "resolve" this issue.

**Comment by bobmazanec** [comment]
Might be the best for now.

I haven't found the right incantations to get `feature` specs to record new `vcr` cassettes (_e.g._, of CDN content), much less use them.

Sorry for the inconvenience :-(

**Comment by bobmazanec** [comment]
In weeks-later hindsight, "rewrite of the scorebook in React.js" was the key here &mdash; `feature` specs involving any page(s) with React content must be tagged `:js` or `js: true` to allow React rendering
