### ISSUE TITLE
Disable segment/intercom/typekit in feature specs

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#614]
These specs are loading all of this JS from CDNs, etc. and it is occasionally making the test runs noticeably slower.

**Comment by bobmazanec** [comment]
I'd _love_ to get all this stuff from VCR (faster, locks version, _etc_.), but I haven't found a way to do this.

If I've missed something, please share!

Other thoughts...
- If you're concerned about only the in-browser examples, filter them out with `rspec --tag ~js:true`
 - Create a new `rake` task using the filter &mdash; _e.g._, `spec:not_browser`?
 - Rewrite the `spec` task to use the filter & add `spec:all` task _not_ to use the filter?
- Omit the 'offensive' libraries in the `test` env
 - at the 'cost' of making it even less like `production`
 - (included for completeness &mdash; I don't like this one)

**Comment by kriskelly** [comment]
I'm leaning towards omitting the libraries from the test env altogether. You're right, it does make the test env less like production, but I think it's a fair trade-off for a speed boost in test runs and to make the feature specs less flaky. We ran into an issue earlier where we had to bump up Capybara's timeout setting to prevent spurious failures on Travis, and disabling all these network dependencies would go a ways towards solving those kinds of problems.

Thanks for the tip re: rspec filtering. you can omit the :true part and just do `rspec --tag ~js`, assuming no one has set it to false anywhere.

**Comment by bobmazanec** [comment]
Before I/you/we start omitting anything from `test`, any reason for me not to try running under [poltergeist](https://github.com/teampoltergeist/poltergeist)?

Maybe it will be faster 'enough' to make the CDN downloads more palatable in comparison?

I'll try a few runs on both my (2012) MacBook Pro and in Travis to see if there's a speedup.

**Comment by kriskelly** [comment]
Sounds good, thanks!

**Comment by bobmazanec** [comment]
Been a while, but I'm back on this.

I've branched from develop 45bc80e (14 Apr).

Using [poltergeist](https://github.com/teampoltergeist/poltergeist) on my local box, I'm seeing some speedup & no failures &mdash; yay.

Sadly, things aren't going so well on [Travis](https://travis-ci.org/bobmazanec/Empirical-Core/builds/58549788) for me.

I'm trying to figure out what's going on (_e.g._, why `<table>`, _et al_, don't seem to be getting rendered) and what's different from my local box.

Part of my "catch up" was to add `FOG_DIRECTORY` and `PROGRESS_REPORT_FOG_DIRECTORY` env vars to my Travis settings
- both with the values from `.env-sample`
- please advise if that's a bad idea!

If any other ideas/suggestions/leads occur, please share and maybe/hopefully save me some guessing! :smile:

TIA

**Comment by bobmazanec** [comment]
'Fixed' ('enough?') by #699?

**Comment by kriskelly** [comment]
Thanks for the fix several months ago, @bobmazanec! Closing
