### ISSUE TITLE
"Sign Up" is Incorrectly Indented in Some Views

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#616]
When the window is small, so that the top menu bar becomes a drop down, "Sign Up" is indented. It should be flush with the other options.

![screenshot 2015-03-18 at 11 19 17 am](https://cloud.githubusercontent.com/assets/6655439/6712013/cdd47498-cd60-11e4-8428-da5c364fd770.png)

**Comment by jenfinery29** [comment]
Working on this!
