### ISSUE TITLE
500 error is not displaying properly

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#617]
The 500 error is printing out like this:
![screenshot 2015-03-18 at 1 24 51 pm](https://cloud.githubusercontent.com/assets/6655439/6715246/9f8ca5d4-cd73-11e4-9855-f11298154609.png)

info about its location is here:
https://github.com/empirical-org/Empirical-Core/blob/75e7a173764f84afee7bcff8899cd1f576bf9238/app/views/errors/error_500.html.slim

**Comment by uanwar88** [comment]
How should it be displaying?

**Comment by RyanNovas** [comment]
"Please go back to the home and try your request again." Should be one line.
The next line should be "If you continue to encounter this problem, please
email us at hello@quill.org." With "If' at the beginning and a period at
the end.

On Fri, Mar 20, 2015 at 9:41 AM, Usman <notifications@github.com> wrote:

> How should it be displaying?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/617#issuecomment-84019303>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>

**Comment by uanwar88** [comment]
I have submitted a pull request for this issue.
