### ISSUE TITLE
Additional Unit Editing Funcitionality Needed

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#618]
There is no way to change names of units, edit the students it has been assigned to, or add additional lessons. These are all things teachers frequently ask for.

**Comment by uanwar88** [comment]
Is this part of the Class Manager? What view is used to create units?

**Comment by uanwar88** [comment]
Once someone has been assigned, does that mean they are working on the issue?
And other people should avoid working on it?
