### ISSUE TITLE
Premium One Page

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#619]
# Premium
The goal of the Quill Premium one page is to explain the benefits, get the user to inquire about a quote.

## Inspiration:
* [Edmodo](https://www.edmodo.com/districts)
* [Newsela](https://newsela.com/about/)
* [Skillshare](https://www.skillshare.com/membership)
* [Treehouse](https://teamtreehouse.com/subscribe/plans?trial=yes)
* [Evernote](https://evernote.com/premium/#premium)
* [Invision](http://www.invisionapp.com/enterprise)

## Copy
* [Google Doc](https://docs.google.com/document/d/1VEV6wwX2ydSq_CZAXetoFFGdEQ-9UOe-EXsb7w04xQ4/edit)

## Mockup
* [1st Mockup](https://drive.google.com/open?id=0B1RagCbDewKWR2RLRmpkUkhReDQ&authuser=0)
* [2nd Mockup](https://drive.google.com/open?id=0B1RagCbDewKWUG5NT2Z3YnhrX2s&authuser=0)

**Comment by petergault** [comment]
# Quill 1 page PDF 

PDF of the 1 page report: 
https://drive.google.com/a/quill.org/file/d/0B-r431ws0zjXY09ObXc2emtYdUE/view?usp=sharing

Ideas:

- [ ] Make all of the columns properly aligned and spaced. 
- [ ] make the text on the Features table larger (column wider), make the quill and quill premium columns narrower.
- [ ] We may want to include a call to action that directs people to the official sales landing page, such as quill.org/premium. 
- [ ] Make sure that the columns preserve space in case this doc is printed out. For example, extra space has been added to the topic of the doc so that the email and phone number is not cut off when printed out. 

# Sales Landing Page Notes: 
- Let's basically re-use this copy. 
- We are going to have the first section be orange, and it will use the same copy as the left hand column. 
- The second section, the blue section, will feature the info in Quill premium. The two CTAs here will be a contact us button that leads to a wufoo form for interest as well as a “Book a Demo” We will also include the sales email and phone number. The Book a demo will guide a user to the same service that Newsela uses. 
- Then we feature the columns
- Finally we will have a section at the bottom that reinforces our mission - that we are a nonprofit building free tools. We can also mention that we may provide free access to schools who do not have the financial resources to purchase Quill Premium, and the school should contact us. We then re-iterate our “book demo” link and the wufoo form.

**Comment by tomcalabrese** [comment]
@petergault I've updated the landing page [mockup](https://drive.google.com/open?id=0B1RagCbDewKWUG5NT2Z3YnhrX2s&authuser=0).

## Questions & To Dos
1. Need to add subtitles to each section "OUR PURPOSE"
* Need titles for each section "Mastery Based Grammar"
* I would recommend we extend "_Use Quill to master the CCSS language standards._" into something longer, that explains what Quill is like "_Quill provides free writing, grammar, and vocabulary
activities to middle and high school students. Use Quill to master the CCSS language standards._"  
* Under the Premium Tab, do we want to include links like "About - Quill Premium - Features - Get a Quote - Questions" that direct a user down the page with '#'?
* Under Quill Premium we say "Quill Premium enables teachers to view and download their data." This seems a bit bare, maybe we want to have another short line. We could talk about what the benefit of downloading data is. 
* Add Quill Premium spreadsheet mockup, once that page is completed. Which page should I show?
* Add FAQ questions and answers.

**Comment by petergault** [comment]
Need to add subtitles to each section "OUR PURPOSE"

OUR PURPOSE

### Master the Common Core

Quill provides 150 writing and grammar activities built from 42 Common Core language standards. 

Quill is being used by over 1,000 schools nationwide. 

--------

Under the Premium Tab, do we want to include links like "About - Quill Premium - Features - Get a Quote - Questions" that direct a user down the page with '#'?

Possibly. We could also make the buttons "Quill Premium, Features, Book A Tour, Get a Quote, and Questions.  Questions & Features directs the user to those sections. 
----

Under Quill Premium we say "Quill Premium enables teachers to view and download their data." This seems a bit bare, maybe we want to have another short line. We could talk about what the benefit of downloading data is.

This is the copy: 
Quill Premium provides teachers and administrators with Quill Progress Reports.

The progress reports show a variety of data on how students are progressing on the Common Core and which concepts the students are struggling with. In 2015-2016 we will launch Quill Grammar Diagnostic, a series of activities that will provide educators with data on which grammatical concepts students known.

Teachers can easily view this data and download it as a spreadsheet. 


-----

Add Quill Premium spreadsheet mockup, once that page is completed. Which page should I show?

The Common Core standards. Use demoaccounts / demoaccounts - Click on progress reports, navigate to the common core, click on Grade 2. 

-----

Add FAQ questions and answers.

I don't have any feedback here. @RyanNovas  @ccowdery thoughts on questions for premiu,

**Comment by RyanNovas** [comment]
is the license for the calendar year or school year?
what happens if i go over my allotted number of students?
if additional apps are added, will i have premium for those as well?
i can't afford premium. do i have other options?

**Comment by tomcalabrese** [comment]
@petergault responding to:

"_Quill Premium provides teachers and administrators with Quill Progress Reports._

_The progress reports show a variety of data on how students are progressing on the Common Core and which concepts the students are struggling with. In 2015-2016 we will launch Quill Grammar Diagnostic, a series of activities that will provide educators with data on which grammatical concepts students known._

_Teachers can easily view this data and download it as a spreadsheet._"

Me and @RyanNovas came up with this alternative:

"Subtitle: Lorem Ipsum
Title: Quill Premium
Body: With Quill Premium you’ll get reports showing detailed views of student progress across activities and concepts, common core coverage, and more."

Problems with the initial copy:
* Assuming that people will know what Quill Progress Reports are.
* This section should be about succinctly describing Quill Premium, and talking about future features like Quill Grammar Diagnostic is not necessary. 
* Only the main features of Quill premium should be outlined, the rest will be seen in the table below.

**Comment by petergault** [comment]
Subtitle: Introducing

Title: Quill Premium

With Quill Premium you’ll get reports showing detailed views of student progress across activities and concepts, common core coverage, and more. 

Teachers, use our interface to dive into the data. You can also download it as a spreadsheet and import it into your gradebook.

**Comment by petergault** [comment]
for the top box
-------------
Subtitle: Student Success
Title: Master the Common Core 
Quill provides 150 writing, grammar, and vocabulary activities built from 42 Common Core standards. 


We are now working on new standards and activities. For the 2015-2016 school year we will launch Quill Grammar Diagnostic, a series of activities that allows you to pinpoint the knowledge levels of your students.

**Comment by RyanNovas** [comment]
The Grammar Diagnostics part is too vague. I don't think it is worth mentioning at this time.

**Comment by tomcalabrese** [comment]
@petergault I made the changes we talked about before to the Premium page.

What would you like the sub-headline to be for "Questions and Answers", right now I have it as "SUPPORT"?

Do you like the screenshot in Quill Premium?

Once I get the final FAQ I can send the page to Vlad.

![premium](https://cloud.githubusercontent.com/assets/8131465/6995682/9cf8a286-db25-11e4-9e98-e7f40f224a23.png)

**Comment by petergault** [comment]
What do I get with a Free Membership?

All of our apps and activities will always remain free, forever. Teachers see their students’ results in the scorebook, and teachers may hover over the activity result to view the details. 

What do I get with a Premium Membership?

With Quill Premium teachers can access Quill Progress Reports, which allow teachers to easily view and download their data. Quill Progress Reports show teachers how students are progressing on the Common Core and which concepts they need help with. Schools may also upload their rosters via CSV. 

How does payment work for a Premium Membership? 

Quill Premium is provided on an annual license based on the school year. You may pay via credit credit or check. 

How much does Quill Premium cost?

Quill Premium is provided on plans based on classroom, grade level, school, and district usage. Please contact us to receive a quote. 
>Link to the book a demo. 

Do you offer financial aid?

Yes, we provide Quill Premium for free to schools which have a demonstrated financial need. This funding is provided to select partners thanks to the support of the Bill & Melinda Gates Foundation. Please contact us to apply. 
> Link to “mailto:hello@quill.org”

Have more Questions? 

Visit our Support center to contact our support team. 
> Link to support.quill.org

**Comment by tomcalabrese** [comment]
@marcellosachs here are resources you'll need to create the Sales Landing Page. 

[Sales Landing Page Mockup](https://drive.google.com/open?id=0B1RagCbDewKWNEoyenpMb1pSMUk&authuser=0)
[Sales Landing Page Mockup with Specs](https://drive.google.com/open?id=0B1RagCbDewKWLTd2ZzhwTnJOMFk&authuser=0)

[Images](https://drive.google.com/open?id=0B1RagCbDewKWfmlrYnVTOTljU19rb3ctcUUzUjNSVUpqQXE3UWJPM3l5a3dzTmFudnhsU2c&authuser=0) for Sales Landing Page

**Comment by petergault** [comment]
Missing links:

Book a demo: https://quill.acuityscheduling.com/schedule.php
Learn More: http://www.quill.org/mission
Get a Quote: for now: mailto:hello@quill.org

In a future iteration we will set up a wufoo form for this, it just needs to get set up.
