### ISSUE TITLE
404 and 500 error pages are not reporting to mixpanel

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#622]
Triggering the 404 or 500 pages on Quill (i.e. quill.org/500 (500) or quill.org/35 (404)) do not report to mixpanel. The staging events do report successfully. Is there some issue with the token?

**Comment by kriskelly** [comment]
@petergault The commit that sends that event to Mixpanel is not on production yet.

**Comment by kriskelly** [comment]
Verified that this is working as of a production push this morning.
