### ISSUE TITLE
Backlog - Expire Links

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#625]
We probably want to expire S3 links and delete them after a period of time so that other people cannot access the data. What would the appropriate logic be here? We should probably expire after 48 hours. 

We may also want to look into attaching the file rather than just providing the link. This would solve the invalidation problem, where we attach it and then delete it.

**Comment by RyanNovas** [comment]
If we attach the file, there could be repercussions as far as spam filters.
