### ISSUE TITLE
Tom + Peter to do - Put together a Wireframe for the CSV Download Modal 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#628]
Ideally we would have a model that pops up that states:

------

Your Quill Progress Report is being emailed to you.

Please check: **sarahsmith@** **gmail.com**

-----

Include an exit button?
or just a button that says close:
or something more fun such as "Got it"?

**Comment by tomcalabrese** [comment]
*Your reports are on the way!*

Your Quill Progress Report is being emailed to you. It should arrive within the next five minutes.

Please Check: sarahsmith@gmail.com

Button "Got it"

**Comment by petergault** [comment]
https://moqups.com/#!/edit/gault8121/6RLG73bg

**Comment by kriskelly** [comment]
It's done and pushed to staging.
