### ISSUE TITLE
Peter to do - Put together copy for the Email 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#629]
Copy for the email. Perhaps someone like Cody could look at it to breath some life into it? For example, we could have a funny 

----
Your Quill Progress Report has arrived! 

*This could be the header or the first line of text. We may want to also include the date + in the header, in case the teacher wants to easily share it - e.g. Quill Progress Report from July 13, 2014.*

----
Your Quill Progress Report has arrived! 

**To download your file, right click on the file and press "Save As"**

[Show link] (link)

You can view your data by opening the CSV file in Excel, Open Office, or Google Sheets. 

[Have questions? Learn more on the Quill support site.](link)

Have comments or feedback? Please respond to this email to help us design Quill. We're an open source nonprofit, and we're building free literacy tools so that people all over the world can become better writers.

**Comment by petergault** [comment]
@tomcalabrese @RyanNovas @kriskelly  what do you think about the copy? perhaps we could make this somewhat engaging with the teachers, rather than something dry. Let's talk to them in a way that makes them want to speak with us.

**Comment by jnssimmons** [comment]
Hi all, 

Checking to see if you want someone to work on the copy for this email?

Thanks,

J.

**Comment by kriskelly** [comment]
@petergault The copy looks fine to me, but then again I'd probably err on the side of dry and instructive. Let me know if you want to sign off on this, and I'll go ahead and change the email text.

**Comment by RyanNovas** [comment]
I think it is fine. Only edit I would make is changing:

"We're a tiny nonprofit trying to build the best literacy tools in the world, and our success is due to you."
To
"We're a tiny nonprofit trying to build the best literacy tools in the world. Our success is due to you."
