### ISSUE TITLE
When hovering over #of students assigned it looks like a link

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#638]
This is static text. It should just be a cursor
![screenshot 2015-03-24 at 12 06 07 pm](https://cloud.githubusercontent.com/assets/6655439/6806362/a37b6644-d21e-11e4-9fa1-3b9047e02e70.png)

**Comment by marcellosachs** [comment]
@RyanNovas fixed (on develop branch, should be apparent in next staging deploy))
