### ISSUE TITLE
Make alerts on add classroom page consistent

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#640]
When the grade and name fields are not edited, they both give alerts. However, they are inconsistent.

![screenshot 2015-03-24 at 12 39 11 pm](https://cloud.githubusercontent.com/assets/6655439/6807122/046a0902-d223-11e4-8db6-0ae25f19a594.png)

The "Name" alert should be centered and in red, as the "Grade" one is. It should say "Please select a name for your classroom."

The "Grade" alert should just say ""Please select a grade for your classroom."

**Comment by marcellosachs** [comment]
@RyanNovas fixed as of 31aa1ffce076872313f455db40b26af9adf3bba1
