### ISSUE TITLE
Progress Reports - Show Totals in the Upper Right Corner 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#643]
We can consider putting the totals in the upper right corner rather than at the bottom of the page. This way teachers can briefly glance at this info when they load the page, rather than having to scroll to the bottom of the page. 

The counter argument here is that the totals summary shown on this page will also likely be the same summary shown at the parent page level. If a user just saw this info when clicking on the link, perhaps we want to show this at the bottom to de-clutter the top. 

![screen shot 2015-03-26 at 12 19 30 am](https://cloud.githubusercontent.com/assets/3667179/6840416/0f39d08e-d34e-11e4-8c68-f8cfddb0ecaa.png)

**Comment by RyanNovas** [comment]
Let's just make the total row on top

**Comment by petergault** [comment]
Yeah that's an option. It's just a bit weird to have the total next to the filter. We could also just show it at the bottom. It does make it noiesy to be at the top.

**Comment by RyanNovas** [comment]
Google does it on top or bottom, depending on which report your pulling up. Screenshots included
![screen shot 2015-03-26 at 11 21 49 am](https://cloud.githubusercontent.com/assets/6655439/6849578/6a3f23ce-d3aa-11e4-8d87-333380613077.png)
![screen shot 2015-03-26 at 11 19 37 am](https://cloud.githubusercontent.com/assets/6655439/6849579/6a3fcc84-d3aa-11e4-859f-63afa7c6d926.png)
