### ISSUE TITLE
Set up Wufoo Form 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#645]
- Check NoRedInk + EdModo - what do they include? 

- Make sure it is fully branded. Talk to Tom if you have questions about the color scheme.

**Comment by RyanNovas** [comment]
This issue is solved from Acuity.

**Comment by petergault** [comment]
Is there a direct link to an acuity form I can see? Basically I want to see what it looks like if I want to express interest in purchasing Quill without booking a meeting.

**Comment by RyanNovas** [comment]
@petergault we don't have that. I can make one. Acuity form is here: https://quill.acuityscheduling.com/schedule.php

**Comment by RyanNovas** [comment]
@petergault wufoo form is here https://quillpremium.wufoo.com/forms/quill-premium-quote/
