### ISSUE TITLE
Experiment - Organize Activities Chronologically 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#647]
# Chronological Cubes
Initially the design thought here was that by organizing the scores by color would help to keep it organized and give a nice initial view of how the students are performing. However, it does make it harder to see that day by day progress as it's all sorted out. We may want to experiment with a view here where we show chronological progression of the activity sessions. 

# Default Time Selections
We also set some defaults for activities completed - show me this current week plus the previous week or perhaps the current week plus the previous 3 weeks. The nice thing about this view is that rather than say a 30 day view, where the completed activities are disappearing on the trailing end (the 31st day activities),  in this view things build up over the week and then reset at the start of the next week. 

e.g. if it is wednesday, you see previous 3 weeks + 3 days (mon-wednesday) of this week. On friday you see previous 3 weeks + 5 days (mon-friday). On Sunday you see 3 weeks + 7 days. On Monday you reset at 3 weeks + 1 day. 

This is one possibility of showing the back story while also showing the progress.

**Comment by RyanNovas** [comment]
I don't like the presets. They are noisy and hardly save time compared to
doing it manually (if they even meet the teachers needs).

I continue to strongly support switching to a chronological view.

On Thu, Mar 26, 2015 at 12:56 AM, Peter Gault <notifications@github.com>
wrote:

> Chronological Cubes
>
> Initially the design thought here was that by organizing the scores by
> color would help to keep it organized and give a nice initial view of how
> the students are performing. However, it does make it harder to see that
> day by day progress as it's all sorted out. We may want to experiment with
> a view here where we show chronological progression of the activity
> sessions.
> Default Time Selections
>
> We also set some defaults for activities completed - show me this current
> week plus the previous week or perhaps the current week plus the previous 3
> weeks. The nice thing about this view is that rather than say a 30 day
> view, where the completed activities are disappearing on the trailing end
> (the 31st day activities), in this view things build up over the week and
> then reset at the start of the next week.
>
> e.g. if it is wednesday, you see previous 3 weeks + 3 days (mon-wednesday)
> of this week. On friday you see previous 3 weeks + 5 days (mon-friday). On
> Sunday you see 3 weeks + 7 days. On Monday you reset at 3 weeks + 1 day.
>
> This is one possibility of showing the back story while also showing the
> progress.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/647>.
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>
