### ISSUE TITLE
Bug - Progress Reports Consistently Fails to Load HTML

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#649]
Progress Reports Bug - Whenever I’m using this page, I’m sometimes getting a page that loads just the API without the HTML. I usually can replicate this by clicking on the back button. 

Is there some way of fixing this problem? Perhaps checking to see if the page loads (such as requiring an image to load?) and if it doesn’t load the page reloads. IDK, whatever works here. 

![screen shot 2015-03-25 at 8 03 25 pm](https://cloud.githubusercontent.com/assets/3667179/6840668/62ad6456-d353-11e4-9d8a-d5aa1f6e9f78.png)

**Comment by kriskelly** [comment]
@petergault This is a Chrome bug related to how it caches AJAX requests. There's supposedly a fix, I am working on that now.
