### ISSUE TITLE
FAQ for Premium Page

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#652]
## Copy for FAQ Section of Premium Page 

Please fill in the order, question, and answer. 
[Google Doc](https://drive.google.com/open?id=164R3J_YBEwbIok0fvc3N9O_mDnahW0ikyakqgtJB3cI&authuser=0)

**Comment by RyanNovas** [comment]
@petergault there is somewhere that you explained the 10% wiggle room for students. You did a good job with it, but I can't find it. Can you put it in here?

**Comment by petergault** [comment]
Yeah, this one is tricky. Here is the copy: 

We know class sizes change. You may add additional students for free up to 10% of your initial purchase.

**Comment by petergault** [comment]
Okay all of these are answered by the premium one page guide.
