### ISSUE TITLE
Handling the Final Activity Session 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#654]
*Note: this is Peter's take on how to handle this. Kris has another solution to handle the problem.*

Solution to the site going down:

Problem: Quill got knocked offline. It seems the reason why is that when students complete ActivitySessions it checks the database to see how that score compares against previous scores. This is an expensive query that is causing the site to crash. 

Here is a potential fix. 

Each activity session has a new field called previous score. When a student starts an activity for the first time, the “previous score” field is set to 0 in the . When the student completes the activity, the site checks the current score against the previous score. In the first attempt the student scores a 50, and the 50 over-writes the 0, so the score is 50. 

When the student presses re-try, it generates a new activity session where it retrieves the previous session and gets the score, which is now the score for the “previous score” field. (We could also handle this as a background, where we automatically prepare a retry activity session with the previous score as soon as the first one ends). 

When the retry activity ends, you simply have to compare the current score against the previous score in the current activity session, rather than referencing all previous activity sessions. If the score is higher, it gets overwritten. If not, the old score remains. 

The downside to this system is that the score becomes dissociated with the activity session. This doesn’t impact the user, but it could cause problems down the road. Here is what I mean: Let’s say on the re-try the student gets a 33%. At this point the site would keep 50% as the final score, rather than 33%. However, 50% is now associated with the activity session. At this point the student has two activity sessions where each session has an average score of 50%. Since we only care about the highest score, we don’t care about the student getting a 33%. The teacher still sees one score, which is set to 50%. What might change is that the completed at date is updated, where it once showed 50%, it now shows that the score is 50% where the date completed is updated. 

When we are doing calculations we also want to make sure that we are counting each Activity once (i.e. if a student has 3 activity sessions associated with a one activity, we want to make sure that we are only counting one session for the student).  In this system the most recent one is always the final one. Perhaps we a new activity session is started, we set the activity session to “in progress: and whenever an in progress one is completed, it is set to final. Since the scores over right, the last completed session is always the final. 

Final thought - 
This session could be stored in the DB (or in reds?) so that it simply checks against the previous score field of the current session, rather than referencing all previous sessions.

**Comment by petergault** [comment]
Let's leave this here and assume it is fixed if the database no longer spikes.

**Comment by marcellosachs** [comment]
good to go : 
![Uploading Screen Shot 2015-04-01 at 2.43.10 PM.png . . .]()
