### ISSUE TITLE
New Acitivites Not Showing Up In Teacher Activity Viewer

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#656]
I just added four new Grade 4 Summative Assessments about Lewis and Clark. They are not showing on the teacher activity viewer.

**Comment by marcellosachs** [comment]
@RyanNovas  this should be good to go !
![screen shot 2015-03-30 at 12 59 53 pm](https://cloud.githubusercontent.com/assets/1789723/6901655/ba10e556-d6dc-11e4-9b6c-3438104f9eb6.png)
