### ISSUE TITLE
Add new Concepts + Explore Rails Admin for admin interface

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#657]
New activities cannot be added to the app until Marcello manually assigns a value to them. 

We could build an interface for this page. However, it is kind of a pain to build a new page for each field. 

@wlaurance Found out a tool called Rails Admin which automatically builds an interface based on the structure of the rails database. We might want to consider moving to this interface rather than maintaining our current interface. 

https://github.com/sferik/rails_admin

Here is a link to the demo: http://rails-admin-tb.herokuapp.com/

**Comment by marcellosachs** [comment]
I fixed this yesterday before seeing this issue. Building cms interfaces is actually not too involved, but if things get crazy or you want to overhaul the cms this Rails admin thing looks interesting..
