### ISSUE TITLE
Standards View - Progress Reports

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#659]
https://moqups.com/gault8121/6RLG73bg/p:a5a15a2a3
Page 2-6 contain the data and the notes.

- Left Aligned. 
- The download report is going to be flush with the logout button.

**Comment by tomcalabrese** [comment]
* [Standards: All Classrooms Mockup](https://drive.google.com/open?id=0B1RagCbDewKWUmJsSHlGZUVJbFE&authuser=0)
* [Standards: Student View Mockup](https://drive.google.com/open?id=0B1RagCbDewKWMzlpMWxMdUdZMXM&authuser=0)

I'll be adding the additional mockups here, along with specs (font weights, padding, etc.)

**Comment by petergault** [comment]
The Download report button is the wrong shade of green - #00C2A2

The download report font is too heavy of a weight. it should be the same as discover, community. 

On the students page their is not enough length. Can you make it a bit longer? 

http://staging.quill.org/teachers/progress_reports/standards/classrooms/3820/students
demoaccount
demoaccount

**Comment by petergault** [comment]
The links should be underlined. For example, the student names should be underlined. 

The breadcrumbs should be this color: 308183

**Comment by petergault** [comment]
Design Questions for Tom:
option 1: Show the links in dark green, don't show the color. 
option 2: Show the links underlined, make the 3 colors darker.

**Comment by petergault** [comment]
For Kris:
**Only show the arrow for the currently sorted table.**

For the arrows that sort the table, we should only show the arrow for the current sort. All of the other arrows should be hidden. When you click on a different column, the arrow pops up in that column, and the other ones disappear.

**Comment by petergault** [comment]
Remove the concepts button for now, make the order first Common Core Standards, than activities.
