### ISSUE TITLE
Relaunch of the Activities Preview Page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#666]
Current page is Quill.org/lessons

1. Rename the domain to Quill.org/activities  from /lessons 

2. Set it up so that /lessons re-directs to /activities. (for old links). 

3. On the “discover” tabs, add the tab “Activities”  

4. In the sub-menu, add the following links: 

Benchmark Assessments http://www.quill.org/lessons?section_id=27

Elementary School http://www.quill.org/lessons?section_id=7

Middle School - http://www.quill.org/lessons?section_id=10

High School - http://www.quill.org/lessons?section_id=18

University - http://www.quill.org/lessons?section_id=17

5. Remove the video and the header text. 

6. Make this copy (these 4 sentences) one paragraph:
We've built over 150 lessons directly from the Common Core State Standards. We are a nonprofit organization, and all of our lessons will always be made freely available. Each of our lessons takes approximately 10-15 minutes. Teachers using Quill in a 1:1 classroom tend to assign Quill lessons as a warm up exercise at the beginning of a class.

7. Change this sentence from:
Click on 'View Story' and 'View Practice Questions' to take a look at our lessons.

Change to: 
Click on 'View Activity’ to take a look at our activities.

8. These two pieces of copy should be left aligned. 

9. The “section” selector.
- Change the black button to the teal color. 
- Fix the drop down carrot so it is to the right of the text. 

10. Change the link “View Lesson” to “View Activity” 

Done! Thanks.

**Comment by marcellosachs** [comment]
@petergault this is up on staging : http://staging.quill.org/activities
lmk if any tweaks are desired!

**Comment by petergault** [comment]
Looks  great, thanks Marcello! It's ready to push to prod.
