### ISSUE TITLE
ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#667]
In `classroom.rb in create_next at line 13`

```
  has_many :units do
    def create_next
      create(name: "Unit #{@association.owner.units.count + 1}")
    end
  end
```

More info on Sentry:
https://app.getsentry.com/empirical-core/production/group/31311752/

**Comment by marcellosachs** [comment]
not sure why an initial unit is created for classrooms set up through clever, we may want to remove that behavior; for now that commit should prevent this error from occurring
