### ISSUE TITLE
undefined method `order_scope' for Section

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#672]
In `app/views/cms/sections/index.html.slim`

This line:
```td.position-select= f.select :position, 1.upto(f.object.order_scope.count + 1).to_a```

This is old code, error was first seen 5 months ago.

More info on Sentry:
https://app.getsentry.com/empirical-core/production/group/39725548/

**Comment by marcellosachs** [comment]
fixed as of 29750865f8cd6c6af03aac5877ff42166b411412
