### ISSUE TITLE
Broken TravisCI build from  09bb09c

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#673]
That commit breaks the build for the following spec:

```
1) Activity Listing Progress Report for a logged-in teacher displays the right headers
     Failure/Error: sign_in_user mr_kotter
     Net::ReadTimeout:
       Net::ReadTimeout
```

Has been broken since. More info here: https://travis-ci.org/empirical-org/Empirical-Core/builds/56741246

**Comment by marcellosachs** [comment]
fixed as of 192274be76c40a81c3510d00da16095bfb20c73e
(increased default wait time on capybara config)
