### ISSUE TITLE
Rename the lessons page to activities

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#676]
Quill.org/lessons should now be quill.org/activities 

- [ ] The url should be /activities
- [ ] The copy should say activities. It now says lessons. 
- [ ] The /lessons page should automatically re-direct to /activities. It should not go to a 404 or 500. 

Bonus
- [ ] We've got people coming to quill.org/about. We should re-direct them to /activities.

**Comment by RyanNovas** [comment]
If people are actually coming to /about, I agree with your former idea of
redirecting it towards /mission. /mission is literally under the "about"
tab, so it makes much more sense.

On Wed, Apr 1, 2015 at 7:06 PM, Peter Gault <notifications@github.com>
wrote:

> Quill.org/lessons should now be quill.org/activities
>
>    -  The url should be /activities
>    -  The copy should say activities. It now says lessons.
>    -  The /lessons page should automatically re-direct to /activities. It
>    should not go to a 404 or 500.
>
> Bonus
>
>    -  We've got people coming to quill.org/about. We should re-direct
>    them to /activities.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/676>.
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>
