### ISSUE TITLE
Updates to the Activity Listing Page 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#679]
- [x] Remove the time spent field. 

- [x] Change the order of the columns (from left to right):

> Student, Date, Activity, Score, Standard, App. 

- [x] By default this page should load activities in descending order by date, so that the most recently completed is at the top. 

- [x] The columns for Activity + App should be wider. Basically, everything should be one line in normal circumstances, and it can break 2 lines for particularly long pieces of text. 

- [x] Fix the page selector so that there is a top line to the page selector. 

- [x] Add some more space between the page selector and the footer, perhaps like ~ a half inch or so, it doesn't have to be exact.

- [x] the CSV file should reflect this new ordering. 

- [x] Add the gray background to the spreadsheet title when it's selected. The color is: #e6e6e6
![screen shot 2015-04-07 at 4 20 15 pm](https://cloud.githubusercontent.com/assets/8131465/7032658/0fb8fd0c-dd42-11e4-8c6f-0b81646d2a59.png)

**Comment by tomcalabrese** [comment]
* [ ] When a user first presses a filter the triangle should point up like this:
![screen shot 2015-04-08 at 6 07 47 pm](https://cloud.githubusercontent.com/assets/8131465/7056492/341a7d00-de1a-11e4-918c-324361d7759d.png)
