### ISSUE TITLE
Bug with extending tables 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#680]
When a table is longer than the page, the bottom supporting info does not extend all the way. 

![screen shot 2015-04-07 at 3 28 55 pm](https://cloud.githubusercontent.com/assets/3667179/7032579/98f4e258-dd41-11e4-993c-8e4547972fe7.png)

**Comment by RyanNovas** [comment]
i haven't been able to reproduce this. do you know if it is still occurring?
