### ISSUE TITLE
Update the Clever Integration 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#684]
Goals with details: 
- [ ] Find the old code for the Clever integration, set it up so that when a teacher enters Clever, we import all of her students
- [ ] Figure out how to set this up as a background process, rather than real-time process. When teachers create student accounts, this is also a background process, so perhaps it can piggyback off of that. 
- [ ] If it is a background process, let's test it to see how long it will take. If it takes more than a minute, let's create an alert for teachers that states "Your students are being imported. Please wait one minute."
- [ ] Set up a testing plan so that Ryan can test the integration with a teacher who has 150 students. 

Background: 
The issue is that we need to import all of a teacher's students into clever so that the teacher can assign activities to students. How it works right now is that a student account is only created when a student clicks on the Quill icon. This is a problem because teachers can't assign activities to students because there are not any students in the class. 

The current solution is to have a teacher sign into Quill via clever, ask all of the students to sign in, and then to assign the activities. 

We originally wrote the code so that we would auto-import the whole school. Let's tweak that now so that we only auto-import all of the students that belong to the teacher. I'm wondering whether we might be able to dig up the code within git and then optimize it so that it creates the accounts as a background job.

**Comment by Veraticus** [comment]
Due to improvements in Clever's API and the clever-ruby gem, I don't think an interim screen will be necessary. This is ready for testing.

**Comment by petergault** [comment]
Thanks Josh
