### ISSUE TITLE
Premium Page updates

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#686]
For Marcello
- [x] Apps and Activities in the FAQ should not be capitalized. 
- [x] Add a dash in the phone number. 
- [x] Fix the URL 

For Ryan
- [ ] Set up the wufoo form. It can mimic the acuity questions, but the key thing here is that they are not booking a call with us, they are just getting a quote. 
- [ ] Fix the google voice number now. Apparently it is broken. 
- [ ] Confirm that sales@quill.org is working. It should be. 

For Tom
- [x] Fix the landing page image.

**Comment by petergault** [comment]
- [ ] Change the order of the questions: 

(left column)
What do I get with a Free Membership?
What do I get with a Premium Membership?
How does payment work on a Premium Membership?

(right column)
How much does Quill Premium cost?
Do you offer financial aid?
Have more questions?

**Comment by petergault** [comment]
for Marcello 

- [ ] Remove the extra spacing being added around the links. 
- [ ] The Support link it should go to http://support.quill.org/
- [ ] The contact us should link to the wufoo form. 

For Ryan
- [ ] Clean up the support.quill.org. Close the old issues that have been fixed, and add the new issues to the issue tracker.  Leave about 3-4 ideas in there that look good.

**Comment by tomcalabrese** [comment]
@marcellosachs I updated the progress report screenshot on the landing page.

* [ ] [Update progress report screenshot](https://drive.google.com/open?id=0B1RagCbDewKWTFdHS1pLNmd4azA&authuser=0)

**Comment by marcellosachs** [comment]
@tomcalabrese k thanks!
