### ISSUE TITLE
When creating a unit, always have "Continue" and "Assign" buttons visible

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#688]
Dozens of teachers have gotten confused about why there is no "continue" or "assign" button on their screens when they are trying to create units. There are only a few reasons.

1) They didn't name the unit

2) They didn't select any activities

3) They have no classes or no students

4) They did not select due dates

Instead of making them write to us for help, let's just make the buttons permanent. If a teacher clicks them and they have made one of the following mistakes, we should have an alert that says something like: 

"You must do/assign/select X before continuing."

**Comment by petergault** [comment]
Yes, so we will make the button stay there as Teal. 

If the user clicks on it but they haven't done all of the required steps, have an alert pop up under the button that states the action they need to complete.
