### ISSUE TITLE
Add Testimonials page to Impact 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#690]
- [ ] Add a new page under impact called "Testimonials" 
- [ ] Make it the default page that loads under impact. 
- [ ] Add the content from this page: https://docs.google.com/a/quill.org/document/d/1BbpDib8oMfSHCQblwLlH98oOgwmMrKMmNbFotvT7V78/edit
- [ ] The current page, which lists all of the stats, doesn't have a name right now. It should be re-named to "Stats"

**Comment by cristiancisneros** [comment]
Peter,

Hi my name is Cristian, I am an aspiring Ruby On Rails developer interested in contributing to Qull.org. I have successfully completed the tasks described in issue #690 (please see screenshots below), however, I have been unsuccessful in making the proper modifications in my forked repository to create a pull request to consider my changes, sorry I am new to GitHub. I wasn't aware that if you reference the issue number, Github will actually update the thread and add my commit information! 

Please disregard my references while I "catch up to speed" with GitHub, I'm still trying to wrap my head around the whole "syncing" a fork concept. 

![testimonials](https://cloud.githubusercontent.com/assets/6709101/7246826/0e32d546-e7b7-11e4-961f-98e54c7b186f.png)

![stats](https://cloud.githubusercontent.com/assets/6709101/7246827/113b98f4-e7b7-11e4-9427-9e49b39c880c.png)
