### ISSUE TITLE
Remove case sensitivity from usernames and passwords

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#696]
We get a ton of feedback from teachers/students that they cannot login, and usually it is just because they are confused about the case of their username and password. We should remove these constraints so it is no longer an issue.

**Comment by bobmazanec** [comment]
Making username/e-mail case-insensitive should be easy.
Password: not so much.

 The User table has only the encrypted form
- if the password given for login encrypts to the stored value, login succeeds
- IM(NS)HO, not practical to cycle through all case permutations of input to see if any work

"Good enough" simply to downcase generated passwords
- teacher creates student
- teacher resets password (#702?)
- (any others?)

**Comment by bobmazanec** [comment]
FWIW, I've added some examples demonstrating the existing functionality -- cf https://github.com/bobmazanec/Empirical-Core/compare/develop...696_case_insensitive_auth

Here are the examples it generates:
```
$ bin/rspec -f documentation spec/models/user_spec.rb
User
  [...]
  .authenticate
    with email
      original case
        with incorrect password
          fails
        with correct password
          succeeds
      swapped case
        with incorrect password
          fails
        with correct password
          succeeds
    with username
      original case
        with incorrect password
          fails
        with correct password
          succeeds
      swapped case
        with incorrect password
          fails
        with correct password
          succeeds
  [...]
```

Worth a PR?

**Comment by petergault** [comment]
Thanks for commenting on this. I think at this point we should put this on pause. We have spoken with teachers, and there are likely a few easier ways we can handle this problem, such as by including a security question as a way of reseting a password.

**Comment by bobmazanec** [comment]
@petergault &mdash; is that comment more for #702 (password reset)?
