### ISSUE TITLE
Add Button for Demo Account to Premium Landing Page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#698]
With the demo account:

1. Add a button to the orange section. 
2. Remove the button from the mission page - we only want one cta here. Perhaps we can shorten it to one line by moving the 2,000 students part to the first section. 
3. Possibility - Add a button in the premium bar that says "Try it". 
4. Possibility - Add a question to the FAQ that states "Can I see a Quill Premium Account?" "Yes! Click here to explore a Quill Premium demo account."

**Comment by tomcalabrese** [comment]
Button Names:

* Try it
* View Demo
* Try it Now
* Give it a Try

**Comment by tomcalabrese** [comment]
@marcellosachs I've created a mockup with two changes, along with brief specs.

1. Remove the "learn more" button from the "mastering the common core" section. 
2. Add the "Try the Demo" button to the "quill premium" section.

[Mockup](https://drive.google.com/open?id=0B1RagCbDewKWV0xzNHJib2dYWmM&authuser=0) of updates for your reference.
