### ISSUE TITLE
Password Reset - Show it to teachers

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#702]
1. When a teacher resets a student's password, it defaults to the student's last name. When this has happened, let's show the password to the teacher. If the student then changes the password, it then disappears again.

**Comment by bobmazanec** [comment]
I think I understand "let's show the password to the teacher:
Given a student named Vinnie Barbarino
When a Teacher clicks the "Reset" button
Then the page shows something like "Vinnie Barbarino's password is now 'barbarino'"

I don't understand "if the student then changes the password, it then disappears again."
Are you suggesting that reset-but-not-yet-changed student passwords should be visible...
- after refresh
- (re-)visiting the page &mdash; _e.g._,
 - navigating away then back again
 - in a new browser window or tab

?

**Comment by bobmazanec** [comment]
What kind of visual feedback are you looking/hoping for?

![screen shot 2015-04-28 at 11 42 39 am](https://cloud.githubusercontent.com/assets/2031462/7375237/d88070f2-ed9c-11e4-89ba-a98216a323d9.png)

(or "Arnold Horshack's password..."?)

Note...
- it is downcased per discussion re: #696
- this is visible only immediately after the Teacher has clicked **Reset** &mdash; _e.g._, if disappears when they refresh

Acceptable?

On a related note...is the point of the **Password** text field solely to line up with the **Class Code** field and push the **Reset** button to the right?
- the text field is marked both `inactive` and `disabled`
- I don't see anything that ever gives it a value to show

**Comment by marcellosachs** [comment]
@bobmazanec sorry for the communication mixup but this issue is about to be closed by a forthcoming deploy, I should have paid attention to the fact that what I was workingon was related to this...

**Comment by marcellosachs** [comment]
@bobmazanec btw, we were thinking of removing case sensitivity for passwords, but it seems technically unfeasible (since its impossible to update old passwords), you don't happen to know of any way around that?

**Comment by bobmazanec** [comment]
@marcellosachs 
OK &mdash; no worries
 - only a few minutes of playing & testing invested
 - standing down

No ideas worth doing (IMO) re: passwords:
 - mass reset of all passwords to known, fixed content & case
 - force all users to change their password
  - add `password_reset_at` field to track who has done it & when
  - force case during the reset
 - loop through all the case combinations on sign-in

**Comment by marcellosachs** [comment]
@bobmazanec sorry again, I will pay closer attention to this kind of thing..

Indeed, I agree that those options seem undesirable. Perhaps we'll shelve the case insensitivity stuff for now...

**Comment by petergault** [comment]
@bobmazanec yes there are other solutions we can use here, such as letting the teacher set a class wide password.
