### ISSUE TITLE
UX Review - Teacher and Student Learning Experience 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#708]
Quill is a free literacy tool built for middle schools and high schools. Teachers sign up for the program, invite their students to the program, and then invite the students to use the program. 

For this issue, could you please go through the full experience of signing up as a teacher, inviting your students to the classroom, and assigning activities to the students. Please then sign up as a student, join the classroom, and complete the activities. As a teacher, then review your results. 

It would be extremely helpful if you could complete the entire process and take notes on your experience as you are using it. 

- [ ] Where could the site be improved? 
- [ ] Should the homepage include more details, such as social proof?
- [ ] What parts are not intuitive?

**Comment by anupbhople** [comment]
I am not sure how should i submit my review. But adding it here.

![image](https://cloud.githubusercontent.com/assets/7895428/7334254/d952e1ea-eb53-11e4-9fe3-5b97cf328a99.png)
