### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#710]
https://docs.google.com/a/quill.org/document/d/1o2eOLMTuwhQTn8NP6fHzK0C7xXwraZ8TPRQ2FoQRAUU/edit

**Comment by cristiancisneros** [comment]
There are two questions and answers on the http://www.quill.org/faq web page that are not mentioned in the Google Doc.

* Technical Questions - How do you set up Quill?
* Pedagogical Questions - Why are the Common Core lessons arranged into stages?

Do you want to revise, add, or remove them?

**Comment by cristiancisneros** [comment]
Peter,

I attached a screenshot that that shows the updated FAQ's. Before I send my pull request, please let me know what you decide to do with the two questions I mentioned in my previous comment. 

![faq](https://cloud.githubusercontent.com/assets/6709101/7443151/c7d16584-f0eb-11e4-8ab0-b7b1467040e8.png)

**Comment by cristiancisneros** [comment]
Regarding the hyperlinks in the Google Doc, do you want to add the full URL or just hyperlink them to "here" ?

**Comment by marcellosachs** [comment]
@petergault what's your take on this?

**Comment by petergault** [comment]
@RyanNovas please merge in the code and review the FAQ for any old info.

**Comment by RyanNovas** [comment]
@cristiancisneros Sorry this fell through the cracks. There have been a bunch of new updates to the FAQ, since so I went ahead and submitted a PR for them. We appreciate your help!
