### ISSUE TITLE
upgrade heroku backups

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#729]
heroku
Earlier this year, we announced the release of our new PGBackups.  This new system comes with two big improvements: enhanced reliability and the ability to schedule backups. 

Over the coming week we will be migrating backups that have been created using the PGBackups add-on to the new backup system.  We've identified apps that you're a collaborator on that will be impacted by this migration:

quill-grammar-prod, empirical-grammar-staging, pgsite, empirical-grammar, quill-grammar-staging

The backups for these apps will be migrated to the new backup system. If you had automatic scheduled backups with the old PGBackups, we'll set up those scheduled backups in the new system. Although, with the new scheduling functionality, you can set a backup time that works for you.  A notification will be sent when we start the migration process on your app and another when it completes. Upon completion of the migration, the PGBackups add-on will be removed from the app.

Developers are required to use the new backup system and associated commands.  The new commands can be found in the Heroku Postgres namespace in the CLI instead of a separate add-on.  A mapping document has been created to ease the transition from the add-on to the new system.  Please make sure to upgrade your version of the Heroku CLI to at least version 3.32.0 to get the latest PGBackups commands:

$ heroku upgrade 

If you have any questions, please email us at pgbackups@heroku.com.  In the meantime, look out for the dashboard notifications and follow the @herokuchangelog to stay up to date with additions and changes to the Heroku platform.

**Comment by marcellosachs** [comment]
@petergault we're good to go. Heroku is handling the upgrade process itself, all we need to do for our part is make sure to use the new command line commands when we want to create backups (for example when downloading the production database). To use the new command lines, a developer needs to have the most recent version of the heroku command line interface (cli), but this upgrade is handled automatically by heroku (https://devcenter.heroku.com/articles/heroku-command#staying-up-to-date)

**Comment by marcellosachs** [comment]
This document shows which new commands are replacing old ones : https://hello.heroku.com/e/36622/les-mapping-pgbackups-commands/4dn8dn/460827119

**Comment by petergault** [comment]
Great, thanks Marcello!
