### ISSUE TITLE
Bug with Emailed Spreadsheets

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#730]
Teachers are not receiving spreadsheets when they click the download link. Is there some way to test whether it is being blocked by their mail provider? One easy fix here would be to allow teachers to edit their profile. They could change their name, email address, school, etc. This way teachers could edit their email address and see if it is specific to their email client. 

This could be a tab called "Teacher Account." within the class manager.

**Comment by RyanNovas** [comment]
Not really any way to test if it is being blocked. I've confirmed it works fine with my Gmail and provided instructions as far as whitelisting and changing email addresses.
