### ISSUE TITLE
Replace Quill Grammar App Hierarchy with Concept Tag Hierarchy 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#737]
*I've broken this up into headers to make the conversation a bit more manageable.*

If you want to jump right into Marcello's proposal, check it out here: https://docs.google.com/document/d/1pBvUDIv_SY8dmsgOVeUsv5xNHf-CTPxcElEPC_jptNM/edit

## Intro - Building a Tree of Knowledge 

Our ideal vision for concept tags is build a Tree of Knowledge. We're essentially trying to build a hierarchy of content that will enable us to tag any question within an app to a tree hierarchy (i.e. a hierarchy of concepts possessing parents, sibling, and children concepts). Marcello has proposed that we build this into the Quill Grammar app now. The current Quill Grammar app is using a legacy hierarchy system from before the era where Quill was split into an API/SOA. 

**The current hierarchy doesn't handle the concept tags well, so this is a good time to consider refactoring the Quill Grammar app so that it utilizes the ideal concept tag system we would like to implement across all of the apps.**

**This is a microcosm of what the LMS will look like in the future, and it is a project contained purely within the Quill Grammar app.**

## Intro - Rules are not granular enough 
Marcello has been working on integrating concept tags into the passage proofreading section. The problem we were working through is that each passage proofreading question was associated with a rule, and this wasn't granular enough (we wanted to tag it at the level of the rulequestion). 

## Underlying weakness - two hierarchies 
In working through the problem, one of the confusing notions here is that the Quill Grammar app has two hierarchies. It has the hierarchy of rule categories / rules / rules questions, and it also has the hierarchy of concept category / concept tags. 

Marcello and I got into a debate about this, as there are reasons for keeping the two hierarchies, and reasons for not. Ultimately, Marcello convinced me that we should go for one hierarchy within the Quill Grammar app. Here is a run through of the debate. 

## Con: Why we should keep two hierarchies - It reflects the common app integration pattern

I prefer for the Quill Grammar app to have two hierarchies. A hierarchy of content within the app, and a hierarchy of concept tags we implemented within the app. I prefer this system because this is how most of our partner apps will look like - the partner will develop a hierarchy before the partner comes to us. When we ask them to implement the concept tags, this system will map on top of their current system. Using two hierarchies now means that we are operating in that model. 

## Pro #1: A chance to set a strong foundation

The heart of this problem is this - over time we want to build a massive library of content across a series of apps. We need a single hierarchy of concepts that acts as the "glue" to bind all of the content from all of the apps into a single knowledge web. To do this right, the concept tags need to be scalable - we need to be add various layers of granularity. Right now concept tags have a simple 2 step relationship. An ideal world, each concept tag would have a parent tag, sibling tag, and child tag. With this system in place, we can build these flexible systems that scale to handle various levels of granularity. 

Here is a good inspiration video - Powers of Ten: 
https://www.youtube.com/watch?v=bhofN1xX6u0

## Pro #2: Using one hierarchy helps app developers understand our platform. 

The Quill Grammar app is our flagship app, and we will use this app to communicate our API infrastructure to other app developers. By using the concept tag system within the app, it will help us communicate it to either developers in a simple way. 

## Pro #3: The main assumption in the Con argument is wrong - Most of our app developers will originate from our platform, rather than integrate later on. 

The con argument is assuming is that most of our app partners will build their apps and then come to us. However, by actively building our open source community, it is very likely that many of our apps will originate within our own eco-system, rather than partnerships with external parties. For this reason, it makes sense to use our existing concept hierarchy, rather than re-creating it. 

## Pro #4: Moving the Quill Grammar app to the Concept tag hierarchy will help the core development team jointly understand this system. 

By integrating the concept tags as the hierarchy for the Quill Grammar app, this will help Marcello and Will better understand this system. With this understanding in place, it will be easier to help other app developers integrate into our platform. This takes back to #1, but it is essentially that by getting the system right now, it will make it easier to grow.

## Con #2: This project might be over our (ultra-lean) budget. 

We have a pretty limited budget right now, and that's the other major concern I have for building this system. While it's obviously an important underlying infrastructure for scaling, we could also come back to this later. 

### Peter's Take: Let's explore building the system and proceed if it seems feasible. 

With all of that being said, the inclination is to explore this system for now, and see how much work we think it is going to be. Once we're all on the same page about it, we can choose to refactor. Here are the details of Marcello's proposal: 

## The link to the proposal 

https://docs.google.com/document/d/1pBvUDIv_SY8dmsgOVeUsv5xNHf-CTPxcElEPC_jptNM/edit

Best,
Peter

**Comment by wlaurance** [comment]
Does this proposal require any changes in the LMS? Or is it all Quill Grammar?

**Comment by petergault** [comment]
**There are 5 specific issues that need to b addressed here. Each one is numbered!**

# Introduction: Terminology 

Marcello would like to start counting by starting at the most granular level (questions) and counting up for the higher levels. 

Concept_Level_0:		A set of questions about one term: e.g. “A”, “Lose” or “Whom” (similar to RuleQuestions)

Concept_Level_1:		A grouping of sets of questions (e.g. “Lose, Loose”, “The, A”) (similar to rules)

Concept_Level_2: 		Examples: Commonly Confused Words, Nouns & Pronouns. (similar to Concept_Categories).  

![conceptnodes-newterms](https://cloud.githubusercontent.com/assets/3667179/7694056/d6dbb83a-fda8-11e4-8792-d45a9a8319e5.png)

#  A. Changing the Content Hierarchy for the Questions.

## 1. Separate RuleQuestions into Category_Level_0 nodes

In the current system, all of the RuleQuestions belong to a single Rule. In the new system each RuleQuestion belongs to a Concept_Level_0 node, and there are multiple nodes for each Rule. 

### Old System: Don’t Subdivide RuleQuestions 

For example, in the old system there are 6 RuleQuestions about Two, To, Too. These six questions all belong to the Rule “Two, To, and Too”. Within these six questions we don’t specify which questions belong to “Two”, which belong to “To” and which belong to “Too”. All six questions belong to the same grouping. 

### New System: Subdivide the RuleQuestions into Category_Level_0. 

In the new system, each of the RuleQuestions belongs to a Category_Level_0 tag: Either “To”, “Too,”, or “Two.” We already have this data - the current concept tag becomes the Category_Level_0. 

![conceptnodes-sentenceexamples](https://cloud.githubusercontent.com/assets/3667179/7694029/8d72ce54-fda8-11e4-8d43-75de3df38db5.png)



## 2. Rules becomes Category_Level1 nodes

Each of the current rules now becomes a Category_Level1 node. This introduces two issues:

### Handling “Practice” Rules
The one thing that is new here (which simply needs to be edited on the content side, is that there is a distinction between Practice sets of content and non-practice. This distinction way made in order to show an explanation before the non-practice sets. 

### Show Explanations as a function of the CMS

Show a picture. Specify show explanation. We used the practice / non-practice division to control showing the explanation. We can do that through a check box on the editor. 


## 3. Concept Categories become Category_Level2
Each practice question is tagged to a Concept Category. That will become the Concept_Level2 Node. 


# B. Change how the Passage Proofreading app works 

## 4. Tag Each Passage Proofreading Error to a Concept_Level0 node. 
Right now each passage proofreading error is tagged to a Rule (Concept_Level1). However, if a student makes a mistake, we don’t know exactly what mistake the student made. For example, in a Their, They’re, There rule, we don’t know which of these words the student messed up. By tagging each of the passage proofreading errors to a level0 node, we will know exactly which mistakes a student made. 

To do this we need to do the following things:
- [ ] Generate a numerical list of concept_level0 ids for all of the grammar concepts. 
- [ ] Go through each of the stories and swap out the rule Ids for the new concept_level0 id. 

![quill-proofreader-ediotr](https://cloud.githubusercontent.com/assets/3667179/7694110/a1f433bc-fda9-11e4-810b-0daf59f1ecd6.png)

## 5. Change how Quill Grammar generates the follow up questions 

At the moment the Quill Grammar app generates an activity by pulling 3 questions for each rule that was flagged (each error made). For example, if the user made a “which vs. “that” error, and which vs. that is rule #55, it would pull 3 RuleQuestions belonging to 55.

Which = id 301 (Concept_level0)
That = id 302 (Concept_level0)

Under the new system, it randomly generates 3 practice questions from any question belonging to the Concept_Level1. In this case, let’s say the user mades a “which” error,  this would be Concept_Level0 id number 301 (and the “that” error would be Concept_Level0 id 302). 301 & 302 belong to the Concept_level1= which vs. that. It would then generate 3 questions in total, such as 1 question from Concept_Level0 id 301 and 2 questions from Concept_Level0 id 302.  (one “which” question, two “that” questions).

**Comment by marcellosachs** [comment]
Here are some notes on how to implement the above specification.
@petergault does this all check out?
One note: this is all based on the assumption that a rule always becomes a concept_level_1 node.
When looking at the data, there seem to be a nontrivial number of exceptions. Going to think this over, maybe we can talk about it next time your at the bathaus, will try to put together examples.

https://github.com/empirical-org/rules_into_concepts

**Comment by wlaurance** [comment]
We have 3 types of information in Quill Grammar, Rule Category, Rule, and Rule Question. We want to "mark up" each record in the 3 types with our concept information. The concept information is used to build the "tree of knowledge". The concept information links our 3 types of information together.

Each of our records will need to implement our Concept protocol. The concept protocol requires the following:

- `concept_level` `Int` Identifies the concept level in the tree.
- `concept_id` `String` Globally Unique identifier for the concept **WE SHOULD TALK ABOUT THESE IDS** probably UUIDv4
- `parent_concept_id` `String` or `null` Refers to their Parent's Id
- `children_concept_ids `String[]` or `null` list's this nodes children. [] (empty list) and `null` should be treated the same in implementation.

The application should have this information as part of the record.

A Category Record implementing the Concept protocol

```json
{
    "concept_level": 2,
    "concept_id": "topLevelId12345",
    "parent_concept_id": null,
    "children_concept_ids": ["abc123", "efg456", "blahId"],
    "title": "1.1b Use Common, Proper, and Possessive Nouns."
}
```

A Rule Record implementing the Concept protocol

```json
{
    "concept_level": 1,
    "concept_id": "abc123",
    "parent_concept_id": "topLevelId12345",
    "children_concept_ids": ["ruleQuestion],
    "title": "1.1b Use Common, Proper, and Possessive Nouns."
    "rule_number": 407,
    "more_rule_questions_data"
}

**Comment by wlaurance** [comment]
1. Next steps

**Comment by wlaurance** [comment]
2. Future Vision

How user will fetch tree of knowlege, JS widget, to associate app records with concept information.

**Comment by wlaurance** [comment]
A3. Rebuild the list of Concept Level 2 with the "conceptCategory" key from each rule question

**Comment by petergault** [comment]
The ```1 level concepts``` do not perfectly map onto the Quill Grammar ```rules```

For example, there is currently a rule called Who vs. Whom. The correct 1 level concept title is ~Relative Pronouns~. However, the passage proofreading needs the rule Who vs. Whom to serve questions related to that rule. We don’t want to serve general Relative Pronoun questions if the student made a Who vs. Whom errors. 


### There are two things we need to do to solve this problem: 

# C1. In passage proofreading serve the same 0 level questions. 
 In the Passage Proofreading app, all of the errors will be mapped to the 0 level rule. 

The proposed solution was that when a student made a 0 level concept error, they would receive random questions from all of the 0 level concepts associated with the parent 1 level concept. The problem, again, is that the 1 level concept is too broad, and it won’t serve the right content (such as serving random questions from all of the relative pronouns).  

Rather than providing a series of random 1 level rules, we will instead simply provide a series of follow up questions from the same 0 level rule. 


# C2. Remap the Questions within the Activities from Rules to 0 level concepts. 

Another problem here is that in each activity we have defined a series of rules and a series of questions associated with those rules. Because the rules will become more broad in this new system, the original mappings will break. 

The solution here is to simply: 
1. Change how the app works so that it draws random questions from the 0 level questions, rather than that the 1 level rules. In the new system, an admin will choose the 0 level concept and then choose the number of questions associated with that concept. 

2. Manually change the IDs for the mapping. Since everything is mapped to the 0 level questions, we will need to manually change all of the IDs so that they reflect the new numbers. 


### Other considerations: 

# C3.Mapping the explanations 

Right now some of the rules have explanations associated with them while others do not. In the new system we want to have an explanation for each one. Here is an easy of doing this:

Generate a CSV with the following headers:
(old) Rule ID number, (old) Rule Name, (old) Rule Explanation (the html). Question ID number (the individual rule question), (new) 0 level concept. 

This CSV uses the Question ID number to associate the old rules with the new 0 level concepts (so that they are on the same row). Because the old rules will be replaced with the new 0 level concepts, and because they don’t perfectly map onto each other, the Question ID is the consistent variable between the old and new system. 

With this CSV in place, one that needs to manually go through the list an associate an explanation with each 0 level concept. 

In this table, some of the question IDs will have blank explanations. Take the explanation from another question that has it filled out and copy it into the other ones. This could also be done manually. There should only be one explanation for each 0 level concept. 


# C4. Mapping the Common Core alignment. 

Each 0 level concept needs to be associated with a Common Core standard. To do this, we should can take all of the pre-existing RuleCategories and for each RuleCategory we can map all of the questions to have the same title. 

Note: This doesn’t solve the question of whether the LMS will understand the Common Core standards. Essentially we can either passback that data through the title (Without the LMS knowing, a priori, the standards), or we can have the LMS know the hierarchy, and associate each concept being passed back with a corresponding ID in the system. We will wait on this for now. The point is just to have this data in the system before we abolish rule categories. 

# Peter Wireframe to do: 

>> Peter needs to map out the interface for (1) creating questions and (2) creating activities, 2 separate interfaces.
