### ISSUE TITLE
Remove the Topic from the Student Profile Tooltip

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#739]
Let's remove the topic from the student profile tooltip and only show it on the teacher profile.

**Comment by luciankahn** [comment]
I'm new to the project and would like to help out with this issue, but I have some questions:

1. Where is the view file for teacher profiles? I see views/profiles/student.html.erb, but nothing for teachers.
2. It looks like a bunch of JavaScript files dictate which specific data gets included in tooltips in various parts of the site, but I can't find any that are related to teacher profiles. Where should I be looking?

If this fix isn't ideal for someone new to the project, please let me know where I can be more helpful. I'm good with Ruby/Rails/JS.

**Comment by marcellosachs** [comment]
hi @luciankahn , appreciate the help!
The teacher profile is the 'scorebook', which is basically handled by a lot of react code in javascripts/. 
The teacher profile is unrelated to profiles/student.html.erb, so you wont have to worry about side effects on the teacher profile when changing the student profile. As for removing topic from the student profile tooltip, I would check out this helper - https://github.com/empirical-org/Empirical-Core/blob/develop/app/views/application/_activity_icon_with_tooltip.html.erb 
which is used in the student profile, but not in the teacher-facing ui (scorebook)

Let me know if you have any other questions!

**Comment by luciankahn** [comment]
Thanks! I have removed it and am about to make a pull request.
