### ISSUE TITLE
Change Activity Planner URL Name

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#743]
Right now if you click the tab "Activity Planner" when signed in as a teacher the URL is: http://www.quill.org/teachers/classrooms/lesson_planner

Instead, it should be:
http://www.quill.org/teachers/classrooms/activity_planner

We're trying to replace all instances of "lesson" to "activity"

**Comment by daniel-chung** [comment]
Hello, I took a crack at this issue because it was labeled "Level: Starter". I'll be sending over a PR shortly; I'm sure I'll need lots of help given that it's my first commit on this project
