### ISSUE TITLE
My Account Page - Teachers

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#744]
## Goals
Create a page within the teacher account which allows them to be able to change names, passwords, emails, etc. 

http://www.quill.org/teachers/account

- [ ] Change name
- [ ] Change password
- [ ] Change email
- [ ] Change school
- [ ] Premium status: Quill Premium, or Quill Free. For premium list number of students. Show date range of premium.

## Mockup
- [ ] Create a Moqup

**Comment by petergault** [comment]
Done and done
