### ISSUE TITLE
Add Quote to Testimonials 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#749]
**Gwen Beck, Covenant Christian School**
*42 students; 601 activities completed*

My students enjoyed the challenges you gave them in Quill this year, and I am planning to continue using your program next year with my sixth-grade class. Not only did they get a review of grammar rules, but I could monitor their keyboarding prowess as well - a double win for me! 

- [ ] Get the testimonials page live. 
- [ ] Make sure there are two buttons in the impact menu - Stats & Testimonials.

**Comment by tomcalabrese** [comment]
I'm assuming that we want to add this quote and not take away one, right?

If so, then we'll need to figure out what to do about the logos because it won't fit with the current logo.

**Comment by petergault** [comment]
No this is for a seperate page, Quill.org/testimonials.
