### ISSUE TITLE
Homepage - Timer issues on the hero bar

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#752]
1) If you click 'next' to go from the blue story to the red story at X seconds into the blue story, then the next time the blue story comes around, the blue story will begin at point X (and not at 0, the beginning of blue story).

2) This is an issue that Vlad brought up, though I was unable to detect it : 
If I click 'next' to go from the blue story to the red story when the blue story is X seconds through, then the red story will not get its needed 10 seconds to play, but will instead get 10 - X seconds to play.
Vlads proposed solution to this was this tweaked version of tabslet.js : https://github.com/vdw/Tabslet/releases/tag/v1.4.6
Even though I couldnt detect the problem it was supposed to be solving, I tried using the new version of tabslet anyways just in case it would solve problem 1) articulated above, but it didn't.

**Comment by petergault** [comment]
Hm, yeah I know the timer is funky, but I'd like to hold off on this a bit for now. We will roll this all into a homepage update.
