### ISSUE TITLE
Add Anthony to the Team Page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#762]
Trim this to two sentences:

Anthony Principe retired from the Newton Public schools after teaching for 34 years in 2011. He is a veteran special education teacher and administrator who was instrumental in developing cutting-edge inclusion programs for students diagnosed with a wide range of disabilities while employed in Newton. Mr. Principe has also worked for the Boston Public Schools as a transition specialist.

Anthony is an advisor to JFY Networks, a Boston-based nonprofit provider of supported blended learning programs to high schools, community colleges and community-based organizations. Learn Launch Accelerator Program has also invited Anthony to take part in their program as a mentor assisting edtech entrepreneurs develop their sales strategies and navigate growth, market entry and exits. He is driven to motivate team members, identify potential partners, and apply technology strategies to enhance educational outcomes.

Anthony is also a marketing and sales consultant.  His clients includ United Van Lines, American Flexible Conduit, Boston Whaler, Papa Ginos and Weathervane Seafood Restaurants.

![img_0492](https://cloud.githubusercontent.com/assets/3667179/8173510/6cbaec5a-139c-11e5-9adf-957391fbb391.JPG)

**Comment by tomcalabrese** [comment]
![screen shot 2015-07-23 at 12 22 35 pm](https://cloud.githubusercontent.com/assets/8131465/8855845/58ff3016-3135-11e5-9de7-b1f50da03256.png)

There's two copies of Anthony's bio on the team page, along with broken thumbnail images.
