### ISSUE TITLE
ActivitySessions#show not behind any authentication

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#763]
Currently anyone can access the activity_sessions#show page for any activity session. Do users need to be authenticated to see the final score page for their activity session? Presumably anonymous users need to be able to see that page, but it shouldn't be possible to access other users' results by entering the correct URL.

**Comment by marcellosachs** [comment]
@kriskelly I imagine this is something that can be handled after oauth is re-established in the lms?

**Comment by kriskelly** [comment]
This is a bit different. OAuth protects the LMS API, but this is just the HTML page that shows scores, so it should be protected by regular login authentication.

**Comment by marcellosachs** [comment]
@kriskelly ok gotcha

**Comment by marcellosachs** [comment]
turns out I fixed this in September
https://github.com/empirical-org/Empirical-Core/blob/develop/app/controllers/activity_sessions_controller.rb#L7
