### ISSUE TITLE
Comments and rules_misseds Tables do not exist 

### ISSUE THREAD

**Issue by jstrocel** [empirical-org/Empirical-Core#769]
I was trying to install empirical on my local machine, and when I ran the empirical:setup rake task, it threw an error stating that the comments and rules_missed tables did not exist from the 20150622172421_drop_unused_tables.rb migration file. When I removed the 2 lines, the rake task worked fine, and the intended tables were missing from the database. Shall I make a pull request with this change in place?

**Comment by marcellosachs** [comment]
Hey @jstrocel, that would be a great pull request actually. It seems the migrations which created those tables were deleted at some point in the past. So indeed no need for a migration that removes them.
