### ISSUE TITLE
Rspec failing due to missing Env variable

### ISSUE THREAD

**Issue by jstrocel** [empirical-org/Empirical-Core#770]
I think I'm missing a setup step. Whenever I try and run rspec, I get this error:

Empirical-Core/app/uploaders/csv_uploader.rb:5:in `fetch': key not found: "PROGRESS_REPORT_FOG_DIRECTORY" (KeyError)

Is this part of a variables file that I need to set up?

**Comment by marcellosachs** [comment]
Hi @jstrocel , sorry you ran into this problem. We forgot to include a step in our README, but that step has now been added in the latest commit. The step is creating a '.env' file and copying over the contents of '.env-sample'. Upon doing that, do your specs now work?

**Comment by marcellosachs** [comment]
@jstrocel on second thought, I decided to move that action into the empirical:setup task, so should be no need to have it in the readme...
