### ISSUE TITLE
Drip Campaign Notes

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#776]
https://docs.google.com/a/quill.org/document/d/10AGqCjiBmCbDnnlLFWubc7GaieQdYWFfdP2IetewJ2E/edit

Here is the strategy for setting up the drip emails to engage teachers.

**Comment by tomcalabrese** [comment]
## Idea

When we segment teachers into different groups (signed up haven't created class, signed up haven't used in a while, etc.) we can send them targeted intercom emails asking them to join our Slack group for feedback:

![screen shot 2015-09-15 at 12 00 06 pm](https://cloud.githubusercontent.com/assets/8131465/9884231/afaddf42-5bac-11e5-9170-4c84af0a0b8a.png)

**Comment by petergault** [comment]
Notes on things to look into with drip:
- Become a teacher champion at 500+ activities
- Congratulations on getting 200+ 
- Activity packs drip inserted.
