### ISSUE TITLE
Assessing Word Complexity by Frequency

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Empirical-Core#777]
1. Go to Flocabulary and pull a list of all 8th grade words
2. Put all words in a spreadsheet, Column 1 (Word), Column 2 (Grade Level), Column 3 (ZipF), Column 4 (per Million).
3. Using https://www.wordsapi.com/, run all words in the spreadsheet through the API and return ZipF and per Million score per word in each corresponding field

WHY:
Create top down list of highest to lowest frequency words -- will be basis for new ranking of word complexity

**Comment by petergault** [comment]
We can use Google Ngram Viewer to pull word frequency

https://books.google.com/ngrams/info

**Comment by petergault** [comment]
http://developer.wordnik.com/docs.html#!/word

**Comment by marcellosachs** [comment]
Created this sheet, contains the words from Flocabulary https://docs.google.com/spreadsheets/d/1imybvcjxXk0Iq14Zfqp9i5l692pdPbbSyfTk-sTmZGY/edit?usp=sharing

Left to do : make script that makes API request to get frequency data.

**Comment by marcellosachs** [comment]
wordsapi requires a credit card to sign up for their freemium subscription, so trying wordnik

**Comment by marcellosachs** [comment]
applied for an api key from wordnik, while I wait to hear back will try google ngram
