### ISSUE TITLE
Missing Activities

### ISSUE THREAD

**Issue by wlaurance** [empirical-org/Empirical-Core#779]
We just finished transitioning the Firebase Quill Grammar to be the production implementation.

The production level activities were preserved but, `http://www.quill.org/activities/1?anonymous=true`, wasn't.

We just need to make a change the activity number.

@petergault can you choose a new activity to feature on the home page from this list, https://www.quill.org/cms/activity_type/story/activities?

**Comment by petergault** [comment]
We're missing activities on firebase for newly created activities. We can put these activities in beta status for now until they are ready.

**Comment by petergault** [comment]
For homepage, please use this for now: https://www.quill.org/activities/39?anonymous=true
