### ISSUE TITLE
4. Activity Packs

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#795]
Moqup:
https://beta.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/view

Questions:
https://docs.google.com/document/d/1xTTd4b78y89mHojsRZ81QDm7iw9jdsGojRd2FZOaryg/edit

### For Peter
- [ ] CMS - Create Activity Pack (define title, description, activities, time). 
- [ ] CMS - Create Activity Pack Category (define category and packs)

### For Elliot + Peter + Interns
- [ ] Activity Packs - Need 18 packs composing all of our activities 

### How do you explore activity packs?
- A list of all of the activity packs, organized into "activity pack catorgies" 

### How do you create activity packs?
- From the CMS, an admin creates "activity 

### How do you assign activity packs?
- You press "assign" and go to the activity planner flow. It's the same as if you checked off 7 lessons. There is an open question here about whether it starts at the second page or first page of the lesson assignment flow. Talk to marcello about this. The one concern here is that from the second page the teacher can no longer edit the unit's name. 

### How do we handle units? Let’s look at teachers using Quill and see how they have used it.
- Teachers care about two things: themes and dates. We could suggest to teachers they incorporate dates, or we could automatically generate the date range from the activities range.

**Comment by petergault** [comment]
![screen shot 2015-07-24 at 4 09 14 pm](https://cloud.githubusercontent.com/assets/3667179/8886402/63a2764c-321e-11e5-9071-c9be89cb5aca.png)

Idea for sign up

**Comment by petergault** [comment]
https://www.educanon.com/roster

Educanon presents teachers with an interactive table. This makes it easy for the teacher to create a group of teacher accounts easily. 

![screen shot 2015-07-24 at 4 39 51 pm(https://cloud.githubusercontent.com/assets/3667179/8886642/c3f30800-3222-11e5-9f5a-7e9ce9fb9aae.png)

# Using Defaults

We can provide checkboxes for:
- Generate Passwords
- Generate Usernames

- *With generate passwords, Quill provides a password by using the student's lass name.*
- *With generate usernames, Quill provides a username by adding the class-code to the student's name.*

**Comment by petergault** [comment]
# Handson Table 

This is what EduCanon uses:
http://handsontable.com/features.html

**Comment by tomcalabrese** [comment]
Explore Activities
![page_explore_activity_packs 23](https://cloud.githubusercontent.com/assets/8131465/9130194/389e7096-3c95-11e5-800f-1253a24d7733.jpg)

Individual Activities 
![page_individual_activity_pack 24](https://cloud.githubusercontent.com/assets/8131465/9130176/0153ce6a-3c95-11e5-9517-d658b68facf0.png)

**Comment by petergault** [comment]
## Activity Pack Categories. 
Create new activity pack category. 
view activity pack category, edit / delete. 

## Activity Pack 
Input name for activity pack 
Input estimated time (string not numbers)
Input Description field 

Input activities (enter activity id). 
Select Activity Pack Category (dropdown of categories). 

Select recommended grade level (check boxes of the “grades”).

**Comment by marcellosachs** [comment]
@petergault this all looks good!
I'm currently working on the admin cms.

**Comment by petergault** [comment]
Here are all of the pages for the activity packs: 
https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a1bd28820

This is the main page:
https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/abcecd92b

**Comment by tomcalabrese** [comment]
# Explore Activity Packs

## Activity Pack Options
**[Activity Pack Option 1:] (https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a2ab1f5c4)**

Features:
- Categories (ex. English Language Learners)
- Activity Pack title
- Short description
- Number of activities
- Estimated time
- Colored & pattern background, similar to [github](https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a8e769979)


**[Activity Pack Option 2:](https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/aad141346)**

Features:
- Categories (ex. English Language Learners)
- Activity Pack title
- Short description
- Number of activities
- Estimated time
- Color line above activity pack color that relates to the pack category (ex. ELL is purple)

**[Activity Pack Option 3:](https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/af25eee02)**

Features:
- Activity Pack title
- Short description
- ‘View’ button
- Photographs, could be from royalty free images - would be pretty easy because we’re not going to have a ton of activity packs
- Be able to sort from a dropdown
- Displays how many activities and activities packs there are when sorted

**[Activity Pack Option 4:](https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/af3acff14)**

Features:
- Activity Pack title
- Number of standardy
- Estimated time
- Author and author photo. Instead we could do “used by” and it could be the person in the testimonial. This is nice because it makes it seem more like it by teachers for teachers.
- Category in each activity pack overview
- Categories in a list (instead of a dropdown) - “All, popular, ell, etc."

## All feature ideas:

- Categories
- Activity Pack title
- Short description
- Number of activities
- Estimated time
- Number of standards
- Save for later (star it)
- Author
- Button vs. clicking on the pack
- Category in each activity pack overview
- Categories in a list

## Tom's feature recommendations:

- Categories
- Activity Pack Title
- Number of standards
- Estimated time
- Click on the pack instead of a button

## Design ideas:

- Colored & pattern background
- Color line related to category
- Activity pack royalty free photos

## General Questions
- Are we going to have categories?
    - How many packs will be shown in each category?
- What’s the page width we can use? This will influence the dimensions of the packs and how many we can fit.

**Comment by petergault** [comment]
# Things built right now 
Categories
Activity Pack title
Short description
Number of activities
Estimated time
Number of standards
Categories in a list

# Things to Build 
Author name (string)
Author Picture (hardcoded picture) 
Click on a pack to load the individual pack. 

# Landing Page notes:
- One pack per category, organized in the same order as the list of categories at the top of the page. 

# Author Notes
For now the authors will be hardcoded in the system. We will not associate them with user profiles or with the community page profiles. The author's name will be a hardcoded string. The author's picture can be a picture dumped into the pictures folder, similar to the Team page - we hardcode the picture's path into the code. 

The goal for the pictures is to do whatever is fastest and easiest. 


# Open Question - page width
I think we will go with 960 px page width and two packs per page. Thoughts on this?

**Comment by petergault** [comment]
@tomcalabrese @RyanNovas @ddmck @marcellosachs @elliotmandel Nice job on getting all of these bits of the activity pack done. This one is closed.
