### ISSUE TITLE
Bulk Upload Student Accounts via Handson Table Grid. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#796]
# Account Creation Flow
- Enable teachers to fill it in via the inputable grid. 

https://www.educanon.com/roster

Educanon presents teachers with an interactive table. This makes it easy for the teacher to create a group of teacher accounts easily. 

This is what EduCanon uses:
http://handsontable.com/features.html

![screen shot 2015-07-24 at 4 39 51 pm](https://cloud.githubusercontent.com/assets/3667179/8886642/c3f30800-3222-11e5-9f5a-7e9ce9fb9aae.png)
# Using Defaults

We can provide checkboxes for:
- Generate Passwords
- Generate Usernames
- _With generate passwords, Quill provides a password by using the student's lass name._
- _With generate usernames, Quill provides a username by adding the class-code to the student's name._
# Current Status

Marcello, can you run a search through the student table to see how many students have student created accounts vs. teacher created accounts? The easy way to do this is to see how many accounts have the "@" sign in their username. 
- [ ] Number of student created vs. teacher created accounts FOR all accounts
- [ ] Number of student created vs. teacher created accounts FOR accounts with 4+ activities completed.

**Comment by tomcalabrese** [comment]
Questions:

For Account Creation Flow, I'm not seeing the real beneift of using Hands on Table, or Educanon's roster form. A teacher is not going to be able to select all of the fields, first name, last name, username, etc. from a master list. It's just a seperate spreadsheet where they can copy and paste fields, and bring it to a similar spreadsheet. Can you explain the value @petergault ?

**Comment by liyajames** [comment]
From our experience, and I'm sure you're seeing the same, teachers definitely would have a list of students they'd want to upload. So 100% there. 

Then depending on age/grade, some parents would actually create the account for the kids. And some age groups, kids will do it themselves. 

Should there be a password assigned or have them create it at sign-up are circumstantial decisions I need to discuss with you guys to know what to recommend.
