### ISSUE TITLE
Teacher Stories

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#798]
# Why Teacher Stories?
The aim here is to illustrate the various groups of people, all over the world, who are using Quill to improve their writing skills. New people can see these stories, and realize that Quill is for them. These stories should be full of info about how schools are actually using Quill, so that people can bond with this and think about how they want to use it themselves. We can then ask teachers to share these stories with others in their network, and it provides us with a series of stories we can share with our audience. 

# 1. Reach out to both paying schools and active teachers and listen to their stories. 
- [ ] Generate a list of both paying schools and active users. Reach out saying you want to connect with Elliot and to discuss getting ready for the fall.

# 2. Teacher Stories - How they Use Quill
- [ ] the who/what/where/why/how for how schools use Quill
- [ ] The problem that the school is facing (school testing, ELLs, data transparency, student writing challenges). 
- [ ] The demographic info of the school 
- [ ] A quote from the teacher. 

# 3. Photos
- [ ] We can use taskrabbiter to take the photos and ask the teacher to get permission slips (perhaps for a DonorsChoose buy). 
- [ ] We can use stockphotos. 
- [ ] We also want a headshot of the teacher. 

# 4. Topics to Cover
Ultimately we should have 5 stories that cover the following categories:

1. public school
2. School in SF or NYC
3. Charter School
4. Low Income School 
5. School using the Data
6. English Language Learners
7. Elementry School
8. Middle School
9. High School. 
10. College
11. International 

# 5. Questions for Teachers
-> from school testing - what is the workflow they use? 
Capture these stories of how the work is done. 
Show me what you do with the results and the data (a key part of the story). 
How do you find tools? How we can optimize for schools?
How many tools do they use? How do they manage it? 
How long do they spend?
What do they love about Quill?

**Comment by tomcalabrese** [comment]
Teacher Story:
![page_teacher_story 2](https://cloud.githubusercontent.com/assets/8131465/9232329/dfd65612-40e1-11e5-9b05-5e000b3fd6ed.png)

Explore Activty pack:
![page_explore_activity_packs 26](https://cloud.githubusercontent.com/assets/8131465/9232336/f2bcd5bc-40e1-11e5-85af-c27cb1d98e37.png)

Individual Activity pack:
![page_individual_activity_pack 27](https://cloud.githubusercontent.com/assets/8131465/9232347/07a425f2-40e2-11e5-92ff-6f7620ac8c32.png)

**Comment by petergault** [comment]
Follow up ideas 
- For each teacher story, show a progress report associated with the story.
