### ISSUE TITLE
2.b. Tour - Welcome to Quill

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#799]
# Quill Terms 
Another way of doing the tour - we introduce Teachers to all of the quill terms: 
- Activity, Unit, Passage, Quill Grammar, Quill Writer
- On each page is a word and a definition 
- It feels somewhat like a dictionary. 
- When you press next, half the page flips over, like turning a book. 

---------

**Goal: Walk teachers through Quill.**
 We want to walk teachers through all of the apps and the Quill experience. We could have teachers sign up, and then present a series of pages that allows them to learn about Quill.

## 1. Our Tools
The Right Tool for the Right Job (Box open with tools)

https://beta.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a4d308138

Quill currently features four tools that teach proofreading, storytelling, grammar, and vocabulary. 

With these tools, students earn points, write stories together, and receive personalized feedback. 

Let's check them out.

![screen shot 2015-07-26 at 11 21 48 pm](https://cloud.githubusercontent.com/assets/3667179/8899748/2a294898-33ed-11e5-96b8-806a19b0eef6.png)

## 3. Quill Proofreader
Students are given a passage filled with grammatical errors and are tasked with finding and correcting the errors. 

Their performance is automatically graded, and they are then given a personalized lesson targeting the concepts they struggled with.
https://beta.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a989c508d

![screen shot 2015-07-26 at 11 18 24 pm](https://cloud.githubusercontent.com/assets/3667179/8899769/671557ce-33ed-11e5-810b-8d934213c875.png)

## 4. Teacher Dashboard

https://beta.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a6612eeff

Use the Activity Planner to assign activities from any of the over 150 Common Core activities on the platform. 

Each of these activities is designed to take about ten minutes. View student results in real-time, and hover over the score to learn more about the student's performance.

![screen shot 2015-07-26 at 11 17 55 pm](https://cloud.githubusercontent.com/assets/3667179/8899766/5c3a6542-33ed-11e5-93ef-13d829742faf.png)

## 5. Progress Reports
All of the activities and tools on Quill are free to use. 

Schools can pay for access to Quill Premium, which provides reports showing which concepts and Common Core standards students have mastered. 

Teachers can download the
reports as a spreadsheet and import them them into their gradebook.

https://beta.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a9f759836

![screen shot 2015-07-26 at 11 16 45 pm](https://cloud.githubusercontent.com/assets/3667179/8899689/747c716e-33ec-11e5-948f-094568f6d514.png)

## 6. Community
Quill is a nonprofit, open source community. More than 100 educators and developers have already contributed to Quill. 

We'd love to hear your ideas. Please click on the community tab to post an idea or view what we're working on.

Together, let's help every student master the writing process. Welcome!

https://beta.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a9e54160b

![screen shot 2015-07-26 at 11 15 28 pm](https://cloud.githubusercontent.com/assets/3667179/8899671/5822540c-33ec-11e5-82bb-2e9a3176cc64.png)

# Future Slides 
These are slides we can think about incorporating in the future. 

## What Your Goal?
Quill contains over twenty pre-created playlists that focus on separate goals. Let’s choose one and then we will assign it to your students.

##Let’s Add Your Students.
Class name + Grade.

## Real Time Data 
You will see real-time updates as your students complete the activities.

## Right on Time 
Each activity is timed to be about 10 minutes in length. This makes it work as a do now at the beginning or end of a class period, or as part of a rotation model.

## Master the Common Core 
Each activity is built directly from a common core standard. We break it down into sections:

4.1a. Use Relative Pronouns 
Who, Whom 
Which, That

## Emotionally Engaging Materials
We handcraft it all. 

## Learning by Writing.
Writing is importaint

## Personalized Learning.
We tailor it to your needs.

**Comment by tomcalabrese** [comment]
@petergault 

Overall:
- The total onboarding elements you're proposing: sign up, create class, add students, learn about games (proofreader, grammar, writer), learn about dashboard, learn about premium, learn about community (this seems premmature), browse activity packs, pick an individual activity pack.  
- In your current itteration, there are too many pages in the onboarding process. From when the teacher clicks sign up to assigning an activity pack to a class there are 13 pages. One of the rules of onboarding is that you want to minimize the amount of steps to only what is necessary, and add guides along the way. Many of the items outlined in "Teacher Tour" could and should be on the homepage/other pre-sign up pages. 

I propose the order with these options: 
- 1. sign up, create class, add students, browse activity packs, pick an individual activity pack. And then once they're past that onboarding flow they can then learn about games, dashboard, premium, and community from the dashboard. 
- 2. sign up, learn about games, create class, add students, and then take them to the dashboard where they're prompoted to add activity packs.

**Comment by liyajames** [comment]
Overall I have 2 feedback:

(1) For the copy, I'd like to see us focus on not the WHAT and HOW but the WHY, for example the why is the activity planner good for me? I'd like that as the tagline. Use Activity Planner to... (some goal based phrase "Activity Planner to save time" or "Plan activities  

(2) Let's make sure we allow them to skip these cards. 

(3) I'm not convinced that we need so many cards, some of these can be mini tours incorporated into the actual experience when they land on it. People scroll these these things pretty quickly just to get oriented, they won't read carefully, so the intros should be brief and only focus on the main big chunks of features.

For the first slide "Our Tools" -  I would suggest visualizing the 4 tools with simple iconography and then using that throughout the remainder slides. Those seem very important in this slide but kind of get lost. 

BTW - We've incorporated simple animations in these types screens and find better engagement with them. And we've limited text to 2-3 lines. Very simple, straightforward, goal oriented and active language.

**Comment by petergault** [comment]
Another way of doing the tour - we introduce Teachers to all of the quill terms: 
- Activity, Unit, Passage, Quill Grammar, Quill Writer
- On each page is a word and a definition 
- It feels somewhat like a dictionary. 
- When you press next, half the page flips over, like turning a book.
