### ISSUE TITLE
1. Account Flow

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#800]
- [ ] Design the new Sign In Page.

**Comment by tomcalabrese** [comment]
Login 
![page_1 _login 0](https://cloud.githubusercontent.com/assets/8131465/9129692/dbc1d002-3c8f-11e5-81a3-a60cfa8f097b.png)

Sign Up - Account Select
![page_a _account_select 3](https://cloud.githubusercontent.com/assets/8131465/9129711/14cbd974-3c90-11e5-8b3e-f1a4c3cb8b44.png)

Student Sign Up - Class Code
![page_class_code 5](https://cloud.githubusercontent.com/assets/8131465/9129725/472ae0e0-3c90-11e5-82d9-712a8681047f.png)

Student Sign Up - Account Information
![page_account_information 6](https://cloud.githubusercontent.com/assets/8131465/9129739/752fe422-3c90-11e5-8c03-143071e9137f.png)

Teacher Sign Up - Find School
![page_find_school 8](https://cloud.githubusercontent.com/assets/8131465/9129818/2be4a8ec-3c91-11e5-80c9-9a79433b8e2f.png)

Teacher Sign Up - Account Information
![page_account_information 9](https://cloud.githubusercontent.com/assets/8131465/9129830/5a126ede-3c91-11e5-8075-96ad9a5dc391.png)
