### ISSUE TITLE
Teacher Home Dashboard Ideas

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#801]
We should show teachers a dashboard where they can view everything that is going on. For example:

- See their classrooms (manage students), add a new classroom
- See how many students have complted quill activities recently.  Perhaps show it as a breakdown. 
- Show a checklist of how far they are in setting up. 
- How much they have left in premium. 
- Show an action they can do to increase the trial length (tweet about Quill, +50 points). 
- Response to Intervention - they can see which concepts or which students are struggling the most.

**Comment by liyajames** [comment]
I've done some user research with teachers and observed that they do 2 things whenenever they are trying to diagnose issues whther it's grading homework, watching over activities or looking at practice exams:

- which students need help (def dashboard level stuff) 
- how are the making mistakes the mistakes so they can adjust how they teach certain groups, seeing trends of this can help them diagnose how they can adjust their teaching technique

**Comment by tomcalabrese** [comment]
## Competitive Research

We need to look and see how noredink is onboarding users:

![screen shot 2015-09-15 at 12 20 57 pm](https://cloud.githubusercontent.com/assets/8131465/9884299/01a1a464-5bad-11e5-957f-d53defd1160f.png)
