### ISSUE TITLE
Broken: updating the activity classification module_url in the admin CMS

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#807]
This form appears to update the form_url but not the module_url.

Steps to reproduce:
- Log in as admin
- Edit any activity classification
- Type 'fake form url' into form url field, type 'fake module url' into module url field.
- Hit update and reload the edit page.
- See 'fake module url' in both fields.
- In fact form_url was the field that gets updated.

Crazy right?

**Comment by ddmck** [comment]
This is now managed by Rails Admin.
