### ISSUE TITLE
User email should be validated for correctness during signup

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#809]
If a user creates an account with an invalid email address, the app blows up when trying to send the user a welcome email.

The error:
```
app/models/user.rb in send_welcome_email at line 266
Net::SMTPFatalError: 550 5.1.3 Invalid address
```

See here for more info:
https://app.getsentry.com/empirical-core/production/group/73587158/

**Comment by petergault** [comment]
@RyanNovas reach out to Kris Kelly if you need pointers about tackling these types of bugs.

**Comment by RyanNovas** [comment]
@petergault this seems to have been solved by @marcellosachs a few months ago.

https://github.com/empirical-org/Empirical-Core/commit/c0c47ea59cf5f9c462a44f7f5624841666653c6e
