### ISSUE TITLE
Concept Tags -> Concepts switch

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#815]
- [x] Rename ConceptTagResults -> ConceptResults
- [x] add 'uid' to concepts
- [x] Modify activity_sessions API endpoint to accept 'concept_results' instead of 'concept_tag_results'

**Comment by petergault** [comment]
Here is a comment from the doc. This might be a seperate issue for the progress reports:
"Add activities_concepts to store relationships between activities and concepts"

**Comment by kriskelly** [comment]
@petergault I removed that from the list here because there's not going to be a direct relationship between activities and concepts in the LMS.
