### ISSUE TITLE
New API endpoints for Quill Grammar forms

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#816]
- [ ] POST / PUT /api/v1/activities (need to update this - see empirical-org/Quill-Grammar#94 for details)
- [ ] GET /api/v1/topic_categories
- [ ] GET /api/v1/activity_flags (production, beta, alpha, etc.)
- [ ] GET /api/v1/concepts (see #818)
- [ ] POST /api/v1/concepts
- [ ] GET /api/v1/topics
- [ ] GET /api/v1/sections

**Comment by petergault** [comment]
When I create a new 0 level concept, how will the post request communicate that the 0 level concept has parents? Will parents be communicated within the post request? 

If the app posts a 0 level concept, does the LMS generate a UID? Does the app need to generate a UID when it posts the concept?

**Comment by kriskelly** [comment]
@petergault For your 2 questions:

- The POST for a new concept will include the parent uid.
- The LMS generates a UID when the concept gets created.

**Comment by kriskelly** [comment]
I split this issue into a bunch of smaller issues to tackle one by one.
