### ISSUE TITLE
New API endpoint: POST /api/v1/concepts

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#825]
POST /api/v1/concepts should create a new Concept record.

Possible request parameters:

```
{
  name: 'concept name',
  parent: 'uid of the parent concept'
}
```

The response should return the new Concept record along with its newly-generated UID.

See #816.

**Comment by marcellosachs** [comment]
@kriskelly would you be down with changing the key 'parent' to be 'parent_uid' ?

**Comment by wlaurance** [comment]
I think `parent_uid` makes the most sense. In JS, if the key is `parent`, I would expect the valued to be the full object instead of just the uid.

**Comment by kriskelly** [comment]
@marcellosachs @wlaurance Sounds fine to me. I think this sort of pattern should be consistent across all the API endpoints, like #830 should be `topic_uid`, etc.
