### ISSUE TITLE
Modify API endpoint: POST /api/v1/activities

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#830]
Moved from Quill-Grammar. See empirical-org/Quill-Grammar#94 for the prior discussion.

Change the behavior of the API endpoint for creating a new activity, specifically it should accept the following request parameters:

(Note: uid will be generated on firebase end)
```
{
   "uid": 'aasdfsaf'
   “name”: “A Great Title”,
   “description”: “Awesome Description long long long”,
   “section”: “QcEM4Upz9CO6oD4YKcmJ4g”,
   “topic”: “QcEM4Upz9CO6oD4YKcmJ4e”,
   “topic_category”: “QcEM4Upz9CO6oD4YKcmJ49”
}
```

Section, topic, and topic category should all be represented by their corresponding UIDs.

*Note: The existing behavior for this endpoint can change however it needs to, since it was only potentially being used by the old Quill-Lessons app.*

**Comment by marcellosachs** [comment]
@kriskelly two things - 
1. i think we can do without topic_category, since every topic belongs to exactly 1 topic_category
2. in the original params, an activity_classification_id is specified. Can that still be sent over from Quill Grammar? (perhaps this last one is also for @wlaurance )

**Comment by marcellosachs** [comment]
@kriskelly also, should we perhaps move from activity_classification_id to activity_classification_uid?

**Comment by marcellosachs** [comment]
activities dont have a title, so not going to include that

**Comment by kriskelly** [comment]
@marcellosachs the `activity_params` method already allows a name field through, so that part should be fine.

**Comment by marcellosachs** [comment]
@kriskelly ok cool I just like to keep the issue-spec up to date. Note: will need to run `bundle exec rake uid:generate_uids` upon deploying in order to give ActivityClassification's uids

**Comment by marcellosachs** [comment]
@kriskelly perhaps there's some tool for automatically scheduling tasks upon deploy, and then after they've run clearing the file of tasks...

**Comment by kriskelly** [comment]
@marcellosachs Unless I'm misunderstanding something, ActivityClassification has had a `uid` field for awhile now and they are already populated on production.

**Comment by petergault** [comment]
@kriskelly @marcellosachs can we confirm this is complete now?

**Comment by marcellosachs** [comment]
@petergault this was indeed done
https://github.com/empirical-org/Empirical-Core/blob/develop/app/controllers/api/v1/activities_controller.rb#L67-L80
