### ISSUE TITLE
3. Teacher Stories

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#834]

**Comment by petergault** [comment]
Ideas: 
- Banner image of kids
- Profile Photo of teacher 
- Headline Excerpt Quote
- Activity Pack -> Includes preview for each activity. 
- "Story" includes about 3 paragraphs of copy. 
- (Aspects of the story: Tips, tricks and things to watch out for.)
- **Progress Report Page with Real/Fake Data.**

**Comment by tomcalabrese** [comment]
## Design:
- [ ] Create Moqup
- [ ] Plugin real teacher story to see how it will live

## For each story we need:
- [ ] Create a template for the other teacher stories, so we know what we need to have from each teacher
- [ ] Photographs of the students from their classrooms (maybe use taskrabbit photographer)
- [ ] Photograph of the teacher (maybe use taskrabbit photographer)
