### ISSUE TITLE
Progress Reports Issue

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#835]
Here is a link to the new reports. The pages 1-4 need to be built:
https://moqups.com/gault8121/6RLG73bg/p:af5f5ced4

**Concept Pages**

# 1.A. Students (Proficiency Students)
This page shows all of the students and how many concepts the student is proficient or not proficient in. See the right hand tab for what this means. 

# 1.B. Students (All Results, no proficiency status)
This page shows the total number of student results for each page. It does not calculate whether the student is proficient. 

(We will show either 1.A. or 1.B. We need to make a product decision here, I don't have a firm answer yet). 

# 2. Drill Down to One Students 
Show one student and the students total results. On this page calculate proficieny by meeting two conditions: student scores over 75% and student has answered more than 10 concepts. 

# 3.A. Current Results Page
The results page a student sees when the student finishes the activity. 
# 3.B. New Results Page
The second results page shows the new (future) design for the results page. This page is currently live on brainpop, and the assets can be copied from there. 

# 4. Tooltip on Scorebook
The tooltip shows a simple table of the student results one each question.

**Comment by kriskelly** [comment]
@petergault For section 3, do you want the "current" results page to work properly (it doesn't because the way that concepts work has changed), or do you want the "new" design? If the latter, we'll need to talk about that because there's going to be a lot of work involved.

**Comment by kriskelly** [comment]
@petergault For section 4, what "level" of concepts do you want to display here?

**Comment by kriskelly** [comment]
Make the current results page work the way it was working w/ concept tags.
