### ISSUE TITLE
Concepts Progress Reports: Single student view

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#838]
Show one student and the student's total results. On this page calculate proficiency by meeting two conditions: student scores over 75% and student has answered more than 10 concepts.

https://moqups.com/gault8121/6RLG73bg/p:a4db79777

See #835 for original issue.

Blocked while waiting for clarification.

**Comment by kriskelly** [comment]
@petergault This needs some clarification. What "level" of concepts should be displayed here? What happens when you click on one of the concept names? Does it drill down further into the concepts, or go to a different page altogether?

**Comment by kriskelly** [comment]
These are 0 level concepts. Also get rid of the Proficiency column. Include level 2 concepts as a separate column.

**Comment by petergault** [comment]
https://moqups.com/gault8121/6RLG73bg/p:a4db79777
