### ISSUE TITLE
First Pass - Sign Up

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#840]
- [x] Account Select page: student or teacher
- [x] Rebuild the page in react
- [x] Select school as a follow up page. 
- [x] By clicking sign up you agree to the terms and services.
- [x] Last part - add Clever to the sign up.

**Comment by tomcalabrese** [comment]
Account Select:
![account_select](https://cloud.githubusercontent.com/assets/8131465/9187330/15a4a636-3f84-11e5-94c6-1c1b91c6b5a6.png)

Student Account (with alert text):
![student_account](https://cloud.githubusercontent.com/assets/8131465/9187337/25115f38-3f84-11e5-8e1a-ca094826092f.png)

Student Account - Class Code:
![student_account_class_code](https://cloud.githubusercontent.com/assets/8131465/9187343/34557682-3f84-11e5-93af-6917780c155b.png)

Teacher Account:
![teacher_account](https://cloud.githubusercontent.com/assets/8131465/9187344/3b7f4adc-3f84-11e5-91b0-8f7cc0456cb1.png)

Teacher Account - Find School:
![teacher_account_school](https://cloud.githubusercontent.com/assets/8131465/9187346/475415fe-3f84-11e5-9efb-d8ba83531d63.png)

Login with Clever:
![login_clever](https://cloud.githubusercontent.com/assets/8131465/9187398/db424466-3f84-11e5-9de4-7a2109982dc4.png)

Login with Google:
![login_google](https://cloud.githubusercontent.com/assets/8131465/9187399/dff904e0-3f84-11e5-81f5-453e5a622a19.png)

Sign Up with Clever:
![sign_clever](https://cloud.githubusercontent.com/assets/8131465/9187405/e6424c44-3f84-11e5-947f-fe2c466d330e.png)

Sign Up with Google:
![sign_google](https://cloud.githubusercontent.com/assets/8131465/9187412/ec2afd22-3f84-11e5-9149-61551e45ab41.png)

**Comment by marcellosachs** [comment]
using this - https://www.twilio.com/blog/2014/09/gmail-api-oauth-rails.html

**Comment by marcellosachs** [comment]
![login_quill](https://cloud.githubusercontent.com/assets/1789723/9452721/ebdd2372-4a83-11e5-8a00-b937d23c73b4.png)

**Comment by marcellosachs** [comment]
heroku config vars have been set

**Comment by petergault** [comment]
- [ ] Last part - add Clever to the sign up.

**Comment by petergault** [comment]
https://dev.clever.com/instant-login/log-in-with-clever
