### ISSUE TITLE
Update Automatic Sign Up Email  - Mail Gun

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#847]
We currently send an outdated design for the sign up email. 
- [ ] Grab the new design from Tom or via mailchimp. 
- [ ] Script the HTML for it
- [ ] Work with Tom to design the copy for the email. 

Tom and Marcello can work together to import the mailchimp design into HTML for mailgun and then draft the copy for the sign up email.

**Comment by tomcalabrese** [comment]
https://docs.google.com/document/d/1OLdT6YnH2GQptqZsD-kNqmRjVFBSbGiuaKBhxiAgaaA/edit

**Comment by tomcalabrese** [comment]
Change the email name, right now it's just "hello"

**Comment by petergault** [comment]
Here is the code. 

https://github.com/empirical-org/Empirical-Core/blob/ba2720c2485cc1de54190fa25614b53e8a5f637c/app/views/user_mailer/welcome_email.html.erb

I sent the email with the copy.

**Comment by marcellosachs** [comment]
@tomcalabrese to change the email name, i think that involves signing into hello@quill.org and changing the 'name' under settings, unless you want the email to be sent from a different email address.

**Comment by tomcalabrese** [comment]
@marcellosachs I changed the name to be "Quill." Is there a way to test the mailgun email to make sure it's displaying Quill on the left side of an email:


![screen shot 2015-09-02 at 3 07 12 pm](https://cloud.githubusercontent.com/assets/8131465/9641355/4f99c3c8-5184-11e5-951c-8e7964907c1d.png)

**Comment by marcellosachs** [comment]
![screen shot 2015-09-14 at 5 14 47 pm](https://cloud.githubusercontent.com/assets/1789723/9862035/2f655b1a-5b04-11e5-8748-81efb695c8b2.png)

unfortuantely it doesnt seem to be doing so...looking into this...

**Comment by marcellosachs** [comment]
can't seem to get this to work. going to split out the name concern into a different issue.
