### ISSUE TITLE
Email Address when Signing Up

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Empirical-Core#851]
Two distinct problems - the issue of an optional email address for students and the issue of any string being accepted for teacher emails.

A student can sign-up and not enter in an email. The problem is that when they forget their pw, there is no way for them to get the reset. 

For teachers - see below -- any string is accepted as an email, including things without the "@" symbol.
<img width="474" alt="screen shot 2015-08-17 at 11 28 59 am" src="https://cloud.githubusercontent.com/assets/12731246/9318623/13c90386-44fa-11e5-8313-c4b9d6fae127.png">

**Comment by marcellosachs** [comment]
@elliotmandel 
1. optional student email
the student email being optional was part of the product specification, I think some students do not have an email address, or perhaps there's an issue around getting email address for young people. I can make the change if it is desired. Thoughts @petergault @tomcalabrese ?

2. proper email validation for teachers
I can implement this

**Comment by petergault** [comment]
Great, thanks Marcello! 

Regarding student passwords - teachers can reset students passwords if they don't have email. This is our best solution for now, until we can implement other things like a security question.
