### ISSUE TITLE
Bug - Continue Button Broken

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#859]
If you are signed in as a student and load a sentence writing activity, you cannot continue past the first question as the button disappears. If you are not signed in the bug is not present. My guess is that this bug is somehow connected to the anonymous sessions, as it seems the bug started over the weekend.  

# Solutions
Could we please try to get one of these solutions implemented ASAP? 
1. Apply a Hotfix 
2. Maintenance Mode 
3. Rollback to the pre-Friday update?

# Steps to repo:
1. Sign in with the user/pass Student/Student
2. Click on the activity "I've, that's,..."
3. Complete the first question. 
4. The button is then gone. 

![screen shot 2015-08-23 at 11 13 01 pm](https://cloud.githubusercontent.com/assets/3667179/9432258/47736674-49ee-11e5-9d60-90ab01fc019e.png)

**Comment by kriskelly** [comment]
@petergault @wlaurance Here's the console error in Chrome:

```
Error: $firebase has been removed. You may instantiate $firebaseArray and $firebaseObject directly now. For simple write operations, just use the Firebase ref directly. See the AngularFire 1.0.0 changelog for details: https://www.firebase.com/docs/web/libraries/angular/changelog.html
    at https://quillgrammarstaging.firebaseapp.com/vendors.min.js:40544:15
    at getResultList (https://quillgrammarstaging.firebaseapp.com/app-9970d18c.js:168:22)
    at ConceptTagResult.conceptTagResult.save (https://quillgrammarstaging.firebaseapp.com/app-9970d18c.js:184:12)
    at https://quillgrammarstaging.firebaseapp.com/app-9970d18c.js:9757:24
    at Scope.$get.Scope.$emit (https://quillgrammarstaging.firebaseapp.com/vendors.min.js:16165:33)
    at Scope.$scope.checkAnswer (https://quillgrammarstaging.firebaseapp.com/app-9970d18c.js:10091:14)
```

This bug is not from anonymous sessions. It is from an update to the firebase library that changed the Firebase API. Most likely crept in between `0.4.2` and `0.4.3`, which has a lot of changes besides the anonymous users support.
