### ISSUE TITLE
use rspec-retry to help with spurious travis failures

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#861]
https://github.com/NoRedInk/rspec-retry

**Comment by RyanNovas** [comment]
@marcellosachs, @ddmck 

I'm going to set this up. Could you please comment with any spurious failures as you encounter them?

**Comment by RyanNovas** [comment]
`rspec ./spec/features/teacher/progress_reports/activity_progress_report_spec.rb:42 # Activity Listing Progress Report for a logged-in teacher can filter by classroom`
`rspec ./spec/features/teacher/progress_reports/activity_progress_report_spec.rb:47 # Activity Listing Progress Report for a logged-in teacher can export a CSV`
`rspec ./spec/features/teacher/unit_templates_manager_spec.rb:63 # unit templates manager unit template profile is accessible from list of unit_templates`

**Comment by RyanNovas** [comment]
I've added this with https://github.com/empirical-org/Empirical-Core/pull/1079
