### ISSUE TITLE
Reset Password Page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#865]
* [Password Reset](https://drive.google.com/folderview?id=0B1RagCbDewKWfjFqVjR2dUc3ZEc2ZzVQQkxUa1pRSDdYb05hQ0lObWxUVWpxN2ZxMjI0WDA&usp=sharing) & [Password Set](https://drive.google.com/folderview?id=0B1RagCbDewKWfmlMYjVGLWFZQWVFLVRhVmZoS0ZkeFFMOTlCWTZqTW43NGpmQ0dEVlBCV1U&usp=sharing) Pages.

**Comment by RyanNovas** [comment]
@petergault do we do something similar elsewhere on the site, where I can grab the code from?
