### ISSUE TITLE
Google Signup Bug

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#870]
If you already have a Quill account, and press sign up with your google account, it signs you in. However, if you don’t have a Quill account already, after your select your email and enter your gmail password, it brings you back to the Student or Teacher selection. 

This happens whether or not you are signed into Google or not signed into google.

**Comment by marcellosachs** [comment]
I have not reproduced this error. One thing which might be causing this is if your gmail account does not have a first and last name associated to it. Did the test account have a gmail account with a first and last name?

**Comment by marcellosachs** [comment]
ok nvm i just repo'd

**Comment by marcellosachs** [comment]
ok have fixed locally, will deploy once travis greens.
Had to add 'profile' to the scope in the initializer. Otherwise name doesnt come through with email, and app does not create a user account without a valid name. Strangely, this scope was not required to pull down names when testing yesterday.
