### ISSUE TITLE
Google Integration small updates

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#877]
Issues with sign in:

Google account needs:
1. peter should own the account. Can we transfer it? 
2. On the google page we should show the Quill logo. 
3. The Q should be capitalized. 
4. Font should be embedded in logo - it's showing up differently on different computers depending on what is installed locally.

**Comment by marcellosachs** [comment]
email has been sent to peter@quill.org to handle 1)

**Comment by marcellosachs** [comment]
does 4) pertain to the google button?

**Comment by marcellosachs** [comment]
ill ask @tomcalabrese about a logo (they ask for 120px by 120px)

**Comment by marcellosachs** [comment]
2) and 3) taken care of - 
![screen shot 2015-09-02 at 4 13 06 pm](https://cloud.githubusercontent.com/assets/1789723/9643070/a577a95a-518d-11e5-9da3-0ca8000cae35.png)

**Comment by marcellosachs** [comment]
@petergault am i good to close this? Wasn't sure about 4)...
