### ISSUE TITLE
Renew SSL Certificate 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#881]
The SSL certificate expires on September 19th. The certificate was registered through the "SSL addon" in Heroku and it may need to be renewed here.

**Comment by kriskelly** [comment]
According to Heroku, it's going to update automatically. So looks like nothing needs to happen here.

```
CERT ISSUED
Cert Issued for '*.quill.org' will be automatically updated prior to expiration on September 03, 2016
```
