### ISSUE TITLE
Chrome Web Store - Visual Assets 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#884]
For the chrome web store we need the following assets:
- Up to 5 screenshots at a certain resolution (1280x something, sign in to check). It’d be great if we could re-use the same brain pop screenshots for now, and we can add more in later. 
- We need a large image and a marque image. Please feel free to design these how you would like. The key thing that I would like to emphasize is a certain call to action. I think "Free Grammar Activities" is strong. For the larger activities, this could be: "150 Free Grammar Activities for K12 Students." or something like that. 

# Link to Current Assets
https://drive.google.com/drive/folders/0B-r431ws0zjXfjVKajJRRl9ybXhMWDg2a2NWRFRTZW1oX2hibW1kWkhkU3YweVB3Y1dkUjA

# Sample Assets  - Large Image
Here was my quick take on the large image as food for thought. 
![screen shot 2015-08-30 at 10 26 38 pm](https://cloud.githubusercontent.com/assets/3667179/9572713/e67d9bd0-4f67-11e5-9f8a-c66c2c116c96.png)

**Comment by tomcalabrese** [comment]
![quill_small_tile](https://cloud.githubusercontent.com/assets/8131465/9585699/7de46b60-4fe6-11e5-9058-c0062d8762cb.png)
![quill_large_tile](https://cloud.githubusercontent.com/assets/8131465/9585701/7df0f2b8-4fe6-11e5-8eb7-621b2c4ec09a.png)
![quill_marquee](https://cloud.githubusercontent.com/assets/8131465/9585702/7df2fbbc-4fe6-11e5-8783-d2436cac51e6.png)
![quill_grammar_screenshot](https://cloud.githubusercontent.com/assets/8131465/9585700/7df0be42-4fe6-11e5-96ff-b372b04b7c18.png)
![quill_results_screenshot](https://cloud.githubusercontent.com/assets/8131465/9585703/7df68d0e-4fe6-11e5-849e-a248fc18a550.png)
![quill_proofreader_screenshot](https://cloud.githubusercontent.com/assets/8131465/9585704/7df88640-4fe6-11e5-889a-ec88f476ebca.png)

Added all of the visual assets to Chrome Web Store. 

FYI, we won't be able to preview it until:
![screen shot 2015-08-31 at 1 44 44 pm](https://cloud.githubusercontent.com/assets/8131465/9585725/98935cbe-4fe6-11e5-8dc4-9b4d1d5786b2.png)
