### ISSUE TITLE
Change the error in the Chrome Web Store screenshot

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#893]
Change the error so that the word is correct (looking) and the answer is green. The concept can be called: "Past Tense Verbs."

**Comment by tomcalabrese** [comment]
![quill_chrome_screen_1](https://cloud.githubusercontent.com/assets/8131465/11130832/3880ab3a-8955-11e5-9ae6-561ad965a3cf.png)

**Comment by petergault** [comment]
@tomcalabrese thanks!
