### ISSUE TITLE
css on the edit student account page needs tweaking

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#895]
It used to look different, i think it has changed a bit due to the various css changes that have occurred in its periphery. May be time for a 'css refactor'

**Comment by petergault** [comment]
- [ ] Add some padding to the bottom of the terms page
- [ ] Add the same column design to the privacy page.

**Comment by petergault** [comment]
- [ ] Update the address to 55 Exchange Place
- [ ] Find and replace for "starr" to update to Exchange.
