### ISSUE TITLE
Invalid Authenticity Token error

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#899]
https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/719164-6a696fde-5379-11e5-871a-c81f66b8ceca

associated paper trail logs : 
https://papertrailapp.com/systems/empirical-grammar/events?q=ActionController%3A%3AInvalidAuthenticityToken

**Comment by marcellosachs** [comment]
http://stackoverflow.com/questions/3364492/actioncontrollerinvalidauthenticitytoken

**Comment by marcellosachs** [comment]
implemented a solution for the ajax requests on accounts/role, if that works for that path I can transfer it to the other requests

**Comment by marcellosachs** [comment]
that solution did not work. 

from a conversation with @kriskelly  -

This might be caused by more than 1 request being made on the same form (without a page refresh).
This could be occurring if the browsers are caching pages such as the sign up page across different users that are signing up (laptops are often re-used by multiple students in a classroom)

**Comment by marcellosachs** [comment]
http://stackoverflow.com/questions/711418/how-to-prevent-browser-page-caching-in-rails

**Comment by marcellosachs** [comment]
still unfortunately not able to repo this one.
going to try the above solution.

**Comment by RyanNovas** [comment]
We haven't seen this error since @ddmck pushed an authentication fix.
