### ISSUE TITLE
Sign Up Improvement

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#901]
We eliminated the "confirm password" field which is good because it can lower conversion rate about 25%. 

A user can update their password from their account page.

They should also be able to reveal their password in case their not sure if they typed it wrong:
![screen shot 2015-09-08 at 1 42 28 pm](https://cloud.githubusercontent.com/assets/8131465/9742632/74742e40-562f-11e5-9cde-084ce891386c.png)

In an effort to improve our converion rate we want to think about removing the Username field from teachers as well. It's an extra step and could be excluded by creating a unique UID some other way. 

http://uxmovement.com/forms/why-the-confirm-password-field-must-die/

**Comment by RyanNovas** [comment]
I agree that we should get rid of the username. The email should already serve as a unique identifier.
