### ISSUE TITLE
Referral Link for Teachers

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Empirical-Core#907]
<img width="1019" alt="screen shot 2015-09-08 at 3 08 36 pm" src="https://cloud.githubusercontent.com/assets/12731246/9748697/84d18e3e-563b-11e5-9c0d-a5c973721a8b.png">

https://moqups.com/#!/edit/elliot19/5FWQWPZd

Placing a button on the progress reports page to allow teachers to refer their colleagues to Quill Premium. Goal will be to give teachers extra activities on premium if they refer friends.

**Comment by tomcalabrese** [comment]
Great Idea!

I think one thing that will make this successful is if we convey right away that a teacher gets X extra activies to view in progress reports if they refer a teacher. 

Dropbox has this down:

![screen shot 2015-09-10 at 9 43 56 am](https://cloud.githubusercontent.com/assets/8131465/9789869/95a1a2ce-57a0-11e5-84cf-abc760b3fdc6.png)

![get-free-dropbox-space](https://cloud.githubusercontent.com/assets/8131465/9789874/9e06ba3a-57a0-11e5-85f5-c77d4d8d6e9b.png)

## Ideas

1. Refer a teacher through email
* Refer a teacher through a unique link
* Like our facebook, twitter, google+, instagram to get more activities
* Sign up for our newsletter to get more

**Comment by tomcalabrese** [comment]
When a person is on a free plan it's a smart idea to give them a preview of what they're missing from the premium one:

![screen shot 2015-10-22 at 9 45 42 am](https://cloud.githubusercontent.com/assets/8131465/10666767/abba3126-78a1-11e5-9e70-631129592302.png)
