### ISSUE TITLE
iPad Activity Planner Dropdown Bug

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#926]
When you're on the activity planner page on an iPad and want to filter using the dropdowns, it won't let you select any of the dropdown lists.

You can see it happening here: https://youtu.be/XYtKDmyEK7Y

**Comment by RyanNovas** [comment]
this is solved by PR #972 

the issue was that the `cursor` css attribute wasn't set to `pointer`
