### ISSUE TITLE
Individual Activity Pack

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#931]
![image](https://cloud.githubusercontent.com/assets/3667179/10319361/b8ed6ff6-6c22-11e5-8f15-183095a466da.png)

# Ideas for the Copy 
- Include text that describes  how many students have completed activities.

**Comment by tomcalabrese** [comment]
This is an outdated screenshot of the page. Think it makes more sense to link to the moqups page: https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a33831663

**Comment by marcellosachs** [comment]
@tomcalabrese are the related activity packs the first three in the same category?

**Comment by tomcalabrese** [comment]
Most recent mockup for this page:
https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/a4f7f1b47
