### ISSUE TITLE
Activity Packs Landing Page 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#932]
# The Design
https://app.moqups.com/tomkentcalabrese@gmail.com/yestgh1v/edit/page/af3acff14

# Things built right now 
Categories
Activity Pack title
Short description
Number of activities
Estimated time
Number of standards
Categories in a list

# Things to Build 
Author name (string)
Author Picture (hardcoded picture) 
Click on a pack to load the individual pack. 

# Landing Page notes:
- One pack per category, organized in the same order as the list of categories at the top of the page. 

# Author Notes
For now the authors will be hardcoded in the system. We will not associate them with user profiles or with the community page profiles. The author's name will be a hardcoded string. The author's picture can be a picture dumped into the pictures folder, similar to the Team page - we hardcode the picture's path into the code. 

The goal for the pictures is to do whatever is fastest and easiest. 

# Open Question - page width
I think we will go with 960 px page width and two packs per page. Thoughts on this?

**Comment by tomcalabrese** [comment]
## Colors of Activity Packs

Primary ELL: #348fdf
Secondary ELL: #014f92

Primary Elementary: #9c2bde
Secondary Elementary: #560684

Primary Middle: #ea9a1a
Secondary Middle: #875a12

Primary High: #ff4542
Secondary High: #c51916

Primary University: #82bf3c
Secondary University: #457818

Primary Themed: #00c2a2
Secondary Themed: #027360

**Comment by marcellosachs** [comment]
@tomcalabrese colors are good to go - also made them part of the category model so you can always update them from the cms

**Comment by marcellosachs** [comment]
The "Expore Activity Packs" tab should be a sub-tab of "Activity Planner", in between "Create a Unit" and "My Units"
