### ISSUE TITLE
Archive classrooms

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#934]
== The Problem ==
There are (~8000) students who have class-codes but are not associated with a classroom id. 

Each classroom has a class code, a unique “password” students use to join the class. Each classroom also has a grade level. 

 When a classroom is deleted, the class code is deleted. 

Here is why this is a problem: when we query the database to look up the grade level of students, we cannot look up for the students who have had their classrooms deleted. 

While the student account still exists, the activity data exists, and class-code exists on the student’s end, the student’s class code cannot be matched to the classroom’s class code. Therefore, we cannot look up the grade level for the student. This is imprint info for us. 

=== A possible solution ===

The goal: we want to re-associate students with the classroom so that we can keep track of student progress.

A technical route
This is not necessarily the best, just my best take given my technical knowledge. 

Note: before we run this process, we first need to build an archive classroom feature. See below for a description of how this works.

By following these steps, we could rectify this problem: 
Using a SQL query, we compare all student class codes to all classroom class codes. The student class code list will be longer, and the ones that do not match the classroom class code are our missing classrooms.
Using Keen.io, we pull a list of the grade level for each class code. Keen has permentantly saved this data. 
We run a rake task where we re-create these (XXX) classrooms. For each classroom, we set a classroom name that is blank. Each classroom is set to state: archived. (see below). We set the grade level to the appropriate grade level from the keen table. 
All students are now properly connected to a grade level. 

== Archive Classroom Feature == 
New feature step: For all classrooms, we create a new state called something like:
Active / Archive
Displayed / Archived
Display / Hide
All classrooms will start in the “display” state. When we run the rake task, we create the new classrooms in the “archived” state. 

In the user interface, we do not display the archived pages on: scorebook, activity planner, or progress reports. We show it in In the classroom manager

**Comment by RyanNovas** [comment]
I have a pending PR for the Archive Classroom Feature. I will update this once it goes live.

For restoring the missing students classrooms, I think the best course of action would be to setup a [permanent archive] (http://help.papertrailapp.com/kb/analytics/log-analytics-with-hadoop-and-hive/) for Papertrail. Then we can see every class that was deleted in the last year, along with the time it occurred at, and go back in the Postgres backups to find the grade levels. This should also allow us to track a huge number of actions on our site in general.

**Comment by petergault** [comment]
@RyanNovas once this is completed, please close this issue and create a new one about reconstructing the classrooms.
