### ISSUE TITLE
Investigate high number of error alerts

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#939]
Heroku is leaving a high number of error alerts. From New Relic, it seems these errors are being caused by the worker not performing properly. 

https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors

**Comment by kriskelly** [comment]
Pretty much all of these are DB-related errors. Heroku has been having DB issues which, according to their most recent email, should be resolved now. These should be safe to ignore. 

I'll make Github issues for the other Sentry/New Relic issues, most of which have been around for 2-3 months and don't seem that dire.

**Comment by marcellosachs** [comment]
@petergault this email in particular (sent yesterday 6pm) (important part bolded)

The replacement database is ready, so we're starting the changeover process for database (BLACK on empirical-grammar) now. HEROKU_POSTGRESQL_BLACK_URL on empirical-grammar will be updated with the new server address momentarily.

If you've copied the value of HEROKU_POSTGRESQL_BLACK_URL to any other apps or tools (such as database administration tools), you'll need to update those values.

*When your database is available again, performance may be temporarily reduced while Postgres rebuilds its cache through normal usage.* For more information on postgres caching, refer to this devcenter article:

**Comment by marcellosachs** [comment]
I'll email them to find out exactly how long this should last
