### ISSUE TITLE
Intercom Needs to Be Changed - Do Not Count Students, Only Teachers

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Empirical-Core#946]
Right now, Intercom is picking up almost 20k users - it is including both students and teachers. We want it to only be tracking teachers. Can we please set the Intercom system to purge all students and only count teachers?

The problem is that when a student completes an activity, the segment tag identifies the student, and this adds the student to intercom. To fix:

- [ ] Set up a new tag called "teacher's student completes activity"
- [ ] The tag should identify the teacher when the student completes the activity. 
- [ ] Test on staging with intercom staging to make sure that the teacher receives the event. 
- [ ] Launch to production. 
- [ ] In segment, turn off the"student completes an activity" tag for intercom. 
- [ ] Delete all of the students (you can do this by searching for people whose role does not equal teacher. Delete them). Check 30 minutes later, there should be no more students. Teachers should start getting this property. 

<img width="987" alt="screen shot 2015-10-20 at 11 08 56 am" src="https://cloud.githubusercontent.com/assets/12731246/10611633/0210160e-771b-11e5-89c4-4d89a7983706.png">

**Comment by RyanNovas** [comment]
Teacher's name is now being passed through "student completes an activity" (someone else had already taken care of this.

No more students are being logged, and recorded ones have been deleted.

**Comment by ddmck** [comment]
Deployed a potential fix earlier today. Will observe and report. https://github.com/empirical-org/Empirical-Core/pull/1279

**Comment by RyanNovas** [comment]
The last fix seems to have worked.
