### ISSUE TITLE
Possible Google SSO Issue

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#952]
Google sign on creates a username based on the student name and it appears as though it does not append the class code. If two students use Google Sign On with the same name, will that create two students with the same username? Will this create an error in the system. 

For example, if a user signs on with the name Peter Gault, I believe it creates the following class code:
`Peter.Gault@` 

Google can't append the class code because the student does not yet have a class. Perhaps we need to stick a 6 character UID onto the class ID?

**Comment by RyanNovas** [comment]
I think that for this, we should just make the username equal the student's email.

**Comment by marcellosachs** [comment]
UsernameGenerator already ensures that *usernames* will not be identical for users with identical *Names*, by adding an incrementing integer to the end of the *username*. Modified code so that it does not include a trailing '@' for cases where there is no classcode.
