### ISSUE TITLE
Update the Team Page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#954]
The goal:

Group all of the people on the team page under separate headers. (I believe it is the h2 header, from this page: https://www.quill.org/team)

The following groups:
- [x] Quill Team
- [x] Board of Directors (Jane Parver, Timothy, Ben). Add Jane, her picture is in drive. 
- [x] Education Advisory Board (Deborah Chang (ask elliot to ask for pic)), Daniel Scibinski (likewise ask for it), Emily Dalton Smith (search drive), Anthony Principe)
- [x] Technical Advisory Board (Oliver Hurst Hiller). 
- [x] Open Source Developers (Alex, Matt Coleman).

For the new people, add in one basic sentence based off of a google search, elliot will update with new copy.

**Comment by petergault** [comment]
- Remove meet the team label and the space around it 
- update marcllo’s headshot with the headshot in drive. 
- swap Kris with Donald, ask for Donald’s headshot, write some copy for him.

- Emily is no longer at gates. It should say former, and it should add in that she was our program officer for the Literacy Courseware Challenge. She is now at Facebook. 

- Questionable - remove magic, bill and will?

- Jane Parver should read board hair. 
Jane Parver is special counsel with Kaye Scholer. 
Jane is also on the board of the national ASCPA and Columbia Law School Board of Vistors.

**Comment by RyanNovas** [comment]
All complete. PR pending @marcellosachs 's approval.
