### ISSUE TITLE
Add the teacher resource 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#968]
- quill.org/teacher-resources
- add to the header
- remove community from the header
- iframe of a community page: http://community.quill.org/teacher-resources/
- 100% width
- pixels: 4000 pixels

**Comment by RyanNovas** [comment]
This is all set up, but the iframe is rejected as it is HTTP and Quill.org is HTTPS. If we give our Wordpress site its own SSL this will no longer be an issue.

**Comment by petergault** [comment]
the urls should be quill.org/teacher-resources and quill.org/teacher-press-kit
