### ISSUE TITLE
Community Page Footer Text

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#969]
Quill is a nonprofit, open source tool, powered by a community of 83 educators and developers. 

Quill is a nonprofit, open source organization, built by a community of 83 educators and developers. 

Quill is a free, open source literacy tool being built by a nonprofit community of educators and developers.

**Comment by petergault** [comment]
- [ ] Update Copy for FAQ, Mission, Community Development. 
- [ ] Insert links into community.

**Comment by tomcalabrese** [comment]
![screen shot 2015-11-12 at 1 54 45 pm](https://cloud.githubusercontent.com/assets/8131465/11128350/45a2f6f0-8947-11e5-9f9d-d771c8571b56.png)

Copy:
"Quill is a free literacy tool powered by an open source community of educators and developers."

- Add this line under the social media icons and above the quill logo in the footer.
- The text styling is the same as "hello@quill.org" & "1 (646) 820-7136"
- Have the whole line be a link, similar to "support", "terms", and "support". It wil link to community.quill.org

**Comment by RyanNovas** [comment]
https://github.com/empirical-org/Empirical-Core/pull/976
