### ISSUE TITLE
get npm working in LMS

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#973]
@RyanNovas @ddmck we may want to look into this at some point.
I find myself continually running into walls because we don't have npm in the rails app (installing redux, installing jest).

**Comment by marcellosachs** [comment]
another library https://github.com/DrBoolean/lenses

**Comment by marcellosachs** [comment]
another library we need npm for - https://github.com/rackt/react-router

**Comment by marcellosachs** [comment]
this would take at least a few days, maybe a few weeks (it would amount to a change in our javascript infrastructure)

**Comment by Echelon9** [comment]
@RyanNovas Fair to now close this as resolved? npm is used widely following the react_rails merge.

**Comment by RyanNovas** [comment]
@Echelon9 , yes it is. Thanks for pointing this out!
