### ISSUE TITLE
Supporters to homepage

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#997]
## Adding supporters to our homepage

Option 1:

![option 1](https://cloud.githubusercontent.com/assets/8131465/11285484/ac5a57d0-8edd-11e5-968b-929119e2a2b4.png)

Option 2:

![option 2](https://cloud.githubusercontent.com/assets/8131465/11285485/ac6260d8-8edd-11e5-8563-381b3fbd758c.png)

## Questions
Do we want to create a supporters page now uisng wordpress? Or just these logos for now.

**Comment by tomcalabrese** [comment]
![supporters section](https://cloud.githubusercontent.com/assets/8131465/11348903/2a7cab56-91f7-11e5-8f0e-414a8129dbd3.png)

We're adding a Supporters section to the homepage. You can view this Zeplin file to see the CSS: (zpl.io/Zf8g2v)

Logo files here: 
![att_supporter_logo](https://cloud.githubusercontent.com/assets/8131465/11348938/6c980274-91f7-11e5-807a-2936227bea4d.png)

![bill_melinda_gates_supporter_logo](https://cloud.githubusercontent.com/assets/8131465/11348939/6c983672-91f7-11e5-8d9e-3dbfea6ddc98.png)

![blackrock_supporter_logo](https://cloud.githubusercontent.com/assets/8131465/11348940/6c9abf28-91f7-11e5-984f-f41d3552fbf6.png)

![edwin_gould_supporter_logo](https://cloud.githubusercontent.com/assets/8131465/11348942/6c9ed252-91f7-11e5-86fe-5cb3db387393.png)

![fast_forward_supporter_logo](https://cloud.githubusercontent.com/assets/8131465/11348941/6c9d9612-91f7-11e5-94d7-37c2dec9fd68.png)

![google_org_supporter_logo](https://cloud.githubusercontent.com/assets/8131465/11348943/6ca23c08-91f7-11e5-9079-8a4c1f663ce9.png)

We're going to have a wordpress supporters page: quill.org/supporters which will be linked in the line "Helping every student succeed thanks to our partners."

**Comment by RyanNovas** [comment]
@tomcalabrese reopen this when we have the supporters page and I'll add in links.
